; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0e,$40 ; 00 v_start (Pitch:14)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$86,$0e,$40 ; 01 v_start 1 (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $41, $0f
	.word @song0ref5
	.byte $48
	.byte $41, $0f
	.word @song0ref5
	.byte $48, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch3:
@song0ch2:
@song0ch1:
@song0ch1loop:
@song0ref42:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song0ref42
	.byte $41, $0f
	.word @song0ref42
	.byte $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch4:
@song0ch4loop:
	.byte $01, $cd, $02, $cd, $00, $ff, $9d
	.byte $41, $0f
	.word @song0ref42
	.byte $41, $0f
	.word @song0ref42
	.byte $41, $0f
	.word @song0ref42
	.byte $42
	.word @song0ch4loop
