; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Adonete:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_adonete_2A03:=music_data_adonete_2A03

music_data_adonete_2A03:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Bean Brained 2A03
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_adonete
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env24,@env17,@env0 ; 00 : Triangle
	.word @env21,@env14,@env17,@env0 ; 01 : HiHat
	.word @env27,@env11,@env17,@env0 ; 02 : Triangle Snare
	.word @env3,@env4,@env17,@env0 ; 03 : Snare Short
	.word @env28,@env15,@env17,@env0 ; 04 : Kick
	.word @env22,@env23,@env17,@env0 ; 05 : Triangle Kick
	.word @env13,@env14,@env19,@env0 ; 06 : sunshine
	.word @env12,@env14,@env17,@env0 ; 07 : Vibraslap 1
	.word @env2,@env14,@env16,@env7 ; 08 : "Meow Synth"
	.word @env9,@env14,@env5,@env0 ; 09 : Marimba
	.word @env26,@env24,@env19,@env0 ; 0a : Strings Rev 2A03
	.word @env18,@env14,@env19,@env0 ; 0b : Chord 2A03
	.word @env25,@env24,@env19,@env0 ; 0c : Electric Piano 2A03
	.word @env1,@env24,@env19,@env0 ; 0d : Strings 2A03

@instruments_exp:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c1,$c2,$c3,$c4,$c4,$c5,$00,$06
@env2:
	.byte $00,$c5,$c9,$cb,$ca,$c9,$c7,$c6,$c5,$00,$08
@env3:
	.byte $00,$c9,$c8,$c7,$c5,$c3,$c2,$c1,$02,$c0,$00,$09
@env4:
	.byte $b9,$bd,$be,$00,$02
@env5:
	.byte $c2,$c0,$00,$01
@env6:
	.byte $b8,$b8,$bc,$bc,$c0,$c0,$00,$00
@env7:
	.byte $00,$b4,$b7,$ba,$bd,$bf,$c0,$00,$06
@env8:
	.byte $b9,$b9,$bc,$bc,$c0,$c0,$00,$00
@env9:
	.byte $00,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$03,$c0,$00,$0a
@env10:
	.byte $00,$cf,$7f,$00,$02
@env11:
	.byte $c0,$bb,$b7,$b3,$af,$ac,$a6,$00,$06
@env12:
	.byte $00,$c9,$c0,$c8,$c0,$c7,$c0,$c6,$c0,$c6,$c0,$c5,$c0,$c4,$c0,$c3,$c0,$c2,$c0,$c2,$c0,$c1,$c0,$c1,$c0,$c1,$c0,$c1,$c0,$00,$1c
@env13:
	.byte $00,$c8,$c6,$c4,$c2,$c0,$00,$05
@env14:
	.byte $c0,$7f,$00,$01
@env15:
	.byte $bf,$bd,$bc,$00,$02
@env16:
	.byte $c1,$c1,$c2,$00,$02
@env17:
	.byte $7f,$00,$00
@env18:
	.byte $00,$c3,$c5,$c5,$c6,$c7,$c8,$c8,$c9,$0a,$c8,$0b,$c7,$08,$c6,$03,$c5,$00,$10
@env19:
	.byte $c1,$7f,$00,$00
@env20:
	.byte $b9,$b9,$bd,$bd,$c0,$c0,$00,$00
@env21:
	.byte $00,$c6,$c3,$c0,$00,$03
@env22:
	.byte $00,$cf,$03,$c0,$00,$03
@env23:
	.byte $c0,$bb,$b6,$b1,$ad,$00,$04
@env24:
	.byte $b4,$7f,$00,$00
@env25:
	.byte $00,$c5,$c5,$c4,$c3,$c2,$c1,$03,$c4,$c4,$c3,$c3,$c2,$c1,$03,$c3,$02,$c2,$c2,$c1,$02,$c0,$c2,$02,$c1,$04,$c0,$c2,$02,$c1,$02,$c0,$02,$c1,$05,$c0,$02,$c1,$03,$c0,$00,$27
@env26:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$00,$05
@env27:
	.byte $00,$cf,$06,$c0,$00,$03
@env28:
	.byte $00,$cb,$ca,$c9,$c7,$c3,$c2,$c1,$c0,$00,$08

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $ff, $9f, $48, $ff, $ff, $9f
@song0ref8:
	.byte $48, $90
@song0ref10:
	.byte $1f, $a1, $20, $8f, $00, $8f, $1d, $a1, $00, $a1, $17, $a1, $19, $8f, $00, $8f, $1c, $a1, $17, $8f, $00, $8f, $48, $16
	.byte $8f, $00, $ff, $ff, $8b, $48
	.byte $41, $16
	.word @song0ref10
	.byte $48, $19, $8f, $00, $ff, $ff, $8b, $48
	.byte $41, $1c
	.word @song0ref10
	.byte $48
	.byte $41, $16
	.word @song0ref10
	.byte $48, $19, $8f, $00, $ff, $ff, $8b, $48
	.byte $41, $1c
	.word @song0ref10
	.byte $48
	.byte $41, $16
	.word @song0ref10
	.byte $48, $19, $8f, $00, $ff, $ff, $8b, $48
	.byte $41, $1c
	.word @song0ref10
	.byte $48
	.byte $41, $16
	.word @song0ref10
@song0ref88:
	.byte $48, $19, $8f, $00, $ff, $ff, $8b, $48, $16, $8f, $00, $8f, $19, $8f, $00, $8f, $1d, $8f, $00, $8f, $22, $c5, $00, $a1
	.byte $1d, $c5, $48, $14, $8f, $00, $8f, $18, $8f, $00, $8f, $1b, $8f, $00, $8f, $20, $c5, $00, $a1, $1b, $c5, $48, $12, $8f
	.byte $00, $8f, $16, $8f, $00, $8f, $19, $8f, $00, $8f, $1e, $c5, $00, $a1, $19, $c5, $48, $11, $8f, $00, $8f, $14, $8f, $00
	.byte $8f, $18, $8f, $00, $8f, $1b, $c5, $00, $a1, $18, $c5, $48
@song0ref172:
	.byte $1b, $8f, $00, $8f, $1b, $8f, $00, $8f, $1b, $8f, $00, $fb, $20, $8f, $00, $8f, $20, $8f, $00, $8f, $48, $20, $8f, $00
	.byte $fb, $94, $1b, $8f, $00, $b3, $1b, $8f, $00, $8f, $1a, $8f, $00, $8f
	.byte $41, $1c
	.word @song0ref8
	.byte $48
	.byte $41, $16
	.word @song0ref10
	.byte $48, $19, $8f, $00, $ff, $ff, $8b, $48
	.byte $41, $1c
	.word @song0ref10
	.byte $48
	.byte $41, $16
	.word @song0ref10
	.byte $48, $19, $8f, $00, $ff, $ff, $8b, $48
	.byte $41, $19
	.word @song0ref10
	.byte $d7, $92, $31, $8f, $2f, $8f, $31, $a1, $2c, $a1, $00, $c5
	.byte $41, $16
	.word @song0ref8
	.byte $48, $19, $8f, $00, $d7, $92, $31, $8f, $2f, $8f, $31, $a1, $34, $99, $36, $81, $37, $81, $36, $a1, $2f, $a1
	.byte $41, $19
	.word @song0ref8
	.byte $8f, $92, $31, $8f, $2f, $8f, $31, $a1, $34, $a1, $36, $85, $37, $87, $36, $87, $34, $85, $36, $a1, $31, $8f, $2f, $8f
	.byte $2c, $8f, $2f, $87, $30, $85
	.byte $41, $16
	.word @song0ref8
	.byte $41, $65
	.word @song0ref88
	.byte $ff, $ff, $8b, $48, $00, $e9, $92
@song0ref326:
	.byte $2f, $8f, $30, $8f, $31, $a1, $2c, $a1, $00, $c5, $48, $ff, $8f, $34, $a1, $33, $a1, $2f, $a1, $31, $a1, $48, $00, $e9
	.byte $41, $16
	.word @song0ref326
	.byte $2f, $8f, $30, $8f, $31, $a1, $2c, $a1, $90, $14, $a1, $17, $8f, $00, $8f, $48, $19, $a1, $14, $c5, $00, $a1, $92, $34
	.byte $a1, $33, $a1, $2f, $a1, $31, $a1, $48, $00, $e9, $90, $19, $c5, $00, $a1, $17, $c5, $48, $19, $c5, $00, $c5, $92, $34
	.byte $a1, $33, $a1, $2f, $a1, $31, $a1, $48, $90
	.byte $41, $18
	.word @song0ref172
	.byte $1b, $8f, $00, $8f, $1b, $8f, $00, $8f, $1b, $8f, $00, $b3, $48
@song0ref426:
	.byte $c7, $20, $8f, $00, $8f, $20, $8f, $00, $8f, $20, $8f, $00, $fb, $44, $00
@song0ch1:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $9a
@song0ref449:
	.byte $19, $a1, $20, $a1, $00, $a1, $19, $a1, $1e, $a1, $00, $a1, $20, $a1, $00, $a1, $1b, $8f, $00, $ff, $ff, $8b
	.byte $41, $10
	.word @song0ref449
	.byte $1d, $8f, $00, $ff, $ff, $8b
	.byte $41, $16
	.word @song0ref449
	.byte $41, $10
	.word @song0ref449
	.byte $ff, $d7, $98
@song0ref489:
	.byte $23, $a1, $24, $a1
@song0ref493:
	.byte $29, $a1, $25, $a1, $20, $a1, $2e, $a1, $2c, $a1, $2a, $a1, $29, $c5, $27, $ff, $ff, $9d, $29, $a1, $25, $a1, $20, $a1
	.byte $2e, $a1, $2c, $a1, $2a, $a1, $29, $a1, $27, $a1, $25, $ff, $d5
	.byte $41, $29
	.word @song0ref489
@song0ref533:
	.byte $23, $a1, $24, $a1, $4b, .lobyte(@env8), .hibyte(@env8), $96, $1d, $ff, $8d, $51, $fe, $80, $ff, $8f, $7f, $4b, .lobyte(@env20)
	.byte .hibyte(@env20), $1b, $ff, $8d, $51, $fe, $80, $ff, $8f, $7f, $4d, $19, $ff, $8d, $51, $fe, $80, $ff, $8f, $7f, $4b
	.byte .lobyte(@env8), .hibyte(@env8), $18, $ff, $8d, $51, $fe, $80, $ff, $8f
@song0ref583:
	.byte $7f, $4b, .lobyte(@env14), .hibyte(@env14), $4c, $94, $20, $8f, $00, $8f, $20, $8f, $00, $8f, $20, $8f, $00, $fb, $20
	.byte $8f, $00, $8f, $20, $8f, $00, $8f, $20, $8f, $00, $fb, $20, $8f, $00, $b3, $23, $8f, $00, $8f, $24, $8f, $00, $8f, $98
	.byte $41, $25
	.word @song0ref493
	.byte $41, $29
	.word @song0ref489
	.byte $41, $29
	.word @song0ref489
	.byte $41, $29
	.word @song0ref489
	.byte $41, $2f
	.word @song0ref533
	.byte $ff, $ff, $8b, $79, $4b, .lobyte(@env20), .hibyte(@env20), $96
@song0ref649:
	.byte $20, $e9, $4d, $1e, $ff, $b1, $4b, .lobyte(@env8), .hibyte(@env8), $1d, $e9, $4b, .lobyte(@env6), .hibyte(@env6), $1d
	.byte $ff, $b1, $4b, .lobyte(@env20), .hibyte(@env20), $20, $e9, $4d, $1e, $ff, $b1, $4b, .lobyte(@env8), .hibyte(@env8)
	.byte $1d, $e9, $4b, .lobyte(@env6), .hibyte(@env6), $1d, $ff, $b1, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $41, $14
	.word @song0ref649
	.byte $41, $1b
	.word @song0ref583
	.byte $8f, $20, $8f, $00, $8f, $20, $8f, $00, $b3
	.byte $41, $0e
	.word @song0ref426
@song0ch2:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $80, $19, $a1, $1d, $91, $00, $b1, $19, $a1, $1e, $8f, $00, $b3, $1d, $8f, $00, $b3, $1b
	.byte $8f, $00, $ff, $c3
@song0ref736:
	.byte $17, $a1, $18, $a1, $19, $a1, $1d, $8f, $00, $b3, $19, $a1, $1e, $8f, $00, $b3, $17, $c5, $19, $8f, $00, $ff, $ff, $8b
	.byte $19, $a1, $1d, $8f, $00, $b3, $19, $a1, $1e, $8f, $00, $b3, $1d, $8f, $00, $b3, $1b, $8f, $00, $fb, $84, $29, $8f, $00
	.byte $b3, $80
	.byte $41, $16
	.word @song0ref736
	.byte $c3
@song0ref790:
	.byte $84, $29, $8f, $00, $b3
@song0ref795:
	.byte $8a, $22, $85, $80, $19, $99, $1d, $8f, $00, $8f, $84, $29, $8f, $00, $8f, $80, $19, $a1, $8a, $22, $85, $80, $1e, $87
	.byte $00, $b3, $84, $29, $85, $80, $1d, $87, $00, $b3, $8a, $22, $85, $80, $1b, $87, $00, $ff, $c3, $84, $29, $85, $80, $17
	.byte $99, $18, $a1
	.byte $41, $16
	.word @song0ref795
	.byte $80, $17, $bd, $8a, $22, $85, $80, $19, $87, $00, $ff, $c3, $84, $29, $85, $80, $17, $99, $18, $a1
	.byte $41, $1a
	.word @song0ref795
	.byte $1b
@song0ref873:
	.byte $8f, $00, $8f, $84, $29, $8f, $00, $ff, $9f, $29, $85, $80, $17, $99, $18, $a1
	.byte $41, $16
	.word @song0ref795
	.byte $80, $17, $bd, $19
	.byte $41, $0e
	.word @song0ref873
@song0ref899:
	.byte $8a, $22, $85, $80, $22, $99, $25, $8f, $00, $8f, $84, $29, $8f, $00, $8f, $80, $22, $a1, $29, $8f
@song0ref919:
	.byte $00, $b3, $84, $29, $85, $80, $22, $bd, $8a, $22, $85, $80, $20, $99, $24, $8f, $00, $8f, $84, $29, $8f, $00, $8f, $80
	.byte $20, $a1, $8a, $22, $85, $80, $27, $87, $00, $b3, $84, $29, $85, $80, $20, $bd, $8a, $22, $85, $80, $1e, $99, $22, $99
	.byte $00, $85
@song0ref969:
	.byte $84, $29, $8f, $00, $8f, $80, $1e, $a1, $8a, $22, $85, $80, $25, $87, $00, $b3, $84, $29, $85, $80, $1e, $bd, $8a, $22
	.byte $85, $80, $1d, $99, $20, $8f, $00, $8f, $84, $29, $8f, $00, $8f, $80, $1d, $a1, $8a, $22, $85, $80, $24, $87, $00, $b3
	.byte $84, $29, $85, $80, $1d, $bd
@song0ref1023:
	.byte $8a
@song0ref1024:
	.byte $22, $85, $80, $1b, $87, $00, $8f, $1b, $8f, $00, $8f, $84, $29, $85, $80, $1b, $87, $00, $8f, $8a, $22, $8f, $00, $d7
	.byte $41, $14
	.word @song0ref1024
	.byte $22, $85, $80, $1b, $bd, $84, $29, $85, $80, $1a, $bd
	.byte $41, $1a
	.word @song0ref795
	.byte $1b, $8f, $00, $ff, $c3, $17, $a1, $18, $a1
	.byte $41, $16
	.word @song0ref795
	.byte $80, $17, $bd, $19, $8f, $00, $ff, $ff, $8b
	.byte $41, $1f
	.word @song0ref795
	.byte $fb, $84, $29, $8f, $00, $b3, $80, $17, $a1, $18, $a1
	.byte $41, $16
	.word @song0ref795
	.byte $80, $17, $bd, $8a, $22, $85, $80, $19, $87, $00, $ff, $ff, $8b
	.byte $41, $1f
	.word @song0ref795
@song0ref1119:
	.byte $b3, $84, $29, $8f, $00, $b3, $8a, $22, $8f, $00, $b3, $84, $29, $85, $80, $17, $99, $18, $a1
	.byte $41, $16
	.word @song0ref795
	.byte $80, $17, $bd, $8a, $22, $85, $80, $19, $87, $00, $b3, $84, $29, $8f, $00, $b3, $8a, $22, $8f, $00, $b3
	.byte $41, $23
	.word @song0ref790
	.byte $41, $0f
	.word @song0ref1119
	.byte $41, $16
	.word @song0ref795
	.byte $80, $17, $bd, $19, $8f, $00, $8f, $84, $29, $8f, $00, $ff, $9f, $29, $8f, $00, $b3
	.byte $41, $0e
	.word @song0ref899
	.byte $8a, $22, $85, $80, $29, $87
	.byte $41, $23
	.word @song0ref919
	.byte $8f, $00, $8f
	.byte $41, $3c
	.word @song0ref969
	.byte $41, $13
	.word @song0ref1024
	.byte $ff, $9f, $84, $29, $85, $80, $17, $99, $18, $a1
@song0ref1219:
	.byte $8a, $22, $85, $80, $19, $99, $00, $a1, $84, $29, $8f, $00, $8f, $80, $17, $a1, $8a, $22, $8f, $00, $b3, $84, $29, $8f
	.byte $00, $b3, $8a, $22, $85, $80, $16, $99, $00, $a1, $84, $29, $8f, $00, $8f, $80, $15, $a1, $8a, $22, $8f, $00, $b3, $84
	.byte $29, $8f, $00, $b3
	.byte $41, $28
	.word @song0ref1219
	.byte $41, $21
	.word @song0ref1219
	.byte $85, $80, $1e, $87, $00, $b3, $84, $29, $85, $80, $1d, $87, $00, $b3
	.byte $41, $28
	.word @song0ref1219
	.byte $41, $14
	.word @song0ref1023
	.byte $41, $14
	.word @song0ref1024
	.byte $41, $13
	.word @song0ref1024
	.byte $8f, $c7
	.byte $41, $0f
	.word @song0ref1024
	.byte $fb, $44, $00
@song0ch3:
@song0ref1312:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $eb, $86, $34
	.byte $8f, $00, $8f, $30, $8f, $00, $fb, $ff, $ff, $9f, $ff, $8f, $35, $8f, $00, $8f, $33, $8f, $00, $8f, $30, $8f, $00, $b3
@song0ref1360:
	.byte $88, $27, $8f, $00, $8f, $82, $2f, $8f, $00, $8f, $86, $30, $8f, $00, $8f, $82, $2f, $8f, $00, $8f
	.byte $41, $10
	.word @song0ref1360
	.byte $88, $27, $8f, $00, $fb, $86
@song0ref1389:
	.byte $33, $8f, $00, $8f, $31, $8f, $00, $8f, $30, $8f, $00, $8f, $8c, $31, $8f, $00, $8f
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $88, $27, $8f, $00, $d7, $86, $35, $8f, $00, $8f
	.byte $41, $10
	.word @song0ref1389
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $88, $27, $8f, $00, $8f, $27, $8f, $00, $b3, $86, $35, $8f, $00, $8f
	.byte $41, $10
	.word @song0ref1389
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
@song0ref1454:
	.byte $88, $27, $8f, $00, $8f, $27, $8f, $00, $8f, $82, $31, $8f, $00, $8f, $86, $35, $8f, $00, $8f
	.byte $41, $10
	.word @song0ref1389
	.byte $41, $10
	.word @song0ref1360
@song0ref1479:
	.byte $88, $27, $8f, $00, $8f, $82, $2f, $8f, $00, $8f, $86, $30, $8f, $00, $8f, $8c, $31, $8f, $00, $8f
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
@song0ref1517:
	.byte $88, $27, $8f, $00, $8f, $82, $2f, $8f, $00, $8f, $86, $30, $8f, $00, $8f, $32, $8f, $00, $8f, $8e, $2c, $c5
	.byte $41, $12
	.word @song0ref1517
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $ff, $ff, $9f
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $ff, $ff, $9f
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $88, $27, $8f, $00, $d7, $86, $34, $8f, $00, $8f, $30, $8f, $00, $fb
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $88, $27, $8f, $00, $fb, $8e, $2c, $ff, $8d
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1454
	.byte $33, $8f, $00, $8f, $31, $8f, $00, $8f, $8e, $2e, $8f, $43, $2c, $8f, $8c, $31, $8f, $00, $8f
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $12
	.word @song0ref1517
	.byte $41, $11
	.word @song0ref1517
	.byte $a1, $86, $35, $8f, $00, $8f
	.byte $41, $10
	.word @song0ref1389
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $10
	.word @song0ref1360
	.byte $41, $10
	.word @song0ref1479
	.byte $41, $12
	.word @song0ref1517
	.byte $41, $12
	.word @song0ref1517
	.byte $41, $12
	.word @song0ref1517
	.byte $88, $27, $8f, $00, $8f, $82, $2f, $8f, $00, $8f, $86, $30, $8f, $00, $fb, $44, $00
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
	.byte $41, $15
	.word @song0ref1312
	.byte $41, $15
	.word @song0ref1312
	.byte $41, $15
	.word @song0ref1312
	.byte $41, $15
	.word @song0ref1312
	.byte $41, $15
	.word @song0ref1312
	.byte $41, $15
	.word @song0ref1312
	.byte $41, $15
	.word @song0ref1312
	.byte $41, $15
	.word @song0ref1312
	.byte $ff, $ff, $9f, $44, $00
