; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_remix8ds2A03:=music_data_remix8ds2A03

music_data_remix8ds2A03:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Remix 8 DS 2A03
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env57,@env21,@env40,@env0 ; 00 : HiHatQuiet
	.word @env17,@env21,@env40,@env0 ; 01 : HiHat
	.word @env26,@env22,@env40,@env0 ; 02 : Triangle Drop
	.word @env26,@env37,@env40,@env0 ; 03 : Triangle
	.word @env7,@env3,@env40,@env0 ; 04 : Drum
	.word @env26,@env34,@env40,@env0 ; 05 : Triangle No Pitch
	.word @env11,@env34,@env41,@env0 ; 06 : 50Square
	.word @env44,@env34,@env41,@env0 ; 07 : 50Square Echo
	.word @env63,@env21,@env40,@env0 ; 08 : HiHat Long Loud
	.word @env54,@env20,@env40,@env0 ; 09 : Drum Snare
	.word @env13,@env34,@env48,@env0 ; 0a : Main 1
	.word @env43,@env2,@env40,@env0 ; 0b : Cymbal
	.word @env44,@env34,@env47,@env0 ; 0c : Main 1 Echo
	.word @env60,@env6,@env40,@env0 ; 0d : idk some iron instrument
	.word @env50,@env34,@env47,@env0 ; 0e : Orchestra
	.word @env36,@env38,@env40,@env0 ; 0f : HiHat Long
	.word @env58,@env34,@env41,@env18 ; 10 : Chord 2A03
	.word @env15,@env34,@env10,@env19 ; 11 : Main 2
	.word @env5,@env34,@env40,@env0 ; 12 : FadeInOut
	.word @env12,@env34,@env8,@env0 ; 13 : some bg
	.word @env51,@env34,@env41,@env18 ; 14 : Chord 2A03 REV

@instruments_exp:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $b7,$b7,$bc,$bc,$c0,$c0,$00,$00
@env2:
	.byte $ba,$bd,$c0,$00,$02
@env3:
	.byte $bb,$c0,$00,$01
@env4:
	.byte $ba,$ba,$bd,$bd,$c0,$c0,$00,$00
@env5:
	.byte $00,$cb,$cf,$c9,$c2,$00,$04
@env6:
	.byte $bd,$bf,$c0,$00,$02
@env7:
	.byte $00,$c8,$c6,$c5,$c4,$c2,$c1,$00,$06
@env8:
	.byte $c2,$c1,$00,$01
@env9:
	.byte $b8,$b8,$be,$be,$c0,$c0,$00,$00
@env10:
	.byte $c2,$c0,$00,$01
@env11:
	.byte $00,$c6,$7f,$00,$02
@env12:
	.byte $00,$c7,$c6,$c5,$c4,$00,$04
@env13:
	.byte $0e,$c4,$cc,$c9,$c7,$c5,$c6,$c5,$10,$c4,$02,$c3,$00,$0b,$c3,$c3,$c2,$c2,$c1,$03,$c0,$00,$14
@env14:
	.byte $b8,$b8,$bc,$bc,$c0,$c0,$00,$00
@env15:
	.byte $0c,$cd,$c3,$c8,$c7,$c7,$c6,$c6,$c5,$c4,$00,$09,$c4,$c4,$c3,$02,$c2,$03,$c1,$04,$c0,$00,$14
@env16:
	.byte $b6,$b6,$ba,$ba,$c0,$c0,$00,$00
@env17:
	.byte $00,$c4,$c3,$c1,$c1,$c0,$00,$05
@env18:
	.byte $00,$c0,$1f,$c0,$bf,$be,$02,$bf,$c0,$02,$c1,$c2,$02,$c1,$c0,$c0,$00,$03
@env19:
	.byte $00,$c0,$0d,$c0,$c1,$c2,$02,$c1,$c0,$c0,$bf,$be,$02,$bf,$c0,$00,$03
@env20:
	.byte $b8,$bd,$bf,$bf,$bd,$00,$04
@env21:
	.byte $be,$c0,$00,$01
@env22:
	.byte $bf,$7f,$00,$00
@env23:
	.byte $b9,$b9,$bc,$bc,$c0,$c0,$00,$00
@env24:
	.byte $c0,$c0,$bb,$bb,$00,$00
@env25:
	.byte $b5,$b5,$b9,$b9,$c0,$c0,$00,$00
@env26:
	.byte $00,$cf,$7f,$00,$02
@env27:
	.byte $b7,$b7,$ba,$ba,$c0,$c0,$00,$00
@env28:
	.byte $b6,$b6,$be,$be,$c0,$c0,$00,$00
@env29:
	.byte $bb,$bb,$bd,$bd,$c0,$c0,$00,$00
@env30:
	.byte $b6,$b6,$bc,$bc,$c0,$c0,$00,$00
@env31:
	.byte $c0,$c0,$bd,$bd,$00,$00
@env32:
	.byte $b9,$b9,$be,$be,$c0,$c0,$00,$00
@env33:
	.byte $b8,$b8,$ba,$ba,$c0,$c0,$00,$00
@env34:
	.byte $c0,$7f,$00,$01
@env35:
	.byte $b8,$b8,$bb,$bb,$c0,$c0,$00,$00
@env36:
	.byte $00,$c6,$c5,$c3,$c2,$00,$04
@env37:
	.byte $bd,$c2,$c0,$00,$02
@env38:
	.byte $bc,$be,$c0,$00,$02
@env39:
	.byte $b6,$b6,$bd,$bd,$c0,$c0,$00,$00
@env40:
	.byte $7f,$00,$00
@env41:
	.byte $c2,$7f,$00,$00
@env42:
	.byte $bb,$bb,$be,$be,$c0,$c0,$00,$00
@env43:
	.byte $00,$ca,$ca,$c9,$c9,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$03,$c3,$03,$c2,$02,$c1,$c1,$c0,$00,$14
@env44:
	.byte $00,$c2,$7f,$00,$02
@env45:
	.byte $b7,$b7,$bb,$bb,$c0,$c0,$00,$00
@env46:
	.byte $00,$c0,$c0,$bf,$06,$c0,$03,$c1,$06,$c0,$00,$01
@env47:
	.byte $c1,$7f,$00,$00
@env48:
	.byte $c0,$c1,$00,$01
@env49:
	.byte $b9,$b9,$bd,$bd,$c0,$c0,$00,$00
@env50:
	.byte $00,$c6,$cb,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$05,$c3,$04,$c2,$04,$c1,$02,$c0,$00,$11
@env51:
	.byte $00,$c8,$7f,$00,$02
@env52:
	.byte $ba,$ba,$be,$be,$c0,$c0,$00,$00
@env53:
	.byte $c0,$c0,$bc,$bc,$00,$00
@env54:
	.byte $00,$c9,$c8,$c6,$c5,$c3,$c2,$c1,$c0,$c0,$00,$09
@env55:
	.byte $b8,$b8,$bd,$bd,$c0,$c0,$00,$00
@env56:
	.byte $b9,$b9,$bd,$bd,$bf,$bf,$00,$00
@env57:
	.byte $00,$c4,$c2,$c1,$c0,$00,$04
@env58:
	.byte $00,$c8,$03,$c7,$06,$c6,$06,$c5,$08,$c4,$00,$09
@env59:
	.byte $b9,$b9,$bb,$bb,$c0,$c0,$00,$00
@env60:
	.byte $00,$c5,$c5,$c4,$02,$c3,$00,$05
@env61:
	.byte $b7,$b7,$bd,$bd,$c0,$c0,$00,$00
@env62:
	.byte $ba,$ba,$bc,$bc,$c0,$c0,$00,$00
@env63:
	.byte $00,$c7,$c6,$c4,$02,$c3,$02,$c2,$00,$07

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $f7
@song0ref17:
	.byte $9c, $2d, $a5, $48, $2e, $cd, $00, $cd, $48, $ff, $9f, $48, $70, $4e, $ff, $a4, $2d, $83, $00, $81, $4e, $fe, $2d, $85
	.byte $00, $4e, $fd, $2d, $83, $00, $81, $4e, $fc, $2d, $85, $00, $51, $02, $70, $4e, $fb, $2d, $83, $00, $81, $4e, $fa, $2d
	.byte $85, $00, $4e, $f9, $2d, $83, $00, $81, $4e, $f8, $2d, $85, $00, $4e, $f7, $2d, $83, $00, $81, $4e, $f6, $2d, $85, $00
	.byte $4e, $f5, $2d, $83, $00, $81, $4e, $f4, $2d, $83, $4e, $f3, $81, $00, $4e, $f2, $2d, $83, $00, $81, $4e, $f1, $2d, $85
	.byte $00, $4e, $f0, $2d, $83, $00, $81, $4e, $ef, $2d, $85, $00, $48, $51, $fe, $00, $4e, $ee, $2d, $83, $00, $81, $4e, $ed
	.byte $2d, $85, $00, $4e, $ec, $2d, $83, $00, $81, $4e, $eb, $2d, $85, $00, $4e, $ea, $2d, $83, $00, $81, $4e, $e9, $2d, $85
	.byte $00, $4e, $e8, $2d, $83, $00, $81, $4e, $e7, $2d, $83, $4e, $e6, $81, $00, $4e, $e5, $2d, $83, $00, $81, $4e, $e4, $2d
	.byte $85, $00, $4e, $e3, $2d, $83, $00, $81, $4e, $e2, $2d, $83, $4e, $e1, $81, $00, $4e, $e0, $2d, $83, $4e, $df, $00, $81
	.byte $4e, $de, $2d, $85, $00, $4e, $dd, $2d, $83, $00, $81, $4e, $dc, $2d, $85, $00, $48, $7d, $4e, $00, $8c
@song0ref230:
	.byte $2e, $87, $8e, $2e, $87, $8c, $2e, $a3, $00, $2e, $87, $8e, $2e, $87, $8c, $2e, $a3, $00, $2e, $87, $8e, $2e, $87, $8c
	.byte $2e, $91, $48, $91, $00
	.byte $41, $12
	.word @song0ref230
@song0ref262:
	.byte $48, $8c, $2e, $91, $4e, $ff, $91, $00, $2e, $81, $4e, $fe, $85, $8e, $2e, $87, $8c, $2e, $87, $4e, $fd, $93, $4e, $fc
	.byte $87, $00, $2e, $87, $8e, $2e, $4e, $fb, $87, $8c, $2e, $8b, $4e, $fa, $95, $4e, $f9, $81, $00, $48, $2e, $87, $8e, $2e
	.byte $4e, $f8, $87, $8c, $2e, $8b, $4e, $f7, $95, $4e, $f6, $81, $00, $2e, $87, $8e, $2e, $83, $4e, $f5, $83, $8c, $2e, $87
	.byte $4e, $f4, $8d, $4e, $f3, $8d, $00, $4e, $f2, $2e, $91, $8e, $2e, $87, $4e, $00, $00, $87, $48, $93, $49, .lobyte(@env46)
	.byte .hibyte(@env46), $94, $2e, $91, $94, $2c, $91, $28, $a5, $25, $a5, $1c, $91, $48, $26, $cd, $2b, $cd, $48, $29, $b9
	.byte $1d, $87, $24, $87, $29, $cd, $48, $27, $ff, $9d, $48, $22, $91, $20, $91, $22, $91, $28, $91, $22, $91, $28, $91, $2a
	.byte $91, $2e, $91, $48, $32, $91, $2e, $91, $2b, $91, $28, $91, $24, $81, $00, $83, $43, $24, $83, $00, $81, $43, $24, $81
	.byte $00, $83, $43, $24, $83, $00, $81, $43, $24, $81, $00, $83, $43, $24, $83, $00, $81, $43, $24, $81, $00, $83, $43, $24
	.byte $83, $00, $81, $48, $29, $b9, $1d, $87, $24, $87, $29, $cd, $48, $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c, $2c
	.byte $a5, $2c, $b9, $2a, $91, $2a, $a5, $48, $2e, $91, $a2, $1d, $91, $29, $91, $1d, $91, $27, $91, $1d, $91, $29, $91, $1d
	.byte $91, $48, $2a, $b9, $29, $87, $2a, $87, $29, $a5, $2a, $a5, $48, $27, $a5, $45, $91, $20, $87, $23, $87, $27, $91, $23
	.byte $91, $22, $91, $20, $91, $48, $22, $87, $23, $87, $7f, $49, .lobyte(@env46), .hibyte(@env46), $94, $22, $87, $94, $23
	.byte $87, $27, $87, $22, $87, $27, $87, $29, $87, $2e, $a5, $7d, $49, .lobyte(@env0), .hibyte(@env0), $4a, $a2, $20, $91
	.byte $22, $91, $48, $23, $91, $22, $91, $23, $91, $27, $91, $45, $91, $29, $91, $2c, $91, $2e, $91, $48, $93, $2a, $a5, $29
	.byte $a5, $27, $a5, $23, $91, $48, $20, $a5, $45, $91, $20, $83, $22, $85, $23, $83, $27, $b9, $45, $91, $48, $29, $91, $2a
	.byte $91, $29, $91, $27, $91, $29, $87, $27, $87, $22, $87, $20, $87, $23, $87, $22, $87, $20, $87, $1d, $87, $48, $49, .lobyte(@env46)
	.byte .hibyte(@env46), $94, $29, $a5, $94, $2e, $91, $2c, $87, $98, $2c, $91, $00, $87, $94, $2e, $87, $98, $2e, $91, $00
	.byte $87, $94, $2c, $91, $48, $49, .lobyte(@env0), .hibyte(@env0), $4a, $93, $a2, $20, $91, $25, $91, $27, $91, $2c, $a5
	.byte $45, $a5, $48, $94, $25, $a5, $2a, $91, $29, $87, $98, $29, $91, $00, $87, $94, $2a, $87, $98, $2a, $91, $00, $87, $94
	.byte $29, $91, $48, $93, $a2, $2c, $91, $27, $91, $25, $91, $20, $a5, $45, $a5, $48, $94, $22, $91, $21, $91, $22, $91, $24
	.byte $91, $98, $24, $91, $94, $25, $91, $98, $25, $91, $94, $27, $91, $48, $29, $eb, $45, $9b, $29, $91, $48, $93, $2a, $91
	.byte $2c, $91, $2e, $91, $98, $2e, $91, $94, $33, $91, $98, $33, $91, $94, $31, $91, $48, $30, $87, $31, $87, $30, $e1, $45
	.byte $a5, $48, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8c, $2e, $87, $8e, $2e, $87, $4e, $ff, $8c, $2e, $8f, $4e, $fe
	.byte $93, $4e, $fd, $00, $2e, $87, $8e, $2e, $83, $4e, $fc, $83, $8c, $2e, $89, $4e, $fb, $95, $4e, $fa, $83, $00, $2e, $87
	.byte $8e, $2e, $85, $4e, $f9, $81, $8c, $2e, $91, $48, $4e, $f8, $91, $00, $4e, $f7, $2e, $87, $8e, $2e, $87, $4e, $f6, $8c
	.byte $2e, $91, $4e, $f5, $91, $00, $4e, $f4, $2e, $81, $00, $83, $2e, $83, $00, $81, $4e, $f3, $2e, $81, $00, $83, $2e, $83
	.byte $00, $81, $4e, $f2, $2e, $81, $00, $83, $2e, $83, $00, $81, $2e, $81, $00, $83, $2e, $83, $00, $81, $48, $4e, $00, $9f
	.byte $29, $81, $2b, $2e, $30, $a5, $2e, $91, $2c, $87, $8e, $2c, $87, $8c, $2b, $91, $2c, $91, $48, $93, $29, $91, $2b, $87
	.byte $8e, $2b, $87, $8c, $2c, $a5, $29, $91, $2b, $87, $8e, $2b, $87, $8c, $2c, $91, $48, $93, $2e, $a5, $30, $91, $33, $91
	.byte $31, $87, $8e, $31, $87, $8c, $30, $87, $8e, $30, $87, $8c, $2e, $91, $48, $93, $2b, $a5, $2c, $cd, $8e, $2c, $91, $48
	.byte $00, $a5, $8c, $29, $a5, $28, $91, $29, $87, $8e, $29, $87, $8c, $2b, $87, $8e, $2b, $87, $8c, $2e, $91, $48, $93, $30
	.byte $91, $2e, $87, $8e, $2e, $87, $8c, $2c, $af, $8e, $2c, $91, $00, $87, $8c, $31, $91, $48, $93, $30, $87, $8e, $30, $87
	.byte $8c, $2c, $91, $29, $87, $8e, $29, $87, $8c, $2c, $87, $29, $87, $2e, $a5, $2c, $91, $48, $7f, $a6, $2c, $87, $2b, $87
	.byte $2c, $87, $2e, $87, $30, $87, $2e, $87, $30, $87, $31, $87, $33, $87, $31, $87, $33, $87, $35, $87, $36, $87, $35, $87
	.byte $33, $87, $31, $87, $48, $00, $9d, $8c, $29, $81, $2b, $2e, $4b, .lobyte(@env53), .hibyte(@env53), $30, $a5, $4b, .lobyte(@env31)
	.byte .hibyte(@env31), $2e, $91, $4d, $2c, $87, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $8e, $2c, $87, $4b, .lobyte(@env31)
	.byte .hibyte(@env31), $8c, $2b, $91, $4d, $2c, $91, $48, $93, $4b, .lobyte(@env24), .hibyte(@env24), $29, $91, $4b, .lobyte(@env53)
	.byte .hibyte(@env53), $2b, $87, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $8e, $2b, $87, $4b, .lobyte(@env31), .hibyte(@env31)
	.byte $8c, $2c, $a5, $4b, .lobyte(@env53), .hibyte(@env53), $29, $91, $4d, $2b, $87, $4b, .lobyte(@env34), .hibyte(@env34)
	.byte $4c, $8e, $2b, $87, $4b, .lobyte(@env31), .hibyte(@env31), $8c, $2c, $91, $48, $93, $4d, $2e, $a5, $4b, .lobyte(@env53)
	.byte .hibyte(@env53), $30, $91, $4b, .lobyte(@env31), .hibyte(@env31), $33, $91, $4d, $31, $87, $4b, .lobyte(@env34), .hibyte(@env34)
	.byte $4c, $8e, $31, $87, $4b, .lobyte(@env53), .hibyte(@env53), $8c, $30, $87, $4b, .lobyte(@env34), .hibyte(@env34), $4c
	.byte $8e, $30, $87, $4b, .lobyte(@env31), .hibyte(@env31), $8c, $2e, $91, $48, $93, $4b, .lobyte(@env53), .hibyte(@env53)
	.byte $2b, $a5, $4b, .lobyte(@env31), .hibyte(@env31), $2c, $cd, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $8e, $2c, $8d
	.byte $8c, $26, $28, $48, $4b, .lobyte(@env53), .hibyte(@env53), $29, $87, $00, $83, $4b, .lobyte(@env34), .hibyte(@env34)
	.byte $4c, $8e, $26, $28, $4b, .lobyte(@env53), .hibyte(@env53), $29, $87, $00, $87, $4d, $8c, $29, $a5, $4d, $28, $91, $4b
	.byte .lobyte(@env31), .hibyte(@env31), $29, $87, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $8e, $29, $87, $4b, .lobyte(@env31)
	.byte .hibyte(@env31), $8c, $2b, $87, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $8e, $2b, $87, $4b, .lobyte(@env31), .hibyte(@env31)
	.byte $8c, $2e, $91, $48, $93, $4d, $2c, $91, $4d, $2b, $87, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $8e, $2b, $87, $4b
	.byte .lobyte(@env31), .hibyte(@env31), $8c, $2c, $b9, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $8e, $2c, $87, $8c, $29
	.byte $2b, $81, $2c, $2e, $2f, $91, $48, $93, $2d, $87, $8e, $2d, $87, $8c, $2b, $91, $28, $87, $8e, $28, $87, $8c, $2b, $87
	.byte $28, $87, $2d, $a5, $2f, $91, $48, $cf, $8e, $2f, $91, $00, $a1, $8c, $2c, $2e, $30, $91, $48, $93, $2e, $87, $8e, $2e
	.byte $87, $8c, $2c, $91, $29, $87, $8e, $29, $87, $8c, $2c, $87, $29, $87, $2e, $a5, $30, $91, $48, $cf, $8e, $30, $91, $00
	.byte $a1, $8c, $2c, $2e, $30, $91, $48, $51, $fd, $00, $30, $87, $8e, $30, $87, $8c, $30, $87, $8e, $30, $87, $8c, $30, $87
	.byte $8e, $30, $87, $8c, $30, $87, $8e, $30, $87, $8c, $30, $87, $00, $87, $30, $87, $00, $87, $30, $87, $00, $87, $30, $87
	.byte $00, $87, $48, $30, $87, $00, $87, $30, $87, $7f, $00, $d7
	.byte $41, $91
	.word @song0ref17
	.byte $41, $12
	.word @song0ref230
	.byte $41, $93
	.word @song0ref262
	.byte $a5, $00, $f5, $44, $00
@song0ch1:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $f7
@song0ref1446:
	.byte $9c, $21, $a5, $4b, .lobyte(@env49), .hibyte(@env49), $a0, $20, $ff, $9d, $4b, .lobyte(@env56), .hibyte(@env56), $20
	.byte $ff, $9d, $4b, .lobyte(@env49), .hibyte(@env49), $20, $ff, $9d, $4b, .lobyte(@env29), .hibyte(@env29), $1e, $cd, $4b
	.byte .lobyte(@env28), .hibyte(@env28), $1d, $a5, $4b, .lobyte(@env9), .hibyte(@env9), $1d, $a5, $4b, .lobyte(@env49), .hibyte(@env49)
	.byte $20, $ff, $9d, $4b, .lobyte(@env56), .hibyte(@env56), $20, $ff, $9d, $4b, .lobyte(@env49), .hibyte(@env49), $20, $ff
	.byte $9d, $4b, .lobyte(@env29), .hibyte(@env29), $1e, $cd, $4b, .lobyte(@env28), .hibyte(@env28), $1d, $a5, $4b, .lobyte(@env9)
	.byte .hibyte(@env9), $1d, $a5, $4d, $1c, $cd, $4b, .lobyte(@env16), .hibyte(@env16), $1c, $cd, $4b, .lobyte(@env30), .hibyte(@env30)
	.byte $1a, $cd, $4b, .lobyte(@env23), .hibyte(@env23), $1a, $cd, $4b, .lobyte(@env14), .hibyte(@env14), $1d, $ff, $9d, $4b
	.byte .lobyte(@env16), .hibyte(@env16), $1b, $cd, $4b, .lobyte(@env27), .hibyte(@env27), $1b, $87, $00, $87, $4d, $1b, $b9
	.byte $4b, .lobyte(@env33), .hibyte(@env33), $1c, $cd, $4b, .lobyte(@env16), .hibyte(@env16), $1c, $cd, $4b, .lobyte(@env30)
	.byte .hibyte(@env30), $1a, $cd, $4b, .lobyte(@env23), .hibyte(@env23), $1a, $81, $00, $83, $43, $1a, $83, $00, $81, $43
	.byte $1a, $83, $00, $81, $43, $1a, $83, $00, $81, $43, $1a, $83, $00, $81, $43, $1a, $83, $00, $81, $43, $1a, $83, $00, $81
	.byte $43, $1a, $83, $00, $81, $4b, .lobyte(@env35), .hibyte(@env35), $1d, $ff, $9d, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $9c, $20, $a5, $20, $b9, $1e, $91, $1e, $a5, $4b, .lobyte(@env39)
	.byte .hibyte(@env39), $a0, $20, $ff, $9d, $4b, .lobyte(@env55), .hibyte(@env55), $1e, $ff, $9d, $4b, .lobyte(@env49), .hibyte(@env49)
	.byte $1e, $ff, $9d, $4b, .lobyte(@env61), .hibyte(@env61), $1d, $ff, $9d, $4b, .lobyte(@env25), .hibyte(@env25), $22, $ff
	.byte $9d, $4b, .lobyte(@env55), .hibyte(@env55), $1e, $ff, $9d, $4b, .lobyte(@env49), .hibyte(@env49), $1e, $ff, $9d, $4b
	.byte .lobyte(@env9), .hibyte(@env9), $1d, $cd, $4b, .lobyte(@env27), .hibyte(@env27), $1d, $cd, $4b, .lobyte(@env23), .hibyte(@env23)
	.byte $1d, $9b, $00, $87, $4d, $1d, $87, $00, $87, $4d, $1d, $87, $00, $9b, $4d, $1d, $b9, $4b, .lobyte(@env42), .hibyte(@env42)
	.byte $1d, $9b, $00, $87, $4d, $1d, $87, $00, $87, $4d, $1d, $87, $00, $d7, $4b, .lobyte(@env4), .hibyte(@env4), $1e, $9b
	.byte $00, $87, $4d, $1e, $87, $00, $87, $4d, $1e, $87, $00, $9b, $4d, $1e, $b9, $4b, .lobyte(@env1), .hibyte(@env1), $1d
	.byte $9b, $00, $87, $4d, $1d, $87, $00, $87, $4d, $1d, $87, $00, $87, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $94, $24
	.byte $cd, $4b, .lobyte(@env23), .hibyte(@env23), $a0, $1d, $b9, $4d, $1d, $cd, $4b, .lobyte(@env14), .hibyte(@env14), $1d
	.byte $91, $bb, $4d, $1d, $cd, $4b, .lobyte(@env49), .hibyte(@env49), $1b, $91, $bb, $4b, .lobyte(@env29), .hibyte(@env29)
	.byte $1b, $e1, $4b, .lobyte(@env62), .hibyte(@env62), $21, $91, $4d, $21, $87, $00, $ff, $73, $89, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $4b, .lobyte(@env34), .hibyte(@env34), $4c, $8c, $2e, $87, $00, $87, $4e, $ff, $2e, $8f, $4e, $fe, $93, $4e, $fd
	.byte $00, $2e, $87, $00, $83, $4e, $fc, $83, $2e, $89, $4e, $fb, $95, $4e, $fa, $83, $00, $2e, $87, $00, $85, $4e, $f9, $81
	.byte $2e, $87, $70, $51, $03, $f0, $4e, $00, $4b, .lobyte(@env52), .hibyte(@env52), $a8, $50, $fb, $27, $33, $ff, $9d, $4b
	.byte .lobyte(@env1), .hibyte(@env1), $a0, $24
@song0ref1879:
	.byte $b9, $4b, .lobyte(@env27), .hibyte(@env27), $22, $cd, $4b, .lobyte(@env1), .hibyte(@env1), $1f, $91, $bb, $4b, .lobyte(@env30)
	.byte .hibyte(@env30), $1d, $cd, $4b, .lobyte(@env59), .hibyte(@env59), $20, $91, $bb, $4b, .lobyte(@env4), .hibyte(@env4)
	.byte $1f, $cd, $4b, .lobyte(@env1), .hibyte(@env1), $1f, $91, $bb, $4b, .lobyte(@env35), .hibyte(@env35), $20, $e1, $4b
	.byte .lobyte(@env49), .hibyte(@env49), $20, $b9, $4b, .lobyte(@env4), .hibyte(@env4), $1f, $cd, $4b, .lobyte(@env32), .hibyte(@env32)
	.byte $1f, $91, $bb, $4b, .lobyte(@env35), .hibyte(@env35), $1e, $cd, $4b, .lobyte(@env1), .hibyte(@env1), $1d, $91, $bb
	.byte $4b, .lobyte(@env4), .hibyte(@env4), $1f, $cd, $4b, .lobyte(@env59), .hibyte(@env59), $20, $91, $cf, $4b, .lobyte(@env33)
	.byte .hibyte(@env33), $21, $cd, $4b, .lobyte(@env45), .hibyte(@env45), $22
	.byte $41, $14
	.word @song0ref1879
	.byte $4b, .lobyte(@env16), .hibyte(@env16), $22, $cd, $4b, .lobyte(@env1), .hibyte(@env1), $1f, $91, $bb, $4b, .lobyte(@env55)
	.byte .hibyte(@env55), $20, $cd, $4b, .lobyte(@env4), .hibyte(@env4), $1f, $91, $ff, $9f, $ff, $8b, $4d, $20, $91, $ff, $9f
	.byte $ff, $9f, $51, $fd, $00
@song0ref2003:
	.byte $43, $20, $87, $00, $87, $43, $20, $87, $00, $87, $43, $20, $87, $00, $87, $43, $20, $87, $00, $87, $43, $20, $87, $00
	.byte $87
	.byte $41, $12
	.word @song0ref2003
	.byte $7f, $00, $d7, $4b, .lobyte(@env34), .hibyte(@env34), $4c
	.byte $41, $64
	.word @song0ref1446
	.byte $22, $a5, $00, $f5, $44, $00
@song0ch2:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
@song0ref2060:
	.byte $86
@song0ref2061:
	.byte $16, $91, $22, $91, $84, $50, $2c, $36, $2d, $87, $8a, $20, $87, $86, $1d, $91, $1b, $87, $19, $87, $16, $87, $1b, $87
	.byte $84, $50, $2c, $36, $2d, $87, $8a, $1b, $87, $86, $1d, $91, $16, $91, $22, $91, $84, $50, $2c, $36, $2d, $87, $8a, $20
	.byte $87, $86, $1d, $91, $1b, $87, $84, $50, $23, $3a, $31, $87, $86, $16, $87, $1b, $87, $84, $50, $48, $34, $28, $87, $8a
	.byte $1b, $87, $86, $1d, $91
	.byte $41, $18
	.word @song0ref2061
@song0ref2141:
	.byte $1b, $91, $1b, $91, $84, $50, $2c, $36, $2d, $87, $86, $19, $87, $16, $87, $14, $87, $11, $87, $1d, $87, $18, $87, $16
	.byte $87, $84, $50, $2c, $36, $2d, $87, $8a, $1d, $87, $84, $50, $20, $3e, $34, $87, $50, $21, $3b, $32, $87
	.byte $41, $30
	.word @song0ref2060
	.byte $41, $18
	.word @song0ref2061
	.byte $41, $1c
	.word @song0ref2141
@song0ref2195:
	.byte $86, $12, $91, $1e, $91, $84, $50, $2c, $36, $2d, $87, $8a, $1c, $87, $86, $19, $91, $17, $87, $15, $87, $12, $87, $17
	.byte $87, $84, $50, $2c, $36, $2d, $87, $8a, $17, $87, $86, $19, $91, $18, $91, $24, $91, $84, $50, $25, $39, $30, $87, $86
	.byte $22, $87, $1f, $91, $1c, $87, $18, $87, $16, $87, $1c, $87, $84, $50, $25, $39, $30, $87, $8a, $1c, $87, $86, $1f, $91
@song0ref2267:
	.byte $1d, $91, $29, $91, $84, $50, $25, $39, $30, $87, $8a, $27, $87, $86, $24, $91, $22, $87, $20, $87, $1d, $87, $1b, $87
	.byte $84, $50, $2c, $36, $2d, $87, $8a, $1b, $87, $86, $1e, $91, $1d, $91, $1d, $91, $84, $50, $2c, $36, $2d, $87, $8a, $14
	.byte $87, $86, $14, $87, $15, $87, $15, $91, $18, $91, $84, $50, $1e, $3d, $34, $87, $50, $1e, $3d, $34, $87, $50, $1e, $3d
	.byte $34, $87, $50, $1e, $3d, $34, $87
	.byte $41, $1c
	.word @song0ref2195
@song0ref2349:
	.byte $84, $50, $2c, $36, $2d, $87, $8a, $22, $87, $86, $1f, $91, $1d, $83, $00, $81, $1d, $83, $00, $81, $1d, $83, $00, $81
	.byte $1d, $83, $00, $81, $1d, $83, $00, $81, $1d, $83, $00, $81, $1d, $83, $00, $81, $1d, $83, $00, $81
	.byte $41, $19
	.word @song0ref2267
@song0ref2396:
	.byte $9b, $84, $50, $18, $41, $38, $87, $86, $1e, $87, $84, $50, $1c, $3e, $35, $87, $00, $a5, $86, $18, $91, $84, $50, $1e
	.byte $3d, $34, $87, $86, $18, $87, $84, $50, $19, $40, $37, $87, $50, $18, $41, $38, $87, $86, $16, $b9, $16, $91, $84, $50
	.byte $20, $34, $29, $91, $86, $20, $a5, $1f, $91, $1e, $b9, $17, $91, $84, $50, $1c, $34, $2a, $91, $8a, $17, $b9, $86, $14
	.byte $b9, $14, $91, $84, $50, $1c, $34, $2a, $91, $86, $1e, $a5, $1d, $91, $16, $b9, $16, $91, $84, $50, $1c, $34, $2a, $91
	.byte $86, $17, $91, $1d, $a5, $17, $b9, $17, $91, $84, $50, $1c, $34, $2a, $91, $86, $1e, $a5, $1b, $91, $17, $b9, $17, $91
	.byte $84, $50, $1c, $34, $2a, $91, $8a, $17, $b9, $86, $14, $91, $14, $91, $84, $50, $1c, $34, $2a, $91, $86, $14, $91, $14
	.byte $91, $1e, $91, $84, $50, $1c, $34, $2a, $91, $86, $1d, $91, $11, $91, $1d, $91, $84, $50, $1c, $34, $2a, $91, $86, $1d
	.byte $91, $84, $50, $1c, $3e, $35, $87, $50, $19, $40, $37, $87, $86, $19, $87, $19, $87, $84, $50, $16, $42, $39, $87, $86
	.byte $50, $3a, $25, $20, $87, $84, $50, $1c, $3e, $35, $87, $50, $21, $3b, $32, $87, $86, $12, $91, $12, $8d, $00, $81, $84
	.byte $50, $1c, $34, $2a, $91, $86, $12, $83, $00, $9f, $12, $91, $84, $50, $1c, $34, $2a, $91, $8a, $12, $91, $86, $11, $91
	.byte $11, $8d, $00, $81, $11, $87, $00, $87, $11, $83, $00, $db, $1b, $91, $1b, $8d, $00, $81, $84, $50, $1c, $34, $2a, $91
	.byte $86, $1b, $83, $00, $9f, $1b, $91, $84, $50, $1c, $34, $2a, $91, $8a, $1b, $91, $86, $19, $91, $19, $8d, $00, $81, $19
	.byte $87, $00, $87, $19, $83, $00, $db, $16, $9b, $16, $87, $84, $50, $1c, $34, $2a, $91, $86, $16, $91, $16, $9b, $16, $87
	.byte $84, $50, $1c, $34, $2a, $91, $86, $15, $91, $89, $15, $87, $00, $91, $84, $50, $1c, $34, $2a, $91, $86, $15, $9b, $84
	.byte $50, $22, $32, $2a, $8b, $8a, $15, $8d, $84, $50, $1c, $34, $2a, $91, $86, $14, $91, $89, $14, $87, $00, $91, $84, $50
	.byte $20, $36, $2a, $91, $86, $18, $9b, $18, $87, $00, $91, $84, $50, $20, $36, $2a, $91, $86, $18, $91, $1d, $91, $1d, $91
	.byte $84, $50, $20, $36, $2a, $91, $00, $9b, $50, $19, $40, $37, $87, $50, $18, $41, $38, $87, $50, $16, $42, $39, $87, $50
	.byte $13, $41, $34, $91, $50, $1e, $3d, $34, $87, $50, $21, $3b, $32, $87, $00, $a5, $50, $2f, $3d, $29, $91, $00, $b9, $50
	.byte $2f, $3d, $29, $91, $00, $91, $a7, $50, $24, $36, $29, $91, $00, $9b, $50, $1a, $3f, $36, $87, $50, $1a, $3f, $36, $87
	.byte $50, $1a, $3f, $36, $87, $50, $1a, $3f, $36, $87, $50, $1a, $3f, $36, $87, $50, $1a, $3f, $36, $87, $50, $1a, $3f, $36
	.byte $87, $86
@song0ref2878:
	.byte $16, $9b, $16, $87, $84, $50, $3b, $39, $25, $91, $86, $18, $91, $18, $9b, $18, $87, $84, $50, $35, $3b, $27, $91, $86
	.byte $1d, $91, $1d, $9b, $1d, $87, $84, $50, $3b, $39, $25, $91, $86, $1b, $91, $1b, $87, $84, $50, $2a, $37, $2e, $87, $8a
	.byte $1b, $87, $86, $1b, $87, $84, $50, $35, $3b, $27, $91, $86, $16, $91
	.byte $41, $16
	.word @song0ref2878
	.byte $86, $1d, $91, $1d, $87, $84, $50, $2a, $37, $2e, $87, $8a, $1d, $87, $86, $1d, $87, $84, $50, $35, $3b, $27, $91, $86
	.byte $1d, $91
	.byte $41, $24
	.word @song0ref2878
	.byte $16, $9b, $16, $87, $84, $50, $3b, $39, $25, $91, $86, $1b, $91, $1b, $9b, $1b, $87, $84, $50, $35, $3b, $27, $91, $86
	.byte $14, $91, $14, $9b, $14, $87, $84, $50, $3b, $39, $25, $91, $86, $14, $91, $15, $87, $84, $50, $2a, $37, $2e, $87, $8a
	.byte $15, $87, $86, $15, $87, $84, $50, $35, $3b, $27, $91, $86, $15, $91
	.byte $41, $24
	.word @song0ref2878
	.byte $41, $16
	.word @song0ref2878
	.byte $86, $1d, $91, $1d, $87, $84, $50, $2a, $37, $2e, $87, $8a, $1d, $87, $86, $1d, $87, $84, $50, $35, $3b, $27, $91, $86
	.byte $1d, $91
	.byte $41, $1c
	.word @song0ref2878
	.byte $86, $1b, $87, $1d, $87, $84, $50, $35, $3b, $27, $91, $86, $15, $91, $15, $9b, $21, $87, $84, $50, $3b, $39, $25, $91
	.byte $86, $15, $91, $15, $9b, $21, $87, $84, $50, $35, $3b, $27, $91, $86, $15, $91, $15, $9b, $21, $87, $84, $50, $3b, $39
	.byte $25, $91, $86, $15, $91, $15, $87, $84, $50, $2a, $37, $2e, $87, $8a, $15, $87, $86, $15, $87, $84, $50, $35, $3b, $27
	.byte $91, $86, $16, $91, $a7, $84, $50, $3b, $39, $25, $91, $8a, $16, $b9, $84, $50, $35, $3b, $27, $91, $8a, $16, $91, $a7
	.byte $84, $50, $3b, $39, $25, $91, $8a, $16, $9b, $84, $50, $2a, $37, $2e, $87, $8a, $16, $91, $84, $50, $35, $3b, $27, $91
	.byte $8a, $16, $91, $86, $16, $87, $00, $87, $16, $87, $00, $87, $16, $87, $00, $87, $16, $83, $00, $8b, $16, $83, $00, $8b
	.byte $16, $83, $00, $b3, $ff, $9f
	.byte $41, $30
	.word @song0ref2061
	.byte $41, $18
	.word @song0ref2061
	.byte $41, $1c
	.word @song0ref2141
	.byte $41, $30
	.word @song0ref2060
	.byte $41, $18
	.word @song0ref2061
	.byte $41, $1c
	.word @song0ref2141
	.byte $41, $60
	.word @song0ref2195
	.byte $41, $1c
	.word @song0ref2195
	.byte $41, $26
	.word @song0ref2349
	.byte $41, $19
	.word @song0ref2267
	.byte $41, $15
	.word @song0ref2396
	.byte $00, $e1, $44, $00
@song0ch3:
	.byte $ff, $9f, $ff, $9f, $a7, $88, $1e, $87, $00, $eb, $a7, $1e, $87, $00, $eb, $a7, $1e, $87, $00, $c3
@song0ref3277:
	.byte $1e, $87, $00, $9b, $a7, $1e, $87, $00, $9b, $1e, $87, $00, $9b, $96, $22, $a5, $1f, $a5, $88, $1e, $87, $80, $22, $87
	.byte $82, $22, $87, $80
@song0ref3305:
	.byte $22
@song0ref3306:
	.byte $87
@song0ref3307:
	.byte $82, $22, $87
@song0ref3310:
	.byte $80, $22, $87, $82, $22, $87, $80, $22, $87, $88, $1e, $87, $80, $22, $87, $82, $22, $87, $80, $22, $87, $82, $22, $87
@song0ref3334:
	.byte $80, $22, $87, $82, $22, $87, $80, $22, $87, $88, $1e, $87, $80, $22, $87, $82, $22, $87, $80, $22, $87, $82, $22, $87
	.byte $88, $1e, $87, $82, $22, $87, $80, $22, $87, $88, $1e, $87, $80, $22, $87, $82, $22, $87, $9e
	.byte $41, $24
	.word @song0ref3305
	.byte $41, $1a
	.word @song0ref3310
	.byte $88, $1e, $87, $1e
	.byte $41, $23
	.word @song0ref3306
	.byte $41, $1c
	.word @song0ref3334
	.byte $9e
	.byte $41, $24
	.word @song0ref3305
	.byte $41, $18
	.word @song0ref3310
	.byte $1e, $87, $1e, $87, $1e
	.byte $41, $23
	.word @song0ref3306
	.byte $41, $1c
	.word @song0ref3310
	.byte $9e
	.byte $41, $24
	.word @song0ref3305
	.byte $41, $18
	.word @song0ref3310
	.byte $1e, $87, $1e, $87, $1e
	.byte $41, $23
	.word @song0ref3306
@song0ref3426:
	.byte $80, $22, $87, $82, $22, $87, $80, $22, $87, $88, $1e, $87, $80, $22, $87, $82, $22, $87, $80, $22, $83, $00, $81, $22
	.byte $83, $00, $81, $22, $83, $00, $81, $22, $83, $00, $81, $22, $83, $00, $81, $22, $83, $00, $81, $22, $83, $00, $81, $22
	.byte $83, $00, $81, $22, $83, $00, $81
	.byte $41, $20
	.word @song0ref3307
@song0ref3484:
	.byte $96, $22, $a5, $22, $a5, $82, $22, $87, $80, $22, $87, $82, $22, $87, $80, $22, $87, $88, $1e, $87, $80, $22, $87, $88
	.byte $1e, $87, $1e, $87, $96, $1f
@song0ref3514:
	.byte $a5, $9a
@song0ref3516:
	.byte $21, $a5, $88, $1e, $91, $00, $91, $9a, $21, $a5, $00, $a5, $21, $a5, $88, $1e, $91, $90, $21, $91, $9a, $21, $a5, $00
	.byte $a5
	.byte $41, $12
	.word @song0ref3516
	.byte $96, $22
	.byte $41, $13
	.word @song0ref3514
	.byte $41, $22
	.word @song0ref3307
	.byte $80, $22, $87, $82, $22, $87, $80, $22, $87, $88, $1e, $87, $80, $22, $87, $82, $22, $87, $80, $22, $87, $88, $1e, $87
	.byte $1e, $87, $00, $91, $1e, $91, $1e, $87, $00, $87, $96, $1f, $a5
@song0ref3589:
	.byte $88, $1e, $87, $00, $87, $90, $21, $a5, $21, $91, $88, $1e, $87, $00, $87, $90, $21, $91, $93, $00, $cd, $80, $22, $87
	.byte $22, $87, $22, $87, $22, $87, $90, $21, $91, $93, $21, $91
	.byte $41, $1e
	.word @song0ref3589
@song0ref3628:
	.byte $88, $1e, $87, $00, $87, $90, $21, $a5, $21, $91, $88, $1e, $87, $00, $87, $90, $21, $91, $93, $21, $91, $88, $1e, $87
	.byte $00, $87, $90, $21, $9b, $88, $1e, $87, $90, $21, $91, $88, $1e, $87, $00, $87, $90, $21, $91, $93, $21, $91
	.byte $41, $18
	.word @song0ref3628
	.byte $83, $1e, $81, $90, $21, $87, $88, $1e, $87, $1e, $91, $90, $21, $87, $88, $1e
	.byte $41, $23
	.word @song0ref3306
	.byte $41, $1e
	.word @song0ref3310
	.byte $96
@song0ref3700:
	.byte $1f, $a5
@song0ref3702:
	.byte $92, $1e, $91, $82, $22, $87, $80, $22, $87, $90, $21
@song0ref3713:
	.byte $91, $82, $22, $87, $80, $22, $83, $22, $81
@song0ref3722:
	.byte $92, $1f, $91, $82, $22, $87, $80, $22, $87, $90, $21, $91, $82, $22, $87, $80, $22, $87, $92, $1e, $91, $82, $22, $87
	.byte $80, $22, $87, $90, $21, $87, $88, $1e, $87, $82, $22, $87, $80, $22, $87
	.byte $41, $13
	.word @song0ref3722
	.byte $41, $19
	.word @song0ref3713
	.byte $96, $22, $a5, $22, $a5, $90, $21, $91, $82, $22, $87, $80, $22, $87
	.byte $41, $28
	.word @song0ref3702
	.byte $41, $13
	.word @song0ref3722
	.byte $41, $19
	.word @song0ref3713
	.byte $96, $22, $a5, $22, $a5
	.byte $41, $2a
	.word @song0ref3700
	.byte $41, $13
	.word @song0ref3722
	.byte $41, $21
	.word @song0ref3713
	.byte $41, $13
	.word @song0ref3722
	.byte $41, $21
	.word @song0ref3713
	.byte $41, $13
	.word @song0ref3722
	.byte $41, $21
	.word @song0ref3713
	.byte $41, $13
	.word @song0ref3722
	.byte $41, $21
	.word @song0ref3713
	.byte $92, $1f, $91, $82, $22, $87, $80, $22, $87, $90, $21, $51, $fc, $b0, $91, $21, $91, $7f, $88, $1e, $87, $7a, $51, $fd
	.byte $40, $00, $87, $90, $21, $91, $21, $91, $21, $91, $7f, $88
	.byte $41, $47
	.word @song0ref3277
	.byte $9e
	.byte $41, $24
	.word @song0ref3305
	.byte $41, $1a
	.word @song0ref3310
	.byte $88, $1e, $87, $1e
	.byte $41, $23
	.word @song0ref3306
	.byte $41, $1c
	.word @song0ref3334
	.byte $9e
	.byte $41, $24
	.word @song0ref3305
	.byte $41, $18
	.word @song0ref3310
	.byte $1e, $87, $1e, $87, $1e
	.byte $41, $23
	.word @song0ref3306
	.byte $41, $1c
	.word @song0ref3310
	.byte $9e
	.byte $41, $24
	.word @song0ref3305
	.byte $41, $18
	.word @song0ref3310
	.byte $1e, $87, $1e, $87, $1e
	.byte $41, $23
	.word @song0ref3306
	.byte $41, $30
	.word @song0ref3426
	.byte $41, $20
	.word @song0ref3307
	.byte $41, $15
	.word @song0ref3484
	.byte $cd, $00, $cd, $44, $00
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
@song0ref3934:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $12
	.word @song0ref3934
	.byte $41, $12
	.word @song0ref3934
	.byte $41, $12
	.word @song0ref3934
	.byte $41, $12
	.word @song0ref3934
	.byte $41, $12
	.word @song0ref3934
	.byte $41, $12
	.word @song0ref3934
	.byte $41, $12
	.word @song0ref3934
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $44, $00
