; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Rave Racer:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_rave_racer_2A03:=music_data_rave_racer_2A03

music_data_rave_racer_2A03:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Euphoria
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_rave_racer
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env29,@env17,@env21,@env1 ; 00 : HiHat Long
	.word @env27,@env17,@env21,@env1 ; 01 : HiHat
	.word @env12,@env31,@env21,@env1 ; 02 : Kick
	.word @env6,@env8,@env21,@env1 ; 03 : Snare Short
	.word @env0,@env9,@env21,@env1 ; 04 : Snare
	.word @env16,@env34,@env21,@env1 ; 05 : Snare Quiet
	.word @env28,@env17,@env24,@env1 ; 06 : Bass
	.word @env13,@env17,@env21,@env1 ; 07 : Triangle
	.word @env2,@env11,@env21,@env1 ; 08 : Crash
	.word @env30,@env17,@env24,@env1 ; 09 : Guitar
	.word @env26,@env17,@env22,@env1 ; 0a : Guitar 50
	.word @env3,@env33,@env22,@env1 ; 0b : Chord Reverse 2A03
	.word @env19,@env17,@env24,@env1 ; 0c : Meow 2A03
	.word @env4,@env17,@env22,@env1 ; 0d : Chord 2A03
	.word @env14,@env17,@env5,@env1 ; 0e : Chord 2A03 2
	.word @env7,@env17,@env24,@env1 ; 0f : Saw Namco 1

@instruments_exp:

@env0:
	.byte $00,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c0,$00,$0d
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $00,$c8,$c7,$02,$c6,$03,$c5,$02,$c4,$05,$c3,$03,$c2,$03,$c1,$00,$0e
@env3:
	.byte $00,$c3,$08,$c4,$07,$c5,$00,$05
@env4:
	.byte $00,$c8,$02,$c7,$03,$c6,$05,$c5,$03,$c4,$00,$09
@env5:
	.byte $c3,$7f,$00,$00
@env6:
	.byte $00,$ca,$c9,$c7,$c5,$c4,$c2,$c0,$00,$07
@env7:
	.byte $00,$c8,$c7,$c6,$06,$c5,$00,$05
@env8:
	.byte $bc,$c0,$bf,$00,$02
@env9:
	.byte $ad,$b5,$be,$00,$02
@env10:
	.byte $b9,$b9,$bc,$bc,$c0,$c0,$00,$00
@env11:
	.byte $bb,$be,$00,$01
@env12:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env13:
	.byte $00,$cf,$7f,$00,$02
@env14:
	.byte $09,$c9,$c8,$04,$c7,$03,$c7,$00,$06,$c6,$c6,$c5,$02,$c4,$c4,$c3,$02,$c2,$03,$c1,$c1,$c0,$07,$c0,$00,$17
@env15:
	.byte $b9,$b9,$c0,$c0,$00,$00
@env16:
	.byte $00,$c3,$c2,$c1,$04,$c0,$00,$05
@env17:
	.byte $c0,$7f,$00,$01
@env18:
	.byte $b8,$b8,$bb,$bb,$c0,$c0,$00,$00
@env19:
	.byte $00,$c8,$02,$c7,$c7,$c6,$02,$c5,$c4,$c3,$c1,$c0,$00,$0b
@env20:
	.byte $bb,$bb,$bc,$bc,$c0,$c0,$00,$00
@env21:
	.byte $7f,$00,$00
@env22:
	.byte $c2,$7f,$00,$00
@env23:
	.byte $bb,$bb,$be,$be,$c0,$c0,$00,$00
@env24:
	.byte $c1,$7f,$00,$00
@env25:
	.byte $b9,$b9,$bd,$bd,$c0,$c0,$00,$00
@env26:
	.byte $06,$c8,$c6,$c5,$00,$03,$c5,$c4,$c3,$c2,$c0,$00,$0a
@env27:
	.byte $00,$c6,$c3,$c0,$00,$03
@env28:
	.byte $00,$c0,$cf,$00,$02
@env29:
	.byte $00,$c6,$c3,$03,$c2,$c2,$c1,$04,$c0,$00,$08
@env30:
	.byte $06,$c6,$c4,$c3,$00,$03,$c3,$c2,$c1,$c1,$c0,$00,$0a
@env31:
	.byte $c0,$bd,$bc,$00,$02
@env32:
	.byte $b9,$b9,$bb,$bb,$c0,$c0,$00,$00
@env33:
	.byte $b4,$7f,$00,$00
@env34:
	.byte $ba,$bf,$be,$00,$02
@env35:
	.byte $ba,$ba,$bc,$bc,$c0,$c0,$00,$00

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $bf, $48, $ff, $bf
@song0ref6:
	.byte $48, $92
@song0ref8:
	.byte $2c, $89, $45, $89, $00, $95, $2c, $89, $2c, $89, $45, $89, $2c, $89, $45, $89, $00, $89, $2c, $89, $45, $89, $00, $89
	.byte $2c, $89, $2c, $89, $45, $89, $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48, $94
@song0ref132:
	.byte $20, $89, $45, $89, $00, $95, $20, $89, $20, $89, $45, $89, $20, $89, $45, $89, $00, $89, $20, $89, $45, $89, $00, $89
	.byte $20, $89, $20, $89, $45, $89, $48
	.byte $41, $1a
	.word @song0ref132
	.byte $1e, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref132
	.byte $48
	.byte $41, $1a
	.word @song0ref132
	.byte $1e, $89, $45, $89
	.byte $41, $1e
	.word @song0ref6
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48, $4b, .lobyte(@env15), .hibyte(@env15), $96
@song0ref306:
	.byte $27, $ff, $bd, $48, $4d, $2a, $ff, $bd, $48, $4d, $29, $ff, $bd, $48, $4d, $25, $ff, $bd, $48, $4d, $27, $ff, $bd, $48
	.byte $4d, $2a, $ff, $bd, $48, $4d, $29, $ff, $bd, $48, $4d, $25, $ff, $bd, $48, $4d
	.byte $41, $18
	.word @song0ref306
	.byte $48, $4b, .lobyte(@env33), .hibyte(@env33), $4c, $92
@song0ref355:
	.byte $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $8f
@song0ref369:
	.byte $00, $83, $31, $81, $00, $85, $31, $8d
@song0ref377:
	.byte $00, $85, $31, $83, $00, $83, $31, $8f, $00, $83, $31, $81, $00, $85, $31, $83, $00, $83, $31
@song0ref396:
	.byte $8f, $00, $83, $48
@song0ref400:
	.byte $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85
	.byte $31, $8d, $00, $85, $31, $83
	.byte $41, $12
	.word @song0ref369
	.byte $48, $31, $81
	.byte $41, $16
	.word @song0ref377
	.byte $41, $15
	.word @song0ref400
	.byte $41, $18
	.word @song0ref396
@song0ref445:
	.byte $8f, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31
	.byte $83, $00, $83, $48
	.byte $41, $4a
	.word @song0ref355
	.byte $41, $12
	.word @song0ref369
	.byte $48, $31, $81
	.byte $41, $16
	.word @song0ref377
	.byte $41, $15
	.word @song0ref400
	.byte $41, $18
	.word @song0ref396
	.byte $41, $1b
	.word @song0ref445
	.byte $48
	.byte $41, $4a
	.word @song0ref355
	.byte $41, $12
	.word @song0ref369
	.byte $48, $31, $81
	.byte $41, $16
	.word @song0ref377
	.byte $41, $15
	.word @song0ref400
	.byte $41, $18
	.word @song0ref396
	.byte $41, $1b
	.word @song0ref445
	.byte $48
	.byte $41, $4a
	.word @song0ref355
	.byte $41, $12
	.word @song0ref369
	.byte $48, $31, $81
	.byte $41, $16
	.word @song0ref377
	.byte $41, $15
	.word @song0ref400
	.byte $41, $18
	.word @song0ref396
	.byte $41, $1b
	.word @song0ref445
	.byte $48, $7a, $9a, $50, $0e, $58, $33, $ad, $50, $0e, $58, $33, $ad, $50, $0e, $58, $33, $ad, $50, $0e, $58, $33, $ad, $48
	.byte $20, $95, $43, $50, $08, $2c, $25, $c5, $43, $19, $89, $43, $50, $f9, $25, $2c, $d1
	.byte $41, $1e
	.word @song0ref6
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $45, $89, $00, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $2a, $89, $45, $89, $48
	.byte $41, $1e
	.word @song0ref8
	.byte $48
	.byte $41, $1a
	.word @song0ref8
	.byte $45, $89, $00, $89, $48, $97
@song0ref628:
	.byte $4b, .lobyte(@env25), .hibyte(@env25), $9c
@song0ref632:
	.byte $27, $95, $45, $89, $4d, $27, $95, $45, $89, $4d, $27, $95, $45, $89, $4d, $25, $95, $45, $89, $4d, $27, $95, $48
@song0ref655:
	.byte $45, $95, $4d, $2a, $95, $45, $89, $4d, $2a, $95, $45, $89, $4d, $2a, $95, $45, $89, $4b, .lobyte(@env32), .hibyte(@env32)
	.byte $2a, $95, $45, $89, $4b, .lobyte(@env25), .hibyte(@env25), $2a, $95, $48
@song0ref685:
	.byte $45, $95, $4b, .lobyte(@env18), .hibyte(@env18), $25, $95, $45, $89, $4d, $25, $95, $45, $89, $4d, $25, $95, $4d, $25
	.byte $89, $4d, $23, $95, $45, $89, $4d, $25, $95, $48
@song0ref714:
	.byte $4d, $28, $95, $45, $89, $4d, $28, $95, $45, $89, $4d, $28, $a1, $45, $89, $4d, $2a, $95, $45, $89, $4d, $2a, $95, $45
	.byte $89, $48, $97, $4b, .lobyte(@env25), .hibyte(@env25)
	.byte $41, $28
	.word @song0ref632
@song0ref747:
	.byte $4b, .lobyte(@env10), .hibyte(@env10), $27, $95, $45, $89, $4d, $27, $95, $45, $89, $4d, $27, $95, $4d, $27, $89, $4b
	.byte .lobyte(@env25), .hibyte(@env25), $25, $95, $45, $89, $4b, .lobyte(@env10), .hibyte(@env10), $27, $95, $48
@song0ref778:
	.byte $4b, .lobyte(@env25), .hibyte(@env25), $25, $95, $45, $89, $4d, $25, $95, $45, $89, $4d, $25, $89, $4d, $25, $95, $45
	.byte $89, $4b, .lobyte(@env18), .hibyte(@env18), $2a, $95, $45, $89, $4d, $2a, $95, $45, $89, $48, $97, $4b, .lobyte(@env25)
	.byte .hibyte(@env25)
	.byte $41, $4f
	.word @song0ref632
	.byte $4b, .lobyte(@env25), .hibyte(@env25)
	.byte $41, $28
	.word @song0ref632
	.byte $41, $1b
	.word @song0ref747
	.byte $95, $4b, .lobyte(@env17), .hibyte(@env17), $4c, $92, $2c, $89, $2c, $89, $2c, $89, $45, $89, $2c, $89, $2c, $89, $2c
	.byte $89, $45, $89, $48, $7f, $51, $fd, $00
	.byte $41, $1e
	.word @song0ref8
	.byte $48, $00, $ff, $bd, $44, $00
@song0ch1:
	.byte $ff, $bf, $ff, $bf, $92
@song0ref869:
	.byte $27, $89, $45, $89, $00, $95, $27, $89, $27, $89, $45, $89, $27, $89, $45, $89, $00, $89, $27, $89, $45, $89, $00, $89
	.byte $27, $89, $27, $89, $45, $89
	.byte $41, $1a
	.word @song0ref869
	.byte $25, $89, $45, $89
	.byte $41, $1e
	.word @song0ref869
	.byte $41, $1a
	.word @song0ref869
	.byte $25, $89, $45, $89
	.byte $41, $1e
	.word @song0ref869
	.byte $41, $1a
	.word @song0ref869
	.byte $25, $89, $45, $89
	.byte $41, $1e
	.word @song0ref869
	.byte $41, $1a
	.word @song0ref869
	.byte $25, $89, $45, $89, $4b, .lobyte(@env32), .hibyte(@env32), $96, $1b, $ff, $bd, $4d, $1e, $ff, $bd, $4d, $1d, $ff, $bd
	.byte $4d, $19, $ff, $bd, $4d, $1b, $ff, $bd, $4d, $1e, $ff, $bd, $4d, $1d, $ff, $bd, $4d, $19, $ff, $bd, $4b, .lobyte(@env33)
	.byte .hibyte(@env33), $4c, $9e
@song0ref976:
	.byte $20, $91, $43, $50, $a1, $2c, $33, $81, $27, $91, $43, $50, $5f, $33, $2c, $81, $43, $20, $85, $43, $50, $b9, $2c, $31
	.byte $81, $25, $91, $43, $50, $47, $31, $2c, $81, $43, $20, $85, $43, $50, $d3, $2c, $2f, $81, $23, $91, $43, $50, $2d, $2f
	.byte $2c, $81, $43, $20, $85, $43, $50, $b9, $2c, $31, $81, $25, $91, $43, $50, $47, $31, $2c, $81, $43, $20, $85, $43, $50
	.byte $a1, $2c, $33, $81, $27, $95
	.byte $41, $26
	.word @song0ref976
@song0ref1057:
	.byte $25, $91, $43, $50, $b9, $31, $38, $81, $2c, $91, $43, $50, $7f, $38, $2c, $81, $43, $20, $85, $43, $50, $83, $2c, $36
	.byte $81, $2a, $91, $43, $50, $7d, $36, $2c, $81, $43, $20, $85, $43, $50, $8d, $2c, $35, $81, $29, $91, $43, $50, $73, $35
	.byte $2c, $81, $43, $20, $83, $43, $50, $ac, $2c, $36, $83, $2a, $8f, $43, $50, $54, $36, $2c, $83, $43, $20, $83, $43, $50
	.byte $a1, $2c, $38, $83, $2c, $95, $23, $8f, $43, $50, $ca, $2f, $36, $83, $2a, $8f, $43, $50, $54, $36, $2c, $83, $43, $20
	.byte $83, $43, $50, $ac, $2c, $36, $83, $2a, $8f, $43, $50, $54, $36, $2c, $83, $43, $20, $83, $43, $50, $b3, $2c, $35, $83
	.byte $29, $8f, $43, $50, $4d, $35, $2c, $83, $43, $20, $83, $43, $50, $c0, $2c, $33, $83, $27, $8f, $43, $50, $40, $33, $2c
	.byte $83, $43, $20, $83, $43, $50, $d0, $2c, $31, $83, $25, $95
	.byte $41, $26
	.word @song0ref976
	.byte $41, $26
	.word @song0ref976
	.byte $41, $4c
	.word @song0ref1057
	.byte $41, $26
	.word @song0ref976
	.byte $41, $26
	.word @song0ref976
	.byte $41, $4c
	.word @song0ref1057
	.byte $41, $26
	.word @song0ref976
	.byte $41, $26
	.word @song0ref976
	.byte $41, $4c
	.word @song0ref1057
	.byte $00, $95, $94
@song0ref1243:
	.byte $25, $89, $00, $89, $25, $89, $25, $89, $00, $89, $25, $89, $00, $89, $25, $89, $25, $89, $00, $89, $25, $89, $00, $89
	.byte $25, $89, $00, $89, $7c
@song0ref1272:
	.byte $25, $89, $00, $89, $25, $89, $00, $89, $25, $89, $25, $89, $00, $89, $25, $89, $00, $95, $23, $89, $00, $a1, $23, $95
	.byte $00, $95
	.byte $41, $1c
	.word @song0ref1243
	.byte $41, $1a
	.word @song0ref1272
	.byte $7f, $98, $1e, $95, $23, $ad
@song0ref1310:
	.byte $1e, $a1, $25, $a1, $23, $95, $97, $1e, $95, $23, $ad, $1e, $a1, $25, $a1, $23, $95, $97, $1e, $95, $23, $ad, $1e, $a1
	.byte $25, $a1, $23, $95, $7c, $94
	.byte $41, $1a
	.word @song0ref1272
	.byte $7f
@song0ref1344:
	.byte $98, $1e, $95, $23, $ad, $1e, $a1, $25, $a1, $23, $95, $97
@song0ref1356:
	.byte $23, $95, $1e, $95, $23, $95, $1e, $a1, $25, $a1, $23, $95, $1e, $95, $23, $ad, $1e, $a1, $25, $a1, $23, $95, $1e, $95
	.byte $97, $23, $95, $1e, $95, $23, $95
	.byte $41, $12
	.word @song0ref1310
	.byte $41, $1f
	.word @song0ref1356
	.byte $41, $12
	.word @song0ref1310
	.byte $41, $1f
	.word @song0ref1356
	.byte $41, $12
	.word @song0ref1310
	.byte $41, $1f
	.word @song0ref1356
	.byte $1e, $a1, $25, $a1, $23, $95, $4b, .lobyte(@env25), .hibyte(@env25), $9a
@song0ref1415:
	.byte $1c, $c5, $4d, $1e, $dd, $4d, $20, $95, $ff, $bf, $4d, $1c, $dd, $4d, $1e, $dd, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $1b, $dd, $4b, .lobyte(@env23), .hibyte(@env23), $19, $dd, $4b, .lobyte(@env25), .hibyte(@env25), $1c, $c5, $4d, $1e
	.byte $dd, $4d, $20, $95, $ff, $bf, $4d, $1c, $dd, $4d, $1e, $dd, $4d, $1e, $dd, $4b, .lobyte(@env35), .hibyte(@env35), $1d
	.byte $dd, $4b, .lobyte(@env25), .hibyte(@env25)
	.byte $41, $20
	.word @song0ref1415
	.byte $7a, $4b, .lobyte(@env17), .hibyte(@env17), $4c, $50, $11, $55, $30, $ad, $50, $11, $55, $30, $ad, $50, $11, $55, $30
	.byte $ad, $50, $11, $55, $30, $ad, $1d, $95, $43, $50, $0a, $29, $22, $c5, $43, $16, $89, $43, $50, $f7, $22, $29, $d1, $00
	.byte $95
	.byte $41, $12
	.word @song0ref628
	.byte $41, $14
	.word @song0ref655
	.byte $41, $14
	.word @song0ref685
	.byte $41, $14
	.word @song0ref714
	.byte $97, $4b, .lobyte(@env25), .hibyte(@env25)
	.byte $41, $12
	.word @song0ref632
	.byte $41, $14
	.word @song0ref655
	.byte $45, $95
	.byte $41, $12
	.word @song0ref747
	.byte $41, $16
	.word @song0ref778
	.byte $97, $7f, $4b, .lobyte(@env17), .hibyte(@env17), $4c
	.byte $41, $2a
	.word @song0ref1344
	.byte $41, $12
	.word @song0ref1310
	.byte $41, $1f
	.word @song0ref1356
	.byte $41, $12
	.word @song0ref1310
	.byte $41, $1f
	.word @song0ref1356
	.byte $41, $12
	.word @song0ref1310
	.byte $41, $18
	.word @song0ref1356
	.byte $1e, $95, $23, $95, $1e, $95, $23, $95, $92, $27, $89, $27, $89, $27, $89, $45, $89, $27, $89, $27, $89, $27, $89, $45
	.byte $89, $51, $fd, $00, $4b, .lobyte(@env32), .hibyte(@env32), $96, $1b, $ff, $a5, $97, $00, $ff, $bd, $44, $00
@song0ch2:
@song0ref1617:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $12
	.word @song0ref1617
	.byte $8c
@song0ref1639:
	.byte $08, $ff, $bd, $0b, $ff, $bd, $0d, $ff, $bd, $0b, $ff, $bd, $08, $ff, $bd, $0b, $ff, $bd, $0d, $ff, $bd, $0b, $ff, $bd
	.byte $41, $18
	.word @song0ref1639
@song0ref1666:
	.byte $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $08, $89, $08, $89
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $08, $89, $00, $89, $08, $89, $08, $89, $00, $ff, $bd
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $41, $18
	.word @song0ref1666
	.byte $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $08, $89, $08, $89, $8e, $3d, $83, $8c, $08, $83, $8e, $38
	.byte $83, $00, $83, $35, $83, $8c, $08, $83, $8e, $31, $83, $8c, $08, $83, $8e, $2c, $83, $8c, $08, $83, $8e, $29, $83, $00
	.byte $83, $25, $83, $8c, $08, $83, $8e, $20, $83, $8c, $08, $83
@song0ref1845:
	.byte $06, $89, $00, $89, $06, $89, $06, $89, $06, $89, $00, $89, $12, $89, $12, $89, $08, $89, $00, $89, $08, $89, $08, $89
	.byte $08, $89, $00, $89, $08, $89, $08, $89, $0d, $89, $8e, $31, $83, $00, $83, $3d, $83, $8c, $0d, $83, $8e, $31, $83, $8c
	.byte $0d, $83, $8e, $3d, $83, $8c, $0d, $83, $8e, $31, $83, $00, $83, $3d, $83, $8c, $0d, $83, $8e, $31, $83, $8c, $0d, $83
	.byte $8e, $3d, $83, $8c, $0d, $83, $8e, $31, $83, $00, $83, $3d, $83, $8c, $0d, $83, $8e, $31, $83, $8c, $0d, $83, $8e, $3d
	.byte $83, $8c, $0d, $83, $8e, $38, $83, $00, $83, $35, $83, $8c, $0d, $83, $8e, $31, $83, $8c, $0d, $83, $8e, $3d, $83, $8c
	.byte $06, $83, $8e, $38, $83, $00, $83, $35, $83, $8c, $06, $83, $8e, $31, $83, $8c, $06, $83, $8e, $3d, $83, $8c, $06, $83
	.byte $8e, $38, $83, $00, $83, $35, $83, $8c, $12, $83, $8e, $31, $83, $8c, $12, $83, $8e, $3d, $81, $8c, $08, $85, $8e, $38
	.byte $81, $00, $85, $35, $81, $8c, $08, $85, $8e, $31, $81, $8c, $08, $85, $8e, $3d, $8c, $08, $87, $8e, $38, $00, $87, $35
	.byte $8c, $14, $87, $8e, $31, $8c, $14, $87, $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $14, $89, $14, $89
	.byte $05, $89, $00, $89, $05, $89, $05, $89, $05, $89, $00, $89, $11, $89, $11, $89
	.byte $41, $aa
	.word @song0ref1845
	.byte $0d, $89, $00, $89, $19, $89, $19, $89, $00, $89, $0d, $89, $19, $89, $19, $89
	.byte $41, $ba
	.word @song0ref1845
	.byte $41, $aa
	.word @song0ref1845
	.byte $0d, $89, $00, $89, $19, $89, $19, $89, $00, $89, $0d, $89, $19, $89, $19, $89, $00, $ff, $bd, $03, $89, $03, $89, $0f
	.byte $89, $0f, $89, $0d, $95, $0f, $95, $0d, $95, $0f, $95, $0d, $95, $0f, $95, $08, $89, $00, $89, $14, $89, $14
@song0ref2148:
	.byte $89, $08, $89, $00, $89, $14, $89, $14, $89, $08, $89, $00, $89, $14, $89, $14, $89
@song0ref2165:
	.byte $08, $89, $00, $89, $14, $89, $14, $89, $0b, $89, $00, $89, $17, $89, $17, $89, $0b, $89, $00, $89, $17, $89, $17, $89
	.byte $0b, $89, $00, $89, $17, $89, $17, $89, $0b, $89, $00, $89, $17, $89, $17, $89, $01, $89, $00, $89, $0d, $89, $0d, $89
	.byte $01, $89, $00, $89, $0d, $89, $0d, $89, $01, $89, $00, $89, $0d, $89, $0d, $89, $01, $89, $00, $89, $0d, $89, $0d, $89
	.byte $04, $89, $00, $89, $10, $89, $10, $89, $04, $89, $00, $89, $10, $89, $10, $89, $03, $89, $00, $89, $0f, $89, $0f, $89
	.byte $03, $89, $00, $89, $0f, $89, $0f
	.byte $41, $19
	.word @song0ref2148
	.byte $41, $28
	.word @song0ref2165
@song0ref2274:
	.byte $04, $89, $00, $89, $10, $89, $10, $89, $04, $89, $00, $89, $10, $89, $10, $89, $04, $89, $00, $89, $10, $89, $10, $89
	.byte $04, $89, $00, $89, $10, $89, $10, $89, $06, $89, $00, $89, $12, $89, $12, $89, $06, $89, $00, $89, $12, $89, $12, $89
	.byte $06, $89, $00, $89, $12, $89, $12, $89, $06, $89, $00, $89, $12, $89, $12
	.byte $41, $19
	.word @song0ref2148
	.byte $41, $67
	.word @song0ref2165
	.byte $41, $19
	.word @song0ref2148
	.byte $41, $28
	.word @song0ref2165
	.byte $41, $3f
	.word @song0ref2274
	.byte $41, $19
	.word @song0ref2148
	.byte $41, $67
	.word @song0ref2165
	.byte $41, $19
	.word @song0ref2148
	.byte $41, $28
	.word @song0ref2165
	.byte $41, $32
	.word @song0ref2274
	.byte $06, $89, $06, $95, $06, $89, $06, $89, $06, $89, $00, $89, $ff, $bf, $ff, $bf, $44, $00
@song0ch3:
	.byte $ff, $bf, $ff, $bf, $84, $28, $89, $78
@song0ref2394:
	.byte $28, $89, $28, $89, $28, $89, $7f, $28, $89, $78, $28, $89, $28, $89, $28, $89, $7f, $28, $89, $78, $28, $89, $28, $89
	.byte $28, $89, $7f, $28, $89, $78, $28, $89, $28, $89, $28, $89, $28, $89
	.byte $41, $1e
	.word @song0ref2394
	.byte $7f
@song0ref2436:
	.byte $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $80, $30, $95, $84, $28, $89, $82, $31, $89, $80
	.byte $30, $95, $86, $2d, $89, $82, $31, $89, $80, $30, $95, $84
	.byte $41, $17
	.word @song0ref2436
	.byte $89, $86, $2d, $89, $84
	.byte $41, $18
	.word @song0ref2436
	.byte $84
	.byte $41, $17
	.word @song0ref2436
	.byte $89, $86, $2d, $89, $84, $28, $89, $82, $31
@song0ref2496:
	.byte $89, $80, $30, $95
@song0ref2500:
	.byte $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $82, $31, $89, $80, $30, $95, $86
	.byte $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d
	.byte $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $86, $2d
	.byte $41, $29
	.word @song0ref2496
	.byte $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $86
	.byte $2d
	.byte $41, $29
	.word @song0ref2496
	.byte $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $86
	.byte $2d
	.byte $41, $29
	.word @song0ref2496
	.byte $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $86
	.byte $2d
	.byte $41, $27
	.word @song0ref2496
	.byte $00, $ff, $bd, $90, $2f, $ad, $84
@song0ref2659:
	.byte $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1
	.byte $41, $14
	.word @song0ref2659
	.byte $41, $14
	.word @song0ref2659
	.byte $90, $2f, $ad
@song0ref2688:
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $95, $84, $28, $89, $82, $31, $89, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $95
	.byte $41, $12
	.word @song0ref2688
	.byte $41, $12
	.word @song0ref2688
	.byte $41, $12
	.word @song0ref2688
	.byte $41, $12
	.word @song0ref2688
	.byte $90, $2f, $ad
	.byte $41, $27
	.word @song0ref2500
	.byte $41, $29
	.word @song0ref2496
@song0ref2736:
	.byte $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $86
	.byte $2d, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $90, $2f, $ad
	.byte $41, $27
	.word @song0ref2500
	.byte $41, $29
	.word @song0ref2496
	.byte $41, $1c
	.word @song0ref2736
@song0ref2791:
	.byte $88, $30, $95, $80, $30
@song0ref2796:
	.byte $95
@song0ref2797:
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $89, $88, $30, $89
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
	.byte $41, $18
	.word @song0ref2796
	.byte $41, $1b
	.word @song0ref2796
	.byte $41, $17
	.word @song0ref2797
	.byte $95, $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $00, $ff, $bd, $90, $2f
	.byte $ad
	.byte $41, $1e
	.word @song0ref2791
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
	.byte $41, $18
	.word @song0ref2796
	.byte $41, $1b
	.word @song0ref2796
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
	.byte $95, $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $90, $2f, $ad
	.byte $41, $1e
	.word @song0ref2791
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
	.byte $41, $18
	.word @song0ref2796
	.byte $41, $1b
	.word @song0ref2796
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
	.byte $95, $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $90, $2f, $ad
	.byte $41, $1e
	.word @song0ref2791
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
@song0ref2971:
	.byte $95, $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $76, $51, $06, $f0, $86, $2d, $89, $2d, $89, $2d, $89
	.byte $2d, $89, $90, $2f, $ad
	.byte $41, $1e
	.word @song0ref2791
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
	.byte $41, $13
	.word @song0ref2971
	.byte $41, $1e
	.word @song0ref2791
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
	.byte $41, $13
	.word @song0ref2971
	.byte $41, $1e
	.word @song0ref2791
	.byte $41, $17
	.word @song0ref2797
	.byte $41, $18
	.word @song0ref2796
	.byte $95, $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $76, $51, $06, $f0, $86, $2d, $89, $2d, $89, $2d, $89
	.byte $2d, $89
	.byte $41, $17
	.word @song0ref2797
	.byte $95, $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $82, $31, $89, $88, $30, $89, $84, $28
	.byte $89, $82, $31, $89, $88, $30, $95, $7b, $51, $03, $f0
@song0ref3097:
	.byte $86, $2d, $89, $2d, $89
@song0ref3102:
	.byte $2d, $89, $2d, $89, $90, $2f, $a1, $8a, $30, $89, $88, $30, $95, $80, $30
@song0ref3117:
	.byte $95
@song0ref3118:
	.byte $84, $28, $89, $82, $31, $89, $86, $2d, $89, $8a, $30, $89, $88, $30, $95, $86, $2d, $89, $2d, $89, $84, $28, $89, $82
	.byte $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $89, $88, $30, $89
	.byte $41, $19
	.word @song0ref3118
	.byte $41, $19
	.word @song0ref3117
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $2d, $89, $88, $30, $95, $86
	.byte $41, $28
	.word @song0ref3102
	.byte $41, $19
	.word @song0ref3118
	.byte $41, $19
	.word @song0ref3117
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $8a, $30, $89, $78, $51, $05, $f0
	.byte $41, $2c
	.word @song0ref3097
	.byte $41, $19
	.word @song0ref3118
	.byte $41, $19
	.word @song0ref3117
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $2d, $89, $88, $30, $95, $86
	.byte $41, $28
	.word @song0ref3102
	.byte $41, $19
	.word @song0ref3118
	.byte $41, $19
	.word @song0ref3117
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $8a, $30, $89, $78, $51, $05, $f0
	.byte $41, $2c
	.word @song0ref3097
	.byte $41, $19
	.word @song0ref3118
	.byte $41, $19
	.word @song0ref3117
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $2d, $89, $88, $30, $95, $86
	.byte $41, $28
	.word @song0ref3102
	.byte $41, $19
	.word @song0ref3118
	.byte $41, $1a
	.word @song0ref3117
	.byte $95, $86, $2e, $89, $2e, $89, $2e, $89, $00, $89, $2e, $89, $2e, $89, $2e, $89, $00, $89, $51, $fe, $00, $84, $28, $89
	.byte $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $86, $2d, $89, $80, $30, $89, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $95, $86, $2d, $89, $82, $31, $89, $86, $2d, $89, $80, $30, $89, $00, $ff, $bd, $44, $00
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $41, $12
	.word @song0ref1617
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $44, $00
