; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Rave Racer:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1

.export _music_data_rave_racer:=music_data_rave_racer

music_data_rave_racer:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Euphoria
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 2, 0

.export music_data_rave_racer
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env27,@env16,@env18,@env2 ; 00 : HiHat Long
	.word @env23,@env16,@env18,@env2 ; 01 : HiHat
	.word @env13,@env29,@env18,@env2 ; 02 : Kick
	.word @env6,@env10,@env18,@env2 ; 03 : Snare Short
	.word @env0,@env11,@env18,@env2 ; 04 : Snare
	.word @env15,@env34,@env18,@env2 ; 05 : Snare Quiet
	.word @env3,@env12,@env18,@env2 ; 06 : Crash
	.word @env28,@env16,@env21,@env2 ; 07 : Guitar
	.word @env24,@env16,@env21,@env2 ; 08 : Bass

@instruments_exp:
	.word @env5, @env30, @env2 ; 00 : Chord Reverse N163
	.word @env2
	.byte $30, $10
	.word @n163_inst0_waves
	.byte $00, $00, $00, $00
	.word @env19, @env16, @env2 ; 01 : Guitar 5B N163
	.word @env2
	.byte $30, $10
	.word @n163_inst1_waves
	.byte $00, $00, $00, $00
	.word @env26, @env30, @env2 ; 02 : Chord N163
	.word @env2
	.byte $00, $10
	.word @n163_inst2_waves
	.byte $00, $00, $00, $00
	.word @env17, @env30, @env2 ; 03 : Chord 2 N163
	.word @env2
	.byte $00, $10
	.word @n163_inst3_waves
	.byte $00, $00, $00, $00
	.word @env32, @env16, @env2 ; 04 : Square Namco
	.word @env2
	.byte $00, $10
	.word @n163_inst4_waves
	.byte $00, $00, $00, $00
	.word @env4, @env9, @env2 ; 05 : Meow Namco
	.word @env2
	.byte $10, $20
	.word @n163_inst5_waves
	.byte $00, $00, $00, $00
	.word @env14, @env16, @env2 ; 06 : Sine Slides
	.word @env2
	.byte $40, $20
	.word @n163_inst6_waves
	.byte $00, $00, $00, $00
	.word @env35, @env16, @env2 ; 07 : Saw Namco
	.word @env2
	.byte $00, $10
	.word @n163_inst7_waves
	.byte $00, $00, $00, $00
	.word @env7, @env16, @env2 ; 08 : Triangle Namco
	.word @env2
	.byte $60, $20
	.word @n163_inst8_waves
	.byte $00, $00, $00, $00

@env0:
	.byte $00,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c0,$00,$0d
@env1:
	.byte $10,$32,$54,$76,$98,$ba,$dc,$fe
@env2:
	.byte $00,$c0,$7f,$00,$02
@env3:
	.byte $00,$c8,$c7,$02,$c6,$03,$c5,$02,$c4,$05,$c3,$03,$c2,$03,$c1,$00,$0e
@env4:
	.byte $00,$cb,$02,$ca,$ca,$c9,$02,$c8,$c7,$c5,$c3,$c0,$00,$0b
@env5:
	.byte $00,$c6,$08,$c7,$07,$c8,$00,$05
@env6:
	.byte $00,$ca,$c9,$c7,$c5,$c4,$c2,$c0,$00,$07
@env7:
	.byte $00,$cf,$cf,$ce,$cc,$c7,$00,$05
@env8:
	.byte $00,$00,$b0,$bb,$bb,$bb,$bb,$bb
@env9:
	.byte $cc,$7f,$00,$00
@env10:
	.byte $bc,$c0,$bf,$00,$02
@env11:
	.byte $ad,$b5,$be,$00,$02
@env12:
	.byte $bb,$be,$00,$01
@env13:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env14:
	.byte $00,$cf,$7f,$00,$02
@env15:
	.byte $00,$c3,$c2,$c1,$04,$c0,$00,$05
@env16:
	.byte $c0,$7f,$00,$01
@env17:
	.byte $09,$ca,$c9,$04,$c8,$03,$c8,$00,$06,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$c1,$c1,$c0,$05,$c0,$00,$19
@env18:
	.byte $7f,$00,$00
@env19:
	.byte $06,$ca,$c9,$c8,$00,$03,$c7,$c7,$c5,$c2,$c0,$00,$0a
@env20:
	.byte $10,$32,$54,$76,$98,$ba,$dc,$fe,$ef,$cd,$ab,$89,$67,$45,$23,$01
@env21:
	.byte $c1,$7f,$00,$00
@env22:
	.byte $00,$00,$00,$00,$ff,$ff,$ff,$ff
@env23:
	.byte $00,$c6,$c3,$c0,$00,$03
@env24:
	.byte $00,$c0,$cf,$00,$02
@env25:
	.byte $68,$35,$12,$01,$00,$11,$32,$65,$98,$ca,$ed,$fe,$ff,$ee,$cd,$9a
@env26:
	.byte $00,$c6,$02,$c5,$07,$c4,$05,$c3,$00,$07
@env27:
	.byte $00,$c6,$c3,$03,$c2,$c2,$c1,$04,$c0,$00,$08
@env28:
	.byte $06,$c6,$c4,$c3,$00,$03,$c3,$c2,$c1,$c1,$c0,$00,$0a
@env29:
	.byte $c0,$bd,$bc,$00,$02
@env30:
	.byte $b4,$7f,$00,$00
@env31:
	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$f0,$ff,$ff,$ff,$ff,$ff
@env32:
	.byte $00,$c8,$c7,$c5,$c3,$00,$04
@env33:
	.byte $00,$00,$00,$00,$aa,$aa,$aa,$aa
@env34:
	.byte $ba,$bf,$be,$00,$02
@env35:
	.byte $00,$cd,$cc,$cb,$06,$ca,$00,$05

@n163_inst0_waves:
	.word @env33

@n163_inst1_waves:
	.word @env33

@n163_inst2_waves:
	.word @env22

@n163_inst3_waves:
	.word @env8

@n163_inst4_waves:
	.word @env22

@n163_inst5_waves:
	.word @env31

@n163_inst6_waves:
	.word @env25

@n163_inst7_waves:
	.word @env1

@n163_inst8_waves:
	.word @env20

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$06,$80

@song0ch0:
	.byte $ff, $9f, $48, $ff, $9f, $48, $8e
@song0ref8:
	.byte $2c, $87, $45, $87, $00, $91, $2c, $87, $2c, $87, $45, $87, $2c, $87, $45, $87, $00, $87, $2c, $87, $45, $87, $00, $87
	.byte $2c, $87, $2c, $87, $45, $87, $48, $2c, $87, $45, $87, $00, $91, $2c, $87, $2c, $87, $45, $87, $2c, $87, $45, $87, $00
	.byte $87, $2c, $87, $45, $87, $00, $87, $2c, $87, $2a, $87, $45, $87, $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48, $00, $ff, $9d, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $3c
	.word @song0ref8
@song0ref182:
	.byte $48, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00, $83, $31, $8b, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31
	.byte $81, $00, $83, $31, $8b
@song0ref211:
	.byte $00, $83, $31, $00, $85, $31, $81, $00, $83, $31, $8b, $00, $83, $48, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00
	.byte $83, $31, $00, $85, $31, $81, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00, $83, $31, $00, $85, $31, $89
	.byte $00, $85, $31, $81, $00, $83, $31, $8b, $00, $83, $48, $31, $00, $85, $31, $81, $00, $83, $31, $8b, $00, $83, $31, $00
	.byte $85, $31, $81, $00, $83, $31, $8b, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81
	.byte $41, $20
	.word @song0ref211
	.byte $8b, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00
	.byte $83
	.byte $41, $74
	.word @song0ref182
	.byte $41, $20
	.word @song0ref211
	.byte $8b, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00
	.byte $83
	.byte $41, $74
	.word @song0ref182
	.byte $41, $20
	.word @song0ref211
	.byte $8b, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00
	.byte $83
	.byte $41, $74
	.word @song0ref182
	.byte $41, $20
	.word @song0ref211
	.byte $8b, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00, $83, $31, $00, $85, $31, $89, $00, $85, $31, $81, $00
	.byte $83, $48, $ff, $9f, $48, $ff, $9f, $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $38
	.word @song0ref8
	.byte $45, $87, $00, $87, $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $38
	.word @song0ref8
	.byte $45, $87, $00, $87, $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $38
	.word @song0ref8
	.byte $45, $87, $00, $87, $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $38
	.word @song0ref8
	.byte $45, $87, $00, $87, $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $38
	.word @song0ref8
	.byte $45, $87, $00, $87, $48
	.byte $41, $3c
	.word @song0ref8
	.byte $48
	.byte $41, $2c
	.word @song0ref8
	.byte $2c, $87, $2c, $87, $2c, $87, $45, $87, $2c, $87, $2c, $87, $2c, $87, $45, $87, $48, $51, $fc, $00
	.byte $41, $1e
	.word @song0ref8
	.byte $48, $00, $ff, $9d, $44, $00
@song0ch1:
	.byte $ff, $9f, $ff, $9f, $8e
@song0ref531:
	.byte $27, $87, $45, $87, $00, $91, $27, $87, $27, $87, $45, $87, $27, $87, $45, $87, $00, $87, $27, $87, $45, $87, $00, $87
	.byte $27, $87
@song0ref557:
	.byte $27, $87, $45, $87, $27, $87, $45, $87, $00, $91, $27, $87, $27, $87, $45, $87, $27, $87, $45, $87, $00, $87, $27, $87
	.byte $45, $87, $00, $87, $27, $87, $25, $87, $45, $87
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $00, $ff, $9d, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $22
	.word @song0ref557
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $22
	.word @song0ref557
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $22
	.word @song0ref557
	.byte $41, $3c
	.word @song0ref531
@song0ref693:
	.byte $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00, $83, $2c, $8b
@song0ref706:
	.byte $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00, $83, $2c, $8b
@song0ref721:
	.byte $00, $83, $2c, $00, $85, $2c, $81, $00, $83, $2c, $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00, $83
	.byte $2c, $00, $85, $2c, $81, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81
	.byte $41, $20
	.word @song0ref706
	.byte $81, $00, $83, $2c, $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81
	.byte $41, $20
	.word @song0ref721
	.byte $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00
	.byte $83
	.byte $41, $44
	.word @song0ref693
	.byte $41, $20
	.word @song0ref706
	.byte $81, $00, $83, $2c, $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81
	.byte $41, $20
	.word @song0ref721
	.byte $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00
	.byte $83
	.byte $41, $44
	.word @song0ref693
	.byte $41, $20
	.word @song0ref706
	.byte $81, $00, $83, $2c, $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81
	.byte $41, $20
	.word @song0ref721
	.byte $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00
	.byte $83
	.byte $41, $44
	.word @song0ref693
	.byte $41, $20
	.word @song0ref706
	.byte $81, $00, $83, $2c, $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81
	.byte $41, $20
	.word @song0ref721
	.byte $8b, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00, $83, $2c, $00, $85, $2c, $89, $00, $85, $2c, $81, $00
	.byte $83, $ff, $9f, $ff, $9f
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $87, $00, $87
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $87, $00, $87
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $87, $00, $87
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $87, $00, $87
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $87, $00, $87
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $2c
	.word @song0ref531
	.byte $27, $87, $27, $87, $27, $87, $45, $87, $27, $87, $27, $87, $27, $87, $45, $87, $51, $fc, $00
	.byte $41, $1e
	.word @song0ref531
	.byte $00, $ff, $9d, $44, $00
@song0ch2:
@song0ref1046:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $90, $08, $ff, $9d, $0b, $ff, $9d, $0d, $ff, $9d, $0b, $ff
	.byte $9d, $08, $ff, $9d, $0b, $ff, $9d, $0d, $ff, $9d, $0b, $ff, $9d, $08, $ff, $9d, $0b, $ff, $9d, $0d, $ff, $9d, $0b, $ff
	.byte $9d, $08, $ff, $9d, $0b, $ff, $9d, $0d, $ff, $9d, $0b
@song0ref1129:
	.byte $ff, $9d
@song0ref1131:
	.byte $08, $87, $00, $87, $08, $87, $08, $87, $08, $87, $00, $87, $08, $87, $08, $87, $08, $87, $00, $87, $08, $87, $08, $87
	.byte $08, $87, $00, $87, $08, $87, $08, $87
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $00
	.byte $41, $22
	.word @song0ref1129
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
	.byte $41, $20
	.word @song0ref1131
@song0ref1230:
	.byte $06, $87, $00, $87, $06, $87, $06, $87, $06, $87, $00, $87, $12, $87, $12, $87, $08, $87, $00, $87, $08, $87, $08, $87
	.byte $08, $87, $00, $87, $08, $87, $08, $87, $0d, $87, $00, $87, $0d, $87, $0d, $87, $0d, $87, $00, $87, $0d, $87, $0d, $87
	.byte $0d, $87, $00, $87, $0d, $87, $0d, $87, $0d, $87, $00, $87, $0d, $87, $0d, $87, $06, $87, $00, $87, $06, $87, $06, $87
	.byte $06, $87, $00, $87, $12, $87, $12, $87, $08, $87, $00, $87, $08, $87, $08, $87, $08, $87, $00, $87, $14, $87, $14, $87
	.byte $08, $87, $00, $87, $08, $87, $08, $87, $08, $87, $00, $87, $14, $87, $14, $87, $05, $87, $00, $87, $05, $87, $05, $87
	.byte $05, $87, $00, $87, $11, $87, $11, $87
	.byte $41, $70
	.word @song0ref1230
	.byte $0d, $87, $00, $87, $19, $87, $19, $87, $00, $87, $0d, $87, $19, $87, $19, $87
	.byte $41, $80
	.word @song0ref1230
	.byte $41, $70
	.word @song0ref1230
	.byte $0d, $87, $00, $87, $19, $87, $19, $87, $00, $87, $0d, $87, $19, $87, $19, $87, $00, $ff, $9d, $03, $87, $03, $87, $0f
	.byte $87, $0f, $87, $0d, $91, $0f, $91, $0d, $91, $0f, $91, $0d, $91, $0f, $91
@song0ref1422:
	.byte $08, $87, $00, $87, $14, $87, $14, $87, $08, $87, $00, $87, $14, $87, $14, $87, $08, $87, $00, $87, $14, $87, $14, $87
	.byte $08, $87, $00, $87, $14, $87, $14, $87, $0b, $87, $00, $87, $17, $87, $17, $87, $0b, $87, $00, $87, $17, $87, $17, $87
	.byte $0b, $87, $00, $87, $17, $87, $17, $87, $0b, $87, $00, $87, $17, $87, $17, $87, $01, $87, $00, $87, $0d, $87, $0d, $87
	.byte $01, $87, $00, $87, $0d, $87, $0d, $87, $01, $87, $00, $87, $0d, $87, $0d, $87, $01, $87, $00, $87, $0d, $87, $0d, $87
	.byte $04, $87, $00, $87, $10, $87, $10, $87, $04, $87, $00, $87, $10, $87, $10, $87, $03, $87, $00, $87, $0f, $87, $0f, $87
	.byte $03, $87, $00, $87, $0f, $87, $0f, $87
	.byte $41, $40
	.word @song0ref1422
@song0ref1553:
	.byte $04, $87, $00, $87, $10, $87, $10, $87, $04, $87, $00, $87, $10, $87, $10, $87, $04, $87, $00, $87, $10, $87, $10, $87
	.byte $04, $87, $00, $87, $10, $87, $10, $87, $06, $87, $00, $87, $12, $87, $12, $87, $06, $87, $00, $87, $12, $87, $12, $87
	.byte $06, $87, $00, $87, $12, $87, $12, $87, $06, $87, $00, $87, $12, $87, $12, $87
	.byte $41, $80
	.word @song0ref1422
	.byte $41, $40
	.word @song0ref1422
	.byte $41, $40
	.word @song0ref1553
	.byte $41, $80
	.word @song0ref1422
	.byte $41, $40
	.word @song0ref1422
	.byte $41, $32
	.word @song0ref1553
	.byte $06, $87, $06, $91, $06, $87, $06, $87, $06, $87, $00, $87, $ff, $9f, $ff, $9f, $44, $00
@song0ch3:
	.byte $ff, $9f, $ff, $9f, $84, $28, $87, $78
@song0ref1662:
	.byte $28, $87, $28, $87, $28, $87, $7f, $28, $87, $78, $28, $87, $28, $87, $28, $87, $7f, $28, $87, $78, $28, $87, $28, $87
	.byte $28, $87, $7f, $28, $87, $78, $28, $87, $28, $87, $28, $87, $28, $87
	.byte $41, $1e
	.word @song0ref1662
	.byte $7f, $28, $87, $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $80, $30, $91
@song0ref1721:
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $91, $86, $2d, $87, $82, $31, $87, $80, $30, $91, $84, $28, $87, $82, $31, $87, $80, $30, $91, $86, $2d, $87
	.byte $82, $31, $87, $80, $30, $87, $86, $2d, $87
	.byte $41, $23
	.word @song0ref1721
	.byte $91, $84, $28, $87, $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $80, $30, $87, $86, $2d, $87, $84, $28
	.byte $87, $82, $31
@song0ref1808:
	.byte $87, $80, $30, $91
@song0ref1812:
	.byte $86, $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $84, $28, $87, $82, $31, $87, $80, $30, $91, $86
	.byte $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $84, $28, $87, $82, $31, $87, $80, $30, $91, $86, $2d
	.byte $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $84, $28, $87, $86, $2d
	.byte $41, $29
	.word @song0ref1808
	.byte $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $84, $28, $87, $86
	.byte $2d
	.byte $41, $29
	.word @song0ref1808
	.byte $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $84, $28, $87, $86
	.byte $2d
	.byte $41, $29
	.word @song0ref1808
	.byte $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $84, $28, $87, $86
	.byte $2d
	.byte $41, $27
	.word @song0ref1808
	.byte $00, $ff, $9d, $8c, $2f, $a5, $84, $28, $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $28
	.byte $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $28
	.byte $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $28, $87, $00, $9b, $8c, $2f, $a5
@song0ref2034:
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $91, $84, $28, $87, $82, $31, $87, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $91, $84, $28, $87, $82, $31, $87, $80, $30, $91, $84, $28, $87, $82, $31, $87, $80, $30, $91
	.byte $41, $1e
	.word @song0ref2034
	.byte $41, $1e
	.word @song0ref2034
	.byte $8c, $2f, $a5
	.byte $41, $27
	.word @song0ref1812
	.byte $41, $29
	.word @song0ref1808
	.byte $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $84, $28, $87, $86
	.byte $2d, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $8c, $2f, $a5
	.byte $41, $27
	.word @song0ref1812
	.byte $41, $29
	.word @song0ref1808
	.byte $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30, $87, $84, $28, $87, $86
	.byte $2d, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $79, $86, $2d, $87, $7f, $80, $30
@song0ref2188:
	.byte $87
@song0ref2189:
	.byte $8c, $2f, $a5, $88, $30, $91, $80, $30, $91
@song0ref2198:
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $87, $88, $30
@song0ref2236:
	.byte $87
@song0ref2237:
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87
	.byte $88, $30, $91, $80, $30, $91
	.byte $41, $24
	.word @song0ref2237
	.byte $41, $3e
	.word @song0ref2198
	.byte $00, $ff, $9d
	.byte $41, $44
	.word @song0ref2189
	.byte $41, $24
	.word @song0ref2237
	.byte $41, $3e
	.word @song0ref2198
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91
	.byte $41, $44
	.word @song0ref2189
	.byte $41, $24
	.word @song0ref2237
	.byte $41, $3e
	.word @song0ref2198
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91
	.byte $41, $44
	.word @song0ref2189
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $87, $8a, $30, $87, $76, $51, $08, $f0, $86, $2d, $87, $2d, $87, $2d, $87, $2d
	.byte $41, $45
	.word @song0ref2188
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $87, $8a, $30, $87, $76, $51, $08, $f0, $86, $2d, $87, $2d, $87, $2d, $87, $2d
	.byte $41, $45
	.word @song0ref2188
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $87, $8a, $30, $87, $76, $51, $08, $f0, $86, $2d, $87, $2d, $87, $2d, $87, $2d
	.byte $41, $45
	.word @song0ref2188
	.byte $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $87, $8a, $30, $87, $76, $51, $08, $f0, $86, $2d, $87, $2d, $87, $2d, $87, $2d
	.byte $41, $23
	.word @song0ref2236
	.byte $82, $31, $87, $88, $30, $87, $84, $28, $87, $82, $31, $87, $88, $30, $91, $7b, $51, $04, $f0
@song0ref2592:
	.byte $86, $2d, $87, $2d, $87
@song0ref2597:
	.byte $2d, $87, $2d, $87, $8c, $2f, $9b
@song0ref2604:
	.byte $8a, $30, $87, $88, $30, $91, $80, $30, $91, $84, $28, $87, $82, $31, $87, $86, $2d, $87, $8a, $30, $87, $88, $30, $91
	.byte $86, $2d, $87, $2d, $87, $84, $28, $87, $82, $31, $87, $80, $30, $87, $8a, $30, $87, $88, $30, $91, $80, $30, $87, $88
	.byte $30, $87, $84, $28, $87, $82, $31, $87, $86, $2d, $87, $8a, $30, $87, $88, $30, $91, $86, $2d, $87, $2d, $87, $84, $28
	.byte $87, $82, $31, $87, $80, $30, $87
	.byte $41, $1e
	.word @song0ref2604
	.byte $86, $2d, $87, $80, $30, $87, $84, $28, $87, $86, $2d, $87, $2d, $87, $2d, $87, $88, $30, $91, $86
	.byte $41, $3c
	.word @song0ref2597
	.byte $41, $1e
	.word @song0ref2604
	.byte $86, $2d, $87, $80, $30, $87, $84, $28, $87, $86, $2d, $87, $2d, $87, $8a, $30, $87, $78, $51, $06, $f0
	.byte $41, $40
	.word @song0ref2592
	.byte $41, $1e
	.word @song0ref2604
	.byte $86, $2d, $87, $80, $30, $87, $84, $28, $87, $86, $2d, $87, $2d, $87, $2d, $87, $88, $30, $91, $86
	.byte $41, $3c
	.word @song0ref2597
	.byte $41, $1e
	.word @song0ref2604
	.byte $86, $2d, $87, $80, $30, $87, $84, $28, $87, $86, $2d, $87, $2d, $87, $8a, $30, $87, $78, $51, $06, $f0
	.byte $41, $40
	.word @song0ref2592
	.byte $41, $1e
	.word @song0ref2604
	.byte $86, $2d, $87, $80, $30, $87, $84, $28, $87, $86, $2d, $87, $2d, $87, $2d, $87, $88, $30, $91, $86
	.byte $41, $3c
	.word @song0ref2597
	.byte $41, $1f
	.word @song0ref2604
	.byte $91, $86, $2e, $87, $2e, $87, $2e, $87, $00, $87, $2e, $87, $2e, $87, $2e, $87, $00, $87, $51, $fd, $00, $84, $28, $87
	.byte $82, $31, $87, $80, $30, $91, $86, $2d, $87, $82, $31, $87, $86, $2d, $87, $80, $30, $87, $84, $28, $87, $82, $31, $87
	.byte $80, $30, $91, $86, $2d, $87, $82, $31, $87, $86, $2d, $87, $80, $30, $87, $00, $a5, $f7, $44, $00
@song0ch12:
@song0ch11:
@song0ch4:
	.byte $41, $24
	.word @song0ref1046
	.byte $41, $24
	.word @song0ref1046
	.byte $41, $24
	.word @song0ref1046
	.byte $41, $24
	.word @song0ref1046
	.byte $41, $24
	.word @song0ref1046
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $44, $00
@song0ch5:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
@song0ref2951:
	.byte $88
@song0ref2952:
	.byte $20, $87, $5a, $87, $00, $91, $20, $87, $20, $87, $5a, $87, $20, $87, $5a, $87, $00, $87, $20, $87, $5a, $87, $00, $87
	.byte $20, $87, $20, $87, $5a, $87, $20, $87, $5a, $87, $00, $91, $20, $87, $20, $87, $5a, $87, $20, $87, $5a, $87, $00, $87
	.byte $20, $87, $5a, $87, $00, $87, $20, $87, $1e, $87, $5a, $87
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $1e
	.word @song0ref2952
	.byte $00, $ff, $9d, $8e
@song0ref3025:
	.byte $20, $8d, $43, $50, $3a, $2c, $33, $81, $27, $8d, $43, $50, $c6, $33, $2c, $81, $43, $20, $83, $43, $50, $27, $2c, $31
	.byte $81, $25, $8d, $43, $50, $d9, $31, $2c, $81, $43, $20, $83, $43, $50, $16, $2c, $2f, $81, $23, $8d, $43, $50, $ea, $2f
	.byte $2c, $81, $43, $20, $83, $43, $50, $27, $2c, $31, $81, $25, $8d, $43, $50, $d9, $31, $2c, $81, $43, $20, $83, $43, $50
	.byte $3a, $2c, $33, $81, $27, $91
	.byte $41, $26
	.word @song0ref3025
@song0ref3106:
	.byte $25, $8d, $43, $50, $4e, $31, $38, $81, $2c, $8d, $43, $50, $8c, $38, $2c, $81, $43, $20, $83, $43, $50, $5b, $2c, $36
	.byte $81, $2a, $8d, $43, $50, $a5, $36, $2c, $81, $43, $20, $83, $43, $50, $50, $2c, $35, $81, $29, $8d, $43, $50, $b1, $35
	.byte $2c, $81, $43, $20, $81, $43, $50, $3d, $2c, $36, $83, $2a, $8b, $43, $50, $c3, $36, $2c, $83, $43, $20, $81, $43, $50
	.byte $4e, $2c, $38, $83, $2c, $91, $23, $8b, $43, $50, $2e, $2f, $36, $83, $2a, $8b, $43, $50, $c3, $36, $2c, $83, $43, $20
	.byte $81, $43, $50, $3d, $2c, $36, $83, $2a, $8b, $43, $50, $c3, $36, $2c, $83, $43, $20, $81, $43, $50, $35, $2c, $35, $83
	.byte $29, $8b, $43, $50, $cb, $35, $2c, $83, $43, $20, $81, $43, $50, $27, $2c, $33, $83, $27, $8b, $43, $50, $d9, $33, $2c
	.byte $83, $43, $20, $81, $43, $50, $1a, $2c, $31, $83, $25, $91
	.byte $41, $26
	.word @song0ref3025
	.byte $41, $26
	.word @song0ref3025
	.byte $41, $4c
	.word @song0ref3106
	.byte $41, $26
	.word @song0ref3025
	.byte $41, $26
	.word @song0ref3025
	.byte $41, $4c
	.word @song0ref3106
	.byte $41, $26
	.word @song0ref3025
	.byte $41, $26
	.word @song0ref3025
	.byte $41, $4c
	.word @song0ref3106
	.byte $7b, $00, $91, $88
@song0ref3293:
	.byte $27, $87, $00, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $87
	.byte $29, $87, $00, $87, $29, $87, $00, $87, $27, $87, $00, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $91, $27, $87
	.byte $00, $9b, $27, $91, $00, $91
	.byte $41, $36
	.word @song0ref3293
	.byte $41, $36
	.word @song0ref3293
	.byte $41, $34
	.word @song0ref3293
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $1e
	.word @song0ref2952
	.byte $7d, $20, $87, $5a, $87, $00, $91, $20, $87, $20, $87, $5a, $87, $20, $87, $90, $3d, $87, $38, $87, $35, $87, $31, $87
	.byte $2c, $87, $29, $87, $25, $87, $20, $87, $00, $ff, $9d
@song0ref3415:
	.byte $7e, $51, $fd, $90, $89, $31, $87, $3d, $87, $31, $87, $3d, $87, $31, $87, $51, $04, $f0, $3d, $87, $31, $87, $3d, $87
	.byte $31, $87, $3d, $87, $31, $87, $51, $fd, $10, $3d, $87, $38, $87, $35, $87, $31, $87, $3d, $87, $38, $87, $35, $87, $31
	.byte $87, $3d, $83, $00, $81, $38, $83, $00, $81, $35, $83, $00, $81, $31, $83, $00, $81, $3d, $81, $00, $83, $38, $81, $00
	.byte $83, $35, $81, $00, $83, $31, $81, $00, $83, $3d, $00, $85, $38, $00, $85, $35, $00, $85, $31, $00, $7f, $85, $ff, $9f
	.byte $ff, $9f
	.byte $41, $57
	.word @song0ref3415
	.byte $41, $57
	.word @song0ref3415
	.byte $41, $57
	.word @song0ref3415
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $93, $8a
@song0ref3542:
	.byte $1e, $91, $23, $a5, $1e, $9b, $25, $9b, $23, $91, $93
@song0ref3553:
	.byte $23, $91, $1e, $91, $23, $91, $1e, $9b, $25, $9b, $23, $91, $1e, $91, $23, $a5, $1e, $9b, $25, $9b, $23, $91, $1e, $91
	.byte $93, $23, $91, $1e, $91, $23, $91, $1e, $9b, $25, $9b, $23, $91, $93
	.byte $41, $31
	.word @song0ref3542
	.byte $41, $31
	.word @song0ref3542
	.byte $41, $2a
	.word @song0ref3542
	.byte $00, $cd, $51, $fc, $00
	.byte $41, $1e
	.word @song0ref2951
	.byte $00, $ff, $9d, $44, $00
@song0ch6:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $82
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $80, $27, $ff, $9d, $2a, $ff, $9d, $29, $ff, $9d, $25, $ff, $9d, $27, $ff, $9d, $2a, $ff, $9d, $29, $ff, $9d, $25, $ff
	.byte $9d, $82
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $3c
	.word @song0ref2952
	.byte $41, $1e
	.word @song0ref2952
	.byte $00, $ff, $9d, $80, $33, $ff, $9d, $36, $ff, $9d, $35, $ff, $9d, $31, $ff, $9d, $33, $ff, $9d, $36, $ff, $9d, $38, $ff
	.byte $9d, $35, $ff, $9d, $33, $ff, $9d, $36, $ff, $9d, $35, $ff, $9d, $31, $ff, $9d, $33, $ff, $9d, $36, $ff, $9d, $38, $ff
	.byte $9d, $35, $ff, $9d, $84
@song0ref3748:
	.byte $28, $b9, $2a, $cd, $2c, $91, $ff, $9f, $28, $cd, $2a, $cd, $27, $cd, $25, $cd, $28, $b9, $2a, $cd, $2c, $91, $ff, $9f
	.byte $28, $cd, $2a, $cd, $2a, $cd, $29, $cd
	.byte $41, $1e
	.word @song0ref3748
	.byte $2c, $cd, $50, $bf, $4c, $28, $a5, $50, $bf, $4c, $28, $a5, $50, $bf, $4c, $28, $a5, $50, $bf, $4c, $28, $a5, $2c, $91
	.byte $43, $50, $fe, $35, $31, $cd, $80, $50, $03, $35, $38, $b9, $00, $91, $86
@song0ref3822:
	.byte $33, $91, $5a, $87, $33, $91, $5a, $87, $33, $91, $5a, $87, $31, $91, $5a, $87, $33, $91, $5a, $91, $36, $91, $5a, $87
	.byte $36, $91, $5a, $87, $36, $91, $5a, $87, $36, $91, $5a, $87, $36, $87, $36, $87, $5a, $91, $31, $91, $5a, $87, $31, $91
	.byte $5a, $87, $31, $91, $31, $87, $2f, $91, $5a, $87, $31, $91, $34, $91, $5a, $87, $34, $91, $5a, $87, $34, $87, $34, $91
	.byte $5a, $87, $36, $91, $5a, $87, $36, $91, $5a, $87, $93
	.byte $41, $2a
	.word @song0ref3822
@song0ref3908:
	.byte $33, $91, $5a, $87, $33, $91, $5a, $87, $33, $91, $33, $87, $31, $91, $5a, $87, $33, $91, $31, $91, $5a, $87, $31, $91
	.byte $5a, $87, $31, $87, $31, $91, $5a, $87, $36, $91, $5a, $87, $36, $91, $5a, $87, $93
	.byte $41, $53
	.word @song0ref3822
	.byte $41, $2a
	.word @song0ref3822
	.byte $41, $29
	.word @song0ref3908
	.byte $41, $53
	.word @song0ref3822
	.byte $41, $2a
	.word @song0ref3822
	.byte $33, $91, $5a, $87, $33, $91, $5a, $87, $33, $91, $33, $87, $31, $91, $5a, $87, $33, $91, $31, $91, $5a, $87, $31, $91
	.byte $5a, $87, $31, $91, $31, $87, $31, $87, $31, $87, $5a, $87, $31, $87, $31, $87, $31, $87, $5a, $87, $51, $fc, $00, $80
	.byte $27, $ff, $89, $93, $00, $ff, $9d, $44, $00
@song0ch7:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
@song0ref4034:
	.byte $82
@song0ref4035:
	.byte $1b, $87, $5a, $87, $00, $91, $1b, $87, $1b, $87, $5a, $87, $1b, $87, $5a, $87, $00, $87, $1b, $87, $5a, $87, $00, $87
	.byte $1b, $87, $1b, $87, $5a, $87, $1b, $87, $5a, $87, $00, $91, $1b, $87, $1b, $87, $5a, $87, $1b, $87, $5a, $87, $00, $87
	.byte $1b, $87, $5a, $87, $00, $87, $1b, $87, $19, $87, $5a, $87
	.byte $41, $3c
	.word @song0ref4035
	.byte $80, $22, $ff, $9d, $25, $ff, $9d, $24, $ff, $9d, $20, $ff, $9d, $22, $ff, $9d, $25, $ff, $9d, $24, $ff, $9d, $20, $ff
	.byte $9d
	.byte $41, $3c
	.word @song0ref4034
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $3c
	.word @song0ref4035
	.byte $41, $1e
	.word @song0ref4035
	.byte $00, $ff, $9d, $80, $2c, $ff, $9d, $2f, $ff, $9d, $2e, $ff, $9d, $2a, $ff, $9d, $2c, $ff, $9d, $2f, $ff, $9d, $31, $ff
	.byte $9d, $2e, $ff, $9d, $2c, $ff, $9d, $2f, $ff, $9d, $2e, $ff, $9d, $2a, $ff, $9d, $2c, $ff, $9d, $2f, $ff, $9d, $31, $ff
	.byte $9d, $2e, $ff, $9d, $84
@song0ref4212:
	.byte $25, $b9, $27, $cd, $29, $91, $ff, $9f, $25, $cd, $27, $cd, $23, $cd, $23, $cd, $25, $b9, $27, $cd, $29, $91, $ff, $9f
	.byte $25, $cd, $27, $cd, $27, $cd, $25, $cd
	.byte $41, $1e
	.word @song0ref4212
	.byte $29, $cd, $50, $c9, $49, $25, $a5, $50, $c9, $49, $25, $a5, $50, $c9, $49, $25, $a5, $50, $c9, $49, $25, $a5, $29, $91
	.byte $43, $50, $fe, $32, $2e, $cd, $80, $50, $03, $32, $35, $b9, $00, $91, $86
@song0ref4286:
	.byte $30, $91, $5a, $87, $30, $91, $5a, $87, $30, $91, $5a, $87, $2e, $91, $5a, $87, $30, $91, $5a, $91, $33, $91, $5a, $87
	.byte $33, $91, $5a, $87, $33, $91, $5a, $87, $31, $91, $5a, $87, $33, $87, $33, $87, $5a, $91, $2c, $91, $5a, $87, $2c, $91
	.byte $5a, $87, $2c, $91, $2c, $87, $2a, $91, $5a, $87, $2c, $91, $2f, $91, $5a, $87, $2f, $91, $5a, $87, $2f, $87, $2f, $91
	.byte $5a, $87, $31, $91, $5a, $87, $31, $91, $5a, $87, $93
	.byte $41, $2a
	.word @song0ref4286
@song0ref4372:
	.byte $2f, $91, $5a, $87, $2f, $91, $5a, $87, $2f, $91, $2f, $87, $2e, $91, $5a, $87, $2f, $91, $2e, $91, $5a, $87, $2e, $91
	.byte $5a, $87, $2e, $87, $2e, $91, $5a, $87, $31, $91, $5a, $87, $31, $91, $5a, $87, $93
	.byte $41, $53
	.word @song0ref4286
	.byte $41, $2a
	.word @song0ref4286
	.byte $41, $29
	.word @song0ref4372
	.byte $41, $53
	.word @song0ref4286
	.byte $41, $2a
	.word @song0ref4286
	.byte $2f, $91, $5a, $87, $2f, $91, $5a, $87, $2f, $91, $2f, $87, $2e, $91, $5a, $87, $2f, $91, $2e, $91, $5a, $87, $2e, $91
	.byte $5a, $87, $2e, $91, $2e, $87, $2e, $87, $2e, $87, $5a, $87, $2e, $87, $2e, $87, $2e, $87, $5a, $87, $51, $fc, $00, $80
	.byte $22, $ff, $89, $93, $00, $ff, $9d, $44, $00
@song0ch8:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $80, $20, $ff, $9d
	.byte $23, $ff, $9d, $22, $ff, $9d, $1e, $ff, $9d, $20, $ff, $9d, $23, $ff, $9d, $22, $ff, $9d, $1e, $ff, $9d, $00, $ff, $9d
	.byte $41, $1e
	.word @song0ref1046
	.byte $00, $91, $82, $25, $87, $00, $87, $25, $87, $25, $87, $00, $87, $25, $87, $00, $87, $25, $87, $25, $87, $00, $87, $25
	.byte $87, $00, $87, $25, $87, $00, $87, $7c, $25, $87, $00, $87, $25, $87, $00, $87, $25, $87, $25, $87, $00, $87, $25, $87
	.byte $00, $91, $23, $87, $00, $9b, $23, $91, $00, $91, $25, $87, $00, $87, $25, $87, $25, $87, $00, $87, $25, $87, $00, $87
	.byte $25, $87, $25, $87, $00, $87, $25, $87, $00, $87, $25, $87, $00, $87
@song0ref4623:
	.byte $25, $87, $00, $87, $25, $87, $00, $87, $25, $87, $25, $87, $00, $87, $25, $87, $00, $91, $23, $87, $00, $9b, $23, $91
	.byte $00, $91, $7f, $8a, $1e, $91, $23, $a5, $1e, $9b, $25, $9b, $23, $91, $93, $1e, $91, $23, $a5, $1e, $9b, $25, $9b, $23
	.byte $91, $93, $1e, $91, $23, $a5, $1e, $9b, $25, $9b, $23, $91, $7c, $82
	.byte $41, $25
	.word @song0ref4623
	.byte $41, $26
	.word @song0ref3553
	.byte $41, $31
	.word @song0ref3542
	.byte $41, $31
	.word @song0ref3542
	.byte $41, $30
	.word @song0ref3542
	.byte $84
@song0ref4701:
	.byte $21, $b9, $23, $cd, $25, $91, $ff, $9f, $21, $cd, $23, $cd, $22, $cd, $20, $cd, $21, $b9, $23, $cd, $25, $91, $ff, $9f
	.byte $21, $cd, $23, $cd, $23, $cd, $23, $cd
	.byte $41, $1e
	.word @song0ref4701
	.byte $25, $cd, $50, $cf, $47, $23, $a5, $50, $cf, $47, $23, $a5, $50, $cf, $47, $23, $a5, $50, $cf, $47, $23, $a5, $25, $91
	.byte $43, $50, $fe, $2e, $2a, $cd, $80, $50, $02, $2e, $31, $b9, $00, $91, $86
@song0ref4775:
	.byte $2c, $91, $5a, $87, $2c, $91, $5a, $87, $2c, $91, $5a, $87, $2a, $91, $5a, $87, $2c, $91, $5a, $91, $2f, $91, $5a, $87
	.byte $2f, $91, $5a, $87, $2f, $91, $5a, $87, $2f, $91, $5a, $87, $2f, $87, $2f, $87, $5a, $91, $29, $91, $5a, $87, $29, $91
	.byte $5a, $87, $29, $91, $29, $87, $27, $91, $5a, $87, $29, $91, $2c, $91, $5a, $87, $2c, $91, $5a, $87, $2c, $87, $2c, $91
	.byte $5a, $87, $2e, $91, $5a, $87, $2e, $91, $5a, $87, $00, $91
	.byte $41, $2a
	.word @song0ref4775
@song0ref4862:
	.byte $2c, $91, $5a, $87, $2c, $91, $5a, $87, $2c, $91, $2c, $87, $2a, $91, $5a, $87, $2c, $91, $2a, $91, $5a, $87, $2a, $91
	.byte $5a, $87, $2a, $87, $2a, $91, $5a, $87, $2e, $91, $5a, $87, $2e, $91, $5a, $87, $00, $91
	.byte $41, $54
	.word @song0ref4775
	.byte $41, $2a
	.word @song0ref4775
	.byte $41, $2a
	.word @song0ref4862
	.byte $41, $54
	.word @song0ref4775
	.byte $41, $2a
	.word @song0ref4775
	.byte $2c, $91, $5a, $87, $2c, $91, $5a, $87, $2c, $91, $2c, $87, $2a, $91, $5a, $87, $2c, $91, $2a, $91, $5a, $87, $2a, $91
	.byte $5a, $87, $2a, $91, $2a, $87, $2a, $87, $2a, $87, $5a, $87, $2a, $87, $2a, $87, $2a, $87, $5a, $87, $51, $fc, $00, $80
	.byte $20, $ff, $89, $93, $00, $ff, $9d, $44, $00
@song0ch9:
	.byte $ff, $9f, $ff, $9f, $8c
@song0ref4982:
	.byte $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e
	.byte $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00
	.byte $9b, $50, $dd, $2e, $1b, $87, $00, $9b
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e
	.byte $1b, $87, $00, $9b, $ff, $9f
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e
	.byte $1b, $87, $00, $9b, $ff, $9f
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $41, $20
	.word @song0ref4982
	.byte $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e
	.byte $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $c3, $50, $dd, $2e, $1b, $87, $50, $dd, $2e, $1b, $87, $50, $dd, $2e
	.byte $1b, $87, $00, $87, $50, $dd, $2e, $1b, $87, $50, $dd, $2e, $1b, $87, $50, $dd, $2e, $1b, $87, $00, $87, $51, $fc, $00
	.byte $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e, $1b, $87, $00, $9b, $50, $dd, $2e
	.byte $1b, $87, $00, $87, $93, $ff, $9f, $44, $00
@song0ch10:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $7d, $00, $a5, $8c, $50, $bc, $36, $18, $87, $00, $c3, $50, $bc, $36, $18, $87
	.byte $00, $9b, $a7, $50, $bc, $36, $18, $87, $00, $c3, $50, $bc, $36, $18, $87, $00, $91, $50, $bc, $36, $18, $87, $00, $a5
	.byte $50, $bc, $36, $18, $87, $00, $c3, $50, $bc, $36, $18, $87, $00, $9b, $a7, $50, $bc, $36, $18, $87, $00, $c3, $50, $bc
	.byte $36, $18, $87, $00, $91, $50, $bc, $36, $18
@song0ref5420:
	.byte $87
@song0ref5421:
	.byte $00, $a5, $50, $bc, $36, $18, $87, $00, $87, $75, $50, $bc, $36, $18, $87, $7d, $00, $af, $50, $bc, $36, $18, $87, $00
	.byte $87, $75, $50, $bc, $36, $18, $87, $7d, $00, $87, $a7, $50, $bc, $36, $18, $87, $00, $87, $75, $50, $bc, $36, $18, $87
	.byte $7d, $00, $91, $50, $bc, $36, $18, $87, $00, $91, $50, $bc, $36, $18, $87, $00, $87, $75, $50, $bc, $36, $18, $87, $7d
	.byte $00
	.byte $41, $27
	.word @song0ref5420
	.byte $41, $27
	.word @song0ref5420
	.byte $41, $27
	.word @song0ref5420
	.byte $87, $00, $a5, $50, $bc, $36, $18, $87, $00, $87, $75, $50, $bc, $36, $18, $87, $7d, $00, $af, $50, $bc, $36, $18, $87
	.byte $00, $87, $75, $50, $bc, $36, $18, $87, $7d, $00, $87, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff
	.byte $9f, $ff, $9f, $ff, $9f
	.byte $41, $26
	.word @song0ref5421
	.byte $41, $27
	.word @song0ref5420
	.byte $41, $27
	.word @song0ref5420
	.byte $41, $27
	.word @song0ref5420
	.byte $87
@song0ref5569:
	.byte $00, $a5, $50, $bc, $36, $18, $87, $00, $c3, $50, $bc, $36, $18, $87, $00, $9b, $a7, $50, $bc, $36, $18, $87, $00, $91
	.byte $50, $bc, $36, $18, $87, $00, $a5, $50, $bc, $36, $18, $87, $00, $9b, $00, $a5, $50, $bc, $36, $18, $87, $00, $c3, $50
	.byte $bc, $36, $18, $87, $00, $9b, $a7, $50, $bc, $36, $18, $87, $00, $91, $50, $bc, $36, $18, $87, $00, $a5, $50, $bc, $36
	.byte $18, $87, $00, $9b
	.byte $41, $21
	.word @song0ref5569
	.byte $ff, $9f
	.byte $41, $2e
	.word @song0ref5569
	.byte $41, $2e
	.word @song0ref5569
	.byte $41, $2e
	.word @song0ref5569
	.byte $41, $2e
	.word @song0ref5569
	.byte $41, $25
	.word @song0ref5569
	.byte $c3, $79, $51, $07, $f0, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18
	.byte $87, $7d
	.byte $41, $25
	.word @song0ref5569
	.byte $c3, $79, $51, $07, $f0, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18
	.byte $87, $7d
	.byte $41, $25
	.word @song0ref5569
	.byte $c3, $79, $51, $07, $f0, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18
	.byte $87, $7d
	.byte $41, $25
	.word @song0ref5569
	.byte $c3, $79, $51, $07, $f0, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18
	.byte $87, $7d, $00, $a5, $50, $bc, $36, $18, $87, $00, $c3, $50, $bc, $36, $18, $87, $00, $9b, $a7, $50, $bc, $36, $18, $87
	.byte $00, $91, $50, $bc, $36, $18, $87, $00, $91, $50, $bc, $36, $18, $87
@song0ref5814:
	.byte $00, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $00, $a5
	.byte $50, $bc, $36, $18, $87, $00, $af, $50, $bc, $36, $18, $87, $00, $87, $50, $bc, $36, $18, $87, $00, $87, $50, $bc, $36
	.byte $18, $87, $00, $87, $a7, $50, $bc, $36, $18, $87, $00
@song0ref5873:
	.byte $91, $50, $bc, $36, $18, $87, $00, $91, $50, $bc, $36, $18, $87, $00
@song0ref5887:
	.byte $87, $50, $bc, $36, $18, $87, $00, $87, $50, $bc, $36, $18, $87, $00, $87, $00, $a5, $50, $bc, $36, $18, $87, $00, $af
	.byte $50, $bc, $36, $18, $87, $00, $87, $50, $bc, $36, $18, $87, $00, $87, $50, $bc, $36, $18, $87, $00, $87, $a7, $50, $bc
	.byte $36, $18, $87, $00, $87, $50, $bc, $36, $18, $87, $00, $91, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc
	.byte $36, $18
	.byte $41, $1f
	.word @song0ref5887
	.byte $41, $30
	.word @song0ref5873
	.byte $41, $51
	.word @song0ref5814
	.byte $41, $1f
	.word @song0ref5887
	.byte $41, $30
	.word @song0ref5873
	.byte $41, $51
	.word @song0ref5814
	.byte $41, $1f
	.word @song0ref5887
	.byte $41, $27
	.word @song0ref5873
	.byte $9b, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $00, $87, $50, $bc, $36, $18, $87, $50
	.byte $bc, $36, $18, $87, $50, $bc, $36, $18, $87, $00, $87, $a7, $50, $bc, $36, $18, $87, $00, $87, $75, $50, $bc, $36, $18
	.byte $87, $7d, $00, $af, $50, $bc, $36, $18, $87, $00, $87, $75, $50, $bc, $36, $18, $87, $7d, $00, $87, $ff, $9f, $44, $00
