; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Finned Frontier:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_VIBRATO = 1

.export _music_data_finned_frontier:=music_data_finned_frontier

music_data_finned_frontier:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Main Theme
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 2, 0

.export music_data_finned_frontier
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env33,@env21,@env25,@env1 ; 00 : HiHat
	.word @env17,@env43,@env25,@env1 ; 01 : Kick
	.word @env35,@env38,@env25,@env1 ; 02 : Triangle Kick
	.word @env48,@env31,@env25,@env1 ; 03 : Triangle Snare
	.word @env0,@env15,@env25,@env1 ; 04 : Snare
	.word @env6,@env7,@env25,@env1 ; 05 : Snare Short
	.word @env4,@env16,@env25,@env1 ; 06 : Crash
	.word @env45,@env21,@env25,@env1 ; 07 : HiHat Long
	.word @env18,@env21,@env25,@env1 ; 08 : Triangle
	.word @env10,@env21,@env8,@env1 ; 09 : Synth
	.word @env11,@env24,@env27,@env41 ; 0a : Synth 50
	.word @env10,@env21,@env5,@env1 ; 0b : Synth 50 2

@instruments_exp:
	.word @env44, @env21, @env1 ; 00 : Sax 3
	.word @env1
	.byte $20, $10
	.word @n163_inst0_waves
	.byte $00, $00, $00, $00
	.word @env3, @env21, @env1 ; 01 : Sax 2
	.word @env1
	.byte $30, $20
	.word @n163_inst1_waves
	.byte $00, $00, $00, $00
	.word @env19, @env21, @env1 ; 02 : Sax 1
	.word @env1
	.byte $00, $10
	.word @n163_inst2_waves
	.byte $00, $00, $00, $00
	.word @env40, @env21, @env1 ; 03 : El Synth
	.word @env1
	.byte $10, $10
	.word @n163_inst3_waves
	.byte $00, $00, $00, $00
	.word @env36, @env21, @env1 ; 04 : El Piano
	.word @env1
	.byte $00, $10
	.word @n163_inst4_waves
	.byte $00, $00, $00, $00
	.word @env13, @env21, @env1 ; 05 : Clay
	.word @env1
	.byte $50, $10
	.word @n163_inst5_waves
	.byte $00, $00, $00, $00
	.word @env42, @env21, @env1 ; 06 : El Synth Long
	.word @env1
	.byte $10, $10
	.word @n163_inst6_waves
	.byte $00, $00, $00, $00
	.word @env50, @env24, @env41 ; 07 : Synth N163
	.word @env1
	.byte $20, $10
	.word @n163_inst7_waves
	.byte $00, $00, $00, $00
	.word @env9, @env34, @env1 ; 08 : Bass
	.word @env1
	.byte $60, $10
	.word @n163_inst8_waves
	.byte $00, $00, $00, $00
	.word @env28, @env21, @env1 ; 09 : Jumpy Square
	.word @env39
	.byte $70, $10
	.word @n163_inst9_waves
	.byte $00, $00, $00, $00

@env0:
	.byte $00,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c0,$00,$0d
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $a5,$a8,$7b,$86,$54,$7a,$b9,$95
@env3:
	.byte $07,$c6,$cb,$cd,$cf,$00,$04,$cc,$c8,$c4,$c2,$c0,$c0,$00,$0c
@env4:
	.byte $00,$c8,$c7,$02,$c6,$03,$c5,$02,$c4,$05,$c3,$03,$c2,$03,$c1,$00,$0e
@env5:
	.byte $c1,$c2,$00,$01
@env6:
	.byte $00,$c9,$c8,$c7,$c5,$c3,$c2,$c1,$02,$c0,$00,$09
@env7:
	.byte $b9,$bd,$be,$00,$02
@env8:
	.byte $c2,$c2,$c1,$c1,$c0,$00,$04
@env9:
	.byte $00,$cf,$cf,$ce,$cc,$00,$04
@env10:
	.byte $09,$ca,$ca,$c9,$c8,$c7,$c6,$00,$06,$c3,$c2,$c1,$c0,$00,$0c
@env11:
	.byte $09,$ca,$c9,$c8,$c6,$c5,$c3,$00,$06,$c2,$c1,$c0,$c0,$00,$0c
@env12:
	.byte $df,$7a,$35,$12,$53,$87,$67,$85
@env13:
	.byte $09,$cf,$02,$ce,$ce,$cd,$cc,$00,$06,$c8,$c6,$c4,$c3,$c2,$00,$0d
@env14:
	.byte $53,$96,$a9,$9a,$88,$88,$77,$87
@env15:
	.byte $ad,$b5,$be,$00,$02
@env16:
	.byte $bb,$be,$00,$01
@env17:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env18:
	.byte $00,$cf,$7f,$00,$02
@env19:
	.byte $07,$c6,$cb,$cf,$cf,$00,$04,$ce,$cc,$c9,$c6,$c0,$00,$0b
@env20:
	.byte $00,$c0,$bd,$bc,$be,$c2,$c4,$c3,$00,$01
@env21:
	.byte $c0,$7f,$00,$01
@env22:
	.byte $7b,$71,$7a,$61,$88,$a9,$dc,$ad,$89,$67,$67,$55,$45,$54,$75,$87
@env23:
	.byte $00,$00,$00,$a0,$aa,$aa,$aa,$aa
@env24:
	.byte $bf,$c0,$00,$01
@env25:
	.byte $7f,$00,$00
@env26:
	.byte $68,$66,$aa,$9b,$14,$30,$73,$77
@env27:
	.byte $c2,$7f,$00,$00
@env28:
	.byte $00,$c6,$c5,$c4,$c2,$c1,$00,$05
@env29:
	.byte $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
@env30:
	.byte $5b,$21,$22,$11,$42,$97,$dc,$ee
@env31:
	.byte $c0,$bb,$b3,$af,$a6,$00,$04
@env32:
	.byte $00,$00,$00,$00,$ff,$ff,$ff,$ff
@env33:
	.byte $00,$c6,$c3,$c0,$00,$03
@env34:
	.byte $b5,$b4,$00,$01
@env35:
	.byte $00,$cf,$03,$c0,$00,$03
@env36:
	.byte $00,$c8,$7f,$00,$02
@env37:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env38:
	.byte $c0,$bb,$b6,$b1,$ad,$00,$04
@env39:
	.byte $00,$c0,$c1,$00,$02
@env40:
	.byte $00,$c6,$ca,$cd,$cf,$cf,$cc,$c8,$c5,$c1,$c0,$00,$0a
@env41:
	.byte $00,$bb,$bd,$bf,$c0,$00,$04
@env42:
	.byte $00,$c6,$ca,$cd,$cf,$00,$04
@env43:
	.byte $c0,$bd,$bc,$00,$02
@env44:
	.byte $07,$c6,$cb,$cf,$cf,$00,$04,$cc,$c8,$c4,$c2,$c0,$c0,$00,$0c
@env45:
	.byte $00,$c6,$c3,$00,$02
@env46:
	.byte $00,$c0,$be,$be,$bf,$c1,$c2,$c2,$00,$01
@env47:
	.byte $00,$00,$00,$00,$aa,$aa,$aa,$aa
@env48:
	.byte $00,$cf,$06,$c0,$00,$03
@env49:
	.byte $3a,$78,$a6,$9a,$aa,$99,$aa,$99
@env50:
	.byte $08,$c8,$02,$c7,$c6,$c4,$00,$05,$c2,$c1,$c0,$c0,$00,$0b

@n163_inst0_waves:
	.word @env14

@n163_inst1_waves:
	.word @env22

@n163_inst2_waves:
	.word @env49

@n163_inst3_waves:
	.word @env26

@n163_inst4_waves:
	.word @env30

@n163_inst5_waves:
	.word @env2

@n163_inst6_waves:
	.word @env26

@n163_inst7_waves:
	.word @env32

@n163_inst8_waves:
	.word @env12

@n163_inst9_waves:
	.word @env23
	.word @env47

@samples:

@tempo_env_1_mid:
	.byte $03,$06,$80

@song0ch0:
	.byte $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $92
@song0ref20:
	.byte $2a, $91, $2a, $87, $45, $87, $28, $87, $45, $87, $25, $87, $45, $87, $28, $91, $2a, $87, $45, $87, $00, $91, $25, $87
	.byte $45, $87
@song0ref46:
	.byte $48, $23
@song0ref48:
	.byte $91, $23
@song0ref50:
	.byte $87, $45, $87, $21, $87, $45, $87, $23, $87, $45, $87, $00, $91, $1e
	.byte $41, $0b
	.word @song0ref50
@song0ref67:
	.byte $48, $25, $91, $25, $87, $45, $87, $23, $87, $45, $87, $21, $87, $45, $87, $23, $91, $25, $87, $45, $87, $00, $91, $1d
	.byte $91, $48, $1e, $87, $45, $87, $00, $87, $1e, $87, $45, $87, $00, $87, $1e, $87, $45, $87, $00, $91, $1c, $91, $1e, $87
	.byte $45, $87, $00, $91, $48
	.byte $41, $2b
	.word @song0ref20
	.byte $41, $0b
	.word @song0ref50
	.byte $41, $32
	.word @song0ref67
	.byte $41, $0e
	.word @song0ref46
	.byte $26
	.byte $41, $0d
	.word @song0ref48
	.byte $48, $21, $91, $1e
	.byte $41, $0d
	.word @song0ref50
	.byte $17, $87, $45, $87, $1a, $91, $1c, $87, $45, $87, $48
@song0ref154:
	.byte $1e, $91, $1e, $87, $45, $87, $1c, $87, $45, $87, $19, $87, $45, $87, $21
@song0ref169:
	.byte $91, $1e, $87, $45, $87, $1c, $87, $45, $87, $1e, $87, $45, $87, $48, $22, $87, $45, $87, $00, $87, $22, $87, $45, $87
	.byte $00, $87, $22, $87, $45, $87, $20
	.byte $41, $0d
	.word @song0ref169
	.byte $41, $0e
	.word @song0ref46
	.byte $26
	.byte $41, $0d
	.word @song0ref48
	.byte $48, $21, $91, $1e
	.byte $41, $0d
	.word @song0ref50
	.byte $17, $87, $45, $87, $1a, $91, $1c, $87, $45, $87, $48, $25, $91, $25, $87, $45, $87, $23, $87, $45, $87, $20, $87, $45
	.byte $87, $28, $91, $25, $87, $45, $87, $23, $87, $45, $87, $25, $87, $45, $87, $48, $25, $87, $45, $87, $00, $87, $25, $87
	.byte $45, $87, $00, $87, $25, $87, $45, $87, $23, $91, $21, $87, $45, $87, $1e, $87, $45, $87, $1c, $87, $45, $87, $48
	.byte $41, $2b
	.word @song0ref20
	.byte $41, $0b
	.word @song0ref50
	.byte $41, $32
	.word @song0ref67
@song0ref297:
	.byte $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $96
@song0ref303:
	.byte $22, $87, $45, $87
@song0ref307:
	.byte $20
@song0ref308:
	.byte $87, $45, $87, $1e, $87, $45, $87, $20, $87, $45, $87, $22, $a5, $1b, $87, $45, $87, $20, $87, $45, $87, $48, $1e, $91
	.byte $1b, $87, $45, $87, $1b, $87, $19, $87, $45, $87, $1b, $87, $49, .lobyte(@env20), .hibyte(@env20), $9d, $45, $a5, $00
	.byte $87, $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $96, $1e, $87, $45, $87, $20, $87, $45, $87, $22, $87, $45, $87
	.byte $20, $87, $45, $87, $1e, $a5, $1b, $87, $45, $87, $22, $87, $45, $81, $23, $24, $81, $48, $25, $91, $22, $87, $45, $87
	.byte $22, $87, $20, $87, $45, $87, $22, $87, $49, .lobyte(@env20), .hibyte(@env20), $9d, $45, $a5, $00, $87
	.byte $41, $5d
	.word @song0ref297
	.byte $41, $12
	.word @song0ref297
	.byte $20, $91, $1e, $91, $48, $1d, $9b, $1e, $9b, $20, $91, $1e, $91, $1d, $91, $1b
@song0ref432:
	.byte $91, $19, $91, $48
@song0ref436:
	.byte $1b, $9b, $1d, $9b, $1e, $91, $1d, $9b, $1b, $9b, $1a, $91, $48, $1b, $87, $49, .lobyte(@env29), .hibyte(@env29), $c5
	.byte $45, $91, $49, .lobyte(@env1), .hibyte(@env1), $4a, $96, $16, $91, $17
	.byte $41, $17
	.word @song0ref432
	.byte $41, $13
	.word @song0ref432
	.byte $a5, $00, $a5, $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $92, $27, $91, $27, $87, $45, $87, $25, $87, $45, $87
	.byte $22, $87, $45, $87, $25, $91, $27, $87, $45, $87, $00, $91, $22, $87, $45, $87, $48, $20, $91
	.byte $41, $0c
	.word @song0ref307
	.byte $00, $91, $1b
	.byte $41, $0b
	.word @song0ref308
	.byte $48, $22, $91
	.byte $41, $0d
	.word @song0ref303
	.byte $91, $22, $87, $45, $87, $00, $a5, $48, $22, $91
	.byte $41, $0d
	.word @song0ref303
	.byte $91, $22, $87, $45, $87, $00, $a5, $48, $22, $91
	.byte $41, $0d
	.word @song0ref303
	.byte $91, $22, $87, $45, $87, $00, $91, $1a, $91, $48, $1b, $87, $45, $87, $00, $87, $1b, $87, $45, $87, $00, $87, $1b, $87
	.byte $45, $87, $00, $91, $19, $91, $1b, $91, $49, .lobyte(@env37), .hibyte(@env37), $93, $48, $ff, $8b, $45, $91, $44, $00
@song0ch1:
@song0ref594:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $94
	.byte $41, $0e
	.word @song0ref154
@song0ref610:
	.byte $1c, $91, $1e, $87, $45, $87, $00, $91, $19, $87, $45, $87
@song0ref622:
	.byte $17
@song0ref623:
	.byte $91, $17
@song0ref625:
	.byte $87, $45, $87, $15, $87, $45, $87, $17, $87, $45, $87, $00, $91, $12
	.byte $41, $0b
	.word @song0ref625
@song0ref642:
	.byte $19, $91, $19, $87, $45, $87, $17, $87, $45, $87, $15, $87, $45, $87, $17, $91, $19, $87, $45, $87, $00, $91, $11, $91
	.byte $12, $87, $45, $87, $00, $87, $12, $87, $45, $87, $00, $87, $12, $87, $45, $87, $00, $91, $10, $91, $12, $87, $45, $87
	.byte $00, $91
	.byte $41, $0e
	.word @song0ref154
	.byte $41, $1d
	.word @song0ref610
	.byte $41, $0b
	.word @song0ref625
	.byte $41, $32
	.word @song0ref642
	.byte $41, $0e
	.word @song0ref622
	.byte $1a
	.byte $41, $0d
	.word @song0ref623
	.byte $15, $91, $12
	.byte $41, $0d
	.word @song0ref625
	.byte $0b, $87, $45, $87, $0e, $91, $10, $87, $45, $87, $12, $91, $12, $87, $45, $87, $10, $87, $45, $87, $0d, $87, $45, $87
	.byte $15
@song0ref742:
	.byte $91, $12, $87, $45, $87, $10, $87, $45, $87, $12, $87, $45, $87, $16, $87, $45, $87, $00, $87, $16, $87, $45, $87, $00
	.byte $87, $16, $87, $45, $87, $14
	.byte $41, $0d
	.word @song0ref742
	.byte $41, $0e
	.word @song0ref622
	.byte $1a
	.byte $41, $0d
	.word @song0ref623
	.byte $15, $91, $12
	.byte $41, $0d
	.word @song0ref625
	.byte $0b, $87, $45, $87, $0e, $91, $10, $87, $45, $87, $19, $91, $19, $87, $45, $87, $17, $87, $45, $87, $14, $87, $45, $87
	.byte $1c, $91, $19, $87, $45, $87, $17, $87, $45, $87, $19, $87, $45, $87, $19, $87, $45, $87, $00, $87, $19, $87, $45, $87
	.byte $00, $87, $19, $87, $45, $87, $17, $91, $15, $87, $45, $87, $12, $87, $45, $87, $10, $87, $45, $87, $00, $ff, $9d, $ff
	.byte $9f, $ff, $9f, $ff, $9f, $49, .lobyte(@env1), .hibyte(@env1), $4a
@song0ref869:
	.byte $16, $87, $45, $87
@song0ref873:
	.byte $14
@song0ref874:
	.byte $87, $45, $87, $12, $87, $45, $87, $14, $87, $45, $87, $16, $a5, $0f, $87, $45, $87, $14, $87, $45, $87, $12, $91, $0f
	.byte $87, $45, $87, $0f, $87, $0d, $87, $45, $87, $0f, $87, $49, .lobyte(@env20), .hibyte(@env20), $9d, $45, $a5, $00, $87
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a, $94, $12, $87, $45, $87, $14, $87, $45, $87, $16, $87, $45, $87, $14, $87
	.byte $45, $87, $12, $a5, $0f, $87, $45, $87, $16, $87, $45, $81, $17, $18, $81, $19, $91, $16, $87, $45, $87, $16, $87, $14
	.byte $87, $45, $87, $16, $87, $49, .lobyte(@env20), .hibyte(@env20), $9d, $45, $a5, $00, $87, $49, .lobyte(@env1), .hibyte(@env1)
	.byte $4a, $94
	.byte $41, $5d
	.word @song0ref869
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a, $94
	.byte $41, $12
	.word @song0ref869
	.byte $14, $91, $12, $91, $11, $9b, $12, $9b, $14, $91, $12, $91, $11, $91, $0f
@song0ref1004:
	.byte $91, $0d, $91, $0f, $9b, $11, $9b, $12, $91, $11, $9b, $0f, $9b, $0d, $91, $0f, $87, $49, .lobyte(@env29), .hibyte(@env29)
	.byte $c5, $45, $91, $77, $49, .lobyte(@env1), .hibyte(@env1), $4a, $92, $16, $91, $17, $91, $19, $91
	.byte $41, $0c
	.word @song0ref436
	.byte $1b, $87, $49, .lobyte(@env29), .hibyte(@env29), $c5, $45, $91, $79, $49, .lobyte(@env1), .hibyte(@env1), $4a, $92
	.byte $22, $91, $23, $91, $25, $91, $27, $9b, $29, $9b, $2a, $91, $29, $9b, $27, $9b, $26, $91, $27, $87, $49, .lobyte(@env29)
	.byte .hibyte(@env29), $c5, $45, $a5, $00, $a5, $49, .lobyte(@env1), .hibyte(@env1), $4a, $94, $1b, $91, $1b, $87, $45, $87
	.byte $19, $87, $45, $87, $16, $87, $45, $87, $19, $91, $1b, $87, $45, $87, $00, $91, $16, $87, $45, $87, $14, $91
	.byte $41, $0c
	.word @song0ref873
	.byte $00, $91, $0f
	.byte $41, $0c
	.word @song0ref874
	.byte $91
	.byte $41, $0d
	.word @song0ref869
	.byte $91, $16, $87, $45, $87, $00, $a5, $16, $91
	.byte $41, $0d
	.word @song0ref869
	.byte $91, $16, $87, $45, $87, $00, $a5, $16, $91
	.byte $41, $0d
	.word @song0ref869
	.byte $91, $16, $87, $45, $87, $00, $91, $0e, $91, $0f, $87, $45, $87, $00, $87, $0f, $87, $45, $87, $00, $87, $0f, $87, $45
	.byte $87, $00, $91, $0d, $91, $0f, $91, $49, .lobyte(@env37), .hibyte(@env37), $93, $ff, $8b, $45, $91, $44, $00
@song0ch2:
	.byte $ff, $9f, $ff, $9f, $84
@song0ref1201:
	.byte $22, $87, $00, $91, $22, $87, $00, $91, $22, $87, $00, $9b, $22, $87, $00, $87, $22, $87, $00, $9b
	.byte $41, $14
	.word @song0ref1201
	.byte $41, $14
	.word @song0ref1201
	.byte $41, $0b
	.word @song0ref1201
	.byte $87
	.byte $41, $0b
	.word @song0ref1201
@song0ref1234:
	.byte $87
@song0ref1235:
	.byte $22, $87, $00
@song0ref1238:
	.byte $9b, $86, $29, $87, $00, $87, $84, $22, $87, $00, $9b, $22, $87, $00, $87, $86, $29, $87, $00, $9b, $84
	.byte $41, $14
	.word @song0ref1235
	.byte $84
	.byte $41, $0e
	.word @song0ref1235
@song0ref1266:
	.byte $86, $29, $81, $29, $83, $29, $87, $29, $87, $00, $87, $29, $87, $84, $22, $87, $00, $91, $22, $87, $86, $29, $87, $00
	.byte $87, $84, $22, $87, $00, $87, $90, $36, $84, $22, $85, $90, $36, $00, $85, $34, $00, $85, $84, $22, $87, $90, $36, $86
	.byte $29, $87, $00, $85, $84, $22, $87, $00
	.byte $41, $15
	.word @song0ref1234
	.byte $84
	.byte $41, $14
	.word @song0ref1235
	.byte $84
	.byte $41, $0e
	.word @song0ref1235
	.byte $41, $2d
	.word @song0ref1266
	.byte $87
@song0ref1337:
	.byte $22, $87, $00, $87, $22, $87, $00, $87, $86, $29, $87, $00, $87, $84, $22, $87, $22, $87, $00, $87, $22, $87, $22, $87
	.byte $00, $87, $86, $29, $87, $00, $9b, $84
	.byte $41, $16
	.word @song0ref1337
	.byte $41, $0f
	.word @song0ref1266
@song0ref1375:
	.byte $9b
@song0ref1376:
	.byte $86, $29, $87, $00, $87, $84, $22, $87, $00, $9b, $86, $29, $87, $00, $87, $84, $22, $87, $22, $87
	.byte $41, $0e
	.word @song0ref1376
@song0ref1399:
	.byte $00, $9b, $86, $29, $87, $00, $87, $84, $22, $87, $22, $87, $86, $29, $87, $00, $87, $84
	.byte $41, $1c
	.word @song0ref1337
	.byte $84
	.byte $41, $16
	.word @song0ref1337
	.byte $41, $0f
	.word @song0ref1266
	.byte $41, $11
	.word @song0ref1375
	.byte $41, $0e
	.word @song0ref1376
	.byte $41, $0e
	.word @song0ref1399
	.byte $84
	.byte $41, $14
	.word @song0ref1235
	.byte $84
	.byte $41, $14
	.word @song0ref1235
	.byte $84
	.byte $41, $0e
	.word @song0ref1235
	.byte $41, $2d
	.word @song0ref1266
	.byte $87
@song0ref1452:
	.byte $22, $87, $00, $9b, $86, $29, $87, $00, $91, $84, $22, $87, $00, $91, $22, $87, $00, $87, $86, $29, $87, $00, $9b, $84
	.byte $41, $14
	.word @song0ref1452
	.byte $84
	.byte $41, $14
	.word @song0ref1452
@song0ref1483:
	.byte $29, $87, $00, $87, $29, $87, $29, $87, $00, $87, $29, $87, $29, $87, $00, $87, $84, $22, $87, $00, $91, $22, $87, $86
	.byte $29, $87, $29, $87, $29, $87, $29, $87, $84
	.byte $41, $14
	.word @song0ref1452
	.byte $84
	.byte $41, $14
	.word @song0ref1452
	.byte $84
	.byte $41, $14
	.word @song0ref1452
	.byte $41, $1e
	.word @song0ref1483
	.byte $84
	.byte $41, $14
	.word @song0ref1452
	.byte $84
	.byte $41, $14
	.word @song0ref1452
	.byte $84
	.byte $41, $14
	.word @song0ref1452
	.byte $41, $1e
	.word @song0ref1483
	.byte $84
	.byte $41, $14
	.word @song0ref1452
	.byte $41, $1e
	.word @song0ref1483
	.byte $84
	.byte $41, $14
	.word @song0ref1452
	.byte $84, $22, $87, $00, $eb, $86, $29, $87, $00, $9b, $84
	.byte $41, $14
	.word @song0ref1235
	.byte $84
	.byte $41, $14
	.word @song0ref1235
	.byte $84
	.byte $41, $0e
	.word @song0ref1235
	.byte $41, $0f
	.word @song0ref1266
	.byte $41, $0b
	.word @song0ref1238
	.byte $41, $0f
	.word @song0ref1266
	.byte $41, $0b
	.word @song0ref1238
	.byte $41, $0c
	.word @song0ref1266
	.byte $29, $87, $00, $91, $29, $87, $00, $91, $29, $87, $00, $87, $90, $33, $84, $22, $85, $90, $33, $00, $85, $31, $00, $85
	.byte $84, $22, $87, $90, $33, $86, $29, $87, $00, $99, $ff, $9f, $44, $00
@song0ch3:
	.byte $ff, $9f, $ff, $9f, $7a, $82
@song0ref1638:
	.byte $28, $87, $00, $91, $28, $87, $00, $91, $28, $87, $00, $9b, $28, $87, $00, $87, $28, $87, $00, $9b
	.byte $41, $14
	.word @song0ref1638
	.byte $41, $14
	.word @song0ref1638
	.byte $28, $87, $00, $91, $28, $87, $00, $91, $28, $81, $88, $31, $83, $31, $81, $31, $83, $31, $87, $31, $91, $31, $91, $31
	.byte $87, $31, $91
@song0ref1691:
	.byte $82, $27, $87, $80, $33, $87, $31, $87, $33, $87
@song0ref1701:
	.byte $8a, $31
@song0ref1703:
	.byte $91, $82, $27, $87, $80, $33, $87, $31, $87, $33, $87, $82, $27, $87, $80, $33, $87, $8a, $31, $91, $80, $31, $87, $33
	.byte $87
	.byte $41, $1c
	.word @song0ref1691
	.byte $41, $14
	.word @song0ref1691
@song0ref1734:
	.byte $88, $31, $81, $31, $83, $31, $87, $31, $91, $31
@song0ref1744:
	.byte $87, $82, $27, $87, $80, $33, $87, $33, $87, $82, $27, $87, $8a, $31, $91, $82, $27, $87, $80, $33
	.byte $41, $0e
	.word @song0ref1744
	.byte $87
	.byte $41, $1c
	.word @song0ref1691
	.byte $41, $1c
	.word @song0ref1691
	.byte $41, $14
	.word @song0ref1691
	.byte $41, $16
	.word @song0ref1734
	.byte $88, $31, $81, $31, $83, $31, $87, $31, $91, $31, $87, $8a, $31, $87, $88, $31, $87, $31, $91, $8c, $30
@song0ref1801:
	.byte $95
@song0ref1802:
	.byte $8e, $32, $8d, $88, $31, $91, $82, $27, $81, $8e, $32, $83, $82, $27, $87, $80, $31, $87, $82, $27, $81, $00, $83, $27
	.byte $81, $8e, $32, $8d, $88, $31, $91, $8e, $32, $91, $82, $27, $87, $00, $87, $27, $81
	.byte $41, $13
	.word @song0ref1802
@song0ref1846:
	.byte $83, $88, $31, $81, $31, $83, $31, $87, $31, $91, $31, $87, $8c, $30, $91, $80, $31, $87, $33
@song0ref1865:
	.byte $87, $8a, $31, $87, $80, $33, $87, $82, $27, $87, $80, $33, $87, $31, $87, $33, $87, $8a, $31, $87, $80, $33, $87, $82
	.byte $27, $87, $27, $87, $8a, $31, $87, $80, $33, $87, $8c, $30, $9b, $30
	.byte $41, $1a
	.word @song0ref1865
	.byte $41, $1f
	.word @song0ref1801
	.byte $41, $13
	.word @song0ref1802
	.byte $41, $2c
	.word @song0ref1846
	.byte $87, $8a, $31, $87, $80, $33, $87, $82, $27, $87, $80, $33, $87, $8c, $30, $91, $8a, $31, $87, $8c, $30, $91, $82, $27
	.byte $41, $0e
	.word @song0ref1865
	.byte $41, $13
	.word @song0ref1703
	.byte $41, $1c
	.word @song0ref1691
	.byte $41, $14
	.word @song0ref1691
	.byte $41, $17
	.word @song0ref1734
	.byte $41, $0e
	.word @song0ref1744
@song0ref1957:
	.byte $87, $8c, $31, $a5, $88, $31, $91, $80, $31, $87, $82, $27, $87, $80, $31, $87, $33, $87, $82, $27, $87, $80, $33, $87
	.byte $88, $31, $91, $80, $31, $87, $33
	.byte $41, $16
	.word @song0ref1957
	.byte $41, $0f
	.word @song0ref1957
@song0ref1994:
	.byte $88, $31, $81, $31, $83, $31, $87, $31, $87, $80, $31, $87, $33, $87, $88, $31, $91, $31, $87, $31, $91, $31, $87, $31
	.byte $91, $82, $27, $87, $00, $91, $27, $87, $88, $31, $87, $31, $87, $31, $87, $31
	.byte $41, $16
	.word @song0ref1957
	.byte $41, $16
	.word @song0ref1957
	.byte $41, $0f
	.word @song0ref1957
	.byte $41, $23
	.word @song0ref1994
	.byte $41, $16
	.word @song0ref1957
	.byte $41, $16
	.word @song0ref1957
	.byte $41, $0f
	.word @song0ref1957
	.byte $41, $23
	.word @song0ref1994
	.byte $41, $0f
	.word @song0ref1957
	.byte $41, $23
	.word @song0ref1994
	.byte $41, $0f
	.word @song0ref1957
	.byte $41, $0c
	.word @song0ref1994
	.byte $82, $27, $87, $00, $87, $80, $33, $87, $33, $87, $30, $87, $00, $87, $33, $87, $33, $87, $30, $87, $00, $87, $33, $87
	.byte $33, $87, $88, $31, $a5
	.byte $41, $1c
	.word @song0ref1691
	.byte $41, $1c
	.word @song0ref1691
	.byte $8c, $31, $a5
	.byte $41, $0c
	.word @song0ref1701
@song0ref2111:
	.byte $88, $31, $81, $31, $83, $31, $87, $31, $91, $31, $87, $8c, $31, $a5
	.byte $41, $0c
	.word @song0ref1701
	.byte $41, $0c
	.word @song0ref2111
	.byte $41, $0c
	.word @song0ref1701
	.byte $88, $31, $81, $31, $83, $31, $87, $31, $91, $31, $87, $31, $9b, $31, $9b, $31, $91, $82, $27, $87, $80, $33, $87, $31
	.byte $87, $82, $27, $87, $8c, $31, $a5, $cf, $00, $cd, $44, $00
@song0ch4:
	.byte $41, $0c
	.word @song0ref594
	.byte $41, $0c
	.word @song0ref594
	.byte $41, $0c
	.word @song0ref594
	.byte $41, $0c
	.word @song0ref594
	.byte $41, $0c
	.word @song0ref594
	.byte $41, $0c
	.word @song0ref594
	.byte $41, $0c
	.word @song0ref594
	.byte $41, $0c
	.word @song0ref594
	.byte $ff, $9f, $44, $00
@song0ch5:
	.byte $ff, $9f, $ff, $9f, $84
@song0ref2205:
	.byte $12, $87, $5a, $87, $00, $87, $12, $87, $5a, $87, $00, $87, $12, $87, $5a, $87
@song0ref2221:
	.byte $12, $87, $5a, $87, $10
@song0ref2226:
	.byte $91
@song0ref2227:
	.byte $12, $87, $5a, $87, $00, $91, $12, $87, $5a, $87, $00, $87, $10, $9b, $12, $87, $15, $81, $17, $83, $18, $87, $5a, $87
	.byte $17, $87, $5a, $87, $15, $87, $12, $87, $10, $91
	.byte $41, $1b
	.word @song0ref2205
	.byte $81, $15, $83, $17, $81, $18, $83
@song0ref2271:
	.byte $19, $87, $5a, $87, $00
@song0ref2276:
	.byte $87, $19, $87, $5a, $87, $00, $87, $19, $87, $5a, $87, $00, $91, $19, $87, $5a, $87, $19, $87, $49, .lobyte(@env37)
	.byte .hibyte(@env37), $9d, $7b, $49, .lobyte(@env1), .hibyte(@env1), $4a, $86
@song0ref2305:
	.byte $12, $91, $00, $91, $0d
@song0ref2310:
	.byte $91, $00, $91, $12, $91, $00, $91, $0d, $91, $00, $91, $0b, $91, $00, $91, $12, $91, $00, $91, $0b
	.byte $41, $0b
	.word @song0ref2310
@song0ref2333:
	.byte $08, $91, $00, $91, $0d, $91, $00, $91, $08, $91, $00, $91, $12, $91, $00, $87, $12, $91, $00, $87, $12, $91, $12, $91
	.byte $00, $87, $12, $91, $00, $87, $12, $91, $49, .lobyte(@env1), .hibyte(@env1), $4a
	.byte $41, $19
	.word @song0ref2305
	.byte $41, $0b
	.word @song0ref2310
	.byte $41, $20
	.word @song0ref2333
	.byte $17, $91, $00, $87, $17, $91, $00, $87, $17
@song0ref2387:
	.byte $91, $17, $91, $00, $87, $17, $91, $00, $87, $17, $91, $15, $91, $00, $87, $15, $91, $00, $87, $15, $91, $15, $91, $00
	.byte $87, $15, $91, $00, $87, $15
@song0ref2417:
	.byte $91, $06, $91, $00, $91, $0d, $91, $00, $91, $06, $91, $00, $91, $0d, $91, $00
	.byte $41, $10
	.word @song0ref2417
	.byte $91, $0b, $91, $00, $87, $0b, $91, $00, $87, $0b, $91, $0b, $91, $00, $87, $0b, $91, $00, $87, $0b
	.byte $41, $0b
	.word @song0ref2387
	.byte $17, $91, $00, $87, $17, $91, $00, $87, $17, $91, $0d, $91, $00, $91
	.byte $41, $0c
	.word @song0ref2333
	.byte $0d, $91, $00, $91
	.byte $41, $0c
	.word @song0ref2333
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a
	.byte $41, $19
	.word @song0ref2305
	.byte $41, $0b
	.word @song0ref2310
	.byte $41, $20
	.word @song0ref2333
	.byte $0f, $91, $00, $87, $0f, $91, $00, $87, $0f
@song0ref2505:
	.byte $91
@song0ref2506:
	.byte $0f, $91, $00, $87, $0f, $91, $00, $87, $0f, $91, $14
@song0ref2517:
	.byte $91, $00, $91, $0f, $91, $00, $91, $14, $91, $00, $91, $0f, $91, $00, $91, $08
	.byte $41, $0f
	.word @song0ref2517
@song0ref2536:
	.byte $16, $91, $00, $87, $16, $91, $00, $87, $16, $91, $0a, $91, $00, $87, $0a, $91, $00, $87, $0a
	.byte $41, $0b
	.word @song0ref2505
	.byte $41, $1b
	.word @song0ref2506
	.byte $41, $0f
	.word @song0ref2517
	.byte $41, $13
	.word @song0ref2536
	.byte $41, $0b
	.word @song0ref2505
	.byte $41, $1b
	.word @song0ref2506
	.byte $91, $00, $91, $0f, $91, $00, $91, $16, $91, $00, $91, $0f, $91, $00
	.byte $41, $0b
	.word @song0ref2505
	.byte $0f, $91, $49, .lobyte(@env1), .hibyte(@env1), $4a, $8e, $0a, $91, $0b
	.byte $41, $0d
	.word @song0ref1004
	.byte $0e, $91, $0f, $87, $49, .lobyte(@env29), .hibyte(@env29), $c5, $5a, $91, $49, .lobyte(@env1), .hibyte(@env1), $4a
	.byte $8e, $0a, $91, $0b
	.byte $41, $0d
	.word @song0ref1004
	.byte $0e, $91, $0f, $87, $49, .lobyte(@env29), .hibyte(@env29), $c5, $5a, $91, $49, .lobyte(@env1), .hibyte(@env1), $4a
	.byte $93, $00, $a5, $49, .lobyte(@env1), .hibyte(@env1), $4a, $86, $0f, $91, $00, $91, $0a
@song0ref2651:
	.byte $91, $00, $91, $0f, $91, $00, $91, $0a, $91, $00, $91, $08, $91, $00, $91, $0f, $91, $00, $91, $08
	.byte $41, $0b
	.word @song0ref2651
@song0ref2674:
	.byte $05, $91, $00, $91, $0a, $91, $00, $91, $05, $91, $00, $91, $0a, $91, $00, $91
	.byte $41, $10
	.word @song0ref2674
	.byte $41, $0c
	.word @song0ref2674
	.byte $0f, $91, $00, $87, $0f, $91, $00, $87, $0f, $91, $00, $91, $0d, $91, $8c, $0f, $91, $49, .lobyte(@env46), .hibyte(@env46)
	.byte $93, $ff, $8b, $00, $91, $44, $00
@song0ch6:
	.byte $ff, $9f, $ff, $9f, $7b, $82
@song0ref2730:
	.byte $1e, $87, $5a, $87, $00, $87, $1e, $87, $5a, $87, $00, $87, $1e, $87, $5a, $87, $00, $91, $1c, $91, $1e, $87, $5a, $87
	.byte $00, $91
	.byte $41, $1a
	.word @song0ref2730
	.byte $41, $1a
	.word @song0ref2730
	.byte $25, $87, $5a, $87, $00, $87, $25, $87, $5a, $87, $00, $87, $25, $87, $5a, $87, $00, $91, $25, $87, $5a, $87, $25, $a5
@song0ref2786:
	.byte $00, $ff, $9d, $ff, $9f, $ff, $9f, $86
@song0ref2794:
	.byte $06, $91, $00, $87, $06, $91, $00, $87, $06, $91, $06, $91, $00, $87, $06, $91, $00, $87, $06, $91, $00, $ff, $9d, $ff
	.byte $9f, $ff, $9f
	.byte $41, $14
	.word @song0ref2794
@song0ref2824:
	.byte $82, $0b, $91, $80, $0f, $87, $5a, $87, $82, $12, $91, $80, $0f, $87, $5a, $87
	.byte $41, $0c
	.word @song0ref2824
	.byte $41, $0c
	.word @song0ref2824
	.byte $41, $0c
	.word @song0ref2824
@song0ref2849:
	.byte $82, $06, $91, $80, $0d, $87, $5a, $87, $82, $0d, $91, $80, $0d, $87, $5a, $87
	.byte $41, $0c
	.word @song0ref2849
	.byte $41, $0c
	.word @song0ref2849
	.byte $82, $06, $91, $80, $0d, $87, $5a, $87, $82, $10, $91, $80, $0d, $87, $5a, $87
	.byte $41, $0c
	.word @song0ref2824
	.byte $41, $0c
	.word @song0ref2824
	.byte $41, $0c
	.word @song0ref2824
	.byte $41, $0c
	.word @song0ref2824
@song0ref2899:
	.byte $82, $0d, $91, $80, $11, $87, $5a, $87, $82, $14, $91, $80, $11, $87, $5a, $87
	.byte $41, $0c
	.word @song0ref2899
	.byte $41, $0c
	.word @song0ref2899
	.byte $41, $0c
	.word @song0ref2899
	.byte $41, $1b
	.word @song0ref2786
	.byte $76, $84
@song0ref2929:
	.byte $1b, $ff, $9d, $1b, $ff, $9d, $1e, $ff, $9d, $1d, $ff, $9d
	.byte $41, $0c
	.word @song0ref2929
	.byte $1b, $ff, $9d, $1d, $ff, $9d, $1e, $cd, $1d, $cd, $1e, $ff, $9d, $1e, $cd, $1d, $cd, $1e, $ff, $9d, $7b, $86, $08, $a5
	.byte $0f, $a5, $16, $a5, $0a, $a5, $0f, $a5, $0f, $a5, $0f, $a5, $00, $a5, $ff, $9f, $ff, $9f, $51, $ff, $60, $82, $16, $ff
	.byte $9d, $7b, $51, $ff, $60, $16, $ff, $9d, $7b, $51, $ff, $60, $16, $ff, $9d, $7b, $1b, $91, $5a, $87, $1b, $91, $5a, $87
	.byte $1b, $91, $5a, $91, $19, $91, $1b, $a5, $ff, $8b, $5a, $91, $44, $00
@song0ch7:
	.byte $ff, $9f, $ff, $9f, $7b, $80
	.byte $41, $10
	.word @song0ref2205
	.byte $00, $91, $10, $91, $12, $87, $5a, $87, $15, $91
	.byte $41, $0b
	.word @song0ref2205
	.byte $9b
	.byte $41, $12
	.word @song0ref2221
	.byte $41, $0b
	.word @song0ref2205
	.byte $91, $10, $91, $12, $87, $5a, $87, $15, $91
	.byte $41, $12
	.word @song0ref2271
	.byte $1c, $87, $5a, $87, $1c, $a5, $00, $91
@song0ref3080:
	.byte $88
@song0ref3081:
	.byte $19, $87, $00, $9b, $19
@song0ref3086:
	.byte $87, $00, $9b, $19, $87, $00, $9b, $19, $87, $00, $87, $93, $1b, $87, $00, $9b, $1b, $87, $00, $9b, $1b, $87, $00, $9b
	.byte $1b, $87, $00, $87
@song0ref3114:
	.byte $93, $1d, $87, $00, $9b, $1d, $87, $00, $9b, $1d, $87, $00, $9b, $1d, $87, $00, $87, $1e, $87, $00, $91, $1e, $87, $00
	.byte $91, $1e, $87, $00, $9b, $1c, $91, $1e, $87, $00, $9b, $00, $91
	.byte $41, $46
	.word @song0ref3081
	.byte $80
@song0ref3155:
	.byte $0b, $87, $5a, $87, $00, $91, $0b, $87, $5a, $87, $00, $91
	.byte $41, $0c
	.word @song0ref3155
	.byte $41, $0c
	.word @song0ref3155
	.byte $41, $0c
	.word @song0ref3155
@song0ref3176:
	.byte $0a
@song0ref3177:
	.byte $87, $5a, $87, $00, $91, $0a, $87, $5a, $87, $00, $91
	.byte $41, $0c
	.word @song0ref3176
	.byte $41, $0c
	.word @song0ref3176
	.byte $41, $0c
	.word @song0ref3176
	.byte $41, $0c
	.word @song0ref3155
	.byte $41, $0c
	.word @song0ref3155
	.byte $41, $0c
	.word @song0ref3155
	.byte $41, $0c
	.word @song0ref3155
@song0ref3209:
	.byte $0d, $87, $5a, $87, $00, $91, $0d, $87, $5a, $87, $00, $91
	.byte $41, $0c
	.word @song0ref3209
	.byte $41, $0c
	.word @song0ref3209
	.byte $41, $0c
	.word @song0ref3209
	.byte $41, $44
	.word @song0ref3080
	.byte $76, $84
@song0ref3235:
	.byte $16, $ff, $9d, $17, $ff, $9d, $17, $cd, $1b, $cd, $1a, $ff, $9d
	.byte $41, $0d
	.word @song0ref3235
	.byte $16, $ff, $9d, $1b, $ff, $9d, $17, $cd, $1a, $cd, $1b, $ff, $9d, $17, $cd, $1a, $cd, $1b, $ff, $9d, $7b, $86, $40, $08
	.byte $a5, $03, $a5, $0a, $a5, $40, $0a, $a5, $03, $a5, $03, $a5, $03, $a5, $00, $a5, $ff, $9f, $ff, $9f, $ff, $9f, $80
@song0ref3298:
	.byte $16, $91, $16, $87, $5a, $87, $14, $87, $5a, $87, $12, $87, $5a, $87, $14, $91, $16, $87, $5a, $87, $00, $a5
	.byte $41, $16
	.word @song0ref3298
@song0ref3323:
	.byte $1b, $87, $5a, $87, $00, $87, $1b, $87, $5a, $87, $00, $87, $1b, $87, $5a, $87, $00, $91, $19, $91, $1b, $a5, $ff, $8b
	.byte $5a, $91, $44, $00
@song0ch8:
	.byte $41, $0c
	.word @song0ref594
	.byte $00, $91
@song0ref3357:
	.byte $88
@song0ref3358:
	.byte $16, $87, $00, $9b, $16, $87, $00, $9b, $15, $87, $00, $9b, $15
@song0ref3371:
	.byte $87, $00, $87, $93, $17, $87, $00, $9b, $17, $87, $00, $9b, $16, $87, $00, $9b, $16, $87, $00, $87, $93, $19, $87, $00
	.byte $9b, $19, $87, $00, $9b, $18, $87, $00, $9b, $18, $87, $00, $87, $19, $87, $00, $91, $19, $87, $00, $91, $19, $87, $00
	.byte $9b, $17, $91, $19, $87, $00, $9b, $00, $91
	.byte $41, $46
	.word @song0ref3358
	.byte $84
@song0ref3432:
	.byte $17, $87, $5a, $87, $00, $91, $17, $87, $5a, $87, $00, $91
	.byte $41, $0c
	.word @song0ref3432
@song0ref3447:
	.byte $15, $87, $5a, $87, $00, $91, $15, $87, $5a, $87, $00, $91
	.byte $41, $0c
	.word @song0ref3447
@song0ref3462:
	.byte $16, $87, $5a, $87, $00, $91, $16, $87, $5a, $87, $00, $91
	.byte $41, $0c
	.word @song0ref3462
	.byte $41, $0c
	.word @song0ref3462
	.byte $41, $0c
	.word @song0ref3462
	.byte $41, $0c
	.word @song0ref3432
	.byte $41, $0c
	.word @song0ref3432
	.byte $41, $0c
	.word @song0ref3447
	.byte $41, $0c
	.word @song0ref3447
@song0ref3495:
	.byte $19, $87, $5a, $87, $00, $91, $19, $87, $5a, $87, $00, $91
	.byte $41, $0c
	.word @song0ref3495
	.byte $41, $0c
	.word @song0ref3495
	.byte $41, $0c
	.word @song0ref3432
	.byte $41, $44
	.word @song0ref3357
	.byte $76, $84
@song0ref3521:
	.byte $12, $ff, $9d, $12, $ff, $9d, $14, $cd, $15, $cd, $17, $cd, $16, $cd
	.byte $41, $0e
	.word @song0ref3521
	.byte $12, $ff, $9d, $14, $ff, $9d, $14, $cd, $16, $cd, $16, $ff, $9d, $14, $cd, $16, $cd, $16, $ff, $9d, $00, $ff, $9d, $ff
	.byte $9f, $7b, $49, .lobyte(@env1), .hibyte(@env1), $4a, $8a, $0f
	.byte $41, $0b
	.word @song0ref3177
	.byte $0f
	.byte $41, $0b
	.word @song0ref3177
@song0ref3577:
	.byte $08, $87, $5a, $87, $00, $91, $0f, $87, $5a, $87, $00, $91
	.byte $41, $0c
	.word @song0ref3577
	.byte $0a, $87, $5a, $87, $00, $91, $05
	.byte $41, $0b
	.word @song0ref3177
	.byte $05, $87, $5a, $87, $00, $91, $51, $ff, $60, $80, $1a, $ff, $9d, $7b, $51, $ff, $60, $1a, $ff, $9d, $7b, $00, $cd, $93
	.byte $14, $91, $16, $a5, $ff, $8b, $5a, $91, $44, $00
@song0ch9:
	.byte $41, $0c
	.word @song0ref594
	.byte $ff, $9f
@song0ref3642:
	.byte $ff, $9f, $ff, $9f, $82
@song0ref3647:
	.byte $06, $87, $5a, $87, $00, $87, $06, $87, $5a, $87, $00, $87, $06, $87, $5a, $87, $00, $91, $04, $91, $06
@song0ref3668:
	.byte $87, $5a, $87, $00, $91, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $1a
	.word @song0ref3647
	.byte $00, $91, $84
	.byte $41, $0b
	.word @song0ref2227
	.byte $41, $0c
	.word @song0ref2226
	.byte $41, $0c
	.word @song0ref2226
	.byte $41, $0c
	.word @song0ref2226
	.byte $41, $0c
	.word @song0ref2226
	.byte $41, $0c
	.word @song0ref2226
	.byte $41, $0c
	.word @song0ref2226
	.byte $91, $10, $87, $5a, $87, $00, $91, $10, $87, $5a, $87, $00
	.byte $41, $0c
	.word @song0ref2226
	.byte $41, $0c
	.word @song0ref2226
	.byte $41, $0c
	.word @song0ref2226
	.byte $41, $0c
	.word @song0ref2226
@song0ref3730:
	.byte $91, $14, $87, $5a, $87, $00, $91, $14, $87, $5a, $87, $00
	.byte $41, $0c
	.word @song0ref3730
	.byte $41, $0c
	.word @song0ref3730
	.byte $41, $0c
	.word @song0ref3730
	.byte $ff, $9d
	.byte $41, $1e
	.word @song0ref3642
	.byte $7c, $5a, $87, $00, $95, $8a
@song0ref3762:
	.byte $0d, $0e, $81, $0f, $91, $0d, $87, $5a, $81, $0f
@song0ref3772:
	.byte $11, $81, $12, $87, $0f, $87, $5a, $87, $0d, $9b
@song0ref3782:
	.byte $0f, $87, $5a, $87, $00, $9f, $0d, $0e, $81, $0f, $91, $0d, $87, $5a, $81, $0f, $12, $81, $15, $87, $14, $87, $5a, $87
	.byte $12, $87, $5a, $87, $0f, $87, $5a, $87, $00, $87, $5a, $87, $00, $95
	.byte $41, $1a
	.word @song0ref3762
@song0ref3823:
	.byte $17, $18, $81, $19, $91, $16
@song0ref3829:
	.byte $87, $5a, $81, $11, $13, $81, $14, $87, $12, $87, $5a, $87, $0f, $91, $0d, $87, $0a, $91, $5a, $87, $00, $95
	.byte $41, $3a
	.word @song0ref3762
	.byte $41, $1a
	.word @song0ref3762
	.byte $41, $1c
	.word @song0ref3823
	.byte $41, $23
	.word @song0ref3762
	.byte $12, $14, $81, $17, $87, $16, $87, $5a, $87, $14, $87, $5a, $87, $12, $87
	.byte $41, $10
	.word @song0ref3782
	.byte $41, $10
	.word @song0ref3772
	.byte $41, $17
	.word @song0ref3823
	.byte $87, $5a, $81
@song0ref3890:
	.byte $17, $19, $81, $1b, $91, $19, $87, $5a, $81, $12, $14, $81, $16, $91, $19
	.byte $41, $11
	.word @song0ref3829
	.byte $87, $5a, $81, $0b, $0c, $81, $0d, $91, $0f, $91, $12, $87, $5a, $87, $0f, $87, $5a, $81, $16, $17, $81, $19, $87, $1b
	.byte $87, $5a, $87, $16, $87, $5a, $87, $12, $95
	.byte $41, $0f
	.word @song0ref3890
	.byte $41, $11
	.word @song0ref3829
	.byte $87, $5a, $87, $00, $ff, $9d, $93, $88, $1b, $87, $00, $9b, $1b
	.byte $41, $2d
	.word @song0ref3086
	.byte $41, $10
	.word @song0ref3114
	.byte $81, $84, $12, $14, $81
	.byte $41, $16
	.word @song0ref3298
	.byte $22, $87, $5a, $87, $00, $87, $22, $87, $5a, $87, $00, $87, $22, $87, $5a, $87, $00, $91, $25, $91, $27, $a5, $ff, $8b
	.byte $5a, $91, $44, $00
@song0ch10:
	.byte $41, $0c
	.word @song0ref594
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $80
	.byte $41, $10
	.word @song0ref2205
	.byte $00, $91, $10, $91, $12
	.byte $41, $0b
	.word @song0ref3668
	.byte $41, $10
	.word @song0ref2205
	.byte $00, $91, $10, $91, $12, $87, $5a, $87, $00, $91, $8a
@song0ref4038:
	.byte $17
@song0ref4039:
	.byte $91, $17
@song0ref4041:
	.byte $87, $5a, $87, $15, $87, $5a, $87, $17, $87, $5a, $87, $1a
	.byte $41, $0d
	.word @song0ref4039
	.byte $15, $91, $12
	.byte $41, $0b
	.word @song0ref4041
@song0ref4062:
	.byte $00, $91, $0b, $87, $5a, $87, $0e, $91, $10, $87, $5a, $87, $12, $91, $12, $87, $5a, $87, $10, $87, $5a, $87, $0d, $87
	.byte $5a, $87, $15
@song0ref4089:
	.byte $91, $12, $87, $5a, $87, $10, $87, $5a, $87, $12, $87, $5a, $87, $16, $87, $5a, $87, $00, $87, $16, $87, $5a, $87, $00
	.byte $87, $16, $87, $5a, $87, $14
	.byte $41, $0d
	.word @song0ref4089
	.byte $41, $0f
	.word @song0ref4038
	.byte $41, $0d
	.word @song0ref4039
	.byte $15, $91, $12
	.byte $41, $0b
	.word @song0ref4041
	.byte $41, $0c
	.word @song0ref4062
	.byte $19, $91, $19, $87, $5a, $87, $17, $87, $5a, $87, $14, $87, $5a, $87, $1c, $91, $19, $87, $5a, $87, $17, $87, $5a, $87
	.byte $19, $87, $5a
	.byte $41, $0c
	.word @song0ref2276
	.byte $87, $19, $87, $5a, $87, $17, $91, $15, $87, $5a, $87, $12, $87, $5a, $87, $10, $87, $5a, $87, $00, $ff, $9d, $ff, $9f
	.byte $ff, $9f, $80
	.byte $41, $10
	.word @song0ref2205
	.byte $00, $91, $10, $91, $12, $87, $5a, $87, $00, $91, $79, $82
@song0ref4209:
	.byte $0f, $ff, $9d, $17, $ff, $9d, $14, $cd, $15, $cd, $16, $cd, $22, $cd
	.byte $41, $0e
	.word @song0ref4209
	.byte $0f, $ff, $9d, $14, $ff, $9d, $17, $cd, $16, $cd, $0f, $ff, $9d, $17, $cd, $16, $cd, $0f, $ff, $9d, $17, $cd, $16, $cd
	.byte $0f, $cd, $5a, $cd, $00, $91, $88, $16, $87, $00, $9b, $16, $87, $00, $9b, $14, $87, $00, $9b, $14, $87, $00, $87, $93
	.byte $18, $87, $00, $9b, $18, $87, $00, $9b, $12, $87, $00, $9b, $12
	.byte $41, $0c
	.word @song0ref3371
	.byte $12, $87, $00, $9b, $12
	.byte $41, $0c
	.word @song0ref3371
	.byte $12, $87, $00, $9b, $12, $87, $00, $87, $7b, $51, $ff, $60, $84, $20, $ff, $9d, $7c
	.byte $41, $12
	.word @song0ref3323
	.byte $20, $91, $22, $a5, $ff, $8b, $5a, $91, $44, $00
@song0ch11:
	.byte $41, $0c
	.word @song0ref594
	.byte $90
@song0ref4333:
	.byte $12, $91, $12, $91, $10, $87, $00, $87, $12, $87, $00, $9b, $12, $87, $00, $87, $10, $87, $00, $87, $12, $87, $00
@song0ref4356:
	.byte $87, $0a, $91
@song0ref4359:
	.byte $0a, $87, $00, $87, $08, $87, $00, $87, $0a, $87, $00, $9b
	.byte $41, $0b
	.word @song0ref4359
@song0ref4374:
	.byte $87, $0d, $91
@song0ref4377:
	.byte $0d, $87, $00, $87, $0b, $87, $00, $87, $0d, $87, $00, $9b
	.byte $41, $0b
	.word @song0ref4377
@song0ref4392:
	.byte $87, $12, $87, $00, $87, $06, $87, $12, $87, $00, $87, $06, $87, $12, $87, $00, $87, $12, $87, $00, $87, $10, $91, $12
	.byte $87, $00, $9b
	.byte $41, $26
	.word @song0ref4333
	.byte $41, $0b
	.word @song0ref4359
	.byte $41, $0f
	.word @song0ref4374
	.byte $41, $0b
	.word @song0ref4377
	.byte $41, $1b
	.word @song0ref4392
@song0ref4434:
	.byte $0b, $87, $00, $87, $0f, $87, $00, $87, $12, $87, $00, $87, $14, $87, $00, $83, $12, $81, $15, $87, $14, $87, $00, $87
	.byte $12, $87, $00, $87, $0e, $87, $0f, $91
	.byte $41, $20
	.word @song0ref4434
@song0ref4469:
	.byte $06, $87, $00, $91, $0a, $87, $00, $91, $0d, $87, $00, $87
	.byte $41, $0c
	.word @song0ref4469
	.byte $41, $0c
	.word @song0ref4469
	.byte $41, $0c
	.word @song0ref4469
	.byte $41, $20
	.word @song0ref4434
	.byte $41, $20
	.word @song0ref4434
@song0ref4496:
	.byte $0d, $87, $00, $91, $11, $87, $00, $91, $14, $87, $00, $87
	.byte $41, $0c
	.word @song0ref4496
	.byte $41, $0c
	.word @song0ref4496
	.byte $19, $87, $00, $87, $17, $87, $00, $87, $16, $87, $00, $87, $14, $87, $00, $87
	.byte $41, $26
	.word @song0ref4333
	.byte $41, $0b
	.word @song0ref4359
	.byte $41, $0f
	.word @song0ref4374
	.byte $41, $0b
	.word @song0ref4377
	.byte $41, $18
	.word @song0ref4392
	.byte $89, $11, $8b, $10, $8b
@song0ref4550:
	.byte $0f, $87, $00, $91, $0f, $87, $00
@song0ref4557:
	.byte $91, $0f, $87, $00, $87, $0d, $91, $0f, $87, $00, $87, $0f, $91, $1b, $91, $0d, $87, $00, $91, $0d, $87, $00, $91, $0d
	.byte $87, $00, $87, $0b, $91, $0d, $87, $00, $87, $0d, $91, $19, $91, $08, $87, $00, $91, $08, $87, $00, $91, $08, $87, $00
	.byte $87, $0d, $91, $08, $87, $00, $87, $08, $91, $14, $91, $0a, $87, $00, $91, $0a, $87, $00, $91, $0a, $87, $00, $87, $0d
	.byte $91, $0a, $87, $00, $87, $08, $91, $0a, $91
	.byte $41, $58
	.word @song0ref4550
	.byte $41, $16
	.word @song0ref4550
	.byte $11, $87, $00, $91, $11, $87, $00, $91, $11, $87, $00, $87, $0f, $91, $11, $87, $00, $87, $11, $91, $1d, $91
@song0ref4666:
	.byte $0b, $87, $00, $91, $0b, $87, $00, $91, $0b, $87, $00, $87, $0a, $91, $0b, $87, $00, $87, $0a, $91, $16, $91
	.byte $41, $0b
	.word @song0ref4550
	.byte $81, $10, $11, $81, $12
	.byte $41, $0b
	.word @song0ref4557
	.byte $41, $16
	.word @song0ref4666
	.byte $41, $0b
	.word @song0ref4550
	.byte $81, $10, $11, $81, $12
	.byte $41, $0b
	.word @song0ref4557
	.byte $41, $16
	.word @song0ref4666
	.byte $00, $ff, $9d, $0f, $91, $0f, $91, $0d, $87, $00, $87, $0f, $87, $00, $9b, $0f, $87, $00, $87, $0d, $87, $00, $87, $0f
	.byte $87, $00, $87, $08, $91
@song0ref4745:
	.byte $08, $87, $00, $87, $06, $87, $00, $87, $08, $87, $00, $9b
	.byte $41, $0b
	.word @song0ref4745
	.byte $41, $0f
	.word @song0ref4356
	.byte $41, $0b
	.word @song0ref4359
	.byte $41, $0f
	.word @song0ref4356
	.byte $41, $0b
	.word @song0ref4359
	.byte $41, $0f
	.word @song0ref4356
	.byte $41, $0b
	.word @song0ref4359
	.byte $87, $86, $03, $91, $00, $87, $03, $91, $00, $87, $03, $91, $00, $91, $01, $91, $8c, $03, $91, $49, .lobyte(@env46)
	.byte .hibyte(@env46), $93, $ff, $8b, $00, $91, $44, $00
@song0ch12:
	.byte $41, $0c
	.word @song0ref594
	.byte $92
@song0ref4812:
	.byte $1e, $87, $2a, $87, $1e, $87, $2a, $87, $2a, $87, $12, $87, $1e, $87, $12, $87, $1e, $87, $2a, $87, $2a, $87, $1e, $87
	.byte $2a, $87, $2a, $87, $1e, $87, $12, $87, $17, $87, $0b, $87, $17, $87, $17, $87, $17, $87, $0b, $87, $0b, $87, $0b, $87
	.byte $17, $87, $23, $87, $23, $87, $23, $87, $17, $87, $23, $87, $23, $87, $17, $87, $0d, $87, $25, $87, $19, $87, $0d, $87
	.byte $19, $87, $25, $87, $25, $87, $0d, $87, $25, $87, $0d, $87, $25, $87, $25, $87, $19, $87, $0d, $87, $19, $87, $0d, $87
	.byte $12, $87, $1e, $87, $1e, $87, $1e, $87, $1e, $87, $06, $87, $12, $87, $06, $87, $1e, $87, $12, $87, $1e, $87, $1e, $87
	.byte $06, $87, $1e, $87, $1e, $87, $12, $87, $12, $87, $12, $87, $12, $87, $12, $87
	.byte $41, $0c
	.word @song0ref4812
	.byte $2a, $87, $1e, $87, $12, $87, $1e, $87, $2a, $87, $1e, $87, $0b
@song0ref4964:
	.byte $87, $23, $87, $0b, $87, $0b, $87, $17, $87, $23
@song0ref4974:
	.byte $87, $17, $87, $23, $87, $0b, $87, $23, $87, $0b, $87, $23, $87, $0b, $87, $0b, $87, $0b, $87, $0b, $87, $0d, $87, $25
	.byte $87, $19, $87, $0d, $87, $0d, $87, $0d, $87, $0d, $87, $19, $87, $0d, $87, $25, $87, $25, $87, $25, $87, $25, $87, $0d
	.byte $87, $25, $87, $25, $87, $06, $87, $12, $87, $12, $87, $06, $87, $06, $87, $19, $87, $06, $87, $19, $87, $12, $87, $06
	.byte $87, $06, $87, $06, $87, $06, $87, $06, $87, $06, $87, $12
@song0ref5058:
	.byte $87, $1e, $87, $06, $87, $06, $87, $06, $87, $00, $87, $1e, $87, $2a, $87, $06, $87, $12, $87, $06, $87, $12, $87, $06
	.byte $87, $00, $87, $1e, $87, $12, $87, $2a, $87, $12, $87, $06, $87, $12, $87, $1e, $87, $00, $87, $1e, $87, $2a, $87, $2a
	.byte $87, $23, $87, $12, $87, $23, $87, $0b, $87, $23, $87, $2a, $87, $12, $87, $00, $87, $06, $87, $1e, $87, $12, $87, $06
	.byte $87, $00, $87, $06, $87, $25, $87, $19, $87, $06, $87, $12, $87, $06, $87, $06, $87, $00, $87, $1e, $87, $25, $87, $0d
	.byte $87, $1e, $87, $06, $87, $1e, $87, $06, $87, $00, $87, $06, $87, $06, $87, $25, $87, $0d, $87, $06, $87, $06, $87, $12
	.byte $87, $00, $87, $06, $87, $25, $87, $19
	.byte $41, $41
	.word @song0ref5058
	.byte $25, $87, $25, $87, $25, $87, $19, $87, $00, $87, $1e, $87, $2c, $87, $14, $87, $25, $87, $0d, $87, $0d, $87, $25, $87
	.byte $00, $87, $0d, $87, $14, $87, $20, $87, $25, $87, $19, $87, $0d, $87, $19, $87, $00, $87, $14, $87, $2c, $87, $20, $87
	.byte $14, $87, $25, $87, $19, $87, $19, $87, $00, $87, $0d, $87, $19, $87, $2c, $87
	.byte $41, $80
	.word @song0ref4812
@song0ref5256:
	.byte $0a, $87, $0a, $87, $16
@song0ref5261:
	.byte $87, $0a, $87, $22, $87, $22, $87, $16, $87, $16, $87, $22, $87, $22, $87, $16, $87, $22, $87, $0a, $87, $16, $87, $16
	.byte $87, $22, $87, $17, $87, $17, $87, $23, $87, $23, $87, $0b, $87, $0b, $87, $17, $87, $17, $87, $0b, $87, $23, $87, $0b
	.byte $87, $17, $87, $0b, $87, $0b, $87, $0b, $87, $0b, $87, $14, $87, $08, $87, $20, $87, $14, $87, $20, $87, $14, $87, $20
	.byte $87, $08, $87, $15, $87, $21, $87, $21, $87, $09, $87, $15, $87, $21, $87, $21, $87, $15, $87, $22, $87, $0a, $87, $22
	.byte $87, $22, $87, $0a
@song0ref5361:
	.byte $87, $0a, $87, $16, $87, $16, $87, $0a, $87, $0a, $87, $22
	.byte $41, $0b
	.word @song0ref5261
	.byte $41, $75
	.word @song0ref5256
	.byte $41, $0b
	.word @song0ref5261
	.byte $0a, $87, $16, $87, $16, $87, $0a
@song0ref5389:
	.byte $87, $0a, $87, $16, $87, $0a, $87, $0a, $87, $0a, $87, $16, $87, $22, $87, $16, $87, $0a, $87, $22, $87, $0a, $87, $22
	.byte $87, $1d, $87, $29, $87, $11, $87, $29, $87, $1d, $87, $29, $87, $11, $87, $1d, $87, $29, $87, $11, $87, $29, $87, $11
	.byte $87, $11, $87, $11, $87, $29, $87, $11, $87, $23, $87, $23, $87, $0b, $87, $23, $87, $23, $87, $0b, $87, $23, $87, $23
	.byte $87, $22, $87, $22, $87, $0a, $87, $22, $87, $0a, $87, $22, $87, $0a, $87, $22, $87, $27, $87, $0f, $87, $27, $87, $1b
	.byte $87, $0f, $87, $0f, $87, $0f, $87, $27, $87, $27, $87, $1b, $87, $0f, $87, $27, $87, $0f, $87, $0f, $87, $27, $87, $27
	.byte $41, $0b
	.word @song0ref4964
	.byte $23, $87, $0b, $87, $23
	.byte $41, $0b
	.word @song0ref5389
	.byte $0a, $87, $22, $87, $0a
@song0ref5525:
	.byte $87, $27, $87, $0f, $87, $27, $87, $0f, $87, $27, $87, $1b, $87, $1b, $87, $1b, $87, $27, $87, $1b
	.byte $41, $0b
	.word @song0ref5525
	.byte $0f, $87, $0b, $87, $23, $87, $0b
	.byte $41, $0b
	.word @song0ref4974
	.byte $0a, $87, $16, $87, $0a, $87, $16, $87, $0a, $87, $0a, $87, $22, $87, $16, $87, $0f, $87, $27, $87, $0f, $87, $0f, $87
	.byte $0f, $87, $0f
@song0ref5585:
	.byte $87, $27, $87, $0f, $87, $1b, $87, $27, $87, $27, $87, $0f, $87, $00, $a5, $1b
	.byte $41, $0d
	.word @song0ref5585
	.byte $27, $87, $27, $87, $0f, $87, $27, $87, $27, $87, $27, $87, $27, $87, $27, $87, $27, $87, $18, $87, $24, $87, $18, $87
	.byte $18, $87, $18, $87, $0c, $87, $18, $87, $0c, $87, $0c, $87, $18, $87, $18, $87, $18, $87, $24, $87, $18, $87, $18, $87
	.byte $0c, $87, $16, $87, $16, $87, $16, $87, $0a, $87, $22, $87, $0a, $87, $16, $87, $22, $87, $22
	.byte $41, $0c
	.word @song0ref5361
	.byte $87, $0a
@song0ref5676:
	.byte $87, $0e, $87, $0e, $87, $0e, $87, $1a, $87, $26, $87, $0e, $87, $26, $87, $26
	.byte $41, $0b
	.word @song0ref5676
	.byte $26, $87, $26, $87, $1a, $87, $1d, $87, $29, $87, $11, $87, $1d, $87, $11, $87, $29, $87, $29, $87, $29, $87, $11, $87
	.byte $29, $87, $29, $87, $11, $87, $29, $87, $11, $87, $1d, $87, $29, $87
	.byte $41, $0b
	.word @song0ref4550
	.byte $9b, $0d, $87, $00, $87, $27, $87, $00, $9b, $ff, $9f, $44, $00
