; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1

.export _music_data_fluffy:=music_data_fluffy

music_data_fluffy:
	.byte 3
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Under the Sun
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Marching For The Light
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.word @song1ch7
	.word @song1ch8
	.word @song1ch9
	.word @song1ch10
	.word @song1ch11
	.word @song1ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Song 1
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word @song2ch5
	.word @song2ch6
	.word @song2ch7
	.word @song2ch8
	.word @song2ch9
	.word @song2ch10
	.word @song2ch11
	.word @song2ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_fluffy
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env22,@env6,@env15,@env1 ; 00 : Kick
	.word @env11,@env21,@env15,@env1 ; 01 : Snare
	.word @env8,@env3,@env16,@env1 ; 02 : Instrument 3
	.word @env19,@env7,@env15,@env1 ; 03 : HiHat
	.word @env12,@env9,@env15,@env1 ; 04 : 2A03 Base 12. 1
	.word @env12,@env14,@env15,@env1 ; 05 : 2A03 Base 12.5
	.word @env5,@env14,@env15,@env1 ; 06 : 2A03 Eepy 12.5

@instruments_exp:
	.word @env12, @env7, @env1 ; 00 : N163 Guitar
	.word @env1
	.byte $00, $10
	.word @n163_inst0_waves
	.byte $00, $00, $00, $00
	.word @env12, @env14, @env1 ; 01 : N163 Square 12.5
	.word @env1
	.byte $20, $10
	.word @n163_inst1_waves
	.byte $00, $00, $00, $00
	.word @env12, @env14, @env1 ; 02 : Instrument 2
	.word @env1
	.byte $40, $10
	.word @n163_inst2_waves
	.byte $00, $00, $00, $00
	.word @env12, @env14, @env1 ; 03 : N163 Atari Bass
	.word @env1
	.byte $10, $10
	.word @n163_inst3_waves
	.byte $00, $00, $00, $00
	.word @env12, @env14, @env1 ; 04 : N163 AltSine
	.word @env1
	.byte $30, $10
	.word @n163_inst4_waves
	.byte $00, $00, $00, $00
	.word @env12, @env14, @env1 ; 05 : N163 Banjo(?)
	.word @env1
	.byte $20, $10
	.word @n163_inst5_waves
	.byte $00, $00, $00, $00

@env0:
	.byte $10,$32,$54,$76,$98,$ba,$dc,$fe
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $00,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env3:
	.byte $c2,$c8,$00,$01
@env4:
	.byte $00,$c0,$be,$be,$c0,$c2,$c2,$00,$01
@env5:
	.byte $07,$cb,$cd,$cb,$c9,$00,$04,$cb,$c9,$c7,$c5,$c5,$c4,$c4,$c3,$c3,$00,$0f
@env6:
	.byte $b9,$c2,$bf,$00,$02
@env7:
	.byte $be,$c0,$00,$01
@env8:
	.byte $00,$cc,$ca,$c6,$c3,$c0,$00,$05
@env9:
	.byte $b7,$c0,$00,$01
@env10:
	.byte $00,$cf,$7f,$00,$02
@env11:
	.byte $00,$ce,$cd,$cc,$ca,$c8,$c6,$c3,$c0,$00,$08
@env12:
	.byte $07,$cf,$cd,$cb,$c9,$00,$04,$cb,$c9,$c7,$c5,$c5,$c4,$c4,$c3,$c3,$00,$0f
@env13:
	.byte $ff,$00,$ff,$ff,$00,$00,$ff,$0f
@env14:
	.byte $c0,$7f,$00,$01
@env15:
	.byte $7f,$00,$00
@env16:
	.byte $c1,$7f,$00,$00
@env17:
	.byte $12,$10,$62,$c8,$ff,$bd,$b7,$ec
@env18:
	.byte $3f,$12,$10,$52,$a8,$ed,$ef,$ad
@env19:
	.byte $00,$c9,$c6,$c4,$c2,$c0,$00,$05
@env20:
	.byte $0f,$0f,$0f,$0f,$ff,$ff,$ff,$ff
@env21:
	.byte $c0,$cb,$c6,$00,$02
@env22:
	.byte $00,$cc,$c0,$cf,$c6,$c4,$c2,$c1,$c0,$00,$08

@n163_inst0_waves:
	.word @env17

@n163_inst1_waves:
	.word @env2

@n163_inst2_waves:
	.word @env0

@n163_inst3_waves:
	.word @env13

@n163_inst4_waves:
	.word @env18

@n163_inst5_waves:
	.word @env20

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $bf
@song0ref7:
	.byte $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $8a
@song0ref30:
	.byte $27, $89, $45, $89, $27, $83, $45, $83, $27, $83, $45, $83, $27, $89, $45, $89, $27, $89, $45, $89
	.byte $41, $14
	.word @song0ref30
@song0ref53:
	.byte $48, $2c, $89, $45, $89, $2c, $83, $45, $83, $2c, $83, $45, $83, $2c, $89, $45, $89, $2c, $89, $45, $89
@song0ref74:
	.byte $2a, $89, $45, $89, $2a, $83, $45, $83, $2a, $83, $45, $83, $2a, $89, $45, $89, $2a, $89, $45, $89, $48
	.byte $41, $14
	.word @song0ref30
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref74
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref30
	.byte $41, $14
	.word @song0ref30
	.byte $41, $28
	.word @song0ref53
	.byte $48
	.byte $41, $14
	.word @song0ref30
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref74
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref30
	.byte $41, $14
	.word @song0ref30
	.byte $41, $28
	.word @song0ref53
	.byte $48
	.byte $41, $14
	.word @song0ref30
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref74
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref30
	.byte $41, $14
	.word @song0ref30
	.byte $41, $28
	.word @song0ref53
	.byte $48
	.byte $41, $14
	.word @song0ref30
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref74
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref74
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref74
	.byte $41, $14
	.word @song0ref30
	.byte $48
	.byte $41, $14
	.word @song0ref74
	.byte $41, $14
	.word @song0ref30
@song0ref201:
	.byte $48
@song0ref202:
	.byte $33, $a9, $00, $81, $38, $91, $00, $81, $36, $91, $00, $81, $33, $a9, $00, $81, $38, $91, $00, $81, $36, $91, $00, $81
	.byte $48
@song0ref227:
	.byte $38, $a9, $00, $81, $36, $91, $00, $81, $33, $91, $00, $81, $38, $a9, $00, $81, $36, $91, $00, $81, $33, $91, $00, $81
	.byte $41, $30
	.word @song0ref201
	.byte $41, $30
	.word @song0ref201
	.byte $41, $30
	.word @song0ref201
	.byte $41, $30
	.word @song0ref201
	.byte $41, $30
	.word @song0ref201
	.byte $41, $30
	.word @song0ref201
	.byte $41, $30
	.word @song0ref201
	.byte $41, $0e
	.word @song0ref7
	.byte $48, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref282:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $8a
@song0ref299:
	.byte $1b, $89, $45, $89, $1b, $83, $45, $83, $1b, $83, $45, $83, $1b, $89, $45, $89, $1b, $89, $45, $89
	.byte $41, $14
	.word @song0ref299
@song0ref322:
	.byte $20, $89, $45, $89, $20, $83, $45, $83, $20, $83, $45, $83, $20, $89, $45, $89, $20, $89, $45, $89
@song0ref342:
	.byte $1e, $89, $45, $89, $1e, $83, $45, $83, $1e, $83, $45, $83, $1e, $89, $45, $89, $1e, $89, $45, $89
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref342
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $28
	.word @song0ref322
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref342
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $28
	.word @song0ref322
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref342
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $28
	.word @song0ref322
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref342
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref342
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref342
	.byte $41, $14
	.word @song0ref299
	.byte $41, $14
	.word @song0ref342
	.byte $41, $14
	.word @song0ref299
	.byte $7a
@song0ref456:
	.byte $27, $91, $00, $81, $27, $a9, $00, $81, $2c, $91, $00, $81, $2a, $91, $00, $81, $27, $a9, $00, $81, $2c, $91, $00, $81
	.byte $2a, $91, $00, $81, $2c, $a9, $00, $81, $2a, $91, $00, $81, $27, $91, $00, $81, $2c, $a9, $00, $81, $2a, $91, $00, $81
	.byte $41, $30
	.word @song0ref456
	.byte $41, $30
	.word @song0ref456
	.byte $41, $30
	.word @song0ref456
	.byte $41, $30
	.word @song0ref456
	.byte $41, $30
	.word @song0ref456
	.byte $41, $30
	.word @song0ref456
	.byte $41, $30
	.word @song0ref456
	.byte $27, $91, $00, $ff, $a9
	.byte $41, $0e
	.word @song0ref282
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $df, $8a
@song0ref545:
	.byte $33, $95, $43, $50, $f8, $3f, $44, $89, $38, $89, $33, $95, $43, $50, $f8, $3f, $44, $89, $38, $89, $00, $ff, $bd, $df
	.byte $41, $10
	.word @song0ref545
	.byte $41, $10
	.word @song0ref545
	.byte $41, $0f
	.word @song0ref545
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $8c
	.byte $41, $18
	.word @song0ref202
	.byte $41, $18
	.word @song0ref227
	.byte $41, $18
	.word @song0ref202
	.byte $41, $18
	.word @song0ref227
	.byte $41, $18
	.word @song0ref202
	.byte $41, $18
	.word @song0ref227
	.byte $41, $18
	.word @song0ref202
	.byte $41, $18
	.word @song0ref227
	.byte $41, $18
	.word @song0ref202
	.byte $41, $18
	.word @song0ref227
	.byte $41, $18
	.word @song0ref202
	.byte $41, $18
	.word @song0ref227
	.byte $41, $18
	.word @song0ref202
	.byte $41, $18
	.word @song0ref227
	.byte $41, $18
	.word @song0ref202
	.byte $41, $18
	.word @song0ref227
	.byte $41, $10
	.word @song0ref282
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $ff, $bf, $ff, $bf, $ff, $bf
@song0ref655:
	.byte $80, $25, $95, $25, $89, $25, $89, $82, $26, $95, $86, $2f, $95, $80, $25, $95, $25, $95, $82, $26, $95, $86, $2f, $95
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
@song0ref724:
	.byte $88, $2a, $95, $29, $95, $27, $95, $25, $95, $2a, $95, $29, $95, $27, $95, $25, $95
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $12
	.word @song0ref655
	.byte $41, $10
	.word @song0ref724
	.byte $00, $ff, $bd, $ff, $bf, $ff, $bf, $42
	.word @song0ch3loop
@song0ch12:
@song0ch11:
@song0ch4:
@song0ch4loop:
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $79, $80
@song0ref796:
	.byte $1b, $95, $1b, $89, $1b, $89, $1b, $95, $1b, $95, $1b, $95, $1b, $89, $1b, $89, $1b, $95, $1b, $95, $19, $95, $19, $89
	.byte $19, $89, $19, $95, $19, $95, $19, $95, $19, $89, $19, $89, $19, $95, $19, $95, $17, $95, $17, $89, $17, $89, $17, $95
	.byte $17, $95, $17, $95, $17, $89, $17, $89, $17, $95, $17, $95
@song0ref856:
	.byte $14, $95, $14, $89, $14, $89, $14, $95, $14, $95, $14, $95, $14, $89, $14, $89, $14, $95, $14, $95
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $41, $14
	.word @song0ref856
	.byte $41, $14
	.word @song0ref856
	.byte $00, $ff, $bd
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $41, $50
	.word @song0ref796
	.byte $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $7c, $80
@song0ref924:
	.byte $0f, $95, $0f, $89, $0f, $89, $0f, $95, $0f, $95, $0f, $95, $0f, $89, $0f, $89, $0f, $95, $0f, $95, $0d, $95, $0d, $89
	.byte $0d, $89, $0d, $95, $0d, $95, $0d, $95, $0d, $89, $0d, $89, $0d, $95, $0d, $95, $0b, $95, $0b, $89, $0b, $89, $0b, $95
	.byte $0b, $95, $0b, $95, $0b, $89, $0b, $89, $0b, $95, $0b
@song0ref983:
	.byte $95
@song0ref984:
	.byte $08, $95, $08, $89, $08, $89, $08, $95, $08, $95, $08, $95, $08, $89, $08, $89, $08, $95, $08, $95
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $41, $14
	.word @song0ref984
	.byte $41, $14
	.word @song0ref984
	.byte $00, $ff, $bd
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $41, $50
	.word @song0ref924
	.byte $42
	.word @song0ch6loop
@song0ch7:
@song0ch7loop:
	.byte $7c, $80
	.byte $41, $14
	.word @song0ref984
@song0ref1055:
	.byte $06, $95, $06, $89, $06, $89, $06, $95, $06, $95, $06, $95, $06, $89, $06, $89, $06, $95, $06, $95, $04, $95, $04, $89
	.byte $04, $89, $04, $95, $04, $95, $04, $95, $04, $89, $04, $89, $04, $95, $04
@song0ref1094:
	.byte $95, $01, $95, $01, $89, $01, $89, $01, $95, $01, $95, $01, $95, $01, $89, $01, $89, $01, $95, $01
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $14
	.word @song0ref1094
	.byte $41, $14
	.word @song0ref1094
	.byte $95, $00, $ff, $bd
	.byte $41, $14
	.word @song0ref984
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $95, $42
	.word @song0ch7loop
@song0ch8:
@song0ch8loop:
	.byte $7a, $86
	.byte $41, $14
	.word @song0ref984
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $14
	.word @song0ref1094
	.byte $41, $14
	.word @song0ref1094
	.byte $95, $00, $ff, $bd
	.byte $41, $14
	.word @song0ref984
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $41, $15
	.word @song0ref983
	.byte $41, $3b
	.word @song0ref1055
	.byte $95, $42
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $df, $82
@song0ref1292:
	.byte $33, $95, $43, $50, $27, $3f, $44, $89, $38, $89, $33, $95, $43, $50, $27, $3f, $44, $89, $38, $89, $00, $ff, $bd, $df
	.byte $41, $10
	.word @song0ref1292
	.byte $41, $10
	.word @song0ref1292
	.byte $41, $0f
	.word @song0ref1292
	.byte $41, $10
	.word @song0ref282
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $8a, $1b, $a9, $00, $81, $20, $91, $00, $81, $1e
@song0ref1344:
	.byte $91, $00, $81
@song0ref1347:
	.byte $1b, $a9, $00, $81, $20, $91, $00, $81, $1e, $91, $00, $81, $20, $a9, $00, $81, $1e, $91, $00, $81, $1b, $91, $00, $81
	.byte $20, $a9, $00, $81, $1e, $91, $00, $81, $1b
	.byte $41, $0f
	.word @song0ref1344
	.byte $41, $21
	.word @song0ref1347
	.byte $41, $0f
	.word @song0ref1344
	.byte $41, $21
	.word @song0ref1347
	.byte $41, $0f
	.word @song0ref1344
	.byte $41, $21
	.word @song0ref1347
	.byte $91, $00, $81
	.byte $41, $10
	.word @song0ref282
	.byte $42
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $df, $82
@song0ref1416:
	.byte $27, $95, $43, $50, $14, $33, $38, $89, $2c, $89, $27, $95, $43, $50, $14, $33, $38, $89, $2c, $89, $00, $ff, $bd, $df
	.byte $41, $10
	.word @song0ref1416
	.byte $41, $10
	.word @song0ref1416
	.byte $41, $0f
	.word @song0ref1416
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $41, $10
	.word @song0ref282
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song0ch10loop
@song1ch0:
@song1ref1:
	.byte $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48
	.byte $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48
	.byte $41, $18
	.word @song1ref1
	.byte $48
	.byte $41, $18
	.word @song1ref1
	.byte $48
	.byte $41, $18
	.word @song1ref1
	.byte $48, $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $48, $ff, $ff, $44, $00
@song1ch4:
@song1ch2:
@song1ch1:
@song1ref65:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $17
	.word @song1ref65
	.byte $41, $17
	.word @song1ref65
	.byte $41, $17
	.word @song1ref65
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $44, $00
@song1ch3:
@song1ref112:
	.byte $80, $25, $8d, $00, $9d, $25, $8d, $82, $26, $8d, $00, $9d, $80, $25, $8d, $00, $8d, $25, $8d, $00, $8d, $25, $8d, $82
	.byte $26, $8d, $00, $8d, $84, $29, $8d, $00, $8d
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
@song1ref217:
	.byte $80, $25, $8d, $00, $9d, $25, $8d, $82, $26, $8d, $00, $9d, $80, $25, $8d, $77, $51, $04, $f0, $88, $2a, $8d, $29, $8d
	.byte $27, $8d, $25, $8d, $2a, $8d, $29, $8d, $27, $8d, $25, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1c
	.word @song1ref217
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1c
	.word @song1ref217
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1a
	.word @song1ref112
	.byte $29, $8d
	.byte $41, $1c
	.word @song1ref112
	.byte $41, $1c
	.word @song1ref217
	.byte $00, $ff, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $80, $25, $9d, $82, $26, $8d, $26
	.byte $8d, $44, $00
@song1ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $80
@song1ref380:
	.byte $19, $8d, $5a, $8d, $19, $85, $5a, $85, $19, $85, $5a, $85, $19, $8d, $5a, $8d, $19
@song1ref397:
	.byte $8d, $5a, $8d, $19, $8d, $5a, $8d, $19, $85, $5a, $85, $19, $85, $5a, $85, $19, $8d, $5a, $8d, $19, $8d, $5a, $8d, $1c
	.byte $8d, $5a, $8d, $1c, $85, $5a, $85, $1c, $85, $5a, $85, $1c, $8d, $5a, $8d, $1c
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $41, $39
	.word @song1ref380
	.byte $41, $17
	.word @song1ref397
	.byte $44, $00
@song1ch6:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $80
@song1ref590:
	.byte $0d, $8d, $5a, $8d, $0d, $85, $5a, $85, $0d, $85, $5a, $85, $0d, $8d, $5a, $8d, $0d
@song1ref607:
	.byte $8d, $5a, $8d, $0d, $8d, $5a, $8d, $0d, $85, $5a, $85, $0d, $85, $5a, $85, $0d, $8d, $5a, $8d, $0d, $8d, $5a, $8d, $10
	.byte $8d, $5a, $8d, $10, $85, $5a, $85, $10, $85, $5a, $85, $10, $8d, $5a, $8d, $10
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $41, $39
	.word @song1ref590
	.byte $41, $17
	.word @song1ref607
	.byte $44, $00
@song1ch7:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $80
@song1ref800:
	.byte $06, $8d, $5a, $8d, $06, $85, $5a, $85, $06, $85, $5a, $85, $06, $8d, $5a, $8d, $06
@song1ref817:
	.byte $8d, $5a, $8d, $06, $8d, $5a, $8d, $06, $85, $5a, $85, $06, $85, $5a, $85, $06, $8d, $5a, $8d, $06, $8d, $5a, $8d, $09
	.byte $8d, $5a, $8d, $09, $85, $5a, $85, $09, $85, $5a, $85, $09, $8d, $5a, $8d, $09
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $44, $00
@song1ch8:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $77, $86
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $41, $39
	.word @song1ref800
	.byte $41, $17
	.word @song1ref817
	.byte $44, $00
@song1ch9:
	.byte $41, $17
	.word @song1ref65
	.byte $df, $88, $50, $14, $31, $3d, $9d
@song1ref1168:
	.byte $31, $95, $00, $85, $31, $85, $00, $85, $31, $85, $00, $85, $31, $95, $00, $85, $31
@song1ref1185:
	.byte $95, $00, $85, $31, $95, $00, $85, $31, $85, $00, $85, $31, $85, $00, $85, $31, $95, $00, $85, $31, $95, $00, $85, $34
	.byte $95, $00, $85, $34, $85, $00, $85, $34, $85, $00, $85, $34, $95, $00, $85, $34
	.byte $41, $17
	.word @song1ref1185
	.byte $41, $39
	.word @song1ref1168
	.byte $41, $17
	.word @song1ref1185
	.byte $41, $39
	.word @song1ref1168
	.byte $41, $17
	.word @song1ref1185
	.byte $41, $39
	.word @song1ref1168
	.byte $41, $17
	.word @song1ref1185
@song1ref1246:
	.byte $31, $9d, $00, $8d, $31, $8d, $34, $8d, $00, $8d, $34, $8d, $00, $8d, $36, $9d, $34, $9d, $31, $9d, $00, $9d, $36, $9d
	.byte $34, $9d, $31, $9d, $2d, $9d, $36, $9d, $34, $9d, $31, $9d, $00, $9d
	.byte $41, $22
	.word @song1ref1246
	.byte $39, $9d, $00, $9d
	.byte $41, $26
	.word @song1ref1246
	.byte $41, $22
	.word @song1ref1246
	.byte $39, $9d, $00, $9d
@song1ref1301:
	.byte $3d, $8d, $39, $8d, $36, $8d, $34, $8d, $36, $ed, $34, $8d, $36, $9d, $34, $9d, $3d, $8d, $39, $8d, $36, $8d, $34, $8d
	.byte $36, $ed, $34, $8d, $36, $9d, $39, $9d, $3d, $8d, $39, $8d, $36, $8d, $34, $8d, $36, $ed, $34, $8d, $36, $9d, $34, $9d
	.byte $34, $8d, $36, $8d, $39, $8d, $3d, $8d, $34, $8d, $36, $8d, $39, $8d, $3d, $8d, $36, $8d, $39, $8d, $3d, $8d, $40, $4c
	.byte $8d, $36, $8d, $39, $8d, $3d, $8d, $40, $4c, $8d
	.byte $41, $50
	.word @song1ref1301
	.byte $49, .lobyte(@env4), .hibyte(@env4), $40, $4e, $ff, $fd, $ff, $bf, $88, $50, $e6, $4e, $42, $bd, $00, $ff, $fd
	.byte $41, $17
	.word @song1ref65
	.byte $ff, $ff, $ff, $44, $00
@song1ch10:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $df, $82, $50, $03, $0d, $19, $9d
@song1ref1435:
	.byte $0d, $95, $00, $85, $0d, $85, $00, $85, $0d, $85, $00, $85, $0d, $95, $00, $85, $0d
@song1ref1452:
	.byte $95, $00, $85, $0d, $95, $00, $85, $0d, $85, $00, $85, $0d, $85, $00, $85, $0d, $95, $00, $85, $0d, $95, $00, $85, $10
	.byte $95, $00, $85, $10, $85, $00, $85, $10, $85, $00, $85, $10, $95, $00, $85, $10
	.byte $41, $17
	.word @song1ref1452
	.byte $41, $39
	.word @song1ref1435
	.byte $41, $17
	.word @song1ref1452
	.byte $41, $39
	.word @song1ref1435
	.byte $41, $17
	.word @song1ref1452
	.byte $41, $39
	.word @song1ref1435
	.byte $41, $17
	.word @song1ref1452
	.byte $41, $39
	.word @song1ref1435
	.byte $41, $17
	.word @song1ref1452
	.byte $41, $39
	.word @song1ref1435
	.byte $41, $17
	.word @song1ref1452
	.byte $84, $0d, $9d, $00, $8d, $0d, $8d, $10, $8d, $00, $8d, $10, $8d, $00, $8d, $12, $9d, $10, $9d, $0d, $9d, $00, $9d, $82
@song1ref1549:
	.byte $12, $9d, $10, $9d, $0d, $9d, $09, $9d, $12, $9d, $10, $9d
@song1ref1561:
	.byte $0d
@song1ref1562:
	.byte $9d, $00, $9d, $0d, $9d, $00, $8d, $0d, $8d, $10, $8d, $00, $8d, $10, $8d, $00, $8d, $12, $9d, $10, $9d, $0d, $9d, $00
	.byte $9d, $12, $9d, $10, $9d, $0d, $9d, $09, $9d, $12, $9d, $10, $9d, $15
	.byte $41, $25
	.word @song1ref1562
	.byte $41, $27
	.word @song1ref1561
	.byte $9d, $00, $9d
@song1ref1609:
	.byte $19, $8d, $15, $8d, $12, $8d, $10, $8d, $12, $ed, $10, $8d, $12, $9d, $10
@song1ref1624:
	.byte $9d, $19, $8d, $15, $8d, $12, $8d, $10, $8d, $12, $ed, $10, $8d, $12, $9d, $15, $9d, $19, $8d, $15, $8d, $12, $8d, $10
	.byte $8d, $12, $ed, $10, $8d, $12, $9d, $10
@song1ref1656:
	.byte $9d, $10, $8d, $12, $8d, $15, $8d, $19, $8d, $10, $8d, $12, $8d, $15, $8d, $19, $8d, $12, $8d, $15, $8d, $19, $8d, $1c
	.byte $8d, $12, $8d, $15, $8d, $19, $8d, $1c, $8d
	.byte $41, $50
	.word @song1ref1609
	.byte $49, .lobyte(@env4), .hibyte(@env4), $1e, $ff, $fd, $ff, $bf, $82, $50, $fc, $2a, $1e, $bd, $00, $ff, $fd
	.byte $41, $17
	.word @song1ref65
	.byte $ff, $ff, $ff, $44, $00
@song1ch11:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $df, $82, $50, $05, $19, $25, $9d
@song1ref1740:
	.byte $25, $95, $00, $85, $25, $85, $00, $85, $25, $85, $00, $85, $25, $95, $00, $85, $25
@song1ref1757:
	.byte $95, $00, $85, $25, $95, $00, $85, $25, $85, $00, $85, $25, $85, $00, $85, $25, $95, $00, $85, $25, $95, $00, $85, $28
	.byte $95, $00, $85, $28, $85, $00, $85, $28, $85, $00, $85, $28, $95, $00, $85, $28
	.byte $41, $17
	.word @song1ref1757
	.byte $41, $39
	.word @song1ref1740
	.byte $41, $17
	.word @song1ref1757
	.byte $41, $39
	.word @song1ref1740
	.byte $41, $17
	.word @song1ref1757
	.byte $41, $39
	.word @song1ref1740
	.byte $41, $17
	.word @song1ref1757
	.byte $41, $39
	.word @song1ref1740
	.byte $41, $17
	.word @song1ref1757
	.byte $41, $39
	.word @song1ref1740
	.byte $41, $17
	.word @song1ref1757
	.byte $0d, $9d, $00, $8d, $0d, $8d, $10, $8d, $00, $8d, $10, $8d, $00, $8d, $12, $9d, $10, $9d, $0d, $9d, $00, $9d, $2a, $9d
	.byte $28, $9d, $25, $9d, $21, $9d, $2a, $9d, $28, $9d
@song1ref1864:
	.byte $25
@song1ref1865:
	.byte $9d, $00, $9d, $25, $9d, $00, $8d, $25, $8d, $28, $8d, $00, $8d, $28, $8d, $00, $8d, $2a, $9d, $28, $9d, $25, $9d, $00
	.byte $9d, $2a, $9d, $28, $9d, $25, $9d, $21, $9d, $2a, $9d, $28, $9d, $2d
	.byte $41, $25
	.word @song1ref1865
	.byte $41, $27
	.word @song1ref1864
	.byte $9d, $00, $9d
@song1ref1912:
	.byte $31, $8d, $2d, $8d, $2a, $8d, $28, $8d, $2a, $ed, $28, $8d, $2a, $9d, $28, $9d, $31, $8d, $2d, $8d, $2a, $8d, $28, $8d
	.byte $2a, $ed, $28, $8d, $2a, $9d, $2d, $9d, $31, $8d, $2d, $8d, $2a, $8d, $28, $8d, $2a, $ed, $28, $8d, $2a, $9d, $28, $9d
@song1ref1960:
	.byte $28, $8d, $2a, $8d, $2d, $8d, $31, $8d, $28, $8d, $2a, $8d, $2d, $8d, $31, $8d, $2a, $8d, $2d, $8d, $31, $8d, $34, $8d
	.byte $2a, $8d, $2d, $8d, $31, $8d, $34, $8d
	.byte $41, $50
	.word @song1ref1912
	.byte $49, .lobyte(@env4), .hibyte(@env4), $36, $ff, $fd, $ff, $bf, $82, $50, $f3, $42, $36, $bd, $00, $ff, $fd
	.byte $41, $17
	.word @song1ref65
	.byte $ff, $ff, $ff, $44, $00
@song1ch12:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $df, $84, $50, $04, $12, $1e, $9d
@song1ref2043:
	.byte $12, $8d, $5a, $8d, $12, $85, $5a, $85, $12, $95, $5a, $95, $12, $8d, $5a, $8d
@song1ref2059:
	.byte $12, $8d, $5a, $8d, $12, $85, $5a, $85, $12, $95, $5a, $95, $12, $8d, $5a, $8d, $15, $8d, $5a, $8d, $15, $85, $5a, $85
	.byte $15, $95, $5a, $95, $15, $8d, $5a, $8d
	.byte $41, $20
	.word @song1ref2043
	.byte $41, $20
	.word @song1ref2059
	.byte $41, $20
	.word @song1ref2043
	.byte $41, $20
	.word @song1ref2059
	.byte $41, $20
	.word @song1ref2043
	.byte $41, $20
	.word @song1ref2059
	.byte $41, $20
	.word @song1ref2043
	.byte $41, $20
	.word @song1ref2059
	.byte $41, $20
	.word @song1ref2043
	.byte $41, $20
	.word @song1ref2059
	.byte $12, $8d, $5a, $8d, $12, $85, $5a, $85, $12, $95, $5a, $95, $12, $8d, $5a, $8d, $82, $25, $9d, $00, $8d, $25, $8d, $28
	.byte $8d, $00, $8d, $28, $8d, $00, $8d, $2a, $9d, $28, $9d, $25, $9d, $00, $9d, $84
	.byte $41, $33
	.word @song1ref1549
	.byte $41, $25
	.word @song1ref1562
	.byte $41, $27
	.word @song1ref1561
	.byte $9d, $00, $9d, $19, $8d, $15, $8d, $12, $8d, $10, $8d, $12, $ed, $04, $8d, $06, $9d, $04
	.byte $41, $1b
	.word @song1ref1624
	.byte $04, $8d, $06, $9d, $04
	.byte $41, $21
	.word @song1ref1656
	.byte $19, $8d, $15, $8d, $12, $8d, $10, $8d, $12, $ed, $04, $8d, $06, $9d, $04
	.byte $41, $1b
	.word @song1ref1624
	.byte $04, $8d, $06, $9d, $04, $9d, $88
	.byte $41, $20
	.word @song1ref1960
	.byte $49, .lobyte(@env4), .hibyte(@env4), $36, $ff, $fd, $ff, $bf, $88, $50, $f3, $42, $36, $bd, $00, $ff, $fd
	.byte $41, $17
	.word @song1ref65
	.byte $ff, $ff, $ff, $44, $00
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $42
	.word @song2ch0loop
@song2ch12:
@song2ch11:
@song2ch10:
@song2ch9:
@song2ch8:
@song2ch7:
@song2ch6:
@song2ch5:
@song2ch3:
@song2ch2:
@song2ch1:
@song2ch1loop:
	.byte $ff, $ff, $bf, $42
	.word @song2ch1loop
@song2ch4:
@song2ch4loop:
	.byte $01, $91, $02, $91, $00, $ff, $ff, $95, $42
	.word @song2ch4loop
