; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @pal
	.word @pal
@pal:
	.word @sfx_pal_song_1
	.word @sfx_pal_song_2

@sfx_pal_song_1:
	.byte $84,$57,$85,$00,$83,$b7,$89,$f0,$01,$83,$75,$01,$83,$74,$01,$83
	.byte $73,$00
@sfx_pal_song_2:
	.byte $84,$b0,$85,$00,$83,$7a,$89,$f0,$01,$83,$37,$01,$83,$75,$01,$83
	.byte $73,$01,$83,$72,$01,$84,$84,$83,$7a,$01,$83,$37,$01,$83,$75,$01
	.byte $83,$73,$01,$84,$b0,$83,$7a,$01,$83,$37,$01,$83,$75,$01,$83,$73
	.byte $01,$84,$84,$83,$7a,$01,$83,$37,$01,$83,$75,$01,$83,$73,$00

.export sounds
