; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Tree Climber:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1

.export _music_data_tree_climber:=music_data_tree_climber

music_data_tree_climber:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Boss (N163) PAL
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 2, 0

.export music_data_tree_climber
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env31,@env23,@env26,@env1 ; 00 : HiHat 1
	.word @env15,@env37,@env26,@env1 ; 01 : Kick
	.word @env38,@env19,@env26,@env1 ; 02 : Triangle Snare
	.word @env32,@env34,@env26,@env1 ; 03 : Triangle Kick
	.word @env3,@env5,@env26,@env1 ; 04 : Snare Short
	.word @env6,@env9,@env26,@env1 ; 05 : HiHat Long
	.word @env2,@env14,@env26,@env1 ; 06 : Crash
	.word @env24,@env23,@env26,@env1 ; 07 : HiHat
	.word @env22,@env23,@env29,@env1 ; 08 : Background
	.word @env20,@env23,@env26,@env1 ; 09 : Snare
	.word @env7,@env23,@env26,@env1 ; 0a : Lead
	.word @env10,@env36,@env26,@env1 ; 0b : Crash Rev
	.word @env0,@env13,@env26,@env1 ; 0c : Snare 1

@instruments_exp:
	.word @env25, @env23, @env1 ; 00 : Chord
	.word @env1
	.byte $50, $10
	.word @n163_inst0_waves
	.byte $00, $00, $00, $00
	.word @env27, @env23, @env1 ; 01 : Bell
	.word @env35
	.byte $10, $10
	.word @n163_inst1_waves
	.byte $00, $00, $00, $00
	.word @env16, @env23, @env1 ; 02 : Triangle N163
	.word @env1
	.byte $20, $20
	.word @n163_inst2_waves
	.byte $00, $00, $00, $00
	.word @env17, @env23, @env1 ; 03 : Whistle
	.word @env1
	.byte $00, $10
	.word @n163_inst3_waves
	.byte $00, $00, $00, $00
	.word @env28, @env23, @env1 ; 04 : Instrument 1
	.word @env35
	.byte $00, $10
	.word @n163_inst4_waves
	.byte $00, $00, $00, $00
	.word @env7, @env23, @env1 ; 05 : Instrument 3
	.word @env1
	.byte $40, $10
	.word @n163_inst5_waves
	.byte $00, $00, $00, $00

@env0:
	.byte $00,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c0,$00,$0d
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $00,$c8,$c7,$02,$c6,$03,$c5,$02,$c4,$05,$c3,$03,$c2,$03,$c1,$00,$0e
@env3:
	.byte $00,$c9,$c8,$c7,$c5,$c3,$c2,$c1,$02,$c0,$00,$09
@env4:
	.byte $00,$00,$00,$00,$00,$00,$00,$ee
@env5:
	.byte $b9,$bb,$bc,$00,$02
@env6:
	.byte $00,$cd,$ca,$ca,$c9,$c7,$00,$05
@env7:
	.byte $07,$ca,$cf,$cc,$c9,$00,$04,$c8,$c7,$c6,$c5,$c3,$c1,$c0,$00,$0d
@env8:
	.byte $00,$00,$00,$00,$00,$00,$00,$bb
@env9:
	.byte $be,$c0,$00,$01
@env10:
	.byte $00,$c1,$c2,$03,$c3,$03,$c4,$05,$c5,$02,$c6,$03,$c7,$02,$c8,$c0,$00,$0f
@env11:
	.byte $00,$00,$00,$00,$bb,$bb,$bb,$bb
@env12:
	.byte $ff,$00,$00,$00,$00,$00,$00,$00
@env13:
	.byte $ad,$b5,$be,$00,$02
@env14:
	.byte $bb,$be,$00,$01
@env15:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env16:
	.byte $00,$cf,$7f,$00,$02
@env17:
	.byte $00,$c1,$c3,$c4,$c5,$c6,$c7,$c8,$c8,$c9,$02,$ca,$05,$cb,$00,$0d
@env18:
	.byte $00,$00,$00,$00,$77,$77,$77,$77
@env19:
	.byte $c0,$bb,$b7,$b3,$af,$ac,$a6,$00,$06
@env20:
	.byte $00,$cc,$c6,$c3,$c0,$00,$04
@env21:
	.byte $00,$00,$00,$00,$ee,$ee,$ee,$ee
@env22:
	.byte $00,$c9,$ca,$02,$c7,$c4,$c2,$00,$06
@env23:
	.byte $c0,$7f,$00,$01
@env24:
	.byte $00,$cc,$c0,$00,$02
@env25:
	.byte $00,$c1,$06,$c2,$06,$c3,$00,$05
@env26:
	.byte $7f,$00,$00
@env27:
	.byte $00,$ce,$cd,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$02,$c4,$c4,$c3,$c2,$02,$c1,$06,$c0,$00,$14
@env28:
	.byte $00,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$0c
@env29:
	.byte $c2,$7f,$00,$00
@env30:
	.byte $10,$32,$54,$76,$98,$ba,$dc,$fe,$ef,$cd,$ab,$89,$67,$45,$23,$01
@env31:
	.byte $00,$c6,$c3,$c0,$00,$03
@env32:
	.byte $00,$cf,$03,$c0,$00,$03
@env33:
	.byte $00,$00,$00,$80,$ee,$ee,$ee,$ee
@env34:
	.byte $c0,$bb,$b6,$b1,$ad,$00,$04
@env35:
	.byte $00,$c0,$c1,$00,$02
@env36:
	.byte $be,$18,$bb,$00,$02
@env37:
	.byte $c0,$be,$bd,$00,$02
@env38:
	.byte $00,$cf,$06,$c0,$00,$03

@n163_inst0_waves:
	.word @env33

@n163_inst1_waves:
	.word @env11
	.word @env8

@n163_inst2_waves:
	.word @env30

@n163_inst3_waves:
	.word @env18

@n163_inst4_waves:
	.word @env21
	.word @env4

@n163_inst5_waves:
	.word @env12

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$06,$80

@song0ch0:
	.byte $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $7a, $ff, $9f, $48
@song0ref14:
	.byte $45, $91, $94
@song0ref17:
	.byte $16, $87, $14, $87, $16, $87, $45, $87, $14, $87, $16, $87, $45, $87, $14, $87, $16, $87, $14, $87, $19, $91, $16, $87
	.byte $45, $87, $48, $93
	.byte $41, $14
	.word @song0ref17
@song0ref48:
	.byte $1b, $91, $19, $87, $45, $87, $48, $93
@song0ref56:
	.byte $1e, $87, $1d, $87, $1e, $87, $45, $87, $1d, $87, $1e, $87, $45, $87, $1d, $87, $1e, $87, $1d, $87, $1e, $91, $1b, $87
	.byte $45, $87, $48
@song0ref83:
	.byte $1d, $91, $45, $87, $1b, $91, $45, $87, $19, $91, $18, $a5, $15, $a5, $48, $45, $91
	.byte $41, $1b
	.word @song0ref17
	.byte $41, $14
	.word @song0ref17
	.byte $41, $2f
	.word @song0ref48
@song0ref109:
	.byte $48
@song0ref110:
	.byte $22, $91, $45, $a5, $1d, $91, $21, $91, $45, $a5, $1d, $91, $48
@song0ref123:
	.byte $20, $91, $45, $91, $20, $91, $22, $91, $1f, $91, $45, $91, $1b, $91, $45, $91, $48
@song0ref140:
	.byte $1e, $91, $45, $91, $1e, $87, $20, $87, $1e, $91, $1d, $91, $45, $87, $19, $91, $45, $87, $16, $91, $48
@song0ref161:
	.byte $1b, $91, $1d, $87, $45, $87, $1e, $91, $22, $87, $45, $87, $20, $9b, $1d, $9b, $24, $91
	.byte $41, $14
	.word @song0ref109
	.byte $25, $91, $45, $91, $22, $91, $45, $91, $48, $27, $91, $45, $a5, $27, $87, $29, $87, $2a, $87, $45, $87, $29, $87, $45
	.byte $87, $27, $87, $45, $87, $25, $87, $45, $87, $48, $29, $a5, $51, $fd, $10, $f7, $48, $7a
@song0ref224:
	.byte $90
@song0ref225:
	.byte $22, $91, $25, $91, $27, $91, $25, $87, $2a, $9b, $29, $91, $27, $91, $29, $91, $48
@song0ref242:
	.byte $2e, $91, $29, $91, $27, $91, $29, $87, $27, $9b, $20, $91, $22, $a5, $48
@song0ref257:
	.byte $25, $91, $24, $91, $22, $91, $20, $87, $29, $9b, $27, $91, $25, $91, $24, $91, $48
@song0ref274:
	.byte $2c, $91, $2a, $91, $29, $91, $27, $91, $2d, $91, $2a, $91, $29, $91, $27, $91, $48
	.byte $41, $3e
	.word @song0ref225
	.byte $48
	.byte $41, $3e
	.word @song0ref225
	.byte $48
	.byte $41, $3e
	.word @song0ref225
	.byte $48, $00, $ff, $9d, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff, $9f, $48, $ff
	.byte $9f, $48
@song0ref328:
	.byte $22, $9b, $22, $9b, $20, $91, $22, $91, $00, $91, $2e, $87, $00, $9b, $48, $ff, $9f, $44, $00
@song0ch1:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $73, $ff, $9f, $93
	.byte $41, $1b
	.word @song0ref14
	.byte $9b
	.byte $41, $14
	.word @song0ref17
	.byte $1b, $91, $19, $87, $45, $9b
	.byte $41, $1a
	.word @song0ref56
	.byte $41, $0d
	.word @song0ref83
	.byte $91, $93, $45, $91
	.byte $41, $19
	.word @song0ref17
	.byte $9b
	.byte $41, $14
	.word @song0ref17
	.byte $1b, $91, $19, $87, $45, $9b
	.byte $41, $1a
	.word @song0ref56
	.byte $41, $0d
	.word @song0ref83
	.byte $91, $93
	.byte $41, $0c
	.word @song0ref110
	.byte $41, $10
	.word @song0ref123
	.byte $41, $14
	.word @song0ref140
	.byte $41, $12
	.word @song0ref161
	.byte $41, $0c
	.word @song0ref110
	.byte $20, $91, $45, $91, $20, $91, $22, $91, $25, $91, $45, $91, $22, $91, $7b, $1b, $91, $45, $a5, $1b, $87, $1d, $87, $1e
	.byte $87, $45, $87, $1d, $87, $45, $87, $1b, $87, $45, $87, $19, $87, $45, $87, $1d, $a5, $51, $fd, $10, $f7, $72, $00, $91
	.byte $41, $10
	.word @song0ref224
	.byte $41, $0d
	.word @song0ref242
	.byte $91, $93
	.byte $41, $10
	.word @song0ref257
	.byte $41, $10
	.word @song0ref274
	.byte $41, $10
	.word @song0ref225
	.byte $41, $0d
	.word @song0ref242
	.byte $91, $93
	.byte $41, $10
	.word @song0ref257
	.byte $41, $10
	.word @song0ref274
	.byte $41, $10
	.word @song0ref225
	.byte $41, $0d
	.word @song0ref242
	.byte $91, $93
	.byte $41, $10
	.word @song0ref257
	.byte $41, $10
	.word @song0ref274
	.byte $41, $10
	.word @song0ref225
	.byte $41, $0d
	.word @song0ref242
	.byte $91, $93
	.byte $41, $10
	.word @song0ref257
	.byte $41, $10
	.word @song0ref274
	.byte $00, $ff, $89
@song0ref524:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $89
	.byte $41, $0d
	.word @song0ref328
	.byte $91, $ff, $9f, $44, $00
@song0ch2:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $e3, $84, $29, $87, $00, $87, $29, $87, $00, $87, $29, $87, $00, $87
@song0ref568:
	.byte $86, $22, $87, $00, $9b, $84, $29, $87, $00, $91, $86, $22, $87, $00, $91, $22, $87, $00, $87, $84, $29, $87, $00, $9b
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $41, $14
	.word @song0ref568
	.byte $29, $87, $00, $91, $29, $87, $00, $91, $29, $87, $00, $87, $29, $87, $00, $9b, $86, $22, $87, $00, $9b, $ff, $9f, $44
	.byte $00
@song0ch3:
	.byte $ff, $9f, $ff, $9f
@song0ref739:
	.byte $8e, $19, $87, $00, $87, $21, $87, $21, $87, $92, $21, $87, $00, $9b
	.byte $41, $0c
	.word @song0ref739
	.byte $8e, $19, $87, $00, $87, $21, $87, $21, $87, $19, $87, $00, $87, $21, $87, $21, $87, $19, $87, $00, $87, $88, $21, $91
	.byte $21, $91, $21, $91
@song0ref784:
	.byte $8c, $1f, $a5
@song0ref787:
	.byte $88, $21, $87, $80, $23, $87, $1f, $87, $82, $17, $87, $80, $21, $87, $23, $87, $82, $17, $87, $80, $1f, $87, $88, $21
	.byte $87, $80, $23, $87, $8a, $23, $91, $82, $17, $87, $80, $23, $87, $1f, $87, $23, $87
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $16
	.word @song0ref787
	.byte $41, $20
	.word @song0ref784
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $1e
	.word @song0ref787
	.byte $41, $12
	.word @song0ref787
	.byte $96, $1f, $9b, $98, $21, $9b, $21, $9b, $21, $91, $21, $9b, $00, $87, $8c, $1f, $a5, $9d, $00, $ff, $44, $00
@song0ch4:
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0e
	.word @song0ref524
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $44, $00
@song0ch5:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $88
@song0ref1006:
	.byte $22
@song0ref1007:
	.byte $87, $00, $87, $29, $87, $00, $87, $27, $87, $00, $87, $29, $87, $00, $87, $2a
	.byte $41, $0f
	.word @song0ref1007
	.byte $41, $11
	.word @song0ref1006
@song0ref1029:
	.byte $87, $00, $87, $29, $87, $00, $87, $27, $87, $00, $87, $25, $87, $00, $87, $1e, $87, $00, $87, $25, $87, $00, $87, $22
	.byte $87, $00, $87, $25
	.byte $41, $0f
	.word @song0ref1029
@song0ref1060:
	.byte $24, $87, $00, $87, $20, $87, $00, $87, $27, $87, $00, $87, $24, $87, $00, $87, $27, $87, $00, $87, $21, $87, $00, $87
	.byte $27, $87, $00, $87, $2a, $87, $00, $87, $29, $87, $00, $87
	.byte $41, $11
	.word @song0ref1006
	.byte $41, $0f
	.word @song0ref1007
	.byte $41, $11
	.word @song0ref1006
	.byte $41, $1c
	.word @song0ref1029
	.byte $41, $0f
	.word @song0ref1029
	.byte $41, $24
	.word @song0ref1060
@song0ref1114:
	.byte $22
@song0ref1115:
	.byte $87, $00, $87, $25, $87, $00, $87, $29, $87, $00, $87, $25, $87, $00, $87, $21
	.byte $41, $0f
	.word @song0ref1115
	.byte $20
	.byte $41, $0f
	.word @song0ref1115
@song0ref1138:
	.byte $1f
@song0ref1139:
	.byte $87, $00, $87, $22, $87, $00, $87, $25, $87, $00, $87, $22, $87, $00, $87, $1e
	.byte $41, $0f
	.word @song0ref1139
@song0ref1158:
	.byte $1d, $87, $00, $87, $22, $87, $00, $87, $25, $87, $00, $87, $27, $87, $00, $87, $1e, $87, $00, $87, $22, $87, $00, $87
	.byte $25, $87, $00, $87, $2a, $87, $00, $87, $20, $87, $24, $87, $27, $87, $2c, $87, $21, $87, $24, $87, $27, $87, $2d, $87
	.byte $41, $11
	.word @song0ref1114
	.byte $41, $0f
	.word @song0ref1115
	.byte $20
	.byte $41, $0f
	.word @song0ref1115
	.byte $41, $11
	.word @song0ref1138
	.byte $41, $0f
	.word @song0ref1139
	.byte $41, $30
	.word @song0ref1158
	.byte $00, $ff, $9d
	.byte $41, $0e
	.word @song0ref524
	.byte $82
@song0ref1232:
	.byte $2e, $cd, $00, $cd, $31, $cd, $30, $cd, $2a, $cd, $00, $cd, $2c, $cd, $2d, $cd
	.byte $41, $10
	.word @song0ref1232
	.byte $00, $ff, $9d
	.byte $41, $0e
	.word @song0ref524
	.byte $ff, $9f, $ff, $9f, $44, $00
@song0ch6:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $f7, $84, $50, $f9, $2e, $22
@song0ref1276:
	.byte $a5
@song0ref1277:
	.byte $16, $85, $00, $16, $87, $00, $87, $16, $85, $00, $16, $87, $00, $87, $14, $87, $16, $87, $00, $a5, $14
	.byte $41, $0f
	.word @song0ref1276
@song0ref1301:
	.byte $19, $87, $16, $87, $00, $a5, $14, $a5, $12, $85, $00, $12, $87, $00, $87, $12, $85, $00, $12, $87, $00, $87, $11, $87
	.byte $12, $87, $00, $a5, $0f, $91, $12, $87, $13, $87, $14, $85, $00, $14, $87, $00, $87, $14, $85, $00, $14, $87, $00, $87
	.byte $14, $87, $15, $87, $00, $91, $11, $91, $1d, $87, $1b, $87, $19, $87, $18, $87
	.byte $41, $15
	.word @song0ref1277
	.byte $41, $0f
	.word @song0ref1276
	.byte $41, $40
	.word @song0ref1301
@song0ref1374:
	.byte $16, $9b, $2e, $87, $00, $91, $16, $91, $15, $9b, $2d, $87, $00, $91, $15, $91, $14, $9b, $2c, $87, $00, $91, $14, $91
	.byte $13, $9b, $2b, $87, $00, $91, $13, $91, $12, $9b, $2a, $87, $00, $91, $12, $91, $11, $9b, $29, $87, $00, $91, $11, $91
	.byte $12, $9b, $2a, $87, $00, $91, $12, $91, $15, $9b, $2c, $87, $00, $91, $15, $91
	.byte $41, $40
	.word @song0ref1374
	.byte $41, $15
	.word @song0ref1277
	.byte $41, $0f
	.word @song0ref1276
	.byte $41, $40
	.word @song0ref1301
	.byte $41, $15
	.word @song0ref1277
	.byte $41, $0f
	.word @song0ref1276
	.byte $41, $40
	.word @song0ref1301
	.byte $41, $15
	.word @song0ref1277
	.byte $41, $0f
	.word @song0ref1276
	.byte $41, $40
	.word @song0ref1301
	.byte $41, $15
	.word @song0ref1277
	.byte $41, $0f
	.word @song0ref1276
	.byte $41, $40
	.word @song0ref1301
	.byte $41, $40
	.word @song0ref1374
	.byte $41, $40
	.word @song0ref1374
	.byte $16, $91, $00, $87, $16, $9b, $14, $91, $16, $91, $00, $91, $2e, $87, $00, $9b, $ff, $9f, $44, $00
@song0ch7:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $84
@song0ref1513:
	.byte $22, $85, $00, $22, $87, $00, $a5, $22, $85, $00, $22, $87, $00, $cd
	.byte $41, $0e
	.word @song0ref1513
@song0ref1530:
	.byte $1e, $85, $00, $1e, $87, $00, $a5, $1e, $85, $00, $1e, $87, $00, $b9, $1e, $87, $1f, $87, $20, $85, $00, $20, $87, $00
	.byte $a5, $20, $87, $21, $87, $00, $91, $1d, $87, $00, $87, $29, $87, $27, $87, $25, $87, $24, $87
	.byte $41, $0e
	.word @song0ref1513
	.byte $41, $0e
	.word @song0ref1513
	.byte $41, $2b
	.word @song0ref1530
@song0ref1582:
	.byte $22, $87, $00, $91, $22, $87, $00, $91, $22, $87, $00, $87, $21, $87, $00, $91, $21, $87, $00, $91, $21, $87, $00, $87
	.byte $20, $87, $00, $91, $20, $87, $00, $91, $20, $87, $00, $87, $1f, $87, $00, $91, $1f, $87, $00, $91, $1f
@song0ref1627:
	.byte $87, $00, $87, $1e, $87, $00, $91, $1e, $87, $00, $91, $1e, $87, $00, $87, $1d, $87, $00, $91, $1d, $87, $00, $91, $1d
	.byte $41, $0f
	.word @song0ref1627
@song0ref1654:
	.byte $20, $87, $00, $91, $21, $87, $00, $91, $24, $87, $00, $87
	.byte $41, $45
	.word @song0ref1582
	.byte $41, $0f
	.word @song0ref1627
	.byte $41, $0c
	.word @song0ref1654
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $0e
	.word @song0ref1513
	.byte $41, $0e
	.word @song0ref1513
	.byte $41, $2b
	.word @song0ref1530
	.byte $41, $0e
	.word @song0ref1513
	.byte $41, $0e
	.word @song0ref1513
	.byte $41, $2b
	.word @song0ref1530
	.byte $41, $0e
	.word @song0ref1513
	.byte $41, $0e
	.word @song0ref1513
	.byte $41, $2b
	.word @song0ref1530
	.byte $41, $45
	.word @song0ref1582
	.byte $41, $0f
	.word @song0ref1627
	.byte $41, $0c
	.word @song0ref1654
	.byte $41, $45
	.word @song0ref1582
	.byte $41, $0f
	.word @song0ref1627
	.byte $41, $0c
	.word @song0ref1654
	.byte $22, $87, $00, $91, $22, $87, $00, $91, $20, $87, $00, $87, $22, $87, $00, $c3, $ff, $9f, $44, $00
@song0ch8:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $77, $4e, $ff, $93, $8a
@song0ref1762:
	.byte $16, $87, $14, $87, $16, $87, $5a, $87, $14, $87, $16, $87, $5a, $87, $14, $87, $16, $87, $14, $87, $19, $91, $16, $87
	.byte $5a, $87, $93
	.byte $41, $14
	.word @song0ref1762
@song0ref1792:
	.byte $1b, $91, $19, $87, $5a, $87, $93, $1e, $87, $1d, $87, $1e, $87, $5a, $87, $1d, $87, $1e, $87, $5a, $87, $1d, $87, $1e
	.byte $87, $1d, $87, $1e, $91, $1b, $87, $5a, $87, $1d, $91, $5a, $87, $1b, $91, $5a, $87, $19, $91, $18, $a5, $15, $a5, $5a
	.byte $91
	.byte $41, $1b
	.word @song0ref1762
	.byte $41, $14
	.word @song0ref1762
	.byte $41, $2f
	.word @song0ref1792
@song0ref1850:
	.byte $22, $91, $5a, $a5, $1d, $91, $21, $91, $5a, $a5, $1d, $91, $20, $91, $5a, $91, $20, $91, $22, $91, $1f, $91, $5a, $91
	.byte $1b, $91, $5a, $91, $1e, $91, $5a, $91, $1e, $87, $20, $87, $1e, $91, $1d, $91, $5a, $87, $19, $91, $5a, $87, $16, $91
	.byte $1b, $91, $1d, $87, $5a, $87, $1e, $91, $22, $87, $5a, $87, $20, $9b, $1d, $9b, $24, $91
	.byte $41, $14
	.word @song0ref1850
	.byte $25, $91, $5a, $91, $22, $91, $5a, $91, $27, $91, $5a, $a5, $27, $87, $29, $87, $2a, $87, $5a, $87, $29, $87, $5a, $87
	.byte $27, $87, $5a, $87, $25, $87, $5a, $87, $29, $a5, $51, $fe, $10, $f7, $7f, $00, $ff, $9d
	.byte $41, $0e
	.word @song0ref524
	.byte $f7, $86, $2e, $91, $30, $91, $31, $a5, $30, $a5, $33, $a5, $31, $91, $33, $87, $31, $87, $2e, $f5, $2c, $a5, $30, $f5
	.byte $33, $a5, $35, $cd, $3a, $a5, $33, $a5, $35, $f5, $31, $91, $33, $91, $31, $f5, $30, $91, $31, $91, $30, $a5, $2e, $a5
	.byte $2d, $a5, $29, $a5, $2e, $cf, $51, $fc, $00, $cd, $cf, $00, $cd
	.byte $41, $0e
	.word @song0ref524
	.byte $ff, $9f, $44, $00
@song0ch9:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $80
@song0ref2042:
	.byte $22, $ff, $9d, $25, $ff, $9d, $1e, $ff, $9d, $20, $cd, $21, $cd
	.byte $41, $0d
	.word @song0ref2042
@song0ref2058:
	.byte $22, $cd, $21, $cd, $20, $cd, $1f, $cd, $1e, $cd, $27, $cd, $25, $cd, $27, $cd
	.byte $41, $10
	.word @song0ref2058
	.byte $00, $ff, $9d
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0d
	.word @song0ref2042
	.byte $41, $0d
	.word @song0ref2042
	.byte $41, $10
	.word @song0ref2058
	.byte $41, $10
	.word @song0ref2058
	.byte $00, $ff, $9d, $ff, $9f, $44, $00
@song0ch10:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $80
@song0ref2112:
	.byte $1d, $ff, $9d, $22, $ff, $9d, $19, $ff, $9d, $1b, $ff, $9d
	.byte $41, $0c
	.word @song0ref2112
@song0ref2127:
	.byte $1d, $cd, $1d, $cd, $1d, $cd, $19, $cd, $19, $cd, $1d, $cd, $1e, $cd, $20, $cd
	.byte $41, $10
	.word @song0ref2127
	.byte $00, $ff, $9d
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0c
	.word @song0ref2112
	.byte $41, $0c
	.word @song0ref2112
	.byte $41, $10
	.word @song0ref2127
	.byte $41, $10
	.word @song0ref2127
	.byte $00, $ff, $9d, $ff, $9f, $44, $00
@song0ch11:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $80
@song0ref2181:
	.byte $19, $ff, $9d, $1d, $ff, $9d, $16, $ff, $9d, $18, $ff, $9d
	.byte $41, $0c
	.word @song0ref2181
@song0ref2196:
	.byte $19, $cd, $19, $cd, $19, $cd, $16, $cd, $16, $cd, $19, $cd, $19, $cd, $1b, $cd
	.byte $41, $10
	.word @song0ref2196
	.byte $00, $ff, $9d
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0c
	.word @song0ref2181
	.byte $41, $0c
	.word @song0ref2181
	.byte $41, $10
	.word @song0ref2196
	.byte $41, $10
	.word @song0ref2196
	.byte $00, $ff, $9d, $ff, $9f, $44, $00
@song0ch12:
	.byte $41, $0e
	.word @song0ref524
	.byte $ff, $9f, $82, $2e, $cd, $00, $cd, $31, $cd, $30, $cd, $2a, $c3, $00, $d7, $2c, $cd, $2d, $cd, $00, $ff, $9d, $ff, $9f
	.byte $ff, $9f, $ff, $9f, $2e, $cd, $2d, $cd, $2c, $cd, $2b, $cd, $2a, $cd, $29, $cd, $2a, $cd, $2c, $cd, $00, $ff, $9d
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0e
	.word @song0ref524
	.byte $41, $0e
	.word @song0ref524
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $44, $00
