; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Finned Frontier:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_finned_frontier_2A03:=music_data_finned_frontier_2A03

music_data_finned_frontier_2A03:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Main Theme 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_finned_frontier
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env15,@env20,@env21,@env1 ; 00 : Triangle
	.word @env28,@env30,@env21,@env1 ; 01 : Triangle Kick
	.word @env38,@env17,@env21,@env1 ; 02 : Triangle Snare
	.word @env27,@env20,@env21,@env1 ; 03 : HiHat
	.word @env14,@env33,@env21,@env1 ; 04 : Kick
	.word @env0,@env12,@env21,@env1 ; 05 : Snare
	.word @env6,@env7,@env21,@env1 ; 06 : Snare Short
	.word @env31,@env20,@env25,@env1 ; 07 : Sax 2A03
	.word @env31,@env20,@env22,@env1 ; 08 : Sax 2A03 50
	.word @env3,@env13,@env21,@env1 ; 09 : Crash
	.word @env34,@env20,@env21,@env1 ; 0a : HiHat Long
	.word @env9,@env20,@env8,@env1 ; 0b : Synth
	.word @env19,@env20,@env22,@env1 ; 0c : Jumpy Square 1
	.word @env9,@env20,@env4,@env1 ; 0d : Synth 50 2

@instruments_exp:

@env0:
	.byte $00,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c0,$00,$0d
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $b7,$b7,$bc,$bc,$c0,$c0,$00,$00
@env3:
	.byte $00,$c8,$c7,$02,$c6,$03,$c5,$02,$c4,$05,$c3,$03,$c2,$03,$c1,$00,$0e
@env4:
	.byte $c1,$c2,$00,$01
@env5:
	.byte $ba,$ba,$bd,$bd,$c0,$c0,$00,$00
@env6:
	.byte $00,$c9,$c8,$c7,$c5,$c3,$c2,$c1,$02,$c0,$00,$09
@env7:
	.byte $b9,$bd,$be,$00,$02
@env8:
	.byte $c2,$c2,$c1,$c1,$c0,$00,$04
@env9:
	.byte $09,$ca,$ca,$c9,$c8,$c7,$c6,$00,$06,$c3,$c2,$c1,$c0,$00,$0c
@env10:
	.byte $b6,$b6,$ba,$ba,$c0,$c0,$00,$00
@env11:
	.byte $b7,$b7,$be,$be,$c0,$c0,$00,$00
@env12:
	.byte $ad,$b5,$be,$00,$02
@env13:
	.byte $bb,$be,$00,$01
@env14:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env15:
	.byte $00,$cf,$7f,$00,$02
@env16:
	.byte $00,$c0,$bd,$bc,$be,$c2,$c4,$c3,$00,$01
@env17:
	.byte $c0,$bb,$b7,$b3,$af,$ac,$a6,$00,$06
@env18:
	.byte $b6,$02,$ba,$ba,$ba,$00,$00
@env19:
	.byte $00,$c4,$c3,$c2,$c1,$c0,$00,$05
@env20:
	.byte $c0,$7f,$00,$01
@env21:
	.byte $7f,$00,$00
@env22:
	.byte $c2,$7f,$00,$00
@env23:
	.byte $b7,$b7,$bb,$bb,$c0,$c0,$00,$00
@env24:
	.byte $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
@env25:
	.byte $c1,$7f,$00,$00
@env26:
	.byte $b9,$b9,$bd,$bd,$c0,$c0,$00,$00
@env27:
	.byte $00,$c6,$c3,$c0,$00,$03
@env28:
	.byte $00,$cf,$03,$c0,$00,$03
@env29:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env30:
	.byte $c0,$bb,$b6,$b1,$ad,$00,$04
@env31:
	.byte $09,$c3,$c8,$cc,$cc,$cb,$c9,$00,$06,$c6,$c3,$c0,$c0,$00,$0c
@env32:
	.byte $b8,$b8,$bd,$bd,$c0,$c0,$00,$00
@env33:
	.byte $c0,$bd,$bc,$00,$02
@env34:
	.byte $00,$c6,$c3,$00,$02
@env35:
	.byte $00,$c0,$be,$be,$bf,$c1,$c2,$c2,$00,$01
@env36:
	.byte $b6,$b6,$b9,$b9,$c0,$c0,$00,$00
@env37:
	.byte $b7,$b7,$bd,$bd,$c0,$c0,$00,$00
@env38:
	.byte $00,$cf,$06,$c0,$00,$03

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $bf, $48, $ff, $bf, $48, $78, $90
@song0ref9:
	.byte $12, $89, $45, $89, $00, $89, $12, $89, $45, $89, $00, $89, $12, $89, $45, $89, $12, $89, $45, $89, $10, $95, $12, $89
	.byte $45, $89, $00, $95, $48, $12, $89, $45, $89, $00, $89, $10, $a1, $12, $89, $15, $83, $17, $83, $18, $89, $45, $89, $17
	.byte $89, $45, $89, $15, $89, $12, $89, $10, $95, $48
	.byte $41, $1b
	.word @song0ref9
	.byte $83, $15, $83, $17, $83, $18, $83, $48, $19, $89, $45, $89, $00, $89, $19, $89, $45, $89, $00, $89, $19, $89, $45, $89
	.byte $00, $95, $19, $89, $45, $89, $19, $89, $49, .lobyte(@env29), .hibyte(@env29), $a3, $48, $79, $49, .lobyte(@env1), .hibyte(@env1)
	.byte $4a, $96
@song0ref113:
	.byte $2a, $95, $2a, $89, $45, $89, $28, $89, $45, $89, $25, $89, $45, $89, $28, $95, $2a, $89, $45, $89, $00, $95, $25, $89
	.byte $45, $89
@song0ref139:
	.byte $48, $23
@song0ref141:
	.byte $95, $23
@song0ref143:
	.byte $89, $45, $89, $21, $89, $45, $89, $23, $89, $45, $89, $00, $95, $1e
	.byte $41, $0b
	.word @song0ref143
@song0ref160:
	.byte $48, $25, $95, $25, $89, $45, $89, $23, $89, $45, $89, $21, $89, $45, $89, $23, $95, $25, $89, $45, $89, $00, $95, $1d
	.byte $95, $48
@song0ref186:
	.byte $1e, $89, $45, $89, $00, $89, $1e, $89, $45, $89, $00, $89, $1e, $89, $45, $89, $00, $95, $1c, $95, $1e, $89, $45, $89
	.byte $00, $95, $48, $49, .lobyte(@env1), .hibyte(@env1), $4a
	.byte $41, $2b
	.word @song0ref113
	.byte $41, $0b
	.word @song0ref143
	.byte $41, $32
	.word @song0ref160
	.byte $41, $0e
	.word @song0ref139
	.byte $26
	.byte $41, $0d
	.word @song0ref141
	.byte $48, $21, $95, $1e
	.byte $41, $0d
	.word @song0ref143
	.byte $17, $89, $45, $89, $1a, $95, $1c, $89, $45, $89, $48, $1e, $95, $1e, $89, $45, $89, $1c, $89, $45, $89, $19, $89, $45
	.byte $89, $21
@song0ref266:
	.byte $95, $1e, $89, $45, $89, $1c, $89, $45, $89, $1e, $89, $45, $89, $48, $22, $89, $45, $89, $00, $89, $22, $89, $45, $89
	.byte $00, $89, $22, $89, $45, $89, $20
	.byte $41, $0d
	.word @song0ref266
	.byte $41, $0e
	.word @song0ref139
	.byte $26
	.byte $41, $0d
	.word @song0ref141
	.byte $48, $21, $95, $1e
	.byte $41, $0d
	.word @song0ref143
	.byte $17, $89, $45, $89, $1a, $95, $1c, $89, $45, $89, $48, $25, $95, $25, $89, $45, $89, $23, $89, $45, $89, $20, $89, $45
	.byte $89, $28, $95, $25, $89, $45, $89, $23, $89, $45, $89, $25, $89, $45, $89, $48
@song0ref354:
	.byte $25, $89, $45, $89, $00, $89, $25, $89, $45, $89, $00, $89, $25, $89, $45, $89, $23, $95, $21, $89, $45, $89, $1e, $89
	.byte $45, $89, $1c, $89, $45, $89, $48, $49, .lobyte(@env1), .hibyte(@env1), $4a
	.byte $41, $2b
	.word @song0ref113
	.byte $41, $0b
	.word @song0ref143
	.byte $41, $32
	.word @song0ref160
@song0ref398:
	.byte $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $9a
@song0ref404:
	.byte $22, $89, $45, $89
@song0ref408:
	.byte $20
@song0ref409:
	.byte $89, $45, $89, $1e, $89, $45, $89, $20, $89, $45, $89, $22, $ad, $1b, $89, $45, $89, $20, $89, $45, $89, $48, $1e, $95
	.byte $1b, $89, $45, $89, $1b, $89, $19, $89, $45, $89, $1b, $89, $49, .lobyte(@env16), .hibyte(@env16), $a3, $45, $ad, $00
	.byte $89, $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $9a, $1e, $89, $45, $89, $20, $89, $45, $89, $22, $89, $45, $89
	.byte $20, $89, $45, $89, $1e, $ad, $1b, $89, $45, $89, $22, $89, $45, $83, $23, $24, $81, $48, $25, $95, $22, $89, $45, $89
	.byte $22, $89, $20, $89, $45, $89, $22, $89, $49, .lobyte(@env16), .hibyte(@env16), $a3, $45, $ad, $00, $89
	.byte $41, $5d
	.word @song0ref398
	.byte $41, $12
	.word @song0ref398
	.byte $20, $95, $1e, $95, $48, $1d, $a1, $1e, $a1, $20, $95, $1e, $95, $1d, $95, $1b
@song0ref533:
	.byte $95, $19, $95, $48
@song0ref537:
	.byte $1b, $89, $49, .lobyte(@env24), .hibyte(@env24), $97, $9a, $1d, $a1, $1e, $95, $1d, $a1, $1b, $a1, $1a, $95, $48, $1b
	.byte $89, $49, .lobyte(@env24), .hibyte(@env24), $d3, $45, $95, $49, .lobyte(@env1), .hibyte(@env1), $4a, $9a, $16, $95
	.byte $17
	.byte $41, $15
	.word @song0ref533
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a, $96, $22, $95, $23, $95, $25, $95, $48, $9a
	.byte $41, $12
	.word @song0ref537
	.byte $00, $c5, $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $96, $27, $95, $27, $89, $45, $89, $25, $89, $45, $89, $22
	.byte $89, $45, $89, $25, $95, $27, $89, $45, $89, $00, $95, $22, $89, $45, $89, $48, $20, $95
	.byte $41, $0c
	.word @song0ref408
	.byte $00, $95, $1b
	.byte $41, $0b
	.word @song0ref409
	.byte $48, $22, $95
	.byte $41, $0d
	.word @song0ref404
	.byte $95, $22, $89, $45, $89, $00, $ad, $48, $22, $95
	.byte $41, $0d
	.word @song0ref404
	.byte $95, $22, $89, $45, $89, $00, $ad, $48, $22, $95
	.byte $41, $0d
	.word @song0ref404
	.byte $95, $22, $89, $45, $89, $00, $95, $1a, $95, $48, $1b, $89, $45, $89, $00, $89, $1b, $89, $45, $89, $00, $89, $1b, $89
	.byte $45, $89, $00, $95, $19, $95, $1b, $95, $49, .lobyte(@env29), .hibyte(@env29), $97, $48, $ff, $a7, $45, $95, $44, $00
@song0ch1:
	.byte $ff, $bf, $ff, $bf, $77, $8e
	.byte $41, $18
	.word @song0ref186
	.byte $15, $95
	.byte $41, $1a
	.word @song0ref186
	.byte $41, $18
	.word @song0ref186
	.byte $15, $95
	.byte $41, $10
	.word @song0ref354
	.byte $00, $95, $25, $89, $45, $89, $25, $ad
@song0ref742:
	.byte $7f, $98
@song0ref744:
	.byte $12, $89, $1e, $89, $2a, $89, $1e, $89, $12, $89, $1e, $89, $2a, $89, $1e, $89
	.byte $41, $10
	.word @song0ref744
@song0ref763:
	.byte $0b, $89, $17, $89, $23, $89, $17, $89, $0b, $89, $17, $89, $23, $89, $17, $89
	.byte $41, $10
	.word @song0ref763
@song0ref782:
	.byte $0d, $89, $19, $89, $25, $89, $19, $89, $0d, $89, $19, $89, $25, $89, $19, $89
	.byte $41, $10
	.word @song0ref782
@song0ref801:
	.byte $06, $89, $12, $89, $1e, $89, $12, $89, $06, $89, $12, $89, $1e, $89, $12, $89
	.byte $41, $10
	.word @song0ref801
	.byte $41, $10
	.word @song0ref744
	.byte $41, $10
	.word @song0ref744
	.byte $41, $10
	.word @song0ref763
	.byte $41, $10
	.word @song0ref763
	.byte $41, $10
	.word @song0ref782
	.byte $41, $10
	.word @song0ref782
	.byte $41, $10
	.word @song0ref801
	.byte $41, $10
	.word @song0ref801
	.byte $77
@song0ref845:
	.byte $8e, $0b, $95, $90, $0f, $89, $45, $89, $8e, $12, $95, $90, $0f, $89, $45, $89
	.byte $41, $0c
	.word @song0ref845
	.byte $41, $0c
	.word @song0ref845
	.byte $41, $0c
	.word @song0ref845
@song0ref870:
	.byte $8e, $06, $95, $90, $0d, $89, $45, $89, $8e, $0d, $95, $90, $0d, $89, $45, $89
	.byte $41, $0c
	.word @song0ref870
	.byte $41, $0c
	.word @song0ref870
	.byte $8e, $06, $95, $90, $0d, $89, $45, $89, $8e, $10, $95, $90, $0d, $89, $45, $89
	.byte $41, $0c
	.word @song0ref845
	.byte $41, $0c
	.word @song0ref845
	.byte $41, $0c
	.word @song0ref845
	.byte $41, $0c
	.word @song0ref845
@song0ref920:
	.byte $8e, $0d, $95, $90, $11, $89, $45, $89, $8e, $14, $95, $90, $11, $89, $45, $89
	.byte $41, $0c
	.word @song0ref920
	.byte $41, $0c
	.word @song0ref920
	.byte $41, $0c
	.word @song0ref920
	.byte $41, $10
	.word @song0ref742
	.byte $41, $10
	.word @song0ref744
	.byte $41, $10
	.word @song0ref763
	.byte $41, $10
	.word @song0ref763
	.byte $41, $10
	.word @song0ref782
	.byte $41, $10
	.word @song0ref782
	.byte $41, $10
	.word @song0ref801
	.byte $41, $10
	.word @song0ref801
	.byte $79, $4b, .lobyte(@env23), .hibyte(@env23), $8e
@song0ref974:
	.byte $1b, $ff, $bd, $4b, .lobyte(@env2), .hibyte(@env2), $1b, $ff, $bd, $4b, .lobyte(@env36), .hibyte(@env36), $1e, $dd
	.byte $4b, .lobyte(@env37), .hibyte(@env37), $1e, $dd, $4b, .lobyte(@env5), .hibyte(@env5), $1d, $dd, $4b, .lobyte(@env26)
	.byte .hibyte(@env26), $1d, $dd, $4b, .lobyte(@env23), .hibyte(@env23)
	.byte $41, $0e
	.word @song0ref974
	.byte $4b, .lobyte(@env23), .hibyte(@env23), $1b, $ff, $bd, $4b, .lobyte(@env11), .hibyte(@env11), $1d, $ff, $bd, $4b, .lobyte(@env36)
	.byte .hibyte(@env36), $1e, $dd, $4b, .lobyte(@env26), .hibyte(@env26), $1d, $dd, $4b, .lobyte(@env32), .hibyte(@env32), $1e
	.byte $ff, $bd, $4b, .lobyte(@env36), .hibyte(@env36), $1e, $dd, $4b, .lobyte(@env26), .hibyte(@env26), $1d, $dd, $4b, .lobyte(@env32)
	.byte .hibyte(@env32), $1e, $ff, $bd, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $96, $27, $a1, $29, $a1, $2a, $95, $29
	.byte $a1, $27, $a1, $26, $95, $27, $89, $49, .lobyte(@env24), .hibyte(@env24), $d3, $45, $ad, $00, $ad, $49, .lobyte(@env1)
	.byte .hibyte(@env1), $4a, $98
@song0ref1085:
	.byte $0f, $89, $1b, $89, $27, $89, $1b, $89, $0f, $89, $1b, $89, $27, $89, $1b, $89
	.byte $41, $10
	.word @song0ref1085
@song0ref1104:
	.byte $0c, $89, $18, $89, $24, $89, $18, $89, $0c, $89, $18, $89, $24, $89, $18, $89
	.byte $41, $10
	.word @song0ref1104
	.byte $51, $ff, $50, $8e, $16, $ff, $bd, $79, $51, $ff, $50, $4b, .lobyte(@env18), .hibyte(@env18), $20, $ff, $bd, $79, $51
	.byte $ff, $50, $4b, .lobyte(@env10), .hibyte(@env10), $20, $ff, $bd, $76, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $0f
	.byte $95, $45, $89, $0f, $95, $45, $89, $0f, $95, $45, $95, $0d, $95, $0f, $ad, $ff, $a7, $45, $95, $44, $00
@song0ch2:
	.byte $ff, $bf, $ff, $bf, $82
@song0ref1183:
	.byte $22, $89, $00, $95, $22, $89, $00, $95, $22, $89, $00, $a1, $22, $89, $00, $89, $22, $89, $00, $a1
	.byte $41, $14
	.word @song0ref1183
	.byte $41, $14
	.word @song0ref1183
	.byte $41, $0b
	.word @song0ref1183
	.byte $89
	.byte $41, $0b
	.word @song0ref1183
	.byte $89
@song0ref1217:
	.byte $22, $83, $80, $1e, $8d, $00, $1e, $95, $84, $29, $83, $80, $1c, $83, $00, $89, $82, $22, $83, $80, $1e, $83, $00, $a1
	.byte $82, $22, $83, $80, $1e, $83, $00, $89, $84, $29, $83, $80, $1c, $83, $00, $89, $1e, $89, $00, $89, $82, $22, $83, $80
	.byte $17, $8d, $00, $17, $95, $84, $29, $83, $80, $15, $83, $00, $89, $82, $22, $83, $80, $17, $83, $00, $a1, $82, $22, $83
	.byte $80, $17, $83, $00, $89, $84, $29, $83, $80, $15, $83, $00, $89, $17, $8b, $00, $87, $82, $22, $83, $80, $19, $8d, $00
	.byte $19, $89, $00, $89, $84, $29, $83, $80, $17, $83, $00, $89, $82, $22, $83, $80, $19, $83, $00, $a1, $82, $22, $83, $80
	.byte $19, $83, $84, $29, $83, $29, $83, $29, $83, $80, $17, $83, $84, $29, $89, $80, $19, $89, $84, $29, $89, $82, $22, $83
	.byte $80, $1e, $83, $00, $89, $12, $89, $82, $22, $83, $80, $1e, $83, $84, $29, $89, $80, $12, $89, $82, $22, $83, $80, $1e
	.byte $83, $00, $89, $36, $82, $22, $81, $80, $1e, $83, $36, $00, $87, $34, $1c, $87, $82, $22, $83, $80, $1c, $83, $36, $84
	.byte $29, $81, $80, $1e, $83, $00, $89, $82, $22, $83, $00, $8f
	.byte $41, $9d
	.word @song0ref1217
@song0ref1424:
	.byte $22, $83, $80, $17, $83, $00, $89, $82, $22, $83, $80, $1b, $83, $00, $89, $84, $29, $83, $80, $1e, $83, $00, $89, $82
	.byte $22, $83, $80, $20, $83, $82, $22, $83, $00, $80, $1e, $81, $21, $89, $82, $22, $83, $80, $20, $83, $82, $22, $83, $00
	.byte $83, $80, $1e, $89, $84, $29, $89, $80, $1a, $89, $1b, $95, $82
	.byte $41, $2d
	.word @song0ref1424
@song0ref1488:
	.byte $82, $22, $83, $80, $12, $83, $00, $95, $16, $89, $84, $29, $83, $00, $8f, $82, $22, $83, $80, $19, $83, $00, $89, $12
	.byte $89, $00, $89, $84, $29, $83, $00, $83, $80, $16
@song0ref1522:
	.byte $89, $82, $22, $83, $00, $83, $22, $83, $00, $83, $84, $29, $83, $80, $19, $83, $00, $89
	.byte $41, $2a
	.word @song0ref1488
	.byte $82
	.byte $41, $2d
	.word @song0ref1424
	.byte $82
	.byte $41, $2d
	.word @song0ref1424
@song0ref1551:
	.byte $82, $22, $83, $80, $19, $83, $00, $95, $1d, $89, $84, $29, $83, $00, $8f, $82, $22, $83, $80, $20, $83, $00, $89, $19
	.byte $89, $00, $89, $84, $29, $83, $00, $83, $80, $1d
	.byte $41, $0b
	.word @song0ref1522
	.byte $80, $20, $83, $00, $89
	.byte $41, $12
	.word @song0ref1551
	.byte $25, $89, $00, $89, $84, $29, $83, $80, $23, $83, $00, $89, $82, $22, $83, $80, $22, $83, $82, $22, $83, $00, $83, $84
	.byte $29, $83, $80, $20, $83, $00, $89, $82
	.byte $41, $96
	.word @song0ref1217
	.byte $87, $1d, $85, $82, $22, $83, $80, $1d, $1c, $8d
@song0ref1641:
	.byte $82, $22, $83, $80, $1b, $83, $00, $95, $1b, $89, $84, $29, $83, $00, $8f, $80, $1b, $89, $82, $22, $83, $00, $83, $80
	.byte $19, $95, $82, $22, $83, $80, $1b, $83, $00, $89, $84, $29, $83, $80, $1b, $8f, $27
@song0ref1682:
	.byte $95
@song0ref1683:
	.byte $82, $22, $83, $80, $17, $83, $00, $95, $17, $89, $84, $29, $83, $00, $8f, $80, $17, $89, $82, $22, $83, $00, $83, $80
	.byte $16, $95, $82, $22, $83, $80, $17, $83, $00, $89, $84, $29, $83, $80, $17, $8f, $23, $95, $82, $22, $83, $80, $14, $83
	.byte $00, $95, $14, $89, $84, $29, $83, $00, $8f, $80, $14, $89, $82, $22, $83, $00, $83, $80, $19, $95, $82, $22, $83, $80
	.byte $14, $83, $00, $89, $84, $29, $83, $80, $14, $8f, $20, $95, $84, $29, $83, $80, $16, $83, $00, $89, $84, $29, $83, $00
	.byte $83, $29, $83, $80, $16, $83, $00, $89, $84, $29, $83, $00, $83, $29, $83, $80, $16, $83, $00, $89, $82, $22, $83, $80
	.byte $19, $8f, $16, $89, $82, $22, $83, $00, $83, $84, $29, $83, $80, $14, $83, $84, $29, $83, $80, $14, $83, $84, $29, $83
	.byte $80, $16, $83, $84, $29, $83, $80, $16, $83
	.byte $41, $94
	.word @song0ref1641
	.byte $41, $22
	.word @song0ref1641
	.byte $80, $1d, $83, $00, $95, $1d, $89, $84, $29, $83, $00, $8f, $80, $1d, $89, $82, $22, $83, $00, $83, $80, $1b, $95, $82
	.byte $22, $83, $80, $1d, $83, $00, $89, $84, $29, $83, $80, $1d, $8f, $29
	.byte $41, $1d
	.word @song0ref1682
@song0ref1883:
	.byte $80, $16, $8f, $22, $95, $84, $29, $83, $80, $1b, $83, $00, $89, $84, $29, $83, $00, $83, $29, $83, $80, $1b, $83, $00
	.byte $89, $84, $29, $83, $00, $83, $29, $83, $80, $1b, $83, $00, $83, $1c, $1d, $81, $82, $22, $83, $80, $1e, $8f, $1b, $89
	.byte $82, $22, $83, $00, $83, $84, $29, $83, $80, $19, $83, $84, $29, $83, $80, $19, $83, $84, $29, $83, $80, $1b, $83, $84
	.byte $29, $83, $00, $83
	.byte $41, $1c
	.word @song0ref1683
	.byte $41, $3b
	.word @song0ref1883
	.byte $41, $1c
	.word @song0ref1683
	.byte $80, $16, $8f, $22, $95, $82, $22, $89, $00, $ff, $81, $84, $29, $89, $00, $a1, $82, $22, $83, $80, $1b, $8d, $00, $1b
	.byte $95, $84, $29, $83, $80, $19, $83, $00, $89, $82, $22, $83, $80, $1b, $83, $00, $a1, $82, $22, $83, $80, $1b, $83, $00
	.byte $89, $84, $29, $83, $80, $19, $83, $00, $89, $1b, $89, $00, $89, $82, $22, $83, $80, $14, $8d, $00, $14, $95, $84, $29
	.byte $83, $80, $12, $83, $00, $89, $82, $22, $83, $80, $14, $83, $00, $a1, $82, $22, $83, $80, $14, $83, $00, $89, $84, $29
	.byte $83, $80, $12, $83, $00, $89, $14, $89, $00, $89
@song0ref2074:
	.byte $82, $22, $83, $80, $16, $9b, $00, $89, $84, $29, $83, $80, $14, $83, $00, $89, $82, $22, $83, $80, $16, $83, $00, $a1
	.byte $82, $22, $83, $80, $16, $83, $84, $29, $83, $29, $83, $29, $83, $80, $14, $83, $84, $29, $83, $00, $83, $80, $16, $89
	.byte $84, $29, $83, $00, $83
	.byte $41, $28
	.word @song0ref2074
	.byte $41, $28
	.word @song0ref2074
	.byte $29, $83, $80, $0f, $8f, $00, $89, $84, $29, $83, $80, $0f, $8f, $00, $89, $84, $29, $83, $80, $0f, $8f, $33, $82, $22
	.byte $87, $80, $33, $00, $87, $31, $00, $81, $0d, $83, $82, $22, $89, $80, $33, $84, $29, $81, $80, $0f, $83, $49, .lobyte(@env35)
	.byte .hibyte(@env35), $a3, $ff, $a7, $00, $95, $44, $00
@song0ch3:
	.byte $ff, $bf, $ff, $bf, $7a, $88
@song0ref2195:
	.byte $28, $89, $00, $95, $28, $89, $00, $95, $28, $89, $00, $a1, $28, $89, $00, $89, $28, $89, $00, $a1
	.byte $41, $14
	.word @song0ref2195
	.byte $41, $14
	.word @song0ref2195
	.byte $28, $89, $00, $95, $28, $89, $00, $95, $28, $83, $8a, $31, $83, $31, $83, $31, $83, $31, $89, $31, $95, $31, $95, $31
	.byte $89, $31, $95
@song0ref2248:
	.byte $88, $27, $89, $86, $33, $89, $31, $89, $33, $89
@song0ref2258:
	.byte $8c, $31
@song0ref2260:
	.byte $95, $88, $27, $89, $86, $33, $89, $31, $89, $33, $89, $88, $27, $89, $86, $33, $89, $8c, $31, $95, $86, $31, $89, $33
	.byte $89
	.byte $41, $1c
	.word @song0ref2248
	.byte $41, $14
	.word @song0ref2248
@song0ref2291:
	.byte $8a, $31, $83, $31, $83, $31, $89, $31, $95, $31
@song0ref2301:
	.byte $89, $88, $27, $89, $86, $33, $89, $33, $89, $88, $27, $89, $8c, $31, $95, $88, $27, $89, $86, $33
	.byte $41, $0e
	.word @song0ref2301
	.byte $89
	.byte $41, $1c
	.word @song0ref2248
	.byte $41, $1c
	.word @song0ref2248
	.byte $41, $14
	.word @song0ref2248
	.byte $41, $16
	.word @song0ref2291
	.byte $8a, $31, $83, $31, $83, $31, $89, $31, $95, $31, $89, $8c, $31, $89, $8a, $31, $89, $31, $95, $92, $30
@song0ref2358:
	.byte $9b
@song0ref2359:
	.byte $94, $32, $8f, $8a, $31, $95, $88, $27, $83, $94, $32, $83, $88, $27, $89, $86, $31, $89, $88, $27, $83, $00, $83, $27
	.byte $83, $94, $32, $8f, $8a, $31, $95, $94, $32, $95, $88, $27, $89, $00, $89, $27, $83
	.byte $41, $13
	.word @song0ref2359
@song0ref2403:
	.byte $83, $8a, $31, $83, $31, $83, $31, $89, $31, $95, $31, $89, $92, $30, $95, $86, $31, $89, $33
@song0ref2422:
	.byte $89, $8c, $31, $89, $86, $33, $89, $88, $27, $89, $86, $33, $89, $31, $89, $33, $89, $8c, $31, $89, $86, $33, $89, $88
	.byte $27, $89, $27, $89, $8c, $31, $89, $86, $33, $89, $92, $30, $a1, $30
	.byte $41, $1a
	.word @song0ref2422
	.byte $41, $1f
	.word @song0ref2358
	.byte $41, $13
	.word @song0ref2359
	.byte $41, $2c
	.word @song0ref2403
	.byte $89, $8c, $31, $89, $86, $33, $89, $88, $27, $89, $86, $33, $89, $92, $30, $95, $8c, $31, $89, $92, $30, $95, $88, $27
	.byte $41, $0e
	.word @song0ref2422
	.byte $41, $13
	.word @song0ref2260
	.byte $41, $1c
	.word @song0ref2248
	.byte $41, $14
	.word @song0ref2248
	.byte $41, $17
	.word @song0ref2291
	.byte $41, $0e
	.word @song0ref2301
@song0ref2514:
	.byte $89, $92, $31, $ad, $8a, $31, $95, $86, $31, $89, $88, $27, $89, $86, $31, $89, $33, $89, $88, $27, $89, $86, $33, $89
	.byte $8a, $31, $95, $86, $31, $89, $33
	.byte $41, $16
	.word @song0ref2514
	.byte $41, $0f
	.word @song0ref2514
@song0ref2551:
	.byte $8a, $31, $83, $31, $83, $31, $89, $31, $89, $86, $31, $89, $33, $89, $8a, $31, $95, $31, $89, $31, $95, $31, $89, $31
	.byte $95, $88, $27, $89, $00, $95, $27, $89, $8a, $31, $89, $31, $89, $31, $89, $31
	.byte $41, $16
	.word @song0ref2514
	.byte $41, $16
	.word @song0ref2514
	.byte $41, $0f
	.word @song0ref2514
	.byte $41, $23
	.word @song0ref2551
	.byte $41, $16
	.word @song0ref2514
	.byte $41, $16
	.word @song0ref2514
	.byte $41, $0f
	.word @song0ref2514
	.byte $41, $23
	.word @song0ref2551
	.byte $41, $0f
	.word @song0ref2514
	.byte $41, $23
	.word @song0ref2551
	.byte $41, $0f
	.word @song0ref2514
	.byte $41, $0c
	.word @song0ref2551
	.byte $88, $27, $89, $00, $89, $86, $33, $89, $33, $89, $30, $89, $00, $89, $33, $89, $33, $89, $30, $89, $00, $89, $33, $89
	.byte $33, $89, $8a, $31, $ad
	.byte $41, $1c
	.word @song0ref2248
	.byte $41, $1c
	.word @song0ref2248
	.byte $92, $31, $ad
	.byte $41, $0c
	.word @song0ref2258
@song0ref2668:
	.byte $8a, $31, $83, $31, $83, $31, $89, $31, $95, $31, $89, $92, $31, $ad
	.byte $41, $0c
	.word @song0ref2258
	.byte $41, $0c
	.word @song0ref2668
	.byte $41, $0c
	.word @song0ref2258
	.byte $8a, $31, $83, $31, $83, $31, $89, $31, $95, $31, $89, $31, $a1, $31, $a1, $31, $95, $88, $27, $89, $86, $33, $89, $31
	.byte $89, $88, $27, $89, $92, $31, $ad, $df, $00, $dd, $44, $00
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
@song0ref2736:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $0c
	.word @song0ref2736
	.byte $41, $0c
	.word @song0ref2736
	.byte $41, $0c
	.word @song0ref2736
	.byte $41, $0c
	.word @song0ref2736
	.byte $41, $0c
	.word @song0ref2736
	.byte $41, $0c
	.word @song0ref2736
	.byte $41, $0c
	.word @song0ref2736
	.byte $ff, $bf, $44, $00
