; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Rave Racer:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1

.export _music_data_rave_racer:=music_data_rave_racer

music_data_rave_racer:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Euphoria
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_rave_racer
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env27,@env16,@env18,@env2 ; 00 : HiHat Long
	.word @env23,@env16,@env18,@env2 ; 01 : HiHat
	.word @env13,@env29,@env18,@env2 ; 02 : Kick
	.word @env6,@env10,@env18,@env2 ; 03 : Snare Short
	.word @env0,@env11,@env18,@env2 ; 04 : Snare
	.word @env15,@env34,@env18,@env2 ; 05 : Snare Quiet
	.word @env3,@env12,@env18,@env2 ; 06 : Crash
	.word @env28,@env16,@env21,@env2 ; 07 : Guitar
	.word @env24,@env16,@env21,@env2 ; 08 : Bass

@instruments_exp:
	.word @env5, @env30, @env2 ; 00 : Chord Reverse N163
	.word @env2
	.byte $30, $10
	.word @n163_inst0_waves
	.byte $00, $00, $00, $00
	.word @env19, @env16, @env2 ; 01 : Guitar 5B N163
	.word @env2
	.byte $30, $10
	.word @n163_inst1_waves
	.byte $00, $00, $00, $00
	.word @env26, @env30, @env2 ; 02 : Chord N163
	.word @env2
	.byte $00, $10
	.word @n163_inst2_waves
	.byte $00, $00, $00, $00
	.word @env17, @env30, @env2 ; 03 : Chord 2 N163
	.word @env2
	.byte $00, $10
	.word @n163_inst3_waves
	.byte $00, $00, $00, $00
	.word @env4, @env9, @env2 ; 04 : Meow Namco
	.word @env2
	.byte $10, $20
	.word @n163_inst4_waves
	.byte $00, $00, $00, $00
	.word @env32, @env16, @env2 ; 05 : Square Namco
	.word @env2
	.byte $00, $10
	.word @n163_inst5_waves
	.byte $00, $00, $00, $00
	.word @env14, @env16, @env2 ; 06 : Sine Slides
	.word @env2
	.byte $40, $20
	.word @n163_inst6_waves
	.byte $00, $00, $00, $00
	.word @env35, @env16, @env2 ; 07 : Saw Namco
	.word @env2
	.byte $00, $10
	.word @n163_inst7_waves
	.byte $00, $00, $00, $00
	.word @env7, @env16, @env2 ; 08 : Triangle Namco
	.word @env2
	.byte $60, $20
	.word @n163_inst8_waves
	.byte $00, $00, $00, $00

@env0:
	.byte $00,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c0,$00,$0d
@env1:
	.byte $10,$32,$54,$76,$98,$ba,$dc,$fe
@env2:
	.byte $00,$c0,$7f,$00,$02
@env3:
	.byte $00,$c8,$c7,$02,$c6,$03,$c5,$02,$c4,$05,$c3,$03,$c2,$03,$c1,$00,$0e
@env4:
	.byte $00,$cb,$02,$ca,$ca,$c9,$02,$c8,$c7,$c5,$c3,$c0,$00,$0b
@env5:
	.byte $00,$c6,$08,$c7,$07,$c8,$00,$05
@env6:
	.byte $00,$ca,$c9,$c7,$c5,$c4,$c2,$c0,$00,$07
@env7:
	.byte $00,$cf,$cf,$ce,$cc,$c7,$00,$05
@env8:
	.byte $00,$00,$b0,$bb,$bb,$bb,$bb,$bb
@env9:
	.byte $cc,$7f,$00,$00
@env10:
	.byte $bc,$c0,$bf,$00,$02
@env11:
	.byte $ad,$b5,$be,$00,$02
@env12:
	.byte $bb,$be,$00,$01
@env13:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env14:
	.byte $00,$cf,$7f,$00,$02
@env15:
	.byte $00,$c3,$c2,$c1,$04,$c0,$00,$05
@env16:
	.byte $c0,$7f,$00,$01
@env17:
	.byte $09,$ca,$c9,$04,$c8,$03,$c8,$00,$06,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$c1,$c1,$c0,$05,$c0,$00,$19
@env18:
	.byte $7f,$00,$00
@env19:
	.byte $06,$ca,$c9,$c8,$00,$03,$c7,$c7,$c5,$c2,$c0,$00,$0a
@env20:
	.byte $10,$32,$54,$76,$98,$ba,$dc,$fe,$ef,$cd,$ab,$89,$67,$45,$23,$01
@env21:
	.byte $c1,$7f,$00,$00
@env22:
	.byte $00,$00,$00,$00,$ff,$ff,$ff,$ff
@env23:
	.byte $00,$c6,$c3,$c0,$00,$03
@env24:
	.byte $00,$c0,$cf,$00,$02
@env25:
	.byte $68,$35,$12,$01,$00,$11,$32,$65,$98,$ca,$ed,$fe,$ff,$ee,$cd,$9a
@env26:
	.byte $00,$c6,$02,$c5,$07,$c4,$05,$c3,$00,$07
@env27:
	.byte $00,$c6,$c3,$03,$c2,$c2,$c1,$04,$c0,$00,$08
@env28:
	.byte $06,$c6,$c4,$c3,$00,$03,$c3,$c2,$c1,$c1,$c0,$00,$0a
@env29:
	.byte $c0,$bd,$bc,$00,$02
@env30:
	.byte $b4,$7f,$00,$00
@env31:
	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$f0,$ff,$ff,$ff,$ff,$ff
@env32:
	.byte $00,$c8,$c7,$c5,$c3,$00,$04
@env33:
	.byte $00,$00,$00,$00,$aa,$aa,$aa,$aa
@env34:
	.byte $ba,$bf,$be,$00,$02
@env35:
	.byte $00,$cd,$cc,$cb,$06,$ca,$00,$05

@n163_inst0_waves:
	.word @env33

@n163_inst1_waves:
	.word @env33

@n163_inst2_waves:
	.word @env22

@n163_inst3_waves:
	.word @env8

@n163_inst4_waves:
	.word @env31

@n163_inst5_waves:
	.word @env22

@n163_inst6_waves:
	.word @env25

@n163_inst7_waves:
	.word @env1

@n163_inst8_waves:
	.word @env20

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $8e
@song0ref2:
	.byte $2c, $89, $45, $89, $00, $95, $2c, $89, $2c, $89, $45, $89, $2c, $89, $45, $89, $00, $89, $2c, $89, $45, $89, $00, $89
	.byte $2c, $89, $2c, $89, $45, $89, $48, $2c, $89, $45, $89, $00, $95, $2c, $89, $2c, $89, $45, $89, $2c, $89, $45, $89, $00
	.byte $89, $2c, $89, $45, $89, $00, $89, $2c, $89, $2a, $89, $45, $89, $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48, $00, $ff, $bd, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $3c
	.word @song0ref2
@song0ref179:
	.byte $48, $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $8f, $00, $83, $31, $81, $00, $85, $31, $8d, $00
	.byte $85, $31, $83, $00, $83, $31, $8f
@song0ref210:
	.byte $00, $83, $31, $81, $00, $85, $31, $83, $00, $83, $31, $8f, $00, $83, $48, $31, $81, $00, $85, $31, $8d, $00, $85, $31
	.byte $83, $00, $83, $31, $81, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31
	.byte $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $8f, $00, $83, $48, $31, $81, $00, $85, $31, $83, $00, $83
	.byte $31, $8f, $00, $83, $31, $81, $00, $85, $31, $83, $00, $83, $31, $8f, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85
	.byte $31, $83
	.byte $41, $23
	.word @song0ref210
	.byte $8f, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31
	.byte $83, $00, $83
	.byte $41, $7e
	.word @song0ref179
	.byte $41, $23
	.word @song0ref210
	.byte $8f, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31
	.byte $83, $00, $83
	.byte $41, $7e
	.word @song0ref179
	.byte $41, $23
	.word @song0ref210
	.byte $8f, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31
	.byte $83, $00, $83
	.byte $41, $7e
	.word @song0ref179
	.byte $41, $23
	.word @song0ref210
	.byte $8f, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85, $31, $8d, $00, $85, $31
	.byte $83, $00, $83, $48, $ff, $bf, $48, $ff, $bf, $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $38
	.word @song0ref2
	.byte $45, $89, $00, $89, $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $38
	.word @song0ref2
	.byte $45, $89, $00, $89, $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $38
	.word @song0ref2
	.byte $45, $89, $00, $89, $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $38
	.word @song0ref2
	.byte $45, $89, $00, $89, $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $38
	.word @song0ref2
	.byte $45, $89, $00, $89, $48
	.byte $41, $3c
	.word @song0ref2
	.byte $48
	.byte $41, $2c
	.word @song0ref2
	.byte $2c, $89, $2c, $89, $2c, $89, $45, $89, $2c, $89, $2c, $89, $2c, $89, $45, $89, $42
	.word @song0ch0loop
@song0ch1:
	.byte $8e
@song0ref531:
	.byte $27, $89, $45, $89, $00, $95, $27, $89, $27, $89, $45, $89, $27, $89, $45, $89, $00, $89, $27, $89, $45, $89, $00, $89
	.byte $27, $89
@song0ref557:
	.byte $27, $89, $45, $89, $27, $89, $45, $89, $00, $95, $27, $89, $27, $89, $45, $89, $27, $89, $45, $89, $00, $89, $27, $89
	.byte $45, $89, $00, $89, $27, $89, $25, $89, $45, $89
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
@song0ch1loop:
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $00, $ff, $bd, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $22
	.word @song0ref557
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $22
	.word @song0ref557
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $1e
	.word @song0ref557
	.byte $41, $22
	.word @song0ref557
	.byte $41, $3c
	.word @song0ref531
@song0ref694:
	.byte $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83, $00, $83, $2c, $8f
@song0ref708:
	.byte $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83, $00, $83, $2c, $8f
@song0ref724:
	.byte $00, $83, $2c, $81, $00, $85, $2c, $83, $00, $83, $2c, $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83
	.byte $00, $83, $2c, $81, $00, $85, $2c, $83, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83
	.byte $41, $23
	.word @song0ref708
	.byte $83, $00, $83, $2c, $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83
	.byte $41, $23
	.word @song0ref724
	.byte $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c
	.byte $83, $00, $83
	.byte $41, $4a
	.word @song0ref694
	.byte $41, $23
	.word @song0ref708
	.byte $83, $00, $83, $2c, $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83
	.byte $41, $23
	.word @song0ref724
	.byte $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c
	.byte $83, $00, $83
	.byte $41, $4a
	.word @song0ref694
	.byte $41, $23
	.word @song0ref708
	.byte $83, $00, $83, $2c, $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83
	.byte $41, $23
	.word @song0ref724
	.byte $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c
	.byte $83, $00, $83
	.byte $41, $4a
	.word @song0ref694
	.byte $41, $23
	.word @song0ref708
	.byte $83, $00, $83, $2c, $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83
	.byte $41, $23
	.word @song0ref724
	.byte $8f, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83, $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c
	.byte $83, $00, $83, $ff, $bf, $ff, $bf
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $89, $00, $89
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $89, $00, $89
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $89, $00, $89
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $89, $00, $89
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $38
	.word @song0ref531
	.byte $45, $89, $00, $89
	.byte $41, $3c
	.word @song0ref531
	.byte $41, $2c
	.word @song0ref531
	.byte $27, $89, $27, $89, $27, $89, $45, $89, $27, $89, $27, $89, $27, $89, $45, $89, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song0ch2loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $90, $08, $ff, $bd, $0b, $ff, $bd, $0d
	.byte $ff, $bd, $0b, $ff, $bd, $08, $ff, $bd, $0b, $ff, $bd, $0d, $ff, $bd, $0b, $ff, $bd, $08, $ff, $bd, $0b, $ff, $bd, $0d
	.byte $ff, $bd, $0b, $ff, $bd, $08, $ff, $bd, $0b, $ff, $bd, $0d, $ff, $bd, $0b
@song0ref1136:
	.byte $ff, $bd
@song0ref1138:
	.byte $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $08, $89, $08, $89
	.byte $08, $89, $00, $89, $08, $89, $08, $89
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $00
	.byte $41, $22
	.word @song0ref1136
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
	.byte $41, $20
	.word @song0ref1138
@song0ref1237:
	.byte $06, $89, $00, $89, $06, $89, $06, $89, $06, $89, $00, $89, $12, $89, $12, $89, $08, $89, $00, $89, $08, $89, $08, $89
	.byte $08, $89, $00, $89, $08, $89, $08, $89, $0d, $89, $00, $89, $0d, $89, $0d, $89, $0d, $89, $00, $89, $0d, $89, $0d, $89
	.byte $0d, $89, $00, $89, $0d, $89, $0d, $89, $0d, $89, $00, $89, $0d, $89, $0d, $89, $06, $89, $00, $89, $06, $89, $06, $89
	.byte $06, $89, $00, $89, $12, $89, $12, $89, $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $14, $89, $14, $89
	.byte $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $14, $89, $14, $89, $05, $89, $00, $89, $05, $89, $05, $89
	.byte $05, $89, $00, $89, $11, $89, $11, $89
	.byte $41, $70
	.word @song0ref1237
	.byte $0d, $89, $00, $89, $19, $89, $19, $89, $00, $89, $0d, $89, $19, $89, $19, $89
	.byte $41, $80
	.word @song0ref1237
	.byte $41, $70
	.word @song0ref1237
	.byte $0d, $89, $00, $89, $19, $89, $19, $89, $00, $89, $0d, $89, $19, $89, $19, $89, $00, $ff, $bd, $03, $89, $03, $89, $0f
	.byte $89, $0f, $89, $0d, $95, $0f, $95, $0d, $95, $0f, $95, $0d, $95, $0f, $95
@song0ref1429:
	.byte $08, $89, $00, $89, $14, $89, $14, $89, $08, $89, $00, $89, $14, $89, $14, $89, $08, $89, $00, $89, $14, $89, $14, $89
	.byte $08, $89, $00, $89, $14, $89, $14, $89, $0b, $89, $00, $89, $17, $89, $17, $89, $0b, $89, $00, $89, $17, $89, $17, $89
	.byte $0b, $89, $00, $89, $17, $89, $17, $89, $0b, $89, $00, $89, $17, $89, $17, $89, $01, $89, $00, $89, $0d, $89, $0d, $89
	.byte $01, $89, $00, $89, $0d, $89, $0d, $89, $01, $89, $00, $89, $0d, $89, $0d, $89, $01, $89, $00, $89, $0d, $89, $0d, $89
	.byte $04, $89, $00, $89, $10, $89, $10, $89, $04, $89, $00, $89, $10, $89, $10, $89, $03, $89, $00, $89, $0f, $89, $0f, $89
	.byte $03, $89, $00, $89, $0f, $89, $0f, $89
	.byte $41, $40
	.word @song0ref1429
@song0ref1560:
	.byte $04, $89, $00, $89, $10, $89, $10, $89, $04, $89, $00, $89, $10, $89, $10, $89, $04, $89, $00, $89, $10, $89, $10, $89
	.byte $04, $89, $00, $89, $10, $89, $10, $89, $06, $89, $00, $89, $12, $89, $12, $89, $06, $89, $00, $89, $12, $89, $12, $89
	.byte $06, $89, $00, $89, $12, $89, $12, $89, $06, $89, $00, $89, $12, $89, $12, $89
	.byte $41, $80
	.word @song0ref1429
	.byte $41, $40
	.word @song0ref1429
	.byte $41, $40
	.word @song0ref1560
	.byte $41, $80
	.word @song0ref1429
	.byte $41, $40
	.word @song0ref1429
	.byte $41, $32
	.word @song0ref1560
	.byte $06, $89, $06, $95, $06, $89, $06, $89, $06, $89, $00, $89, $42
	.word @song0ch2loop
@song0ch3:
	.byte $84, $28, $89, $78
@song0ref1661:
	.byte $28, $89, $28, $89, $28, $89, $7f, $28, $89, $78, $28, $89, $28, $89, $28, $89, $7f, $28, $89, $78, $28, $89, $28, $89
	.byte $28, $89, $7f, $28, $89, $78, $28, $89, $28, $89, $28, $89, $28, $89
	.byte $41, $1e
	.word @song0ref1661
	.byte $7f, $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $80, $30, $95
@song0ref1720:
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $95, $86, $2d, $89, $82, $31, $89, $80, $30, $95, $84, $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d, $89
	.byte $82, $31, $89, $80, $30, $89, $86, $2d, $89
	.byte $41, $23
	.word @song0ref1720
	.byte $95, $84, $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $80, $30, $89, $86, $2d, $89
@song0ref1802:
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $95
@song0ref1811:
	.byte $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $82, $31, $89, $80, $30, $95, $86
	.byte $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d
	.byte $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $80, $30, $95, $86, $2d, $89
	.byte $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89
@song0ch3loop:
	.byte $41, $38
	.word @song0ref1802
	.byte $41, $38
	.word @song0ref1802
	.byte $41, $38
	.word @song0ref1802
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $84
	.byte $28, $89, $82, $31, $89, $80, $30, $95, $86, $2d, $89, $82, $31, $89, $79, $86, $2d, $89, $7f, $80, $30, $89, $00, $ff
	.byte $bd, $8c, $2f, $ad, $84, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00
	.byte $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00
	.byte $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $28, $89, $00, $a1, $8c, $2f, $ad
@song0ref2020:
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $95, $84, $28, $89, $82, $31, $89, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $95, $84, $28, $89, $82, $31, $89, $80, $30, $95, $84, $28, $89, $82, $31, $89, $80, $30, $95
	.byte $41, $1e
	.word @song0ref2020
	.byte $41, $1e
	.word @song0ref2020
	.byte $8c, $2f, $ad
	.byte $41, $32
	.word @song0ref1811
	.byte $41, $38
	.word @song0ref1802
	.byte $8c, $2f, $ad
	.byte $41, $32
	.word @song0ref1811
	.byte $41, $38
	.word @song0ref1802
@song0ref2089:
	.byte $8c, $2f, $ad, $88, $30, $95, $80, $30, $95
@song0ref2098:
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $89, $88, $30
@song0ref2136:
	.byte $89
@song0ref2137:
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89
	.byte $88, $30, $95, $80, $30, $95
	.byte $41, $24
	.word @song0ref2137
	.byte $41, $3e
	.word @song0ref2098
	.byte $00, $ff, $bd
	.byte $41, $44
	.word @song0ref2089
	.byte $41, $24
	.word @song0ref2137
	.byte $41, $3e
	.word @song0ref2098
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95
	.byte $41, $44
	.word @song0ref2089
	.byte $41, $24
	.word @song0ref2137
	.byte $41, $3e
	.word @song0ref2098
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95
	.byte $41, $44
	.word @song0ref2089
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $76, $51, $06, $f0, $86, $2d, $89, $2d, $89, $2d, $89, $2d, $89
	.byte $41, $44
	.word @song0ref2089
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $76, $51, $06, $f0, $86, $2d, $89, $2d, $89, $2d, $89, $2d, $89
	.byte $41, $44
	.word @song0ref2089
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $76, $51, $06, $f0, $86, $2d, $89, $2d, $89, $2d, $89, $2d, $89
	.byte $41, $44
	.word @song0ref2089
	.byte $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89
	.byte $80, $30, $89, $8a, $30, $89, $76, $51, $06, $f0, $86, $2d, $89, $2d, $89, $2d, $89, $2d
	.byte $41, $23
	.word @song0ref2136
	.byte $82, $31, $89, $88, $30, $89, $84, $28, $89, $82, $31, $89, $88, $30, $95, $7b, $51, $03, $f0
@song0ref2495:
	.byte $86, $2d, $89, $2d, $89
@song0ref2500:
	.byte $2d, $89, $2d, $89, $8c, $2f, $a1
@song0ref2507:
	.byte $8a, $30, $89, $88, $30, $95, $80, $30, $95, $84, $28, $89, $82, $31, $89, $86, $2d, $89, $8a, $30, $89, $88, $30, $95
	.byte $86, $2d, $89, $2d, $89, $84, $28, $89, $82, $31, $89, $80, $30, $89, $8a, $30, $89, $88, $30, $95, $80, $30, $89, $88
	.byte $30, $89, $84, $28, $89, $82, $31, $89, $86, $2d, $89, $8a, $30, $89, $88, $30, $95, $86, $2d, $89, $2d, $89, $84, $28
	.byte $89, $82, $31, $89, $80, $30, $89
	.byte $41, $1e
	.word @song0ref2507
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $2d, $89, $88, $30, $95, $86
	.byte $41, $3c
	.word @song0ref2500
	.byte $41, $1e
	.word @song0ref2507
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $8a, $30, $89, $78, $51, $05, $f0
	.byte $41, $40
	.word @song0ref2495
	.byte $41, $1e
	.word @song0ref2507
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $2d, $89, $88, $30, $95, $86
	.byte $41, $3c
	.word @song0ref2500
	.byte $41, $1e
	.word @song0ref2507
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $8a, $30, $89, $78, $51, $05, $f0
	.byte $41, $40
	.word @song0ref2495
	.byte $41, $1e
	.word @song0ref2507
	.byte $86, $2d, $89, $80, $30, $89, $84, $28, $89, $86, $2d, $89, $2d, $89, $2d, $89, $88, $30, $95, $86
	.byte $41, $3c
	.word @song0ref2500
	.byte $41, $1f
	.word @song0ref2507
	.byte $95, $86, $2e, $89, $2e, $89, $2e, $89, $00, $89, $2e, $89, $2e, $89, $2e, $89, $00, $89, $42
	.word @song0ch3loop
@song0ch12:
@song0ch11:
@song0ch4:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song0ch4loop:
@song0ref2761:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $1e
	.word @song0ref2761
	.byte $41, $1e
	.word @song0ref2761
	.byte $41, $1e
	.word @song0ref2761
	.byte $41, $1e
	.word @song0ref2761
	.byte $41, $1e
	.word @song0ref2761
	.byte $42
	.word @song0ch4loop
@song0ch5:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song0ch5loop:
	.byte $8a
@song0ref2827:
	.byte $20, $89, $5a, $89, $00, $95, $20, $89, $20, $89, $5a, $89, $20, $89, $5a, $89, $00, $89, $20, $89, $5a, $89, $00, $89
	.byte $20, $89, $20, $89, $5a, $89, $20, $89, $5a, $89, $00, $95, $20, $89, $20, $89, $5a, $89, $20, $89, $5a, $89, $00, $89
	.byte $20, $89, $5a, $89, $00, $89, $20, $89, $1e, $89, $5a, $89
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $1e
	.word @song0ref2827
	.byte $00, $ff, $bd, $8e
@song0ref2900:
	.byte $20, $91, $43, $50, $3a, $2c, $33, $81, $27, $91, $43, $50, $c6, $33, $2c, $81, $43, $20, $85, $43, $50, $27, $2c, $31
	.byte $81, $25, $91, $43, $50, $d9, $31, $2c, $81, $43, $20, $85, $43, $50, $16, $2c, $2f, $81, $23, $91, $43, $50, $ea, $2f
	.byte $2c, $81, $43, $20, $85, $43, $50, $27, $2c, $31, $81, $25, $91, $43, $50, $d9, $31, $2c, $81, $43, $20, $85, $43, $50
	.byte $3a, $2c, $33, $81, $27, $95
	.byte $41, $26
	.word @song0ref2900
@song0ref2981:
	.byte $25, $91, $43, $50, $4e, $31, $38, $81, $2c, $91, $43, $50, $8c, $38, $2c, $81, $43, $20, $85, $43, $50, $5b, $2c, $36
	.byte $81, $2a, $91, $43, $50, $a5, $36, $2c, $81, $43, $20, $85, $43, $50, $50, $2c, $35, $81, $29, $91, $43, $50, $b1, $35
	.byte $2c, $81, $43, $20, $83, $43, $50, $3d, $2c, $36, $83, $2a, $8f, $43, $50, $c3, $36, $2c, $83, $43, $20, $83, $43, $50
	.byte $4e, $2c, $38, $83, $2c, $95, $23, $8f, $43, $50, $2e, $2f, $36, $83, $2a, $8f, $43, $50, $c3, $36, $2c, $83, $43, $20
	.byte $83, $43, $50, $3d, $2c, $36, $83, $2a, $8f, $43, $50, $c3, $36, $2c, $83, $43, $20, $83, $43, $50, $35, $2c, $35, $83
	.byte $29, $8f, $43, $50, $cb, $35, $2c, $83, $43, $20, $83, $43, $50, $27, $2c, $33, $83, $27, $8f, $43, $50, $d9, $33, $2c
	.byte $83, $43, $20, $83, $43, $50, $1a, $2c, $31, $83, $25, $95
	.byte $41, $26
	.word @song0ref2900
	.byte $41, $26
	.word @song0ref2900
	.byte $41, $4c
	.word @song0ref2981
	.byte $41, $26
	.word @song0ref2900
	.byte $41, $26
	.word @song0ref2900
	.byte $41, $4c
	.word @song0ref2981
	.byte $41, $26
	.word @song0ref2900
	.byte $41, $26
	.word @song0ref2900
	.byte $41, $4c
	.word @song0ref2981
	.byte $7b, $00, $95, $8a
@song0ref3168:
	.byte $27, $89, $00, $89, $27, $89, $27, $89, $00, $89, $27, $89, $00, $89, $27, $89, $27, $89, $00, $89, $27, $89, $00, $89
	.byte $29, $89, $00, $89, $29, $89, $00, $89, $27, $89, $00, $89, $27, $89, $27, $89, $00, $89, $27, $89, $00, $95, $27, $89
	.byte $00, $a1, $27, $95, $00, $95
	.byte $41, $36
	.word @song0ref3168
	.byte $41, $36
	.word @song0ref3168
	.byte $41, $34
	.word @song0ref3168
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $1e
	.word @song0ref2827
	.byte $7d, $20, $89, $5a, $89, $00, $95, $20, $89, $20, $89, $5a, $89, $20, $89, $90, $3d, $89, $38, $89, $35, $89, $31, $89
	.byte $2c, $89, $29, $89, $25, $89, $20, $89, $00, $ff, $bd
@song0ref3290:
	.byte $7e, $51, $fd, $90, $8b, $31, $89, $3d, $89, $31, $89, $3d, $89, $31, $89, $51, $03, $f0, $3d, $89, $31, $89, $3d, $89
	.byte $31, $89, $3d, $89, $31, $89, $51, $fe, $10, $3d, $89, $38, $89, $35, $89, $31, $89, $3d, $89, $38, $89, $35, $89, $31
	.byte $89, $3d, $85, $00, $81, $38, $85, $00, $81, $35, $85, $00, $81, $31, $85, $00, $81, $3d, $83, $00, $83, $38, $83, $00
	.byte $83, $35, $83, $00, $83, $31, $83, $00, $83, $3d, $81, $00, $85, $38, $81, $00, $85, $35, $81, $00, $85, $31, $81, $00
	.byte $7f, $85, $ff, $bf, $ff, $bf
	.byte $41, $5b
	.word @song0ref3290
	.byte $41, $5b
	.word @song0ref3290
	.byte $41, $5b
	.word @song0ref3290
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $97, $88
@song0ref3421:
	.byte $1e, $95, $23, $ad, $1e, $a1, $25, $a1, $23, $95, $97
@song0ref3432:
	.byte $23, $95, $1e, $95, $23, $95, $1e, $a1, $25, $a1, $23, $95, $1e, $95, $23, $ad, $1e, $a1, $25, $a1, $23, $95, $1e, $95
	.byte $97, $23, $95, $1e, $95, $23, $95, $1e, $a1, $25, $a1, $23, $95, $97
	.byte $41, $31
	.word @song0ref3421
	.byte $41, $31
	.word @song0ref3421
	.byte $41, $2a
	.word @song0ref3421
	.byte $00, $dd, $42
	.word @song0ch5loop
@song0ch6:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $82
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
@song0ch6loop:
	.byte $80, $27, $ff, $bd, $2a, $ff, $bd, $29, $ff, $bd, $25, $ff, $bd, $27, $ff, $bd, $2a, $ff, $bd, $29, $ff, $bd, $25, $ff
	.byte $bd, $82
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $3c
	.word @song0ref2827
	.byte $41, $1e
	.word @song0ref2827
	.byte $00, $ff, $bd, $80, $33, $ff, $bd, $36, $ff, $bd, $35, $ff, $bd, $31, $ff, $bd, $33, $ff, $bd, $36, $ff, $bd, $38, $ff
	.byte $bd, $35, $ff, $bd, $33, $ff, $bd, $36, $ff, $bd, $35, $ff, $bd, $31, $ff, $bd, $33, $ff, $bd, $36, $ff, $bd, $38, $ff
	.byte $bd, $35, $ff, $bd, $84
@song0ref3615:
	.byte $28, $c5, $2a, $dd, $2c, $95, $ff, $bf, $28, $dd, $2a, $dd, $27, $dd, $25, $dd, $28, $c5, $2a, $dd, $2c, $95, $ff, $bf
	.byte $28, $dd, $2a, $dd, $2a, $dd, $29, $dd
	.byte $41, $1e
	.word @song0ref3615
	.byte $2c, $dd, $50, $ca, $4c, $28, $ad, $50, $ca, $4c, $28, $ad, $50, $ca, $4c, $28, $ad, $50, $ca, $4c, $28, $ad, $2c, $95
	.byte $43, $50, $fe, $35, $31, $dd, $80, $50, $03, $35, $38, $c5, $00, $95, $86
@song0ref3689:
	.byte $33, $95, $5a, $89, $33, $95, $5a, $89, $33, $95, $5a, $89, $31, $95, $5a, $89, $33, $95, $5a, $95, $36, $95, $5a, $89
	.byte $36, $95, $5a, $89, $36, $95, $5a, $89, $36, $95, $5a, $89, $36, $89, $36, $89, $5a, $95, $31, $95, $5a, $89, $31, $95
	.byte $5a, $89, $31, $95, $31, $89, $2f, $95, $5a, $89, $31, $95, $34, $95, $5a, $89, $34, $95, $5a, $89, $34, $89, $34, $95
	.byte $5a, $89, $36, $95, $5a, $89, $36, $95, $5a, $89, $97
	.byte $41, $2a
	.word @song0ref3689
@song0ref3775:
	.byte $33, $95, $5a, $89, $33, $95, $5a, $89, $33, $95, $33, $89, $31, $95, $5a, $89, $33, $95, $31, $95, $5a, $89, $31, $95
	.byte $5a, $89, $31, $89, $31, $95, $5a, $89, $36, $95, $5a, $89, $36, $95, $5a, $89, $97
	.byte $41, $53
	.word @song0ref3689
	.byte $41, $2a
	.word @song0ref3689
	.byte $41, $29
	.word @song0ref3775
	.byte $41, $53
	.word @song0ref3689
	.byte $41, $2a
	.word @song0ref3689
	.byte $33, $95, $5a, $89, $33, $95, $5a, $89, $33, $95, $33, $89, $31, $95, $5a, $89, $33, $95, $31, $95, $5a, $89, $31, $95
	.byte $5a, $89, $31, $95, $31, $89, $31, $89, $31, $89, $5a, $89, $31, $89, $31, $89, $31, $89, $5a, $89, $42
	.word @song0ch6loop
@song0ch7:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song0ref3886:
	.byte $82
@song0ref3887:
	.byte $1b, $89, $5a, $89, $00, $95, $1b, $89, $1b, $89, $5a, $89, $1b, $89, $5a, $89, $00, $89, $1b, $89, $5a, $89, $00, $89
	.byte $1b, $89, $1b, $89, $5a, $89, $1b, $89, $5a, $89, $00, $95, $1b, $89, $1b, $89, $5a, $89, $1b, $89, $5a, $89, $00, $89
	.byte $1b, $89, $5a, $89, $00, $89, $1b, $89, $19, $89, $5a, $89
	.byte $41, $3c
	.word @song0ref3887
@song0ch7loop:
	.byte $80, $22, $ff, $bd, $25, $ff, $bd, $24, $ff, $bd, $20, $ff, $bd, $22, $ff, $bd, $25, $ff, $bd, $24, $ff, $bd, $20, $ff
	.byte $bd
	.byte $41, $3c
	.word @song0ref3886
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $3c
	.word @song0ref3887
	.byte $41, $1e
	.word @song0ref3887
	.byte $00, $ff, $bd, $80, $2c, $ff, $bd, $2f, $ff, $bd, $2e, $ff, $bd, $2a, $ff, $bd, $2c, $ff, $bd, $2f, $ff, $bd, $31, $ff
	.byte $bd, $2e, $ff, $bd, $2c, $ff, $bd, $2f, $ff, $bd, $2e, $ff, $bd, $2a, $ff, $bd, $2c, $ff, $bd, $2f, $ff, $bd, $31, $ff
	.byte $bd, $2e, $ff, $bd, $84
@song0ref4065:
	.byte $25, $c5, $27, $dd, $29, $95, $ff, $bf, $25, $dd, $27, $dd, $23, $dd, $23, $dd, $25, $c5, $27, $dd, $29, $95, $ff, $bf
	.byte $25, $dd, $27, $dd, $27, $dd, $25, $dd
	.byte $41, $1e
	.word @song0ref4065
	.byte $29, $dd, $50, $d2, $49, $25, $ad, $50, $d2, $49, $25, $ad, $50, $d2, $49, $25, $ad, $50, $d2, $49, $25, $ad, $29, $95
	.byte $43, $50, $fe, $32, $2e, $dd, $80, $50, $02, $32, $35, $c5, $00, $95, $86
@song0ref4139:
	.byte $30, $95, $5a, $89, $30, $95, $5a, $89, $30, $95, $5a, $89, $2e, $95, $5a, $89, $30, $95, $5a, $95, $33, $95, $5a, $89
	.byte $33, $95, $5a, $89, $33, $95, $5a, $89, $31, $95, $5a, $89, $33, $89, $33, $89, $5a, $95, $2c, $95, $5a, $89, $2c, $95
	.byte $5a, $89, $2c, $95, $2c, $89, $2a, $95, $5a, $89, $2c, $95, $2f, $95, $5a, $89, $2f, $95, $5a, $89, $2f, $89, $2f, $95
	.byte $5a, $89, $31, $95, $5a, $89, $31, $95, $5a, $89, $97
	.byte $41, $2a
	.word @song0ref4139
@song0ref4225:
	.byte $2f, $95, $5a, $89, $2f, $95, $5a, $89, $2f, $95, $2f, $89, $2e, $95, $5a, $89, $2f, $95, $2e, $95, $5a, $89, $2e, $95
	.byte $5a, $89, $2e, $89, $2e, $95, $5a, $89, $31, $95, $5a, $89, $31, $95, $5a, $89, $97
	.byte $41, $53
	.word @song0ref4139
	.byte $41, $2a
	.word @song0ref4139
	.byte $41, $29
	.word @song0ref4225
	.byte $41, $53
	.word @song0ref4139
	.byte $41, $2a
	.word @song0ref4139
	.byte $2f, $95, $5a, $89, $2f, $95, $5a, $89, $2f, $95, $2f, $89, $2e, $95, $5a, $89, $2f, $95, $2e, $95, $5a, $89, $2e, $95
	.byte $5a, $89, $2e, $95, $2e, $89, $2e, $89, $2e, $89, $5a, $89, $2e, $89, $2e, $89, $2e, $89, $5a, $89, $42
	.word @song0ch7loop
@song0ch8:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song0ch8loop:
	.byte $80, $20, $ff, $bd, $23, $ff, $bd, $22, $ff, $bd, $1e, $ff, $bd, $20, $ff, $bd, $23, $ff, $bd, $22, $ff, $bd, $1e, $ff
	.byte $bd, $00, $ff, $bd
	.byte $41, $1e
	.word @song0ref2761
	.byte $00, $95, $82, $25, $89, $00, $89, $25, $89, $25, $89, $00, $89, $25, $89, $00, $89, $25, $89, $25, $89, $00, $89, $25
	.byte $89, $00, $89, $25, $89, $00, $89, $7c, $25, $89, $00, $89, $25, $89, $00, $89, $25, $89, $25, $89, $00, $89, $25, $89
	.byte $00, $95, $23, $89, $00, $a1, $23, $95, $00, $95, $25, $89, $00, $89, $25, $89, $25, $89, $00, $89, $25, $89, $00, $89
	.byte $25, $89, $25, $89, $00, $89, $25, $89, $00, $89, $25, $89, $00, $89
@song0ref4462:
	.byte $25, $89, $00, $89, $25, $89, $00, $89, $25, $89, $25, $89, $00, $89, $25, $89, $00, $95, $23, $89, $00, $a1, $23, $95
	.byte $00, $95, $7f, $88, $1e, $95, $23, $ad, $1e, $a1, $25, $a1, $23, $95, $97, $1e, $95, $23, $ad, $1e, $a1, $25, $a1, $23
	.byte $95, $97, $1e, $95, $23, $ad, $1e, $a1, $25, $a1, $23, $95, $7c, $82
	.byte $41, $25
	.word @song0ref4462
	.byte $41, $26
	.word @song0ref3432
	.byte $41, $31
	.word @song0ref3421
	.byte $41, $31
	.word @song0ref3421
	.byte $41, $30
	.word @song0ref3421
	.byte $84
@song0ref4540:
	.byte $21, $c5, $23, $dd, $25, $95, $ff, $bf, $21, $dd, $23, $dd, $22, $dd, $20, $dd, $21, $c5, $23, $dd, $25, $95, $ff, $bf
	.byte $21, $dd, $23, $dd, $23, $dd, $23, $dd
	.byte $41, $1e
	.word @song0ref4540
	.byte $25, $dd, $50, $d7, $47, $23, $ad, $50, $d7, $47, $23, $ad, $50, $d7, $47, $23, $ad, $50, $d7, $47, $23, $ad, $25, $95
	.byte $43, $50, $fe, $2e, $2a, $dd, $80, $50, $02, $2e, $31, $c5, $00, $95, $86
@song0ref4614:
	.byte $2c, $95, $5a, $89, $2c, $95, $5a, $89, $2c, $95, $5a, $89, $2a, $95, $5a, $89, $2c, $95, $5a, $95, $2f, $95, $5a, $89
	.byte $2f, $95, $5a, $89, $2f, $95, $5a, $89, $2f, $95, $5a, $89, $2f, $89, $2f, $89, $5a, $95, $29, $95, $5a, $89, $29, $95
	.byte $5a, $89, $29, $95, $29, $89, $27, $95, $5a, $89, $29, $95, $2c, $95, $5a, $89, $2c, $95, $5a, $89, $2c, $89, $2c, $95
	.byte $5a, $89, $2e, $95, $5a, $89, $2e, $95, $5a, $89, $00, $95
	.byte $41, $2a
	.word @song0ref4614
@song0ref4701:
	.byte $2c, $95, $5a, $89, $2c, $95, $5a, $89, $2c, $95, $2c, $89, $2a, $95, $5a, $89, $2c, $95, $2a, $95, $5a, $89, $2a, $95
	.byte $5a, $89, $2a, $89, $2a, $95, $5a, $89, $2e, $95, $5a, $89, $2e, $95, $5a, $89, $00, $95
	.byte $41, $54
	.word @song0ref4614
	.byte $41, $2a
	.word @song0ref4614
	.byte $41, $2a
	.word @song0ref4701
	.byte $41, $54
	.word @song0ref4614
	.byte $41, $2a
	.word @song0ref4614
	.byte $2c, $95, $5a, $89, $2c, $95, $5a, $89, $2c, $95, $2c, $89, $2a, $95, $5a, $89, $2c, $95, $2a, $95, $5a, $89, $2a, $95
	.byte $5a, $89, $2a, $95, $2a, $89, $2a, $89, $2a, $89, $5a, $89, $2a, $89, $2a, $89, $2a, $89, $5a, $89, $42
	.word @song0ch8loop
@song0ch9:
	.byte $8c
@song0ref4806:
	.byte $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e
	.byte $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00
	.byte $a1, $50, $e3, $2e, $1b, $89, $00, $a1
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
@song0ch9loop:
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e
	.byte $1b, $89, $00, $a1, $ff, $bf
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e
	.byte $1b, $89, $00, $a1, $ff, $bf
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $41, $20
	.word @song0ref4806
	.byte $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e
	.byte $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $d1, $50, $e3, $2e, $1b, $89, $50, $e3, $2e, $1b, $89, $50, $e3, $2e
	.byte $1b, $89, $00, $89, $50, $e3, $2e, $1b, $89, $50, $e3, $2e, $1b, $89, $50, $e3, $2e, $1b, $89, $00, $89, $42
	.word @song0ch9loop
@song0ch10:
	.byte $ff, $bf, $ff, $bf, $7d, $00, $ad, $8c, $50, $c7, $36, $18, $89, $00, $d1, $50, $c7, $36, $18, $89, $00, $a1, $af, $50
	.byte $c7, $36, $18, $89, $00, $d1, $50, $c7, $36, $18, $89, $00, $95, $50, $c7, $36, $18, $89, $00, $ad, $50, $c7, $36, $18
	.byte $89, $00, $d1, $50, $c7, $36, $18, $89, $00, $a1, $af, $50, $c7, $36, $18, $89, $00, $d1, $50, $c7, $36, $18, $89, $00
	.byte $95, $50, $c7, $36, $18, $89
@song0ref5208:
	.byte $00, $ad, $50, $c7, $36, $18, $89, $00, $89, $75, $50, $c7, $36, $18, $89, $7d, $00, $b9, $50, $c7, $36, $18, $89, $00
	.byte $89, $75, $50, $c7, $36, $18, $89, $7d, $00, $89, $af, $50, $c7, $36, $18, $89, $00, $89, $75, $50, $c7, $36, $18, $89
	.byte $7d, $00, $95, $50, $c7, $36, $18, $89, $00, $95, $50, $c7, $36, $18, $89, $00, $89, $75, $50, $c7, $36, $18, $89, $7d
	.byte $00, $89
@song0ch10loop:
	.byte $41, $27
	.word @song0ref5208
	.byte $41, $27
	.word @song0ref5208
	.byte $41, $27
	.word @song0ref5208
	.byte $00, $ad, $50, $c7, $36, $18, $89, $00, $89, $75, $50, $c7, $36, $18, $89, $7d, $00, $b9, $50, $c7, $36, $18, $89, $00
	.byte $89, $75, $50, $c7, $36, $18, $89, $7d, $00, $89, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $ff, $bf, $ff, $bf
	.byte $41, $27
	.word @song0ref5208
	.byte $41, $27
	.word @song0ref5208
	.byte $41, $27
	.word @song0ref5208
	.byte $41, $27
	.word @song0ref5208
@song0ref5356:
	.byte $00, $ad, $50, $c7, $36, $18, $89, $00, $d1, $50, $c7, $36, $18, $89, $00, $a1, $af, $50, $c7, $36, $18, $89, $00, $95
	.byte $50, $c7, $36, $18, $89, $00, $ad, $50, $c7, $36, $18, $89, $00, $a1, $00, $ad, $50, $c7, $36, $18, $89, $00, $d1, $50
	.byte $c7, $36, $18, $89, $00, $a1, $af, $50, $c7, $36, $18, $89, $00, $95, $50, $c7, $36, $18, $89, $00, $ad, $50, $c7, $36
	.byte $18, $89, $00, $a1
	.byte $41, $21
	.word @song0ref5356
	.byte $ff, $bf
	.byte $41, $2e
	.word @song0ref5356
	.byte $41, $2e
	.word @song0ref5356
	.byte $41, $2e
	.word @song0ref5356
	.byte $41, $2e
	.word @song0ref5356
	.byte $41, $25
	.word @song0ref5356
	.byte $d1, $79, $51, $06, $f0, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18
	.byte $89, $7d
	.byte $41, $25
	.word @song0ref5356
	.byte $d1, $79, $51, $06, $f0, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18
	.byte $89, $7d
	.byte $41, $25
	.word @song0ref5356
	.byte $d1, $79, $51, $06, $f0, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18
	.byte $89, $7d
	.byte $41, $25
	.word @song0ref5356
	.byte $d1, $79, $51, $06, $f0, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18
	.byte $89, $7d, $00, $ad, $50, $c7, $36, $18, $89, $00, $d1, $50, $c7, $36, $18, $89, $00, $a1, $af, $50, $c7, $36, $18, $89
	.byte $00, $95, $50, $c7, $36, $18, $89, $00, $95, $50, $c7, $36, $18, $89
@song0ref5601:
	.byte $00, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $00, $ad
	.byte $50, $c7, $36, $18, $89, $00, $b9, $50, $c7, $36, $18, $89, $00, $89, $50, $c7, $36, $18, $89, $00, $89, $50, $c7, $36
	.byte $18, $89, $00, $89, $af, $50, $c7, $36, $18, $89, $00
@song0ref5660:
	.byte $95, $50, $c7, $36, $18, $89, $00, $95, $50, $c7, $36, $18, $89, $00
@song0ref5674:
	.byte $89, $50, $c7, $36, $18, $89, $00, $89, $50, $c7, $36, $18, $89, $00, $89, $00, $ad, $50, $c7, $36, $18, $89, $00, $b9
	.byte $50, $c7, $36, $18, $89, $00, $89, $50, $c7, $36, $18, $89, $00, $89, $50, $c7, $36, $18, $89, $00, $89, $af, $50, $c7
	.byte $36, $18, $89, $00, $89, $50, $c7, $36, $18, $89, $00, $95, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7
	.byte $36, $18
	.byte $41, $1f
	.word @song0ref5674
	.byte $41, $30
	.word @song0ref5660
	.byte $41, $51
	.word @song0ref5601
	.byte $41, $1f
	.word @song0ref5674
	.byte $41, $30
	.word @song0ref5660
	.byte $41, $51
	.word @song0ref5601
	.byte $41, $1f
	.word @song0ref5674
	.byte $41, $27
	.word @song0ref5660
	.byte $a1, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $00, $89, $50, $c7, $36, $18, $89, $50
	.byte $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $00, $89, $42
	.word @song0ch10loop
