; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Finned Frontier:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_VIBRATO = 1

.export _music_data_finned_frontier:=music_data_finned_frontier

music_data_finned_frontier:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Main Theme
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_finned_frontier
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env33,@env22,@env26,@env1 ; 00 : HiHat
	.word @env17,@env43,@env26,@env1 ; 01 : Kick
	.word @env35,@env38,@env26,@env1 ; 02 : Triangle Kick
	.word @env48,@env21,@env26,@env1 ; 03 : Triangle Snare
	.word @env0,@env15,@env26,@env1 ; 04 : Snare
	.word @env6,@env7,@env26,@env1 ; 05 : Snare Short
	.word @env4,@env16,@env26,@env1 ; 06 : Crash
	.word @env45,@env22,@env26,@env1 ; 07 : HiHat Long
	.word @env18,@env22,@env26,@env1 ; 08 : Triangle
	.word @env10,@env22,@env8,@env1 ; 09 : Synth
	.word @env11,@env25,@env28,@env41 ; 0a : Synth 50
	.word @env10,@env22,@env5,@env1 ; 0b : Synth 50 2

@instruments_exp:
	.word @env44, @env22, @env1 ; 00 : Sax 3
	.word @env1
	.byte $20, $10
	.word @n163_inst0_waves
	.byte $00, $00, $00, $00
	.word @env3, @env22, @env1 ; 01 : Sax 2
	.word @env1
	.byte $30, $20
	.word @n163_inst1_waves
	.byte $00, $00, $00, $00
	.word @env19, @env22, @env1 ; 02 : Sax 1
	.word @env1
	.byte $00, $10
	.word @n163_inst2_waves
	.byte $00, $00, $00, $00
	.word @env40, @env22, @env1 ; 03 : El Synth
	.word @env1
	.byte $10, $10
	.word @n163_inst3_waves
	.byte $00, $00, $00, $00
	.word @env36, @env22, @env1 ; 04 : El Piano
	.word @env1
	.byte $00, $10
	.word @n163_inst4_waves
	.byte $00, $00, $00, $00
	.word @env13, @env22, @env1 ; 05 : Clay
	.word @env1
	.byte $50, $10
	.word @n163_inst5_waves
	.byte $00, $00, $00, $00
	.word @env42, @env22, @env1 ; 06 : El Synth Long
	.word @env1
	.byte $10, $10
	.word @n163_inst6_waves
	.byte $00, $00, $00, $00
	.word @env50, @env25, @env41 ; 07 : Synth N163
	.word @env1
	.byte $20, $10
	.word @n163_inst7_waves
	.byte $00, $00, $00, $00
	.word @env9, @env34, @env1 ; 08 : Bass
	.word @env1
	.byte $60, $10
	.word @n163_inst8_waves
	.byte $00, $00, $00, $00
	.word @env29, @env22, @env1 ; 09 : Jumpy Square
	.word @env39
	.byte $70, $10
	.word @n163_inst9_waves
	.byte $00, $00, $00, $00

@env0:
	.byte $00,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c0,$00,$0d
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $a5,$a8,$7b,$86,$54,$7a,$b9,$95
@env3:
	.byte $07,$c6,$cb,$cd,$cf,$00,$04,$cc,$c8,$c4,$c2,$c0,$c0,$00,$0c
@env4:
	.byte $00,$c8,$c7,$02,$c6,$03,$c5,$02,$c4,$05,$c3,$03,$c2,$03,$c1,$00,$0e
@env5:
	.byte $c1,$c2,$00,$01
@env6:
	.byte $00,$c9,$c8,$c7,$c5,$c3,$c2,$c1,$02,$c0,$00,$09
@env7:
	.byte $b9,$bd,$be,$00,$02
@env8:
	.byte $c2,$c2,$c1,$c1,$c0,$00,$04
@env9:
	.byte $00,$cf,$cf,$ce,$cc,$00,$04
@env10:
	.byte $09,$ca,$ca,$c9,$c8,$c7,$c6,$00,$06,$c3,$c2,$c1,$c0,$00,$0c
@env11:
	.byte $09,$ca,$c9,$c8,$c6,$c5,$c3,$00,$06,$c2,$c1,$c0,$c0,$00,$0c
@env12:
	.byte $df,$7a,$35,$12,$53,$87,$67,$85
@env13:
	.byte $09,$cf,$02,$ce,$ce,$cd,$cc,$00,$06,$c8,$c6,$c4,$c3,$c2,$00,$0d
@env14:
	.byte $53,$96,$a9,$9a,$88,$88,$77,$87
@env15:
	.byte $ad,$b5,$be,$00,$02
@env16:
	.byte $bb,$be,$00,$01
@env17:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env18:
	.byte $00,$cf,$7f,$00,$02
@env19:
	.byte $07,$c6,$cb,$cf,$cf,$00,$04,$ce,$cc,$c9,$c6,$c0,$00,$0b
@env20:
	.byte $00,$c0,$bd,$bc,$be,$c2,$c4,$c3,$00,$01
@env21:
	.byte $c0,$bb,$b7,$b3,$af,$ac,$a6,$00,$06
@env22:
	.byte $c0,$7f,$00,$01
@env23:
	.byte $7b,$71,$7a,$61,$88,$a9,$dc,$ad,$89,$67,$67,$55,$45,$54,$75,$87
@env24:
	.byte $00,$00,$00,$a0,$aa,$aa,$aa,$aa
@env25:
	.byte $bf,$c0,$00,$01
@env26:
	.byte $7f,$00,$00
@env27:
	.byte $68,$66,$aa,$9b,$14,$30,$73,$77
@env28:
	.byte $c2,$7f,$00,$00
@env29:
	.byte $00,$c6,$c5,$c4,$c2,$c1,$00,$05
@env30:
	.byte $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
@env31:
	.byte $5b,$21,$22,$11,$42,$97,$dc,$ee
@env32:
	.byte $00,$00,$00,$00,$ff,$ff,$ff,$ff
@env33:
	.byte $00,$c6,$c3,$c0,$00,$03
@env34:
	.byte $b5,$b4,$00,$01
@env35:
	.byte $00,$cf,$03,$c0,$00,$03
@env36:
	.byte $00,$c8,$7f,$00,$02
@env37:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env38:
	.byte $c0,$bb,$b6,$b1,$ad,$00,$04
@env39:
	.byte $00,$c0,$c1,$00,$02
@env40:
	.byte $00,$c6,$ca,$cd,$cf,$cf,$cc,$c8,$c5,$c1,$c0,$00,$0a
@env41:
	.byte $00,$bb,$bd,$bf,$c0,$00,$04
@env42:
	.byte $00,$c6,$ca,$cd,$cf,$00,$04
@env43:
	.byte $c0,$bd,$bc,$00,$02
@env44:
	.byte $07,$c6,$cb,$cf,$cf,$00,$04,$cc,$c8,$c4,$c2,$c0,$c0,$00,$0c
@env45:
	.byte $00,$c6,$c3,$00,$02
@env46:
	.byte $00,$c0,$be,$be,$bf,$c1,$c2,$c2,$00,$01
@env47:
	.byte $00,$00,$00,$00,$aa,$aa,$aa,$aa
@env48:
	.byte $00,$cf,$06,$c0,$00,$03
@env49:
	.byte $3a,$78,$a6,$9a,$aa,$99,$aa,$99
@env50:
	.byte $08,$c8,$02,$c7,$c6,$c4,$00,$05,$c2,$c1,$c0,$c0,$00,$0b

@n163_inst0_waves:
	.word @env14

@n163_inst1_waves:
	.word @env23

@n163_inst2_waves:
	.word @env49

@n163_inst3_waves:
	.word @env27

@n163_inst4_waves:
	.word @env31

@n163_inst5_waves:
	.word @env2

@n163_inst6_waves:
	.word @env27

@n163_inst7_waves:
	.word @env32

@n163_inst8_waves:
	.word @env12

@n163_inst9_waves:
	.word @env24
	.word @env47

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $79, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $92
@song0ref15:
	.byte $2a, $95, $2a, $89, $45, $89, $28, $89, $45, $89, $25, $89, $45, $89, $28, $95, $2a, $89, $45, $89, $00, $95, $25, $89
	.byte $45, $89
@song0ref41:
	.byte $48, $23
@song0ref43:
	.byte $95, $23
@song0ref45:
	.byte $89, $45, $89, $21, $89, $45, $89, $23, $89, $45, $89, $00, $95, $1e
	.byte $41, $0b
	.word @song0ref45
@song0ref62:
	.byte $48, $25, $95, $25, $89, $45, $89, $23, $89, $45, $89, $21, $89, $45, $89, $23, $95, $25, $89, $45, $89, $00, $95, $1d
	.byte $95, $48, $1e, $89, $45, $89, $00, $89, $1e, $89, $45, $89, $00, $89, $1e, $89, $45, $89, $00, $95, $1c, $95, $1e, $89
	.byte $45, $89, $00, $95, $48
	.byte $41, $2b
	.word @song0ref15
	.byte $41, $0b
	.word @song0ref45
	.byte $41, $32
	.word @song0ref62
	.byte $41, $0e
	.word @song0ref41
	.byte $26
	.byte $41, $0d
	.word @song0ref43
	.byte $48, $21, $95, $1e
	.byte $41, $0d
	.word @song0ref45
	.byte $17, $89, $45, $89, $1a, $95, $1c, $89, $45, $89, $48
@song0ref149:
	.byte $1e, $95, $1e, $89, $45, $89, $1c, $89, $45, $89, $19, $89, $45, $89, $21
@song0ref164:
	.byte $95, $1e, $89, $45, $89, $1c, $89, $45, $89, $1e, $89, $45, $89, $48, $22, $89, $45, $89, $00, $89, $22, $89, $45, $89
	.byte $00, $89, $22, $89, $45, $89, $20
	.byte $41, $0d
	.word @song0ref164
	.byte $41, $0e
	.word @song0ref41
	.byte $26
	.byte $41, $0d
	.word @song0ref43
	.byte $48, $21, $95, $1e
	.byte $41, $0d
	.word @song0ref45
	.byte $17, $89, $45, $89, $1a, $95, $1c, $89, $45, $89, $48, $25, $95, $25, $89, $45, $89, $23, $89, $45, $89, $20, $89, $45
	.byte $89, $28, $95, $25, $89, $45, $89, $23, $89, $45, $89, $25, $89, $45, $89, $48, $25, $89, $45, $89, $00, $89, $25, $89
	.byte $45, $89, $00, $89, $25, $89, $45, $89, $23, $95, $21, $89, $45, $89, $1e, $89, $45, $89, $1c, $89, $45, $89, $48
	.byte $41, $2b
	.word @song0ref15
	.byte $41, $0b
	.word @song0ref45
	.byte $41, $32
	.word @song0ref62
@song0ref292:
	.byte $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $96
@song0ref298:
	.byte $22, $89, $45, $89
@song0ref302:
	.byte $20
@song0ref303:
	.byte $89, $45, $89, $1e, $89, $45, $89, $20, $89, $45, $89, $22, $ad, $1b, $89, $45, $89, $20, $89, $45, $89, $48, $1e, $95
	.byte $1b, $89, $45, $89, $1b, $89, $19, $89, $45, $89, $1b, $89, $49, .lobyte(@env20), .hibyte(@env20), $a3, $45, $ad, $00
	.byte $89, $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $96, $1e, $89, $45, $89, $20, $89, $45, $89, $22, $89, $45, $89
	.byte $20, $89, $45, $89, $1e, $ad, $1b, $89, $45, $89, $22, $89, $45, $83, $23, $24, $81, $48, $25, $95, $22, $89, $45, $89
	.byte $22, $89, $20, $89, $45, $89, $22, $89, $49, .lobyte(@env20), .hibyte(@env20), $a3, $45, $ad, $00, $89
	.byte $41, $5d
	.word @song0ref292
	.byte $41, $12
	.word @song0ref292
	.byte $20, $95, $1e, $95, $48, $1d, $a1, $1e, $a1, $20, $95, $1e, $95, $1d, $95, $1b
@song0ref427:
	.byte $95, $19, $95, $48, $1b, $a1, $1d, $a1, $1e, $95, $1d, $a1, $1b, $a1, $1a, $95, $48, $1b, $89, $49, .lobyte(@env30)
	.byte .hibyte(@env30), $d3, $45, $95, $49, .lobyte(@env1), .hibyte(@env1), $4a, $96, $16, $95, $17
	.byte $41, $17
	.word @song0ref427
	.byte $41, $13
	.word @song0ref427
	.byte $ad, $00, $ad, $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $92, $27, $95, $27, $89, $45, $89, $25, $89, $45, $89
	.byte $22, $89, $45, $89, $25, $95, $27, $89, $45, $89, $00, $95, $22, $89, $45, $89, $48, $20, $95
	.byte $41, $0c
	.word @song0ref302
	.byte $00, $95, $1b
	.byte $41, $0b
	.word @song0ref303
	.byte $48, $22, $95
	.byte $41, $0d
	.word @song0ref298
	.byte $95, $22, $89, $45, $89, $00, $ad, $48, $22, $95
	.byte $41, $0d
	.word @song0ref298
	.byte $95, $22, $89, $45, $89, $00, $ad, $48, $22, $95
	.byte $41, $0d
	.word @song0ref298
	.byte $95, $22, $89, $45, $89, $00, $95, $1a, $95, $48, $1b, $89, $45, $89, $00, $89, $1b, $89, $45, $89, $00, $89, $1b, $89
	.byte $45, $89, $00, $95, $19, $95, $1b, $95, $49, .lobyte(@env37), .hibyte(@env37), $97, $48, $ff, $a7, $45, $95, $44, $00
@song0ch1:
	.byte $79, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $94
	.byte $41, $0e
	.word @song0ref149
@song0ref602:
	.byte $1c, $95, $1e, $89, $45, $89, $00, $95, $19, $89, $45, $89
@song0ref614:
	.byte $17
@song0ref615:
	.byte $95, $17
@song0ref617:
	.byte $89, $45, $89, $15, $89, $45, $89, $17, $89, $45, $89, $00, $95, $12
	.byte $41, $0b
	.word @song0ref617
@song0ref634:
	.byte $19, $95, $19, $89, $45, $89, $17, $89, $45, $89, $15, $89, $45, $89, $17, $95, $19, $89, $45, $89, $00, $95, $11, $95
	.byte $12, $89, $45, $89, $00, $89, $12, $89, $45, $89, $00, $89, $12, $89, $45, $89, $00, $95, $10, $95, $12, $89, $45, $89
	.byte $00, $95
	.byte $41, $0e
	.word @song0ref149
	.byte $41, $1d
	.word @song0ref602
	.byte $41, $0b
	.word @song0ref617
	.byte $41, $32
	.word @song0ref634
	.byte $41, $0e
	.word @song0ref614
	.byte $1a
	.byte $41, $0d
	.word @song0ref615
	.byte $15, $95, $12
	.byte $41, $0d
	.word @song0ref617
	.byte $0b, $89, $45, $89, $0e, $95, $10, $89, $45, $89, $12, $95, $12, $89, $45, $89, $10, $89, $45, $89, $0d, $89, $45, $89
	.byte $15
@song0ref734:
	.byte $95, $12, $89, $45, $89, $10, $89, $45, $89, $12, $89, $45, $89, $16, $89, $45, $89, $00, $89, $16, $89, $45, $89, $00
	.byte $89, $16, $89, $45, $89, $14
	.byte $41, $0d
	.word @song0ref734
	.byte $41, $0e
	.word @song0ref614
	.byte $1a
	.byte $41, $0d
	.word @song0ref615
	.byte $15, $95, $12
	.byte $41, $0d
	.word @song0ref617
	.byte $0b, $89, $45, $89, $0e, $95, $10, $89, $45, $89, $19, $95, $19, $89, $45, $89, $17, $89, $45, $89, $14, $89, $45, $89
	.byte $1c, $95, $19, $89, $45, $89, $17, $89, $45, $89, $19, $89, $45, $89, $19, $89, $45, $89, $00, $89, $19, $89, $45, $89
	.byte $00, $89, $19, $89, $45, $89, $17, $95, $15, $89, $45, $89, $12, $89, $45, $89, $10, $89, $45, $89, $00, $ff, $bd, $ff
	.byte $bf, $ff, $bf, $ff, $bf, $49, .lobyte(@env1), .hibyte(@env1), $4a
@song0ref861:
	.byte $16, $89, $45, $89
@song0ref865:
	.byte $14
@song0ref866:
	.byte $89, $45, $89, $12, $89, $45, $89, $14, $89, $45, $89, $16, $ad, $0f, $89, $45, $89, $14, $89, $45, $89, $12, $95, $0f
	.byte $89, $45, $89, $0f, $89, $0d, $89, $45, $89, $0f, $89, $49, .lobyte(@env20), .hibyte(@env20), $a3, $45, $ad, $00, $89
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a, $94, $12, $89, $45, $89, $14, $89, $45, $89, $16, $89, $45, $89, $14, $89
	.byte $45, $89, $12, $ad, $0f, $89, $45, $89, $16, $89, $45, $83, $17, $18, $81, $19, $95, $16, $89, $45, $89, $16, $89, $14
	.byte $89, $45, $89, $16, $89, $49, .lobyte(@env20), .hibyte(@env20), $a3, $45, $ad, $00, $89, $49, .lobyte(@env1), .hibyte(@env1)
	.byte $4a, $94
	.byte $41, $5d
	.word @song0ref861
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a, $94
	.byte $41, $12
	.word @song0ref861
	.byte $14, $95, $12, $95, $11, $a1, $12, $a1, $14, $95, $12, $95, $11, $95, $0f, $95, $0d, $95, $0f, $a1, $11, $a1, $12, $95
	.byte $11, $a1, $0f, $a1, $0d, $95, $0f, $89, $49, .lobyte(@env30), .hibyte(@env30), $d3, $45, $95, $77, $49, .lobyte(@env1)
	.byte .hibyte(@env1), $4a, $92, $16, $95, $17, $95, $19, $95, $1b, $a1, $1d, $a1, $1e, $95, $1d, $a1, $1b, $a1, $19, $95
	.byte $1b, $89, $49, .lobyte(@env30), .hibyte(@env30), $d3, $45, $95, $79, $49, .lobyte(@env1), .hibyte(@env1), $4a, $92
	.byte $22, $95, $23, $95, $25, $95, $27, $a1, $29, $a1, $2a, $95, $29, $a1, $27, $a1, $26, $95, $27, $89, $49, .lobyte(@env30)
	.byte .hibyte(@env30), $d3, $45, $ad, $00, $ad, $49, .lobyte(@env1), .hibyte(@env1), $4a, $94, $1b, $95, $1b, $89, $45, $89
	.byte $19, $89, $45, $89, $16, $89, $45, $89, $19, $95, $1b, $89, $45, $89, $00, $95, $16, $89, $45, $89, $14, $95
	.byte $41, $0c
	.word @song0ref865
	.byte $00, $95, $0f
	.byte $41, $0c
	.word @song0ref866
	.byte $95
	.byte $41, $0d
	.word @song0ref861
	.byte $95, $16, $89, $45, $89, $00, $ad, $16, $95
	.byte $41, $0d
	.word @song0ref861
	.byte $95, $16, $89, $45, $89, $00, $ad, $16, $95
	.byte $41, $0d
	.word @song0ref861
	.byte $95, $16, $89, $45, $89, $00, $95, $0e, $95, $0f, $89, $45, $89, $00, $89, $0f, $89, $45, $89, $00, $89, $0f, $89, $45
	.byte $89, $00, $95, $0d, $95, $0f, $95, $49, .lobyte(@env37), .hibyte(@env37), $97, $ff, $a7, $45, $95, $44, $00
@song0ch2:
	.byte $84
@song0ref1198:
	.byte $22, $89, $00, $95, $22, $89, $00, $95, $22, $89, $00, $a1, $22, $89, $00, $89, $22, $89, $00, $a1
	.byte $41, $14
	.word @song0ref1198
	.byte $41, $14
	.word @song0ref1198
	.byte $41, $0b
	.word @song0ref1198
	.byte $89
	.byte $41, $0b
	.word @song0ref1198
@song0ref1231:
	.byte $89
@song0ref1232:
	.byte $22, $89, $00
@song0ref1235:
	.byte $a1, $86, $29, $89, $00, $89, $84, $22, $89, $00, $a1, $22, $89, $00, $89, $86, $29, $89, $00, $a1, $84
	.byte $41, $14
	.word @song0ref1232
	.byte $84
	.byte $41, $0e
	.word @song0ref1232
@song0ref1263:
	.byte $86, $29, $83, $29, $83, $29, $89, $29, $89, $00, $89, $29, $89, $84, $22, $89, $00, $95, $22, $89, $86, $29, $89, $00
	.byte $89, $84, $22, $89, $00, $89, $90, $36, $84, $22, $87, $90, $36, $00, $87, $34, $00, $87, $84, $22, $89, $90, $36, $86
	.byte $29, $87, $00, $89, $84, $22, $89, $00
	.byte $41, $15
	.word @song0ref1231
	.byte $84
	.byte $41, $14
	.word @song0ref1232
	.byte $84
	.byte $41, $0e
	.word @song0ref1232
	.byte $41, $2d
	.word @song0ref1263
	.byte $89
@song0ref1334:
	.byte $22, $89, $00, $89, $22, $89, $00, $89, $86, $29, $89, $00, $89, $84, $22, $89, $22, $89, $00, $89, $22, $89, $22, $89
	.byte $00, $89, $86, $29, $89, $00, $a1, $84
	.byte $41, $16
	.word @song0ref1334
	.byte $41, $0f
	.word @song0ref1263
@song0ref1372:
	.byte $a1
@song0ref1373:
	.byte $86, $29, $89, $00, $89, $84, $22, $89, $00, $a1, $86, $29, $89, $00, $89, $84, $22, $89, $22, $89
	.byte $41, $0e
	.word @song0ref1373
@song0ref1396:
	.byte $00, $a1, $86, $29, $89, $00, $89, $84, $22, $89, $22, $89, $86, $29, $89, $00, $89, $84
	.byte $41, $1c
	.word @song0ref1334
	.byte $84
	.byte $41, $16
	.word @song0ref1334
	.byte $41, $0f
	.word @song0ref1263
	.byte $41, $11
	.word @song0ref1372
	.byte $41, $0e
	.word @song0ref1373
	.byte $41, $0e
	.word @song0ref1396
	.byte $84
	.byte $41, $14
	.word @song0ref1232
	.byte $84
	.byte $41, $14
	.word @song0ref1232
	.byte $84
	.byte $41, $0e
	.word @song0ref1232
	.byte $41, $2d
	.word @song0ref1263
	.byte $89
@song0ref1449:
	.byte $22, $89, $00, $a1, $86, $29, $89, $00, $95, $84, $22, $89, $00, $95, $22, $89, $00, $89, $86, $29, $89, $00, $a1, $84
	.byte $41, $14
	.word @song0ref1449
	.byte $84
	.byte $41, $14
	.word @song0ref1449
@song0ref1480:
	.byte $29, $89, $00, $89, $29, $89, $29, $89, $00, $89, $29, $89, $29, $89, $00, $89, $84, $22, $89, $00, $95, $22, $89, $86
	.byte $29, $89, $29, $89, $29, $89, $29, $89, $84
	.byte $41, $14
	.word @song0ref1449
	.byte $84
	.byte $41, $14
	.word @song0ref1449
	.byte $84
	.byte $41, $14
	.word @song0ref1449
	.byte $41, $1e
	.word @song0ref1480
	.byte $84
	.byte $41, $14
	.word @song0ref1449
	.byte $84
	.byte $41, $14
	.word @song0ref1449
	.byte $84
	.byte $41, $14
	.word @song0ref1449
	.byte $41, $1e
	.word @song0ref1480
	.byte $84
	.byte $41, $14
	.word @song0ref1449
	.byte $41, $1e
	.word @song0ref1480
	.byte $84
	.byte $41, $14
	.word @song0ref1449
	.byte $84, $22, $89, $00, $ff, $81, $86, $29, $89, $00, $a1, $84
	.byte $41, $14
	.word @song0ref1232
	.byte $84
	.byte $41, $14
	.word @song0ref1232
	.byte $84
	.byte $41, $0e
	.word @song0ref1232
	.byte $41, $0f
	.word @song0ref1263
	.byte $41, $0b
	.word @song0ref1235
	.byte $41, $0f
	.word @song0ref1263
	.byte $41, $0b
	.word @song0ref1235
	.byte $41, $0c
	.word @song0ref1263
	.byte $29, $89, $00, $95, $29, $89, $00, $95, $29, $89, $00, $89, $90, $33, $84, $22, $87, $90, $33, $00, $87, $31, $00, $87
	.byte $84, $22, $89, $90, $33, $86, $29, $87, $00, $a1, $ff, $bf, $44, $00
@song0ch3:
	.byte $7a, $82
@song0ref1632:
	.byte $28, $89, $00, $95, $28, $89, $00, $95, $28, $89, $00, $a1, $28, $89, $00, $89, $28, $89, $00, $a1
	.byte $41, $14
	.word @song0ref1632
	.byte $41, $14
	.word @song0ref1632
	.byte $28, $89, $00, $95, $28, $89, $00, $95, $28, $83, $88, $31, $83, $31, $83, $31, $83, $31, $89, $31, $95, $31, $95, $31
	.byte $89, $31, $95
@song0ref1685:
	.byte $82, $27, $89, $80, $33, $89, $31, $89, $33, $89
@song0ref1695:
	.byte $8a, $31
@song0ref1697:
	.byte $95, $82, $27, $89, $80, $33, $89, $31, $89, $33, $89, $82, $27, $89, $80, $33, $89, $8a, $31, $95, $80, $31, $89, $33
	.byte $89
	.byte $41, $1c
	.word @song0ref1685
	.byte $41, $14
	.word @song0ref1685
@song0ref1728:
	.byte $88, $31, $83, $31, $83, $31, $89, $31, $95, $31
@song0ref1738:
	.byte $89, $82, $27, $89, $80, $33, $89, $33, $89, $82, $27, $89, $8a, $31, $95, $82, $27, $89, $80, $33
	.byte $41, $0e
	.word @song0ref1738
	.byte $89
	.byte $41, $1c
	.word @song0ref1685
	.byte $41, $1c
	.word @song0ref1685
	.byte $41, $14
	.word @song0ref1685
	.byte $41, $16
	.word @song0ref1728
	.byte $88, $31, $83, $31, $83, $31, $89, $31, $95, $31, $89, $8a, $31, $89, $88, $31, $89, $31, $95, $8c, $30
@song0ref1795:
	.byte $9b
@song0ref1796:
	.byte $8e, $32, $8f, $88, $31, $95, $82, $27, $83, $8e, $32, $83, $82, $27, $89, $80, $31, $89, $82, $27, $83, $00, $83, $27
	.byte $83, $8e, $32, $8f, $88, $31, $95, $8e, $32, $95, $82, $27, $89, $00, $89, $27, $83
	.byte $41, $13
	.word @song0ref1796
@song0ref1840:
	.byte $83, $88, $31, $83, $31, $83, $31, $89, $31, $95, $31, $89, $8c, $30, $95, $80, $31, $89, $33
@song0ref1859:
	.byte $89, $8a, $31, $89, $80, $33, $89, $82, $27, $89, $80, $33, $89, $31, $89, $33, $89, $8a, $31, $89, $80, $33, $89, $82
	.byte $27, $89, $27, $89, $8a, $31, $89, $80, $33, $89, $8c, $30, $a1, $30
	.byte $41, $1a
	.word @song0ref1859
	.byte $41, $1f
	.word @song0ref1795
	.byte $41, $13
	.word @song0ref1796
	.byte $41, $2c
	.word @song0ref1840
	.byte $89, $8a, $31, $89, $80, $33, $89, $82, $27, $89, $80, $33, $89, $8c, $30, $95, $8a, $31, $89, $8c, $30, $95, $82, $27
	.byte $41, $0e
	.word @song0ref1859
	.byte $41, $13
	.word @song0ref1697
	.byte $41, $1c
	.word @song0ref1685
	.byte $41, $14
	.word @song0ref1685
	.byte $41, $17
	.word @song0ref1728
	.byte $41, $0e
	.word @song0ref1738
@song0ref1951:
	.byte $89, $8c, $31, $ad, $88, $31, $95, $80, $31, $89, $82, $27, $89, $80, $31, $89, $33, $89, $82, $27, $89, $80, $33, $89
	.byte $88, $31, $95, $80, $31, $89, $33
	.byte $41, $16
	.word @song0ref1951
	.byte $41, $0f
	.word @song0ref1951
@song0ref1988:
	.byte $88, $31, $83, $31, $83, $31, $89, $31, $89, $80, $31, $89, $33, $89, $88, $31, $95, $31, $89, $31, $95, $31, $89, $31
	.byte $95, $82, $27, $89, $00, $95, $27, $89, $88, $31, $89, $31, $89, $31, $89, $31
	.byte $41, $16
	.word @song0ref1951
	.byte $41, $16
	.word @song0ref1951
	.byte $41, $0f
	.word @song0ref1951
	.byte $41, $23
	.word @song0ref1988
	.byte $41, $16
	.word @song0ref1951
	.byte $41, $16
	.word @song0ref1951
	.byte $41, $0f
	.word @song0ref1951
	.byte $41, $23
	.word @song0ref1988
	.byte $41, $0f
	.word @song0ref1951
	.byte $41, $23
	.word @song0ref1988
	.byte $41, $0f
	.word @song0ref1951
	.byte $41, $0c
	.word @song0ref1988
	.byte $82, $27, $89, $00, $89, $80, $33, $89, $33, $89, $30, $89, $00, $89, $33, $89, $33, $89, $30, $89, $00, $89, $33, $89
	.byte $33, $89, $88, $31, $ad
	.byte $41, $1c
	.word @song0ref1685
	.byte $41, $1c
	.word @song0ref1685
	.byte $8c, $31, $ad
	.byte $41, $0c
	.word @song0ref1695
@song0ref2105:
	.byte $88, $31, $83, $31, $83, $31, $89, $31, $95, $31, $89, $8c, $31, $ad
	.byte $41, $0c
	.word @song0ref1695
	.byte $41, $0c
	.word @song0ref2105
	.byte $41, $0c
	.word @song0ref1695
	.byte $88, $31, $83, $31, $83, $31, $89, $31, $95, $31, $89, $31, $a1, $31, $a1, $31, $95, $82, $27, $89, $80, $33, $89, $31
	.byte $89, $82, $27, $89, $8c, $31, $ad, $df, $00, $dd, $44, $00
@song0ch4:
@song0ref2165:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $0c
	.word @song0ref2165
	.byte $41, $0c
	.word @song0ref2165
	.byte $41, $0c
	.word @song0ref2165
	.byte $41, $0c
	.word @song0ref2165
	.byte $41, $0c
	.word @song0ref2165
	.byte $41, $0c
	.word @song0ref2165
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $44, $00
@song0ch5:
	.byte $84
@song0ref2209:
	.byte $12, $89, $5a, $89, $00, $89, $12, $89, $5a, $89, $00, $89, $12, $89, $5a, $89
@song0ref2225:
	.byte $12, $89, $5a, $89, $10
@song0ref2230:
	.byte $95
@song0ref2231:
	.byte $12, $89, $5a, $89, $00, $95, $12, $89, $5a, $89, $00, $89, $10, $a1, $12, $89, $15, $83, $17, $83, $18, $89, $5a, $89
	.byte $17, $89, $5a, $89, $15, $89, $12, $89, $10, $95
	.byte $41, $1b
	.word @song0ref2209
	.byte $83, $15, $83, $17, $83, $18, $83
@song0ref2275:
	.byte $19, $89, $5a, $89, $00
@song0ref2280:
	.byte $89, $19, $89, $5a, $89, $00, $89, $19, $89, $5a, $89, $00, $95, $19, $89, $5a, $89, $19, $89, $49, .lobyte(@env37)
	.byte .hibyte(@env37), $a3, $7b, $49, .lobyte(@env1), .hibyte(@env1), $4a, $86
@song0ref2309:
	.byte $12, $95, $00, $95, $0d
@song0ref2314:
	.byte $95, $00, $95, $12, $95, $00, $95, $0d, $95, $00, $95, $0b, $95, $00, $95, $12, $95, $00, $95, $0b
	.byte $41, $0b
	.word @song0ref2314
@song0ref2337:
	.byte $08, $95, $00, $95, $0d, $95, $00, $95, $08, $95, $00, $95, $12, $95, $00, $89, $12, $95, $00, $89, $12, $95, $12, $95
	.byte $00, $89, $12, $95, $00, $89, $12, $95, $49, .lobyte(@env1), .hibyte(@env1), $4a
	.byte $41, $19
	.word @song0ref2309
	.byte $41, $0b
	.word @song0ref2314
	.byte $41, $20
	.word @song0ref2337
	.byte $17, $95, $00, $89, $17, $95, $00, $89, $17
@song0ref2391:
	.byte $95, $17, $95, $00, $89, $17, $95, $00, $89, $17, $95, $15, $95, $00, $89, $15, $95, $00, $89, $15, $95, $15, $95, $00
	.byte $89, $15, $95, $00, $89, $15
@song0ref2421:
	.byte $95, $06, $95, $00, $95, $0d, $95, $00, $95, $06, $95, $00, $95, $0d, $95, $00
	.byte $41, $10
	.word @song0ref2421
	.byte $95, $0b, $95, $00, $89, $0b, $95, $00, $89, $0b, $95, $0b, $95, $00, $89, $0b, $95, $00, $89, $0b
	.byte $41, $0b
	.word @song0ref2391
	.byte $17, $95, $00, $89, $17, $95, $00, $89, $17, $95, $0d, $95, $00, $95
	.byte $41, $0c
	.word @song0ref2337
	.byte $0d, $95, $00, $95
	.byte $41, $0c
	.word @song0ref2337
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a
	.byte $41, $19
	.word @song0ref2309
	.byte $41, $0b
	.word @song0ref2314
	.byte $41, $20
	.word @song0ref2337
	.byte $0f, $95, $00, $89, $0f, $95, $00, $89, $0f
@song0ref2509:
	.byte $95
@song0ref2510:
	.byte $0f, $95, $00, $89, $0f, $95, $00, $89, $0f, $95, $14
@song0ref2521:
	.byte $95, $00, $95, $0f, $95, $00, $95, $14, $95, $00, $95, $0f, $95, $00, $95, $08
	.byte $41, $0f
	.word @song0ref2521
@song0ref2540:
	.byte $16, $95, $00, $89, $16, $95, $00, $89, $16, $95, $0a, $95, $00, $89, $0a, $95, $00, $89, $0a
	.byte $41, $0b
	.word @song0ref2509
	.byte $41, $1b
	.word @song0ref2510
	.byte $41, $0f
	.word @song0ref2521
	.byte $41, $13
	.word @song0ref2540
	.byte $41, $0b
	.word @song0ref2509
	.byte $41, $1b
	.word @song0ref2510
	.byte $95, $00, $95, $0f, $95, $00, $95, $16, $95, $00, $95, $0f, $95, $00
	.byte $41, $0b
	.word @song0ref2509
	.byte $0f, $95, $00
@song0ref2597:
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a, $8e, $0a, $95, $0b, $95, $0d, $93, $81, $0f, $a1, $11, $a1, $12, $95, $11
	.byte $a1, $0f, $a1, $0e, $93, $81, $0f, $89, $49, .lobyte(@env30), .hibyte(@env30), $d3, $5a, $95
	.byte $41, $19
	.word @song0ref2597
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a, $97, $00, $ab, $49, .lobyte(@env1), .hibyte(@env1), $4a, $86, $0f, $95, $00
	.byte $95, $0a
@song0ref2650:
	.byte $95, $00, $95, $0f, $95, $00, $95, $0a, $95, $00, $95, $08, $95, $00, $95, $0f, $95, $00, $95, $08
	.byte $41, $0b
	.word @song0ref2650
@song0ref2673:
	.byte $05, $95, $00, $95, $0a, $95, $00, $95, $05, $95, $00, $95, $0a, $95, $00, $95
	.byte $41, $10
	.word @song0ref2673
	.byte $41, $0c
	.word @song0ref2673
	.byte $0f, $95, $00, $89, $0f, $95, $00, $89, $0f, $95, $00, $95, $0d, $95, $8c, $0f, $95, $49, .lobyte(@env46), .hibyte(@env46)
	.byte $97, $ff, $a7, $00, $95, $44, $00
@song0ch6:
	.byte $7b, $82
@song0ref2725:
	.byte $1e, $89, $5a, $89, $00, $89, $1e, $89, $5a, $89, $00, $89, $1e, $89, $5a, $89, $00, $95, $1c, $95, $1e, $89, $5a, $89
	.byte $00, $95
	.byte $41, $1a
	.word @song0ref2725
	.byte $41, $1a
	.word @song0ref2725
	.byte $25, $89, $5a, $89, $00, $89, $25, $89, $5a, $89, $00, $89, $25, $89, $5a, $89, $00, $95, $25, $89, $5a, $89, $25, $ad
@song0ref2781:
	.byte $00, $ff, $bd, $ff, $bf, $ff, $bf, $86
@song0ref2789:
	.byte $06, $95, $00, $89, $06, $95, $00, $89, $06, $95, $06, $95, $00, $89, $06, $95, $00, $89, $06, $95, $00, $ff, $bd, $ff
	.byte $bf, $ff, $bf
	.byte $41, $14
	.word @song0ref2789
@song0ref2819:
	.byte $82, $0b, $95, $80, $0f, $89, $5a, $89, $82, $12, $95, $80, $0f, $89, $5a, $89
	.byte $41, $0c
	.word @song0ref2819
	.byte $41, $0c
	.word @song0ref2819
	.byte $41, $0c
	.word @song0ref2819
@song0ref2844:
	.byte $82, $06, $95, $80, $0d, $89, $5a, $89, $82, $0d, $95, $80, $0d, $89, $5a, $89
	.byte $41, $0c
	.word @song0ref2844
	.byte $41, $0c
	.word @song0ref2844
	.byte $82, $06, $95, $80, $0d, $89, $5a, $89, $82, $10, $95, $80, $0d, $89, $5a, $89
	.byte $41, $0c
	.word @song0ref2819
	.byte $41, $0c
	.word @song0ref2819
	.byte $41, $0c
	.word @song0ref2819
	.byte $41, $0c
	.word @song0ref2819
@song0ref2894:
	.byte $82, $0d, $95, $80, $11, $89, $5a, $89, $82, $14, $95, $80, $11, $89, $5a, $89
	.byte $41, $0c
	.word @song0ref2894
	.byte $41, $0c
	.word @song0ref2894
	.byte $41, $0c
	.word @song0ref2894
	.byte $41, $1b
	.word @song0ref2781
	.byte $76, $84
@song0ref2924:
	.byte $1b, $ff, $bd, $1b, $ff, $bd, $1e, $ff, $bd, $1d, $ff, $bd
	.byte $41, $0c
	.word @song0ref2924
	.byte $1b, $ff, $bd, $1d, $ff, $bd, $1e, $dd, $1d, $dd, $1e, $ff, $bd, $1e, $dd, $1d, $dd, $1e, $ff, $bd, $7b, $86, $08, $ad
	.byte $0f, $ad, $16, $ad, $0a, $ad, $0f, $ad, $0f, $ad, $0f, $ad, $00, $ad, $ff, $bf, $ff, $bf, $51, $ff, $60, $82, $16, $ff
	.byte $bd, $7b, $51, $ff, $60, $16, $ff, $bd, $7b, $51, $ff, $60, $16, $ff, $bd, $7b, $1b, $95, $5a, $89, $1b, $95, $5a, $89
	.byte $1b, $95, $5a, $95, $19, $95, $1b, $ad, $ff, $a7, $5a, $95, $44, $00
@song0ch7:
	.byte $7b, $80
	.byte $41, $10
	.word @song0ref2209
	.byte $00, $95, $10, $95, $12, $89, $5a, $89, $15, $95
	.byte $41, $0b
	.word @song0ref2209
	.byte $a1
	.byte $41, $12
	.word @song0ref2225
	.byte $41, $0b
	.word @song0ref2209
	.byte $95, $10, $95, $12, $89, $5a, $89, $15, $95
	.byte $41, $12
	.word @song0ref2275
	.byte $1c, $89, $5a, $89, $1c, $ad, $00, $95
@song0ref3071:
	.byte $88
@song0ref3072:
	.byte $19, $89, $00, $a1, $19
@song0ref3077:
	.byte $89, $00, $a1, $19, $89, $00, $a1, $19, $89, $00, $89, $97, $1b, $89, $00, $a1, $1b, $89, $00, $a1, $1b, $89, $00, $a1
	.byte $1b, $89, $00, $89
@song0ref3105:
	.byte $97, $1d, $89, $00, $a1, $1d, $89, $00, $a1, $1d, $89, $00, $a1, $1d, $89, $00, $89, $1e, $89, $00, $95, $1e, $89, $00
	.byte $95, $1e, $89, $00, $a1, $1c, $95, $1e, $89, $00, $a1, $00, $95
	.byte $41, $46
	.word @song0ref3072
	.byte $80
@song0ref3146:
	.byte $0b, $89, $5a, $89, $00, $95, $0b, $89, $5a, $89, $00, $95
	.byte $41, $0c
	.word @song0ref3146
	.byte $41, $0c
	.word @song0ref3146
	.byte $41, $0c
	.word @song0ref3146
@song0ref3167:
	.byte $0a
@song0ref3168:
	.byte $89, $5a, $89, $00, $95, $0a, $89, $5a, $89, $00, $95
	.byte $41, $0c
	.word @song0ref3167
	.byte $41, $0c
	.word @song0ref3167
	.byte $41, $0c
	.word @song0ref3167
	.byte $41, $0c
	.word @song0ref3146
	.byte $41, $0c
	.word @song0ref3146
	.byte $41, $0c
	.word @song0ref3146
	.byte $41, $0c
	.word @song0ref3146
@song0ref3200:
	.byte $0d, $89, $5a, $89, $00, $95, $0d, $89, $5a, $89, $00, $95
	.byte $41, $0c
	.word @song0ref3200
	.byte $41, $0c
	.word @song0ref3200
	.byte $41, $0c
	.word @song0ref3200
	.byte $41, $44
	.word @song0ref3071
	.byte $76, $84
@song0ref3226:
	.byte $16, $ff, $bd, $17, $ff, $bd, $17, $dd, $1b, $dd, $1a, $ff, $bd
	.byte $41, $0d
	.word @song0ref3226
	.byte $16, $ff, $bd, $1b, $ff, $bd, $17, $dd, $1a, $dd, $1b, $ff, $bd, $17, $dd, $1a, $dd, $1b, $ff, $bd, $7b, $86, $40, $08
	.byte $ad, $03, $ad, $0a, $ad, $40, $0a, $ad, $03, $ad, $03, $ad, $03, $ad, $00, $ad, $ff, $bf, $ff, $bf, $ff, $bf, $80
@song0ref3289:
	.byte $16, $95, $16, $89, $5a, $89, $14, $89, $5a, $89, $12, $89, $5a, $89, $14, $95, $16, $89, $5a, $89, $00, $ad
	.byte $41, $16
	.word @song0ref3289
@song0ref3314:
	.byte $1b, $89, $5a, $89, $00, $89, $1b, $89, $5a, $89, $00, $89, $1b, $89, $5a, $89, $00, $95, $19, $95, $1b, $ad, $ff, $a7
	.byte $5a, $95, $44, $00
@song0ch8:
	.byte $7b, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $00, $95
@song0ref3354:
	.byte $88
@song0ref3355:
	.byte $16, $89, $00, $a1, $16, $89, $00, $a1, $15, $89, $00, $a1, $15
@song0ref3368:
	.byte $89, $00, $89, $97, $17, $89, $00, $a1, $17, $89, $00, $a1, $16, $89, $00, $a1, $16, $89, $00, $89, $97, $19, $89, $00
	.byte $a1, $19, $89, $00, $a1, $18, $89, $00, $a1, $18, $89, $00, $89, $19, $89, $00, $95, $19, $89, $00, $95, $19, $89, $00
	.byte $a1, $17, $95, $19, $89, $00, $a1, $00, $95
	.byte $41, $46
	.word @song0ref3355
	.byte $84
@song0ref3429:
	.byte $17, $89, $5a, $89, $00, $95, $17, $89, $5a, $89, $00, $95
	.byte $41, $0c
	.word @song0ref3429
@song0ref3444:
	.byte $15, $89, $5a, $89, $00, $95, $15, $89, $5a, $89, $00, $95
	.byte $41, $0c
	.word @song0ref3444
@song0ref3459:
	.byte $16, $89, $5a, $89, $00, $95, $16, $89, $5a, $89, $00, $95
	.byte $41, $0c
	.word @song0ref3459
	.byte $41, $0c
	.word @song0ref3459
	.byte $41, $0c
	.word @song0ref3459
	.byte $41, $0c
	.word @song0ref3429
	.byte $41, $0c
	.word @song0ref3429
	.byte $41, $0c
	.word @song0ref3444
	.byte $41, $0c
	.word @song0ref3444
@song0ref3492:
	.byte $19, $89, $5a, $89, $00, $95, $19, $89, $5a, $89, $00, $95
	.byte $41, $0c
	.word @song0ref3492
	.byte $41, $0c
	.word @song0ref3492
	.byte $41, $0c
	.word @song0ref3429
	.byte $41, $44
	.word @song0ref3354
	.byte $76, $84
@song0ref3518:
	.byte $12, $ff, $bd, $12, $ff, $bd, $14, $dd, $15, $dd, $17, $dd, $16, $dd
	.byte $41, $0e
	.word @song0ref3518
	.byte $12, $ff, $bd, $14, $ff, $bd, $14, $dd, $16, $dd, $16, $ff, $bd, $14, $dd, $16, $dd, $16, $ff, $bd, $00, $ff, $bd, $ff
	.byte $bf, $7b, $49, .lobyte(@env1), .hibyte(@env1), $4a, $8a, $0f
	.byte $41, $0b
	.word @song0ref3168
	.byte $0f
	.byte $41, $0b
	.word @song0ref3168
@song0ref3574:
	.byte $08, $89, $5a, $89, $00, $95, $0f, $89, $5a, $89, $00, $95
	.byte $41, $0c
	.word @song0ref3574
	.byte $0a, $89, $5a, $89, $00, $95, $05
	.byte $41, $0b
	.word @song0ref3168
	.byte $05, $89, $5a, $89, $00, $95, $51, $ff, $60, $80, $1a, $ff, $bd, $7b, $51, $ff, $60, $1a, $ff, $bd, $7b, $00, $dd, $97
	.byte $14, $95, $16, $ad, $ff, $a7, $5a, $95, $44, $00
@song0ch9:
	.byte $7b
	.byte $41, $0c
	.word @song0ref2165
@song0ref3638:
	.byte $ff, $bf, $82
@song0ref3641:
	.byte $06, $89, $5a, $89, $00, $89, $06, $89, $5a, $89, $00, $89, $06, $89, $5a, $89, $00, $95, $04, $95, $06
@song0ref3662:
	.byte $89, $5a, $89, $00, $95, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $1a
	.word @song0ref3641
	.byte $00, $95, $84
	.byte $41, $0b
	.word @song0ref2231
	.byte $41, $0c
	.word @song0ref2230
	.byte $41, $0c
	.word @song0ref2230
	.byte $41, $0c
	.word @song0ref2230
	.byte $41, $0c
	.word @song0ref2230
	.byte $41, $0c
	.word @song0ref2230
	.byte $41, $0c
	.word @song0ref2230
	.byte $95, $10, $89, $5a, $89, $00, $95, $10, $89, $5a, $89, $00
	.byte $41, $0c
	.word @song0ref2230
	.byte $41, $0c
	.word @song0ref2230
	.byte $41, $0c
	.word @song0ref2230
	.byte $41, $0c
	.word @song0ref2230
@song0ref3724:
	.byte $95, $14, $89, $5a, $89, $00, $95, $14, $89, $5a, $89, $00
	.byte $41, $0c
	.word @song0ref3724
	.byte $41, $0c
	.word @song0ref3724
	.byte $41, $0c
	.word @song0ref3724
	.byte $ff, $bd, $ff, $bf
	.byte $41, $1c
	.word @song0ref3638
	.byte $7c, $5a, $89, $00, $9b, $8a
@song0ref3758:
	.byte $0d, $0e, $81, $0f, $95, $0d, $89, $5a, $83, $0f
@song0ref3768:
	.byte $11, $81, $12, $89, $0f, $89, $5a, $89, $0d, $a1
@song0ref3778:
	.byte $0f, $89, $5a, $89, $00, $a7, $0d, $0e, $81, $0f, $95, $0d, $89, $5a, $83, $0f, $12, $81, $15, $89, $14, $89, $5a, $89
	.byte $12, $89, $5a, $89, $0f, $89, $5a, $89, $00, $89, $5a, $89, $00, $9b
	.byte $41, $1a
	.word @song0ref3758
@song0ref3819:
	.byte $17, $18, $81, $19, $95, $16
@song0ref3825:
	.byte $89, $5a, $83, $11, $13, $81, $14, $89, $12, $89, $5a, $89, $0f, $95, $0d, $89, $0a, $95, $5a, $89, $00, $9b
	.byte $41, $3a
	.word @song0ref3758
	.byte $41, $1a
	.word @song0ref3758
	.byte $41, $1c
	.word @song0ref3819
	.byte $41, $23
	.word @song0ref3758
	.byte $12, $14, $81, $17, $89, $16, $89, $5a, $89, $14, $89, $5a, $89, $12, $89
	.byte $41, $10
	.word @song0ref3778
	.byte $41, $10
	.word @song0ref3768
	.byte $41, $17
	.word @song0ref3819
	.byte $89, $5a, $83
@song0ref3886:
	.byte $17, $19, $81, $1b, $95, $19, $89, $5a, $83, $12, $14, $81, $16, $95, $19
	.byte $41, $11
	.word @song0ref3825
	.byte $89, $5a, $83, $0b, $0c, $81, $0d, $95, $0f, $95, $12, $89, $5a, $89, $0f, $89, $5a, $83, $16, $17, $81, $19, $89, $1b
	.byte $89, $5a, $89, $16, $89, $5a, $89, $12, $9b
	.byte $41, $0f
	.word @song0ref3886
	.byte $41, $11
	.word @song0ref3825
	.byte $89, $5a, $89, $00, $ff, $bd, $97, $88, $1b, $89, $00, $a1, $1b
	.byte $41, $2d
	.word @song0ref3077
	.byte $41, $10
	.word @song0ref3105
	.byte $83, $84, $12, $14, $81
	.byte $41, $16
	.word @song0ref3289
	.byte $22, $89, $5a, $89, $00, $89, $22, $89, $5a, $89, $00, $89, $22, $89, $5a, $89, $00, $95, $25, $95, $27, $ad, $ff, $a7
	.byte $5a, $95, $44, $00
@song0ch10:
	.byte $7b
	.byte $41, $0c
	.word @song0ref2165
	.byte $ff, $bf, $80
	.byte $41, $10
	.word @song0ref2209
	.byte $00, $95, $10, $95, $12
	.byte $41, $0b
	.word @song0ref3662
	.byte $41, $10
	.word @song0ref2209
	.byte $00, $95, $10, $95, $12, $89, $5a, $89, $00, $95, $8a
@song0ref4031:
	.byte $17
@song0ref4032:
	.byte $95, $17
@song0ref4034:
	.byte $89, $5a, $89, $15, $89, $5a, $89, $17, $89, $5a, $89, $1a
	.byte $41, $0d
	.word @song0ref4032
	.byte $15, $95, $12
	.byte $41, $0b
	.word @song0ref4034
@song0ref4055:
	.byte $00, $95, $0b, $89, $5a, $89, $0e, $95, $10, $89, $5a, $89, $12, $95, $12, $89, $5a, $89, $10, $89, $5a, $89, $0d, $89
	.byte $5a, $89, $15
@song0ref4082:
	.byte $95, $12, $89, $5a, $89, $10, $89, $5a, $89, $12, $89, $5a, $89, $16, $89, $5a, $89, $00, $89, $16, $89, $5a, $89, $00
	.byte $89, $16, $89, $5a, $89, $14
	.byte $41, $0d
	.word @song0ref4082
	.byte $41, $0f
	.word @song0ref4031
	.byte $41, $0d
	.word @song0ref4032
	.byte $15, $95, $12
	.byte $41, $0b
	.word @song0ref4034
	.byte $41, $0c
	.word @song0ref4055
	.byte $19, $95, $19, $89, $5a, $89, $17, $89, $5a, $89, $14, $89, $5a, $89, $1c, $95, $19, $89, $5a, $89, $17, $89, $5a, $89
	.byte $19, $89, $5a
	.byte $41, $0c
	.word @song0ref2280
	.byte $89, $19, $89, $5a, $89, $17, $95, $15, $89, $5a, $89, $12, $89, $5a, $89, $10, $89, $5a, $89, $00, $ff, $bd, $ff, $bf
	.byte $ff, $bf, $80
	.byte $41, $10
	.word @song0ref2209
	.byte $00, $95, $10, $95, $12, $89, $5a, $89, $00, $95, $79, $82
@song0ref4202:
	.byte $0f, $ff, $bd, $17, $ff, $bd, $14, $dd, $15, $dd, $16, $dd, $22, $dd
	.byte $41, $0e
	.word @song0ref4202
	.byte $0f, $ff, $bd, $14, $ff, $bd, $17, $dd, $16, $dd, $0f, $ff, $bd, $17, $dd, $16, $dd, $0f, $ff, $bd, $17, $dd, $16, $dd
	.byte $0f, $dd, $5a, $dd, $00, $95, $88, $16, $89, $00, $a1, $16, $89, $00, $a1, $14, $89, $00, $a1, $14, $89, $00, $89, $97
	.byte $18, $89, $00, $a1, $18, $89, $00, $a1, $12, $89, $00, $a1, $12
	.byte $41, $0c
	.word @song0ref3368
	.byte $12, $89, $00, $a1, $12
	.byte $41, $0c
	.word @song0ref3368
	.byte $12, $89, $00, $a1, $12, $89, $00, $89, $7b, $51, $ff, $60, $84, $20, $ff, $bd, $7c
	.byte $41, $12
	.word @song0ref3314
	.byte $20, $95, $22, $ad, $ff, $a7, $5a, $95, $44, $00
@song0ch11:
	.byte $7b, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $90
@song0ref4332:
	.byte $12, $95, $12, $95, $10, $89, $00, $89, $12, $89, $00, $a1, $12, $89, $00, $89, $10, $89, $00, $89, $12, $89, $00
@song0ref4355:
	.byte $89, $0a, $95
@song0ref4358:
	.byte $0a, $89, $00, $89, $08, $89, $00, $89, $0a, $89, $00, $a1
	.byte $41, $0b
	.word @song0ref4358
@song0ref4373:
	.byte $89, $0d, $95
@song0ref4376:
	.byte $0d, $89, $00, $89, $0b, $89, $00, $89, $0d, $89, $00, $a1
	.byte $41, $0b
	.word @song0ref4376
@song0ref4391:
	.byte $89, $12, $89, $00, $89, $06, $89, $12, $89, $00, $89, $06, $89, $12, $89, $00, $89, $12, $89, $00, $89, $10, $95, $12
	.byte $89, $00, $a1
	.byte $41, $26
	.word @song0ref4332
	.byte $41, $0b
	.word @song0ref4358
	.byte $41, $0f
	.word @song0ref4373
	.byte $41, $0b
	.word @song0ref4376
	.byte $41, $1b
	.word @song0ref4391
@song0ref4433:
	.byte $0b, $89, $00, $89, $0f, $89, $00, $89, $12, $89, $00, $89, $14, $89, $00, $85, $12, $81, $15, $89, $14, $89, $00, $89
	.byte $12, $89, $00, $89, $0e, $89, $0f, $95
	.byte $41, $20
	.word @song0ref4433
@song0ref4468:
	.byte $06, $89, $00, $95, $0a, $89, $00, $95, $0d, $89, $00, $89
	.byte $41, $0c
	.word @song0ref4468
	.byte $41, $0c
	.word @song0ref4468
	.byte $41, $0c
	.word @song0ref4468
	.byte $41, $20
	.word @song0ref4433
	.byte $41, $20
	.word @song0ref4433
@song0ref4495:
	.byte $0d, $89, $00, $95, $11, $89, $00, $95, $14, $89, $00, $89
	.byte $41, $0c
	.word @song0ref4495
	.byte $41, $0c
	.word @song0ref4495
	.byte $19, $89, $00, $89, $17, $89, $00, $89, $16, $89, $00, $89, $14, $89, $00, $89
	.byte $41, $26
	.word @song0ref4332
	.byte $41, $0b
	.word @song0ref4358
	.byte $41, $0f
	.word @song0ref4373
	.byte $41, $0b
	.word @song0ref4376
	.byte $41, $18
	.word @song0ref4391
	.byte $8d, $11, $8d, $10, $8d
@song0ref4549:
	.byte $0f, $89, $00, $95, $0f, $89, $00
@song0ref4556:
	.byte $95, $0f, $89, $00, $89, $0d, $95, $0f, $89, $00, $89, $0f, $95, $1b, $95, $0d, $89, $00, $95, $0d, $89, $00, $95, $0d
	.byte $89, $00, $89, $0b, $95, $0d, $89, $00, $89, $0d, $95, $19, $95, $08, $89, $00, $95, $08, $89, $00, $95, $08, $89, $00
	.byte $89, $0d, $95, $08, $89, $00, $89, $08, $95, $14, $95, $0a, $89, $00, $95, $0a, $89, $00, $95, $0a, $89, $00, $89, $0d
	.byte $95, $0a, $89, $00, $89, $08, $95, $0a, $95
	.byte $41, $58
	.word @song0ref4549
	.byte $41, $16
	.word @song0ref4549
	.byte $11, $89, $00, $95, $11, $89, $00, $95, $11, $89, $00, $89, $0f, $95, $11, $89, $00, $89, $11, $95, $1d, $95
@song0ref4665:
	.byte $0b, $89, $00, $95, $0b, $89, $00, $95, $0b, $89, $00, $89, $0a, $95, $0b, $89, $00, $89, $0a, $95, $16, $95
	.byte $41, $0b
	.word @song0ref4549
	.byte $83, $10, $11, $81, $12
	.byte $41, $0b
	.word @song0ref4556
	.byte $41, $16
	.word @song0ref4665
	.byte $41, $0b
	.word @song0ref4549
	.byte $83, $10, $11, $81, $12
	.byte $41, $0b
	.word @song0ref4556
	.byte $41, $16
	.word @song0ref4665
	.byte $00, $ff, $bd, $0f, $95, $0f, $95, $0d, $89, $00, $89, $0f, $89, $00, $a1, $0f, $89, $00, $89, $0d, $89, $00, $89, $0f
	.byte $89, $00, $89, $08, $95
@song0ref4744:
	.byte $08, $89, $00, $89, $06, $89, $00, $89, $08, $89, $00, $a1
	.byte $41, $0b
	.word @song0ref4744
	.byte $41, $0f
	.word @song0ref4355
	.byte $41, $0b
	.word @song0ref4358
	.byte $41, $0f
	.word @song0ref4355
	.byte $41, $0b
	.word @song0ref4358
	.byte $41, $0f
	.word @song0ref4355
	.byte $41, $0b
	.word @song0ref4358
	.byte $89, $86, $03, $95, $00, $89, $03, $95, $00, $89, $03, $95, $00, $95, $01, $95, $8c, $03, $95, $49, .lobyte(@env46)
	.byte .hibyte(@env46), $97, $ff, $a7, $00, $95, $44, $00
@song0ch12:
	.byte $7b, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $92
@song0ref4817:
	.byte $1e, $89, $2a, $89, $1e, $89, $2a, $89, $2a, $89, $12, $89, $1e, $89, $12, $89, $1e, $89, $2a, $89, $2a, $89, $1e, $89
	.byte $2a, $89, $2a, $89, $1e, $89, $12, $89, $17, $89, $0b, $89, $17, $89, $17, $89, $17, $89, $0b, $89, $0b, $89, $0b, $89
	.byte $17, $89, $23, $89, $23, $89, $23, $89, $17, $89, $23, $89, $23, $89, $17, $89, $0d, $89, $25, $89, $19, $89, $0d, $89
	.byte $19, $89, $25, $89, $25, $89, $0d, $89, $25, $89, $0d, $89, $25, $89, $25, $89, $19, $89, $0d, $89, $19, $89, $0d, $89
	.byte $12, $89, $1e, $89, $1e, $89, $1e, $89, $1e, $89, $06, $89, $12, $89, $06, $89, $1e, $89, $12, $89, $1e, $89, $1e, $89
	.byte $06, $89, $1e, $89, $1e, $89, $12, $89, $12, $89, $12, $89, $12, $89, $12, $89
	.byte $41, $0c
	.word @song0ref4817
	.byte $2a, $89, $1e, $89, $12, $89, $1e, $89, $2a, $89, $1e, $89, $0b
@song0ref4969:
	.byte $89, $23, $89, $0b, $89, $0b, $89, $17, $89, $23
@song0ref4979:
	.byte $89, $17, $89, $23, $89, $0b, $89, $23, $89, $0b, $89, $23, $89, $0b, $89, $0b, $89, $0b, $89, $0b, $89, $0d, $89, $25
	.byte $89, $19, $89, $0d, $89, $0d, $89, $0d, $89, $0d, $89, $19, $89, $0d, $89, $25, $89, $25, $89, $25, $89, $25, $89, $0d
	.byte $89, $25, $89, $25, $89, $06, $89, $12, $89, $12, $89, $06, $89, $06, $89, $19, $89, $06, $89, $19, $89, $12, $89, $06
	.byte $89, $06, $89, $06, $89, $06, $89, $06, $89, $06, $89, $12
@song0ref5063:
	.byte $89, $1e, $89, $06, $89, $06, $89, $06, $89, $00, $89, $1e, $89, $2a, $89, $06, $89, $12, $89, $06, $89, $12, $89, $06
	.byte $89, $00, $89, $1e, $89, $12, $89, $2a, $89, $12, $89, $06, $89, $12, $89, $1e, $89, $00, $89, $1e, $89, $2a, $89, $2a
	.byte $89, $23, $89, $12, $89, $23, $89, $0b, $89, $23, $89, $2a, $89, $12, $89, $00, $89, $06, $89, $1e, $89, $12, $89, $06
	.byte $89, $00, $89, $06, $89, $25, $89, $19, $89, $06, $89, $12, $89, $06, $89, $06, $89, $00, $89, $1e, $89, $25, $89, $0d
	.byte $89, $1e, $89, $06, $89, $1e, $89, $06, $89, $00, $89, $06, $89, $06, $89, $25, $89, $0d, $89, $06, $89, $06, $89, $12
	.byte $89, $00, $89, $06, $89, $25, $89, $19
	.byte $41, $41
	.word @song0ref5063
	.byte $25, $89, $25, $89, $25, $89, $19, $89, $00, $89, $1e, $89, $2c, $89, $14, $89, $25, $89, $0d, $89, $0d, $89, $25, $89
	.byte $00, $89, $0d, $89, $14, $89, $20, $89, $25, $89, $19, $89, $0d, $89, $19, $89, $00, $89, $14, $89, $2c, $89, $20, $89
	.byte $14, $89, $25, $89, $19, $89, $19, $89, $00, $89, $0d, $89, $19, $89, $2c, $89
	.byte $41, $80
	.word @song0ref4817
@song0ref5261:
	.byte $0a, $89, $0a, $89, $16
@song0ref5266:
	.byte $89, $0a, $89, $22, $89, $22, $89, $16, $89, $16, $89, $22, $89, $22, $89, $16, $89, $22, $89, $0a, $89, $16, $89, $16
	.byte $89, $22, $89, $17, $89, $17, $89, $23, $89, $23, $89, $0b, $89, $0b, $89, $17, $89, $17, $89, $0b, $89, $23, $89, $0b
	.byte $89, $17, $89, $0b, $89, $0b, $89, $0b, $89, $0b, $89, $14, $89, $08, $89, $20, $89, $14, $89, $20, $89, $14, $89, $20
	.byte $89, $08, $89, $15, $89, $21, $89, $21, $89, $09, $89, $15, $89, $21, $89, $21, $89, $15, $89, $22, $89, $0a, $89, $22
	.byte $89, $22, $89, $0a
@song0ref5366:
	.byte $89, $0a, $89, $16, $89, $16, $89, $0a, $89, $0a, $89, $22
	.byte $41, $0b
	.word @song0ref5266
	.byte $41, $75
	.word @song0ref5261
	.byte $41, $0b
	.word @song0ref5266
	.byte $0a, $89, $16, $89, $16, $89, $0a
@song0ref5394:
	.byte $89, $0a, $89, $16, $89, $0a, $89, $0a, $89, $0a, $89, $16, $89, $22, $89, $16, $89, $0a, $89, $22, $89, $0a, $89, $22
	.byte $89, $1d, $89, $29, $89, $11, $89, $29, $89, $1d, $89, $29, $89, $11, $89, $1d, $89, $29, $89, $11, $89, $29, $89, $11
	.byte $89, $11, $89, $11, $89, $29, $89, $11, $89, $23, $89, $23, $89, $0b, $89, $23, $89, $23, $89, $0b, $89, $23, $89, $23
	.byte $89, $22, $89, $22, $89, $0a, $89, $22, $89, $0a, $89, $22, $89, $0a, $89, $22, $89, $27, $89, $0f, $89, $27, $89, $1b
	.byte $89, $0f, $89, $0f, $89, $0f, $89, $27, $89, $27, $89, $1b, $89, $0f, $89, $27, $89, $0f, $89, $0f, $89, $27, $89, $27
	.byte $41, $0b
	.word @song0ref4969
	.byte $23, $89, $0b, $89, $23
	.byte $41, $0b
	.word @song0ref5394
	.byte $0a, $89, $22, $89, $0a
@song0ref5530:
	.byte $89, $27, $89, $0f, $89, $27, $89, $0f, $89, $27, $89, $1b, $89, $1b, $89, $1b, $89, $27, $89, $1b
	.byte $41, $0b
	.word @song0ref5530
	.byte $0f, $89, $0b, $89, $23, $89, $0b
	.byte $41, $0b
	.word @song0ref4979
	.byte $0a, $89, $16, $89, $0a, $89, $16, $89, $0a, $89, $0a, $89, $22, $89, $16, $89, $0f, $89, $27, $89, $0f, $89, $0f, $89
	.byte $0f, $89, $0f
@song0ref5590:
	.byte $89, $27, $89, $0f, $89, $1b, $89, $27, $89, $27, $89, $0f, $89, $00, $ad, $1b
	.byte $41, $0d
	.word @song0ref5590
	.byte $27, $89, $27, $89, $0f, $89, $27, $89, $27, $89, $27, $89, $27, $89, $27, $89, $27, $89, $18, $89, $24, $89, $18, $89
	.byte $18, $89, $18, $89, $0c, $89, $18, $89, $0c, $89, $0c, $89, $18, $89, $18, $89, $18, $89, $24, $89, $18, $89, $18, $89
	.byte $0c, $89, $16, $89, $16, $89, $16, $89, $0a, $89, $22, $89, $0a, $89, $16, $89, $22, $89, $22
	.byte $41, $0c
	.word @song0ref5366
	.byte $89, $0a
@song0ref5681:
	.byte $89, $0e, $89, $0e, $89, $0e, $89, $1a, $89, $26, $89, $0e, $89, $26, $89, $26
	.byte $41, $0b
	.word @song0ref5681
	.byte $26, $89, $26, $89, $1a, $89, $1d, $89, $29, $89, $11, $89, $1d, $89, $11, $89, $29, $89, $29, $89, $29, $89, $11, $89
	.byte $29, $89, $29, $89, $11, $89, $29, $89, $11, $89, $1d, $89, $29, $89
	.byte $41, $0b
	.word @song0ref4549
	.byte $a1, $0d, $89, $00, $89, $27, $89, $00, $a1, $ff, $bf, $44, $00
