; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for song_sel:
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1

.export _music_data_song_sel:=music_data_song_sel

music_data_song_sel:
	.byte 6
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : blank1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : blank2
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.word @song1ch7
	.word @song1ch8
	.word @song1ch9
	.word @song1ch10
	.word @song1ch11
	.word @song1ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Euphoria
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word @song2ch5
	.word @song2ch6
	.word @song2ch7
	.word @song2ch8
	.word @song2ch9
	.word @song2ch10
	.word @song2ch11
	.word @song2ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Bean Brain
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word @song3ch5
	.word @song3ch6
	.word @song3ch7
	.word @song3ch8
	.word @song3ch9
	.word @song3ch10
	.word @song3ch11
	.word @song3ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 04 : Fork Lifter
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word @song4ch5
	.word @song4ch6
	.word @song4ch7
	.word @song4ch8
	.word @song4ch9
	.word @song4ch10
	.word @song4ch11
	.word @song4ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 05 : Finned Frontier Sel
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word @song5ch5
	.word @song5ch6
	.word @song5ch7
	.word @song5ch8
	.word @song5ch9
	.word @song5ch10
	.word @song5ch11
	.word @song5ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_song_sel
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env17,@env46,@env25,@env1 ; 00 : Kick
	.word @env42,@env21,@env25,@env1 ; 01 : HiHat Long
	.word @env33,@env21,@env25,@env1 ; 02 : HiHat
	.word @env0,@env15,@env25,@env1 ; 03 : Snare
	.word @env20,@env51,@env25,@env1 ; 04 : Snare Quiet
	.word @env35,@env39,@env25,@env1 ; 05 : Triangle Kick
	.word @env50,@env19,@env25,@env1 ; 06 : Triangle Snare
	.word @env4,@env5,@env25,@env1 ; 07 : Snare Short
	.word @env3,@env16,@env25,@env1 ; 08 : Crash
	.word @env18,@env21,@env25,@env1 ; 09 : Triangle
	.word @env8,@env21,@env6,@env1 ; 0a : Synth
	.word @env9,@env14,@env25,@env1 ; 0b : Snare Short 1
	.word @env44,@env21,@env30,@env1 ; 0c : Guitar
	.word @env37,@env21,@env30,@env1 ; 0d : Bass 1
	.word @env10,@env24,@env27,@env45 ; 0e : Synth 50

@instruments_exp:
	.word @env41, @env48, @env1 ; 00 : Chord N163
	.word @env1
	.byte $20, $10
	.word @n163_inst0_waves
	.byte $00, $00, $00, $00
	.word @env36, @env21, @env1 ; 01 : El Piano
	.word @env1
	.byte $10, $10
	.word @n163_inst1_waves
	.byte $00, $00, $00, $00
	.word @env43, @env21, @env1 ; 02 : El Synth
	.word @env1
	.byte $00, $10
	.word @n163_inst2_waves
	.byte $00, $00, $00, $00
	.word @env18, @env21, @env1 ; 03 : Sine Slides
	.word @env1
	.byte $30, $20
	.word @n163_inst3_waves
	.byte $00, $00, $00, $00
	.word @env7, @env34, @env1 ; 04 : Bass
	.word @env1
	.byte $50, $10
	.word @n163_inst4_waves
	.byte $00, $00, $00, $00
	.word @env11, @env21, @env1 ; 05 : Triangle Namco
	.word @env1
	.byte $00, $20
	.word @n163_inst5_waves
	.byte $00, $00, $00, $00
	.word @env2, @env21, @env1 ; 06 : Sax 2
	.word @env1
	.byte $20, $20
	.word @n163_inst6_waves
	.byte $00, $00, $00, $00
	.word @env47, @env21, @env1 ; 07 : Sax 3
	.word @env1
	.byte $40, $10
	.word @n163_inst7_waves
	.byte $00, $00, $00, $00
	.word @env29, @env21, @env1 ; 08 : Jumpy Square
	.word @env40
	.byte $60, $10
	.word @n163_inst8_waves
	.byte $00, $00, $00, $00

@env0:
	.byte $00,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c0,$00,$0d
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $07,$c6,$cb,$cd,$cf,$00,$04,$cc,$c8,$c4,$c2,$c0,$c0,$00,$0c
@env3:
	.byte $00,$c8,$c7,$02,$c6,$03,$c5,$02,$c4,$05,$c3,$03,$c2,$03,$c1,$00,$0e
@env4:
	.byte $00,$c9,$c8,$c7,$c5,$c3,$c2,$c1,$02,$c0,$00,$09
@env5:
	.byte $b9,$bd,$be,$00,$02
@env6:
	.byte $c2,$c2,$c1,$c1,$c0,$00,$04
@env7:
	.byte $00,$cf,$cf,$ce,$cc,$00,$04
@env8:
	.byte $09,$ca,$ca,$c9,$c8,$c7,$c6,$00,$06,$c3,$c2,$c1,$c0,$00,$0c
@env9:
	.byte $00,$ca,$c9,$c7,$c5,$c4,$c2,$c0,$00,$07
@env10:
	.byte $09,$ca,$c9,$c8,$c6,$c5,$c3,$00,$06,$c2,$c1,$c0,$c0,$00,$0c
@env11:
	.byte $00,$cf,$cf,$ce,$cc,$c7,$00,$05
@env12:
	.byte $df,$7a,$35,$12,$53,$87,$67,$85
@env13:
	.byte $53,$96,$a9,$9a,$88,$88,$77,$87
@env14:
	.byte $bc,$c0,$bf,$00,$02
@env15:
	.byte $ad,$b5,$be,$00,$02
@env16:
	.byte $bb,$be,$00,$01
@env17:
	.byte $00,$cb,$ca,$c9,$c7,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env18:
	.byte $00,$cf,$7f,$00,$02
@env19:
	.byte $c0,$bb,$b7,$b3,$af,$ac,$a6,$00,$06
@env20:
	.byte $00,$c3,$c2,$c1,$04,$c0,$00,$05
@env21:
	.byte $c0,$7f,$00,$01
@env22:
	.byte $7b,$71,$7a,$61,$88,$a9,$dc,$ad,$89,$67,$67,$55,$45,$54,$75,$87
@env23:
	.byte $00,$00,$00,$a0,$aa,$aa,$aa,$aa
@env24:
	.byte $bf,$c0,$00,$01
@env25:
	.byte $7f,$00,$00
@env26:
	.byte $68,$66,$aa,$9b,$14,$30,$73,$77
@env27:
	.byte $c2,$7f,$00,$00
@env28:
	.byte $10,$32,$54,$76,$98,$ba,$dc,$fe,$ef,$cd,$ab,$89,$67,$45,$23,$01
@env29:
	.byte $00,$c6,$c5,$c4,$c2,$c1,$00,$05
@env30:
	.byte $c1,$7f,$00,$00
@env31:
	.byte $5b,$21,$22,$11,$42,$97,$dc,$ee
@env32:
	.byte $00,$00,$00,$00,$ff,$ff,$ff,$ff
@env33:
	.byte $00,$c6,$c3,$c0,$00,$03
@env34:
	.byte $b5,$b4,$00,$01
@env35:
	.byte $00,$cf,$03,$c0,$00,$03
@env36:
	.byte $00,$c8,$7f,$00,$02
@env37:
	.byte $00,$c0,$cf,$00,$02
@env38:
	.byte $68,$35,$12,$01,$00,$11,$32,$65,$98,$ca,$ed,$fe,$ff,$ee,$cd,$9a
@env39:
	.byte $c0,$bb,$b6,$b1,$ad,$00,$04
@env40:
	.byte $00,$c0,$c1,$00,$02
@env41:
	.byte $00,$c6,$02,$c5,$07,$c4,$05,$c3,$00,$07
@env42:
	.byte $00,$c6,$c3,$03,$c2,$c2,$c1,$04,$c0,$00,$08
@env43:
	.byte $00,$c6,$ca,$cd,$cf,$cf,$cc,$c8,$c5,$c1,$c0,$00,$0a
@env44:
	.byte $06,$c6,$c4,$c3,$00,$03,$c3,$c2,$c1,$c1,$c0,$00,$0a
@env45:
	.byte $00,$bb,$bd,$bf,$c0,$00,$04
@env46:
	.byte $c0,$bd,$bc,$00,$02
@env47:
	.byte $07,$c6,$cb,$cf,$cf,$00,$04,$cc,$c8,$c4,$c2,$c0,$c0,$00,$0c
@env48:
	.byte $b4,$7f,$00,$00
@env49:
	.byte $00,$00,$00,$00,$aa,$aa,$aa,$aa
@env50:
	.byte $00,$cf,$06,$c0,$00,$03
@env51:
	.byte $ba,$bf,$be,$00,$02

@n163_inst0_waves:
	.word @env32

@n163_inst1_waves:
	.word @env31

@n163_inst2_waves:
	.word @env26

@n163_inst3_waves:
	.word @env38

@n163_inst4_waves:
	.word @env12

@n163_inst5_waves:
	.word @env28

@n163_inst6_waves:
	.word @env22

@n163_inst7_waves:
	.word @env13

@n163_inst8_waves:
	.word @env23
	.word @env49

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $41, $0f
	.word @song0ref5
	.byte $48
	.byte $41, $0f
	.word @song0ref5
	.byte $48, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
@song0ch2:
@song0ch1:
@song0ch1loop:
@song0ref50:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song0ref50
	.byte $41, $0f
	.word @song0ref50
	.byte $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch3:
@song0ch3loop:
	.byte $90, $31, $cd, $00, $ff, $ed
	.byte $41, $0f
	.word @song0ref50
	.byte $41, $0f
	.word @song0ref50
	.byte $41, $0f
	.word @song0ref50
	.byte $42
	.word @song0ch3loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song1ref5:
	.byte $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $41, $0f
	.word @song1ref5
	.byte $48
	.byte $41, $0f
	.word @song1ref5
	.byte $48, $ff, $ff, $bf, $42
	.word @song1ch0loop
@song1ch12:
@song1ch11:
@song1ch10:
@song1ch9:
@song1ch8:
@song1ch7:
@song1ch6:
@song1ch5:
@song1ch4:
@song1ch2:
@song1ch1:
@song1ch1loop:
@song1ref50:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song1ref50
	.byte $41, $0f
	.word @song1ref50
	.byte $ff, $ff, $bf, $42
	.word @song1ch1loop
@song1ch3:
@song1ch3loop:
	.byte $90, $2c, $cd, $00, $ff, $ed
	.byte $41, $0f
	.word @song1ref50
	.byte $41, $0f
	.word @song1ref50
	.byte $41, $0f
	.word @song1ref50
	.byte $42
	.word @song1ch3loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $98
@song2ref6:
	.byte $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $8f, $00, $83
	.byte $41, $10
	.word @song2ref6
@song2ref25:
	.byte $31, $81
@song2ref27:
	.byte $00, $85, $31, $83, $00, $83
@song2ref33:
	.byte $31, $8f
@song2ref35:
	.byte $00, $83, $48
@song2ref38:
	.byte $31, $81, $00, $85, $31, $8d, $00, $85, $31, $83, $00, $83, $31, $81, $00, $85, $31, $83, $00, $83
	.byte $41, $11
	.word @song2ref38
	.byte $8d
	.byte $41, $0f
	.word @song2ref27
@song2ref65:
	.byte $83, $00, $83, $31, $8f, $00, $83, $31, $81, $00, $85, $31, $83, $00, $83, $31, $8f, $00, $83
	.byte $41, $14
	.word @song2ref38
	.byte $41, $18
	.word @song2ref33
	.byte $31, $8f, $00, $83
	.byte $41, $11
	.word @song2ref38
	.byte $8d, $00, $85, $31, $83
	.byte $41, $0f
	.word @song2ref35
	.byte $8f, $00, $83
	.byte $41, $10
	.word @song2ref6
	.byte $41, $20
	.word @song2ref25
	.byte $41, $11
	.word @song2ref38
	.byte $8d
	.byte $41, $0f
	.word @song2ref27
	.byte $41, $13
	.word @song2ref65
	.byte $41, $14
	.word @song2ref38
	.byte $41, $18
	.word @song2ref33
	.byte $31, $8f, $00, $83
	.byte $41, $11
	.word @song2ref38
	.byte $8d, $00, $85, $31, $83, $00, $83, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $98
@song2ref149:
	.byte $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83, $00, $83, $2c, $8f, $00, $83
	.byte $41, $10
	.word @song2ref149
@song2ref168:
	.byte $2c, $81
@song2ref170:
	.byte $00, $85, $2c, $83
@song2ref174:
	.byte $00, $83, $2c
@song2ref177:
	.byte $8f
@song2ref178:
	.byte $00, $83, $2c, $81, $00, $85, $2c, $8d, $00, $85, $2c, $83, $00, $83, $2c, $81, $00, $85, $2c, $83
	.byte $41, $13
	.word @song2ref178
	.byte $8d
	.byte $41, $0f
	.word @song2ref170
	.byte $83, $00, $83, $2c, $8f, $00, $83
	.byte $41, $1e
	.word @song2ref168
	.byte $41, $18
	.word @song2ref174
	.byte $41, $17
	.word @song2ref174
	.byte $8d, $00, $85, $2c, $83
	.byte $41, $0f
	.word @song2ref178
	.byte $41, $10
	.word @song2ref177
	.byte $8f, $00, $83
	.byte $41, $1e
	.word @song2ref168
	.byte $41, $13
	.word @song2ref178
	.byte $8d
	.byte $41, $0f
	.word @song2ref170
	.byte $83, $00, $83, $2c, $8f, $00, $83
	.byte $41, $1e
	.word @song2ref168
	.byte $41, $18
	.word @song2ref174
	.byte $41, $17
	.word @song2ref174
	.byte $8d, $00, $85, $2c, $83, $00, $83, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $9a
@song2ref273:
	.byte $06, $89, $00, $89, $06, $89, $06, $89, $06, $89, $00, $89, $12, $89, $12, $89, $08, $89, $00, $89, $08, $89, $08, $89
	.byte $08, $89, $00, $89, $08, $89, $08
@song2ref304:
	.byte $89, $0d, $89, $00, $89, $0d, $89, $0d, $89, $0d, $89, $00, $89, $0d, $89, $0d
	.byte $41, $10
	.word @song2ref304
	.byte $89
	.byte $41, $1c
	.word @song2ref273
@song2ref327:
	.byte $14, $89, $14, $89, $08, $89, $00, $89, $08, $89, $08, $89, $08, $89, $00, $89, $14, $89, $14, $89, $05, $89, $00, $89
	.byte $05, $89, $05, $89, $05, $89, $00, $89, $11, $89, $11, $89
	.byte $41, $2f
	.word @song2ref273
	.byte $41, $10
	.word @song2ref304
	.byte $89
	.byte $41, $1c
	.word @song2ref273
	.byte $41, $14
	.word @song2ref327
	.byte $0d, $89, $00, $89, $19, $89, $19, $89, $00, $89, $0d, $89, $19, $89, $19, $89, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $7f
@song2ref397:
	.byte $90, $2f, $ad, $86, $30, $95, $82, $30
@song2ref405:
	.byte $95
@song2ref406:
	.byte $80, $28, $89, $84, $31, $89, $82, $30, $89, $88, $30, $89, $86, $30, $95, $82, $30, $95, $80, $28, $89, $84, $31, $89
	.byte $82, $30, $89, $88, $30, $89, $86, $30, $95, $82, $30, $89, $86, $30, $89
	.byte $41, $17
	.word @song2ref406
	.byte $41, $18
	.word @song2ref405
@song2ref451:
	.byte $95, $80, $28, $89, $84, $31, $89, $82, $30, $89, $88, $30, $89, $76, $51, $06, $f0, $96, $2d, $89, $2d, $89, $2d, $89
	.byte $2d, $89
	.byte $41, $20
	.word @song2ref397
	.byte $41, $17
	.word @song2ref406
	.byte $41, $18
	.word @song2ref405
	.byte $41, $11
	.word @song2ref451
	.byte $42
	.word @song2ch3loop
@song2ch12:
@song2ch11:
@song2ch4:
@song2ch4loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $ff, $bf, $7e, $51, $fd, $90, $8b, $8a
@song2ref523:
	.byte $31, $89, $3d, $89, $31, $89, $3d, $89, $31, $89, $51, $03, $f0, $3d, $89, $31, $89, $3d, $89, $31, $89, $3d, $89, $31
	.byte $89, $51, $fe, $10, $3d, $89, $38, $89, $35, $89, $31, $89, $3d, $89, $38, $89, $35, $89, $31, $89, $3d, $85, $00, $81
	.byte $38, $85, $00, $81, $35, $85, $00, $81, $31, $85, $00, $81, $3d, $83, $00, $83, $38, $83, $00, $83, $35, $83, $00, $83
	.byte $31, $83, $00, $83, $3d, $81, $00, $85, $38, $81, $00, $85, $35, $81, $00, $85, $31, $81, $00, $7f, $85, $ff, $bf, $ff
	.byte $bf, $7e, $51, $fd, $90, $8b
	.byte $41, $58
	.word @song2ref523
	.byte $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $80, $28, $c5, $2a, $dd, $2c, $95, $ff, $bf, $28, $dd, $2a, $dd, $27, $dd, $25, $dd, $28, $c5, $2a, $dd, $2c, $95, $ff
	.byte $bf, $28, $dd, $2a, $dd, $2a, $dd, $29, $dd, $42
	.word @song2ch6loop
@song2ch7:
@song2ch7loop:
	.byte $80, $25, $c5, $27, $dd, $29, $95, $ff, $bf, $25, $dd, $27, $dd, $23, $dd, $23, $dd, $25, $c5, $27, $dd, $29, $95, $ff
	.byte $bf, $25, $dd, $27, $dd, $27, $dd, $25, $dd, $42
	.word @song2ch7loop
@song2ch8:
@song2ch8loop:
	.byte $80, $21, $c5, $23, $dd, $25, $95, $ff, $bf, $21, $dd, $23, $dd, $22, $dd, $20, $dd, $21, $c5, $23, $dd, $25, $95, $ff
	.byte $bf, $21, $dd, $23, $dd, $23, $dd, $23, $dd, $42
	.word @song2ch8loop
@song2ch9:
@song2ch9loop:
	.byte $86
@song2ref744:
	.byte $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e, $1b, $89, $00, $a1, $50, $e3, $2e
	.byte $1b, $89, $00, $a1
	.byte $41, $10
	.word @song2ref744
	.byte $41, $10
	.word @song2ref744
	.byte $41, $10
	.word @song2ref744
	.byte $41, $10
	.word @song2ref744
	.byte $41, $10
	.word @song2ref744
	.byte $41, $10
	.word @song2ref744
	.byte $41, $10
	.word @song2ref744
	.byte $42
	.word @song2ch9loop
@song2ch10:
@song2ch10loop:
	.byte $7d, $00, $ad, $86
@song2ref801:
	.byte $50, $c7, $36, $18, $89, $00, $d1, $50, $c7, $36, $18, $89, $00, $a1, $af, $50, $c7, $36, $18, $89, $00, $95, $50, $c7
	.byte $36, $18, $89, $00, $ad, $50, $c7, $36, $18, $89, $00, $a1, $00, $ad, $50, $c7, $36, $18, $89, $00, $d1, $50, $c7, $36
	.byte $18, $89, $00, $a1, $af, $50, $c7, $36, $18, $89, $00, $d1, $79, $51, $06, $f0, $50, $c7, $36, $18, $89, $50, $c7, $36
	.byte $18, $89, $50, $c7, $36, $18, $89, $50, $c7, $36, $18, $89, $7d, $00, $ad
	.byte $41, $2c
	.word @song2ref801
	.byte $42
	.word @song2ch10loop
@song3ch0:
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song3ref5:
	.byte $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48
	.byte $41, $0f
	.word @song3ref5
	.byte $48
	.byte $41, $0f
	.word @song3ref5
	.byte $48, $ff, $ff, $bf, $42
	.word @song3ch0loop
@song3ch12:
@song3ch11:
@song3ch10:
@song3ch9:
@song3ch8:
@song3ch7:
@song3ch6:
@song3ch5:
@song3ch4:
@song3ch2:
@song3ch1:
@song3ch1loop:
@song3ref50:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song3ref50
	.byte $41, $0f
	.word @song3ref50
	.byte $ff, $ff, $bf, $42
	.word @song3ch1loop
@song3ch3:
@song3ch3loop:
	.byte $80, $22, $91, $00, $ff, $ff, $a9
	.byte $41, $0f
	.word @song3ref50
	.byte $41, $0f
	.word @song3ref50
	.byte $41, $0f
	.word @song3ref50
	.byte $42
	.word @song3ch3loop
@song4ch0:
@song4ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $94, $25, $cd, $00, $ff, $ed
@song4ref11:
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf
	.byte $41, $0f
	.word @song4ref11
	.byte $41, $0f
	.word @song4ref11
	.byte $42
	.word @song4ch0loop
@song4ch12:
@song4ch11:
@song4ch10:
@song4ch9:
@song4ch8:
@song4ch7:
@song4ch6:
@song4ch5:
@song4ch4:
@song4ch3:
@song4ch2:
@song4ch1:
@song4ch1loop:
@song4ref52:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song4ref52
	.byte $41, $0f
	.word @song4ref52
	.byte $ff, $ff, $bf, $42
	.word @song4ch1loop
@song5ch0:
@song5ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7b, $94, $2a, $95, $2a, $89, $45, $89, $28, $89, $45, $89
	.byte $25, $89, $45, $89, $28, $95, $2a, $89, $45, $89, $00, $95, $25, $89, $45, $89, $48, $23, $95
@song5ref36:
	.byte $23
@song5ref37:
	.byte $89, $45, $89, $21, $89, $45, $89, $23, $89, $45, $89, $00, $95, $1e
	.byte $41, $0b
	.word @song5ref37
	.byte $48, $25, $95, $25, $89, $45, $89
	.byte $41, $09
	.word @song5ref36
	.byte $95, $25, $89, $45, $89, $00, $95, $1d, $95, $48, $1e, $89, $45, $89, $00, $89, $1e, $89, $45, $89, $00, $89, $1e, $89
	.byte $45, $89, $00, $95
@song5ref92:
	.byte $1c, $95, $1e, $89, $45, $89, $00, $95, $42
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $7b, $9c, $1e, $95, $1e, $89, $45, $89, $1c, $89, $45, $89, $19, $89, $45, $89
	.byte $41, $08
	.word @song5ref92
	.byte $19, $89, $45, $89, $17, $95
@song5ref129:
	.byte $17
@song5ref130:
	.byte $89, $45, $89, $15, $89, $45, $89, $17, $89, $45, $89, $00, $95, $12
	.byte $41, $0b
	.word @song5ref130
	.byte $19, $95, $19, $89, $45, $89
	.byte $41, $09
	.word @song5ref129
	.byte $95, $19, $89, $45, $89, $00, $95, $11, $95, $12, $89, $45, $89, $00, $89, $12, $89, $45, $89, $00, $89, $12, $89, $45
	.byte $89, $00, $95, $10, $95, $12, $89, $45, $89, $00, $95, $42
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
@song5ref195:
	.byte $8a, $22, $89, $00, $a1, $8c, $29, $89, $00, $89, $8a, $22, $89, $00, $a1, $22, $89, $00, $89, $8c, $29, $89, $00, $a1
	.byte $41, $14
	.word @song5ref195
	.byte $41, $0e
	.word @song5ref195
	.byte $8c, $29, $83, $29, $83, $29, $89, $29, $89, $00, $89, $29, $89, $8a, $22, $89, $00, $95, $22, $89, $8c, $29, $89, $00
	.byte $89, $8a, $22, $89, $00, $89, $92, $36, $8a, $22, $87, $92, $36, $00, $87, $34, $00, $87, $8a, $22, $89, $92, $36, $8c
	.byte $29, $87, $00, $89, $8a, $22, $89, $00, $89, $42
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
	.byte $7a
@song5ref287:
	.byte $80, $27, $89, $84, $33, $89, $31, $89, $33, $89, $8e, $31, $95
	.byte $41, $08
	.word @song5ref287
@song5ref303:
	.byte $80, $27, $89, $84, $33, $89, $8e, $31, $95, $84, $31, $89, $33, $89
	.byte $41, $0a
	.word @song5ref287
	.byte $41, $08
	.word @song5ref287
	.byte $41, $0a
	.word @song5ref303
	.byte $41, $0a
	.word @song5ref287
	.byte $41, $08
	.word @song5ref287
	.byte $80, $27, $89, $86, $31, $83, $31, $83, $31, $89, $31, $95, $31
@song5ref345:
	.byte $89, $80, $27, $89, $84, $33, $89, $33, $89, $80, $27, $89, $8e, $31, $95, $80, $27, $89, $84, $33
	.byte $41, $0e
	.word @song5ref345
	.byte $89, $42
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song5ch4loop
@song5ch5:
@song5ch5loop:
	.byte $7b, $49, .lobyte(@env1), .hibyte(@env1), $4a, $84
@song5ref391:
	.byte $12, $95, $00, $95, $0d, $95, $00, $95
	.byte $41, $08
	.word @song5ref391
@song5ref402:
	.byte $0b, $95, $00, $95, $12, $95, $00, $95
	.byte $41, $08
	.word @song5ref402
@song5ref413:
	.byte $0d, $95, $00, $95, $08, $95, $00, $95
	.byte $41, $08
	.word @song5ref413
@song5ref424:
	.byte $12, $95, $00, $89, $12, $95, $00, $89, $12, $95
	.byte $41, $0a
	.word @song5ref424
	.byte $42
	.word @song5ch5loop
@song5ch6:
@song5ch6loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $84
@song5ref448:
	.byte $06, $95, $00, $89, $06, $95, $00, $89, $06, $95
	.byte $41, $0a
	.word @song5ref448
	.byte $42
	.word @song5ch6loop
@song5ch7:
@song5ch7loop:
	.byte $7b, $97, $82
@song5ref468:
	.byte $19, $89, $00, $a1, $19, $89, $00, $a1, $19, $89, $00, $a1, $19, $89, $00, $89, $97, $1b, $89, $00, $a1, $1b, $89, $00
	.byte $a1, $1b, $89, $00, $a1, $1b, $89, $00, $89, $97, $1d, $89, $00, $a1, $1d, $89, $00, $a1, $1d, $89, $00, $a1, $1d, $89
	.byte $00, $89, $1e, $89, $00, $95, $1e, $89, $00, $95, $1e, $89, $00, $a1, $1c, $95, $1e, $89, $00, $a1, $42
	.word @song5ch7loop
@song5ch8:
@song5ch8loop:
	.byte $7b, $97, $82, $16, $89, $00, $a1, $16, $89, $00, $a1, $15, $89, $00, $a1, $15, $89, $00, $89, $97, $17, $89, $00, $a1
	.byte $17, $89, $00, $a1, $16, $89, $00, $a1, $16, $89, $00, $89, $97
	.byte $41, $08
	.word @song5ref468
	.byte $18, $89, $00, $a1, $18, $89, $00, $89, $19, $89, $00, $95, $19, $89, $00, $95, $19, $89, $00, $a1, $17, $95, $19, $89
	.byte $00, $a1, $42
	.word @song5ch8loop
@song5ch9:
@song5ch9loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $8c, $06, $89, $5a, $89, $00, $89, $06, $89, $5a, $89, $00, $89, $06, $89, $5a, $89, $00
	.byte $95, $04, $95, $06, $89, $5a, $89, $00, $95, $42
	.word @song5ch9loop
@song5ch10:
@song5ch10loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $8e, $12, $89, $5a, $89, $00, $89, $12, $89, $5a, $89, $00, $89, $12, $89, $5a, $89, $00
	.byte $95, $10, $95, $12, $89, $5a, $89, $00, $95, $42
	.word @song5ch10loop
@song5ch11:
@song5ch11loop:
	.byte $7b, $88, $12, $95, $12, $95, $10, $89, $00, $89, $12, $89, $00, $a1, $12, $89, $00, $89, $10, $89, $00, $89, $12, $89
	.byte $00, $89, $0a, $95
@song5ref712:
	.byte $0a, $89, $00, $89, $08, $89, $00, $89, $0a, $89, $00, $a1
	.byte $41, $0b
	.word @song5ref712
	.byte $89, $0d, $95
@song5ref730:
	.byte $0d, $89, $00, $89, $0b, $89, $00, $89, $0d, $89, $00, $a1
	.byte $41, $0b
	.word @song5ref730
	.byte $89, $12, $89, $00, $89, $06, $89, $12, $89, $00, $89, $06, $89, $12, $89, $00, $89, $12, $89, $00, $89, $10, $95, $12
	.byte $89, $00, $a1, $42
	.word @song5ch11loop
@song5ch12:
@song5ch12loop:
	.byte $7b, $90, $1e
@song5ref779:
	.byte $89, $2a, $89, $1e, $89, $2a, $89, $2a, $89, $12, $89, $1e, $89, $12, $89, $1e, $89, $2a
	.byte $41, $09
	.word @song5ref779
	.byte $1e, $89, $12, $89, $17, $89, $0b, $89, $17, $89, $17, $89, $17, $89, $0b, $89, $0b, $89, $0b, $89, $17, $89, $23, $89
	.byte $23, $89, $23, $89, $17, $89, $23, $89, $23, $89, $17, $89, $0d
@song5ref837:
	.byte $89, $25, $89, $19, $89, $0d, $89, $19, $89, $25, $89, $25, $89, $0d, $89, $25, $89, $0d, $89, $25
	.byte $41, $09
	.word @song5ref837
	.byte $0d, $89, $12, $89, $1e, $89, $1e, $89, $1e, $89, $1e, $89, $06, $89, $12, $89, $06, $89, $1e, $89, $12, $89, $1e, $89
	.byte $1e, $89, $06, $89, $1e, $89, $1e, $89, $12, $89, $42
	.word @song5ch12loop
