; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for DDRKirby(ISQ):
; FAMISTUDIO_EXP_N163 = 1
; FAMISTUDIO_EXP_N163_CHN_CNT = 8
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_ddrkirbyisq_2A03:=music_data_ddrkirbyisq_2A03

music_data_ddrkirbyisq_2A03:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Who Unleashed The Dog
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.word @song0ch10
	.word @song0ch11
	.word @song0ch12
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_ddrkirbyisq
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env35,@env20,@env28,@env0 ; 00 : HiHat Quick
	.word @env8,@env1,@env28,@env0 ; 01 : Kick
	.word @env4,@env18,@env28,@env0 ; 02 : HiHat
	.word @env38,@env7,@env28,@env0 ; 03 : Snare 2
	.word @env26,@env17,@env28,@env0 ; 04 : Snare
	.word @env8,@env11,@env28,@env0 ; 05 : Kick Alt
	.word @env21,@env25,@env28,@env0 ; 06 : Crash Alt
	.word @env33,@env20,@env28,@env0 ; 07 : Intro Reversed Crash
	.word @env40,@env2,@env28,@env0 ; 08 : Snare Alt
	.word @env27,@env9,@env28,@env0 ; 09 : Crash
	.word @env42,@env30,@env28,@env0 ; 0a : Snare Rev
	.word @env10,@env20,@env32,@env0 ; 0b : 25
	.word @env23,@env20,@env28,@env0 ; 0c : 12.5
	.word @env10,@env20,@env29,@env0 ; 0d : 50
	.word @env3,@env41,@env5,@env0 ; 0e : 25 N163 Flick 2A03
	.word @env31,@env20,@env28,@env0 ; 0f : 12.5 Chord 2A03
	.word @env19,@env9,@env28,@env0 ; 10 : Crash NoV
	.word @env39,@env20,@env6,@env0 ; 11 : P2 Up Down 2A03
	.word @env14,@env20,@env28,@env0 ; 12 : Crash Alt Rev
	.word @env13,@env20,@env28,@env0 ; 13 : Triangle
	.word @env37,@env16,@env28,@env0 ; 14 : Crash End

@instruments_exp:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c0,$00,$01
@env2:
	.byte $ba,$bd,$c0,$00,$02
@env3:
	.byte $00,$c3,$7f,$00,$02
@env4:
	.byte $00,$ca,$c8,$c6,$c3,$c0,$00,$05
@env5:
	.byte $c3,$7f,$00,$00
@env6:
	.byte $c2,$c1,$00,$01
@env7:
	.byte $b8,$ba,$bc,$bd,$00,$03
@env8:
	.byte $00,$cc,$ca,$c7,$c5,$c0,$00,$05
@env9:
	.byte $bd,$c0,$00,$01
@env10:
	.byte $00,$c5,$7f,$00,$02
@env11:
	.byte $c4,$c0,$00,$01
@env12:
	.byte $b9,$b9,$bc,$bc,$c0,$c0,$00,$00
@env13:
	.byte $00,$cf,$7f,$00,$02
@env14:
	.byte $00,$c6,$c7,$c8,$c8,$c9,$c9,$ca,$cb,$cb,$cc,$cd,$cd,$ce,$ce,$cf,$00,$0f
@env15:
	.byte $c0,$c0,$bd,$bd,$b6,$b6,$00,$00
@env16:
	.byte $b7,$b9,$bc,$be,$bf,$c0,$00,$05
@env17:
	.byte $b8,$ba,$bc,$bf,$bb,$00,$00
@env18:
	.byte $bd,$bf,$00,$01
@env19:
	.byte $00,$c9,$7f,$00,$02
@env20:
	.byte $c0,$7f,$00,$01
@env21:
	.byte $00,$cf,$05,$ce,$ce,$cd,$cd,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c8,$c7,$c6,$c5,$c4,$c3,$c0,$00,$14
@env22:
	.byte $c0,$c0,$bd,$bd,$b8,$b8,$00,$00
@env23:
	.byte $00,$c4,$7f,$00,$02
@env24:
	.byte $c0,$cc,$d8,$00,$00
@env25:
	.byte $bc,$be,$c0,$00,$02
@env26:
	.byte $00,$cd,$cb,$c8,$c6,$c4,$c2,$c1,$c0,$00,$08
@env27:
	.byte $00,$ca,$c9,$02,$c8,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c4,$c3,$00,$0d
@env28:
	.byte $7f,$00,$00
@env29:
	.byte $c2,$7f,$00,$00
@env30:
	.byte $bd,$07,$bc,$ba,$b8,$00,$04
@env31:
	.byte $00,$c6,$c7,$c8,$c6,$c5,$00,$05
@env32:
	.byte $c1,$7f,$00,$00
@env33:
	.byte $00,$c8,$7f,$00,$02
@env34:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env35:
	.byte $00,$c4,$c2,$c1,$c0,$00,$04
@env36:
	.byte $c0,$c0,$bd,$bd,$b7,$b7,$00,$00
@env37:
	.byte $00,$cb,$02,$ca,$02,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c5,$c5,$c3,$c2,$c2,$c1,$c0,$00,$12
@env38:
	.byte $00,$cc,$cb,$c9,$c8,$c6,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0c
@env39:
	.byte $00,$c4,$02,$c3,$03,$c2,$c1,$03,$c0,$00,$08
@env40:
	.byte $00,$cf,$ce,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c6,$c5,$00,$0b
@env41:
	.byte $cc,$c0,$00,$01
@env42:
	.byte $00,$c0,$c1,$c1,$c2,$c2,$c3,$c4,$c6,$c8,$c9,$cb,$cc,$c0,$00,$0d

@samples:
	.byte $EF,$20,$0e,$40 ; 00 don (Pitch:14)
	.byte $F7,$1f,$0e,$40 ; 01 kat (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $af, $48, $ff, $af, $48, $49, .lobyte(@env34), .hibyte(@env34), $96, $0d, $83, $96, $50, $b9, $19, $20, $8d, $14
	.byte $af, $50, $40, $20, $1b, $89, $00, $81, $0c, $83, $50, $b4, $18, $1f, $8d, $13, $a5, $50, $65, $1f, $1a, $87, $08, $87
	.byte $00, $83, $48, $50, $87, $18, $1f, $89, $14, $99, $00, $81, $50, $87, $18, $1f, $89, $13, $99, $00, $81, $50, $80, $17
	.byte $1e, $89, $12, $99, $00, $81, $50, $80, $15, $1c, $89, $10, $99
@song0ref81:
	.byte $00, $81
@song0ref83:
	.byte $48, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2c, $93, $50, $1d, $38, $31, $89, $25, $87, $00, $93, $2c, $93, $50
	.byte $1d, $38, $31, $89, $25, $87, $00, $93, $23, $89, $00, $87, $23, $83, $25, $8d, $48, $95, $20, $93, $23, $93, $25, $93
	.byte $27, $83, $50, $f9, $33, $34, $83, $28, $87, $27, $83, $50, $f9, $33, $34, $83, $28, $87, $25, $99, $50, $18, $31, $2c
	.byte $89, $20, $81, $48, $2c, $93, $50, $1d, $38, $31, $89, $25, $87, $00, $93, $2c, $83, $00, $83, $2c, $83, $00, $81, $23
	.byte $83, $25, $8d, $50, $0f, $31, $2c, $93, $23, $89, $00, $87, $23, $83, $25, $8d, $48, $95, $20, $93, $23, $89, $25, $87
	.byte $28, $89, $20, $87, $2b, $93, $20, $89, $2a, $93, $20, $87, $28, $93
	.byte $41, $64
	.word @song0ref83
	.byte $48, $25, $89, $50, $1d, $31, $2c, $87, $7a, $25, $89, $50, $1d, $31, $2c, $87, $78, $25, $89, $50, $1d, $31, $2c, $87
	.byte $75, $25, $89, $50, $1d, $31, $2c, $87, $73, $25, $89, $50, $1d, $31, $2c, $87, $71, $25, $89, $50, $1d, $31, $2c, $87
	.byte $00, $a9, $48, $ff, $af, $48, $ff, $af, $48, $ff, $af, $48, $7b
@song0ref276:
	.byte $0d, $85, $00, $81, $0d, $83, $00, $81, $0d, $85, $00, $81, $0d, $83, $00, $81, $01, $85, $00, $81, $01, $83, $00, $81
	.byte $41, $18
	.word @song0ref276
	.byte $0d, $85, $00, $81, $0d, $83, $00, $81, $0d, $85, $00, $81, $0d, $83, $00, $81, $48
	.byte $41, $18
	.word @song0ref276
	.byte $41, $18
	.word @song0ref276
	.byte $0d, $85, $00, $81, $0d, $83, $00, $81, $0d, $85, $00, $81, $0d, $83, $00, $81, $48
	.byte $41, $18
	.word @song0ref276
	.byte $41, $18
	.word @song0ref276
	.byte $0d, $85, $00, $81, $0d, $83, $00, $81, $0d, $85, $00, $81, $0d, $83, $00, $81, $48, $ab, $70, $51, $04, $f0, $4b, .lobyte(@env24)
	.byte .hibyte(@env24), $25, $ff, $81, $48, $4b, .lobyte(@env20), .hibyte(@env20), $4c
@song0ref382:
	.byte $9a, $50, $f8, $35, $37, $89, $2b, $c9, $2c, $d5, $48, $28, $d5, $2a, $d5, $48, $25, $d5, $28, $d5, $48, $23, $d5, $24
	.byte $d5, $48, $25, $d5, $51, $fe, $00, $d7, $48, $ff, $af, $48, $7b, $96
	.byte $41, $18
	.word @song0ref276
	.byte $41, $18
	.word @song0ref276
	.byte $0d, $85, $00, $81, $0d, $83, $00, $81, $0d, $85, $00, $81, $0d, $83, $00, $81, $48
	.byte $41, $18
	.word @song0ref276
	.byte $41, $18
	.word @song0ref276
	.byte $0d, $85, $00, $81, $0d, $83, $00, $81, $0d, $85, $00, $81, $0d, $83, $00, $81, $48, $7f, $9a
@song0ref468:
	.byte $50, $f8, $35, $37, $89, $2b, $c9, $2c, $d5, $48, $28, $d5, $2a, $d5, $48, $2c, $d5, $2f, $d5, $48, $2a, $d5, $28, $d5
	.byte $48, $25, $d5, $51, $fe, $00, $d7, $48, $ff, $af, $48, $7b, $96
	.byte $41, $18
	.word @song0ref276
	.byte $41, $18
	.word @song0ref276
	.byte $0d, $85, $00, $81, $0d, $83, $00, $81, $0d, $85, $00, $81, $0d, $83, $00, $81, $48
	.byte $41, $18
	.word @song0ref276
	.byte $41, $18
	.word @song0ref276
	.byte $0d, $85, $00, $81, $0d, $83, $00, $81, $0d, $85, $00, $81, $0d, $83
	.byte $41, $66
	.word @song0ref81
	.byte $41, $64
	.word @song0ref83
	.byte $41, $64
	.word @song0ref83
	.byte $41, $55
	.word @song0ref83
	.byte $93, $50, $1d, $31, $2c, $87, $2a, $93, $28, $89, $2a, $9d, $28, $83, $00, $83, $28, $81, $00, $83
@song0ref580:
	.byte $48, $50, $7f, $31, $19, $89, $0d, $87, $09
@song0ref589:
	.byte $89, $25, $83, $00, $81, $31, $89, $00, $87, $50, $7f, $31, $19, $89, $0d, $9d, $50, $7f, $31, $19, $89, $50, $7f, $31
	.byte $19, $87, $50, $7f, $38, $1c, $89, $10, $87, $12, $93, $48
@song0ref625:
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19, $89, $50, $7f, $30, $18, $87, $0c, $89, $18, $87, $50, $7f, $2f, $17, $89, $0b
	.byte $87, $50, $cd, $25, $2b, $89, $1f, $87, $13, $93, $14, $93, $50, $43, $20, $18, $93
	.byte $41, $22
	.word @song0ref580
@song0ref669:
	.byte $50, $7f, $31, $19, $87, $31, $89, $25, $87, $50, $7f, $31, $19, $89, $0d, $87, $50, $f7, $27, $28, $89, $1c, $87, $1e
	.byte $93, $20, $93, $50, $07, $2c, $2b, $89, $1f, $87
	.byte $41, $36
	.word @song0ref580
	.byte $41, $22
	.word @song0ref580
	.byte $41, $16
	.word @song0ref669
	.byte $41, $36
	.word @song0ref580
	.byte $41, $22
	.word @song0ref580
	.byte $41, $16
	.word @song0ref669
	.byte $41, $36
	.word @song0ref580
	.byte $41, $22
	.word @song0ref580
	.byte $41, $16
	.word @song0ref669
	.byte $41, $64
	.word @song0ref83
	.byte $41, $64
	.word @song0ref83
	.byte $48, $7f
	.byte $41, $17
	.word @song0ref382
	.byte $48, $7f, $00, $ff, $ad, $48, $ff, $af, $48
	.byte $41, $17
	.word @song0ref468
	.byte $48, $7f, $00, $ff, $ad, $48, $ff, $af, $48, $ff, $af, $48, $ff, $af, $44, $00
@song0ch1:
	.byte $ff, $af, $ff, $af, $ff, $af, $ed, $98, $08, $89, $00, $87, $0b, $93, $0c, $93
@song0ref786:
	.byte $0d, $93, $14, $89, $00, $87, $01, $89, $00, $87, $14, $89, $00, $9d, $14, $89, $00, $87, $01, $93, $14, $89, $00, $87
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $50, $f2, $19, $1a, $8d, $50, $f1, $1a, $1b, $8b, $50, $f3, $1b, $1c, $8b, $50, $e5, $1c, $1d, $85, $50, $f5, $1d, $1e
	.byte $8b, $50, $f5, $1e, $1f, $8d, $50, $e9, $1f, $20, $83, $50, $f6, $20, $21, $8d, $50, $f5, $21, $22, $8b, $50, $f8, $22
	.byte $23, $8b, $50, $ee, $23, $24, $85, $50, $f8, $24, $25, $8b, $50, $f9, $25, $26, $8d, $50, $f0, $26, $27, $83, $50, $fa
	.byte $27, $28, $8d, $50, $f9, $28, $29, $8b, $50, $fa, $29, $2a, $8b, $50, $f4, $2a, $2b, $85, $50, $fb, $2b, $2c, $8b, $50
	.byte $fb, $2c, $2d, $8d, $50, $f6, $2d, $2e, $83, $50, $fc, $2e, $2f, $8d, $50, $fb, $2f, $30, $8b, $50, $fc, $30, $31, $8b
	.byte $50, $fc, $31, $32, $8d, $50, $fc, $32, $33, $8b, $50, $fd, $33, $34, $8b
@song0ref960:
	.byte $01, $93, $0d, $89, $00, $87, $01, $89, $00, $87, $0d, $89, $00, $9d, $0d, $89, $00, $87, $01, $93, $0d, $89, $00, $87
	.byte $41, $18
	.word @song0ref960
	.byte $41, $18
	.word @song0ref960
	.byte $41, $18
	.word @song0ref960
	.byte $41, $18
	.word @song0ref960
	.byte $41, $18
	.word @song0ref960
	.byte $41, $18
	.word @song0ref960
	.byte $41, $18
	.word @song0ref960
@song0ref1005:
	.byte $a2
@song0ref1006:
	.byte $19, $89, $1c, $87, $1e, $89, $1f, $87, $20, $89, $23, $87, $25, $89, $28, $87, $79, $19, $89, $1c, $87, $1e, $89, $1f
	.byte $87, $20, $89, $23, $87, $25, $89, $28, $87, $74, $19, $89, $1c, $87, $1e, $89, $1f, $87, $20, $89, $23, $87, $25, $89
	.byte $28, $87, $71, $19, $89, $1c, $87, $1e, $89, $1f, $87, $20, $89, $23, $87, $25, $89, $28, $87
@song0ref1073:
	.byte $7f, $25, $89, $23, $87, $20, $89, $1f, $87, $1e, $89, $1c, $87, $19, $89, $17, $87, $79, $25, $89, $23, $87, $20, $89
	.byte $1f, $87, $1e, $89, $1c, $87, $19, $89, $17, $87, $74, $25, $89, $23, $87, $20, $89, $1f, $87, $1e, $89, $1c, $87, $19
	.byte $89, $17, $87, $71, $25, $89, $23, $87, $20, $89, $1f, $87, $1e, $89, $1c, $87, $19, $89, $17, $87, $7f
	.byte $41, $80
	.word @song0ref1006
	.byte $7f
	.byte $41, $80
	.word @song0ref1006
	.byte $7f
	.byte $41, $68
	.word @song0ref1006
	.byte $70, $51, $04, $f0, $4b, .lobyte(@env24), .hibyte(@env24), $96, $25, $ff, $81
@song0ref1164:
	.byte $4e, $00, $4b, .lobyte(@env15), .hibyte(@env15), $9e
@song0ref1170:
	.byte $23, $ff, $ad, $4b, .lobyte(@env36), .hibyte(@env36), $22, $ff, $ad, $4b, .lobyte(@env22), .hibyte(@env22), $21, $ff
	.byte $ad, $4b, .lobyte(@env12), .hibyte(@env12), $20, $ff, $ad, $4e, $00, $4b, .lobyte(@env15), .hibyte(@env15), $23, $ff
	.byte $ad, $4b, .lobyte(@env36), .hibyte(@env36), $22, $ff, $ad, $4b, .lobyte(@env22), .hibyte(@env22), $21, $ff, $ad, $4b
	.byte .lobyte(@env12), .hibyte(@env12), $20, $ff, $ad, $4e, $00, $4b, .lobyte(@env15), .hibyte(@env15)
	.byte $41, $18
	.word @song0ref1170
	.byte $00, $89, $4b, .lobyte(@env20), .hibyte(@env20), $4c, $9c, $19, $87, $00, $89, $25, $87, $31, $89, $00, $93, $31, $87
	.byte $98, $23, $a9, $50, $fa, $2f, $31, $93, $25
@song0ref1253:
	.byte $93, $d7, $51, $ff, $40, $4e, $00, $95, $4e, $01, $95, $4e, $02, $95, $4e, $03, $95, $4e, $04, $95, $4e, $05, $95, $4e
	.byte $06, $95, $4e, $07, $95, $4e, $08, $95, $4e, $09, $95, $4e, $0a, $95, $4e, $0b, $95, $4e, $0c, $95, $4e, $0d, $95, $4e
	.byte $0e, $95, $4e, $0f, $95, $4e, $10, $d7, $7f, $4e, $00, $00, $89, $9c, $19, $87, $20, $89, $25, $87, $2f, $89, $00, $93
	.byte $2f, $87, $98, $2a, $a9, $50, $fc, $36, $38, $93, $2c
	.byte $41, $13
	.word @song0ref1253
	.byte $7f
	.byte $41, $18
	.word @song0ref1164
	.byte $4b, .lobyte(@env20), .hibyte(@env20), $4c, $98
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $41, $18
	.word @song0ref786
	.byte $0d, $93, $14, $89, $00, $87, $01, $89, $00, $87, $14, $89, $00, $87, $70, $51, $06, $f0, $4b, .lobyte(@env24), .hibyte(@env24)
	.byte $96, $25, $d5, $4b, .lobyte(@env20), .hibyte(@env20), $4c
	.byte $41, $40
	.word @song0ref1005
	.byte $81, $00, $ff, $ab, $ff, $af
	.byte $41, $40
	.word @song0ref1073
	.byte $00, $ff, $ad, $ff, $af, $7f
	.byte $41, $40
	.word @song0ref1006
	.byte $81, $00, $ff, $ab, $ff, $af
	.byte $41, $40
	.word @song0ref1073
	.byte $00, $ff, $ad, $ff, $af, $ff, $af, $ff, $af, $44, $00
@song0ch2:
	.byte $ff, $af, $ff, $af, $ff, $af, $ff, $af, $a6
@song0ref1448:
	.byte $50, $7f, $33, $19, $93, $00, $93, $50, $20, $3a, $2c, $93, $50, $7f, $33, $19, $93, $00, $93, $50, $7f, $31, $19, $93
	.byte $50, $20, $3a, $2c, $93, $00, $93, $50, $7f, $33, $19, $93, $00, $93, $50, $20, $3a, $2c, $93, $50, $7f, $33, $19, $93
	.byte $00, $93, $50, $56, $31, $25, $89, $50, $56, $31, $25, $87, $50, $20, $3a, $2c, $93, $00, $93
	.byte $41, $1e
	.word @song0ref1448
	.byte $50, $1d, $3a, $2d, $93, $50, $7f, $33, $19, $93
	.byte $41, $22
	.word @song0ref1448
	.byte $41, $18
	.word @song0ref1448
	.byte $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $89, $50, $22, $39, $2b, $93, $50, $50, $36, $28, $87, $50, $60, $33, $25
	.byte $89, $50, $71, $30, $22, $87
@song0ref1564:
	.byte $50, $7f, $33, $19, $89, $0d, $9d, $50, $20, $3a, $2c, $93, $50, $7f, $33, $19, $89, $0d, $9d, $50, $7f, $31, $19, $89
	.byte $0d, $87, $50, $7f, $31, $1c, $89, $10, $87, $12, $93, $50, $7f, $33, $19, $89, $0d, $87, $25, $89, $19, $87, $50, $20
	.byte $3a, $2c, $93, $50, $7f, $33, $19, $89, $0d, $87, $1f, $93, $50, $7f, $31, $19, $89, $1e, $87, $50, $7f, $31, $1c, $89
	.byte $10, $87, $1c, $93
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
@song0ref1803:
	.byte $50, $7f, $33, $19, $89, $0d, $9d, $50, $7f, $33, $19, $89, $0d, $9d, $50, $7f, $33, $19, $89, $0d, $9d, $50, $7f, $33
	.byte $19, $89, $0d, $9d, $50, $7f, $33, $19, $89, $13, $9d, $50, $7f, $33, $19, $89, $13, $93, $13, $87, $50, $7f, $33, $19
	.byte $89, $13, $9d, $50, $7f, $33, $19, $89, $13, $9d, $50, $7f, $33, $19, $89, $12, $9d, $50, $7f, $33, $19, $89, $12, $9d
	.byte $50, $7f, $33, $19, $89, $12, $9d, $50, $7f, $33, $19, $89, $12, $9d, $50, $7f, $33, $19, $89, $10, $9d, $50, $7f, $33
	.byte $19, $89, $10, $9d, $50, $7f, $33, $19, $89, $10, $9d, $50, $7f, $33, $19, $89, $10, $9d
	.byte $41, $39
	.word @song0ref1803
	.byte $87, $50, $50, $36, $28, $89, $50, $50, $36, $28, $87, $50, $18, $3f, $31, $93, $50, $1d, $3c, $2e, $93, $50, $22, $39
	.byte $2b, $93, $50, $28, $36, $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93, $50, $7f, $31, $19, $89, $0d, $87, $19
	.byte $41, $17
	.word @song0ref589
	.byte $41, $1a
	.word @song0ref625
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19
	.byte $41, $17
	.word @song0ref589
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19, $89
	.byte $41, $16
	.word @song0ref669
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19
	.byte $41, $17
	.word @song0ref589
	.byte $41, $1a
	.word @song0ref625
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19
	.byte $41, $17
	.word @song0ref589
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19, $89
	.byte $41, $16
	.word @song0ref669
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19
	.byte $41, $17
	.word @song0ref589
	.byte $41, $1a
	.word @song0ref625
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19
	.byte $41, $17
	.word @song0ref589
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19, $89
	.byte $41, $16
	.word @song0ref669
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19
	.byte $41, $17
	.word @song0ref589
	.byte $41, $1a
	.word @song0ref625
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19
	.byte $41, $17
	.word @song0ref589
	.byte $50, $7f, $31, $19, $89, $0d, $87, $19, $89
	.byte $41, $16
	.word @song0ref669
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $39, $3c, $2e, $89, $50, $18, $3f, $31, $93, $50, $39, $3c, $2e, $87, $50, $22, $39, $2b, $93, $50, $28, $36
	.byte $28, $93
	.byte $41, $2e
	.word @song0ref1564
	.byte $41, $1f
	.word @song0ref1564
	.byte $93, $50, $40, $3a, $2c, $89, $50, $28, $36, $28, $93, $50, $60, $33, $25, $87, $50, $71, $30, $22, $89, $50, $7f, $2d
	.byte $1f, $87, $50, $7f, $2a, $1c, $89, $50, $7f, $27, $19, $87, $0d, $d5, $50, $2b, $19, $0d, $d5, $00, $ff, $ad, $44, $00
@song0ch3:
	.byte $ff, $af, $ff, $af, $82, $26, $89, $00, $9d, $84, $32, $89, $00, $87, $82, $26, $89, $00, $87, $26, $89, $00, $93, $84
	.byte $33, $87, $88, $32, $89, $00, $87, $82, $26, $89, $00, $87, $26, $85, $70, $51, $03, $10, $8e, $2f, $8b, $7f, $84, $32
	.byte $85, $71, $8e, $2f, $8b, $7f, $88, $32, $89, $72, $8e, $2f, $87, $7f, $82, $26, $85, $73, $51, $03, $40, $8e, $2f, $8b
	.byte $7f, $82, $26, $83, $75, $51, $03, $80, $8e, $2f, $a3, $7f, $88, $32, $83, $79, $51, $04, $c0, $8e, $2f, $99, $7f, $84
	.byte $2f
@song0ref2475:
	.byte $87
@song0ref2476:
	.byte $92, $2e, $a9
@song0ref2479:
	.byte $88, $32, $89, $80, $30, $83, $00, $81, $82, $26, $89, $80, $30, $83, $00, $81, $82, $26, $89, $84, $32, $87, $82, $26
	.byte $89, $80, $30, $83, $00, $81, $88, $32, $89, $80, $30, $83, $00, $81, $84, $32, $89, $80, $30, $83, $00, $81, $82, $26
	.byte $89, $80, $30, $83, $00, $81, $84, $32, $89, $80, $30, $83, $00, $81
	.byte $41, $2e
	.word @song0ref2479
	.byte $41, $2e
	.word @song0ref2479
@song0ref2547:
	.byte $88, $32, $89, $80, $30, $83, $00, $81, $82, $26, $89, $80, $30, $83, $00, $81, $82, $26, $89, $84, $32, $83, $71, $8e
	.byte $2f, $81, $7f, $82, $26, $83, $72, $51, $06, $50, $8e, $2f, $8d, $7f, $88, $32, $89, $76, $51, $07, $d0, $8e, $2f, $9d
	.byte $7f
	.byte $41, $30
	.word @song0ref2476
	.byte $41, $2e
	.word @song0ref2479
	.byte $41, $2e
	.word @song0ref2479
	.byte $41, $1a
	.word @song0ref2547
@song0ref2608:
	.byte $7f
@song0ref2609:
	.byte $92, $2e, $a9
@song0ref2612:
	.byte $86, $31, $93, $82, $26, $89, $80, $30, $83, $00, $81, $82, $26, $89, $84, $32, $87, $82, $26, $89, $80, $30, $83, $00
	.byte $81, $86, $31, $93, $84, $32, $89, $80, $30, $83, $00, $81, $82, $26, $89, $80, $30, $83, $00, $81, $84, $32, $89, $80
	.byte $30, $83, $00, $81
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $1a
	.word @song0ref2612
	.byte $41, $28
	.word @song0ref2609
	.byte $41, $26
	.word @song0ref2612
@song0ref2679:
	.byte $86, $31, $93, $94, $31, $93, $82, $26, $89, $26, $87, $86, $31, $93, $82, $27, $89, $80, $30, $83, $00, $81, $82, $2a
	.byte $89, $80, $30, $83, $00, $81, $51, $fc, $00, $a0, $2e, $ff, $81, $ab
	.byte $41, $28
	.word @song0ref2608
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $16
	.word @song0ref2679
	.byte $41, $28
	.word @song0ref2609
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $19
	.word @song0ref2679
	.byte $00, $93, $7f, $95, $ff, $af, $ff, $af, $ff, $af, $79, $51, $01, $f0, $84
@song0ref2780:
	.byte $32, $89, $00, $87, $34, $89, $00, $87, $32, $89, $00, $87, $34, $89, $00, $87, $32, $89, $00, $87, $34, $89, $00, $87
	.byte $41, $18
	.word @song0ref2780
	.byte $41, $18
	.word @song0ref2780
	.byte $41, $18
	.word @song0ref2780
	.byte $32, $89, $00, $87, $7b, $34, $89, $76, $80, $30, $83, $00, $81, $7b, $88, $32, $89, $7f, $80, $30, $83, $00, $81, $76
	.byte $84, $34, $89, $7f, $80, $30, $83, $00, $81, $82, $26, $89, $84, $32, $83, $71, $8e, $2f, $81, $7f, $82, $26, $83, $72
	.byte $51, $02, $30, $8e, $2f, $8d, $7f, $88, $32, $89, $75, $51, $05, $a0, $8e, $2f, $9d
	.byte $41, $28
	.word @song0ref2608
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $1a
	.word @song0ref2612
	.byte $41, $28
	.word @song0ref2609
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $16
	.word @song0ref2679
@song0ref2902:
	.byte $8c, $22, $9f, $82, $26, $87, $84, $24, $89, $00, $87, $8a, $15, $89, $84, $32, $87, $90, $21, $93, $84, $24, $89, $00
	.byte $87, $8a, $15, $89, $84, $32, $87, $24, $89, $24, $87, $8c, $22, $93, $8a, $15, $89, $8c, $22, $93, $8a, $15, $87, $8c
	.byte $22, $93, $90, $21, $93, $84, $24, $89, $24, $87, $86, $31, $89, $84, $24, $87, $24, $89, $24, $87
	.byte $41, $32
	.word @song0ref2902
	.byte $41, $32
	.word @song0ref2902
	.byte $41, $20
	.word @song0ref2902
	.byte $a4, $22, $9d, $86, $31, $89, $31, $87, $2f, $89, $00, $87, $30, $89, $84, $32, $87, $32, $89, $32, $87
	.byte $41, $32
	.word @song0ref2902
	.byte $41, $32
	.word @song0ref2902
	.byte $41, $32
	.word @song0ref2902
	.byte $41, $20
	.word @song0ref2902
	.byte $a4, $22, $9d, $86, $31, $89, $31, $87, $2f, $89, $00, $87, $30, $89, $84, $32, $87, $32, $89, $32
	.byte $41, $31
	.word @song0ref2475
	.byte $41, $2e
	.word @song0ref2479
	.byte $41, $2e
	.word @song0ref2479
	.byte $41, $1a
	.word @song0ref2547
	.byte $7f
	.byte $41, $30
	.word @song0ref2476
	.byte $41, $2e
	.word @song0ref2479
	.byte $41, $2e
	.word @song0ref2479
	.byte $41, $16
	.word @song0ref2679
	.byte $41, $28
	.word @song0ref2609
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $1a
	.word @song0ref2612
	.byte $41, $28
	.word @song0ref2609
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $41, $26
	.word @song0ref2612
	.byte $86, $31, $93, $82, $26, $89, $80, $30, $83, $00, $81, $82, $26, $89, $84, $32, $83, $71, $8e, $2f, $81, $7f, $82, $26
	.byte $83, $72, $51, $06, $50, $8e, $2f, $8d, $7f, $86, $31, $89, $76, $51, $07, $d0, $8e, $2f, $9d, $7f, $a8, $32, $a9, $7d
	.byte $32, $a9, $7a, $32, $a9, $77, $32, $a9, $75, $32, $a9, $73, $32, $a9, $72, $32, $a9, $71, $32, $a9, $44, $00
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
@song0ref3181:
	.byte $ff, $af, $ff, $af, $ff, $af, $ff, $af, $ff, $af, $ff, $af, $ff, $af, $ff, $af, $ff, $af, $ff, $af
	.byte $41, $14
	.word @song0ref3181
	.byte $41, $14
	.word @song0ref3181
	.byte $41, $14
	.word @song0ref3181
	.byte $41, $14
	.word @song0ref3181
	.byte $41, $14
	.word @song0ref3181
	.byte $41, $14
	.word @song0ref3181
	.byte $41, $14
	.word @song0ref3181
	.byte $41, $14
	.word @song0ref3181
	.byte $ff, $af, $ff, $af, $ff, $af, $ff, $af, $44, $00
